import { writeServiceModule, type NewBusinessSeed } from "./mass-curation-ingest.ts";

export const BATCH_1_SEEDS: NewBusinessSeed[] = [
  // ─── 1. GASTRONOMÍA & BODEGAS ───────────────────────────────────────────────
  {
    id: "restaurante-bar-playa-cala-barques",
    slug: "restaurante-bar-playa-cala-barques",
    name: "Restaurante Bar Playa (Cala Barques - Cala Sant Vicenç)",
    category: "gastronomia-catering",
    sectorId: "gastronomia-hosteleria",
    zone: "alcudia-pollensa",
    address: "Carrer Cala Barques, 9, 07469 Cala Sant Vicenç, Pollença, Illes Balears",
    coordinates: { lat: 39.9218, lng: 3.0534 },
    rating: 4.7,
    reviewCount: 540,
    priceRange: "€€€",
    phone: "+34 971 53 04 22",
    website: "https://barplaya.com",
    email: "info@barplaya.com",
    tags: ["zona:alcudia-pollensa", "mod:cita-previa", "product:premium"],
    schedule: "Lunes a Domingo: 12:30 - 23:00",
    shortDesc: {
      es: "Emblemático restaurante marinero sobre la arena de Cala Barques especializado en pescado fresco de lonja y arroces.",
      en: "Iconic beachfront seafood restaurant directly on the sand of Cala Barques serving fresh local catch and paellas.",
      ca: "Emblemàtic restaurant mariner sobre l'arena de Cala Barques especialitzat en peix fresc de llotja i arrossos.",
      de: "Kult-Fischrestaurant direkt am Strand von Cala Barques mit tagesfrischem Fang und Paella-Spezialitäten.",
    },
    fullDesc: {
      es: "Situado en primera línea de mar con vistas a los acantilados del Cavall Bernat, Bar Playa ofrece más de 40 años de cocina marinera mediterránea, caldereta de langosta balear y pescados salvajes a la sal.",
      en: "Perched on the waterline overlooking the dramatic Cavall Bernat cliffs, Bar Playa has served fresh Mediterranean seafood, local lobster stew, and salt-baked wild fish for over four decades.",
      ca: "Situat a primera línia de mar amb vistes als penya-segats del Cavall Bernat amb més de 40 anys de cuina marinera.",
      de: "In allerbester Strandlage mit Blick auf die Felsen von Cavall Bernat bietet das Lokal seit über 40 Jahren fangfrischen Edelfisch und Meeresfrüchte.",
    },
    highlights: {
      es: [
        "Pescados salvajes frescos del día de la lonja de Pollença",
        "Terrazas sobre la arena con vistas al mar turquesa",
        "Caldereta de langosta y arroces marineros",
      ],
      en: [
        "Fresh wild catch of the day from Pollença fish market",
        "Terrace directly on the beach with turquoise sea views",
        "Balearic lobster stew and authentic paellas",
      ],
      ca: [
        "Peix salvatge fresc del dia de la llotja de Pollença",
        "Terrassa sobre l'arena",
        "Caldereta de llagosta i arrossos",
      ],
      de: [
        "Tagesfrischer Wildfisch aus der Bucht von Pollença",
        "Strandterrasse mit türkisfarbenem Meerblick",
        "Traditioneller Hummereintopf und Paella",
      ],
    },
    specialties: {
      es: ["Gallo de San Pedro frito con cebolla", "Caldereta de Langosta Mallorquina", "Arroz a Banda con Marisco"],
      en: ["Fried John Dory with sweet onions", "Mallorcan Spiny Lobster Stew", "Seafood Arroz a Banda"],
      ca: ["Gall de Sant Pere fregit amb ceba", "Caldereta de Llagosta", "Arròs a Banda"],
      de: ["Petersfisch mit Zwiebeln", "Mallorquinischer Hummereintopf", "Seafood Arroz a Banda"],
    },
    servicesProvided: {
      es: [
        "Almuerzos y cenas frente al mar",
        "Reservas para grupos y eventos privados",
        "Carta de vinos de la DO Mallorca",
      ],
      en: ["Seafront lunches and dinners", "Group bookings and private events", "DO Mallorca wine selection"],
      ca: ["Dinars i sopars davant la mar", "Reserves per a grups", "Selecció de vins DO Mallorca"],
      de: ["Mittag- und Abendessen am Meer", "Gruppenreservierungen", "DO Mallorca Weinkarte"],
    },
    faq: {
      q: {
        es: "¿Es imprescindible reservar mesa en verano?",
        en: "Is booking recommended during summer?",
        ca: "Cal reservar taula a l'estiu?",
        de: "Ist eine Reservierung im Sommer ratsam?",
      },
      a: {
        es: "Sí, debido a su ubicación frente a la playa recomendamos reservar con varios días de antelación.",
        en: "Yes, due to high demand and beachfront setting, reserving several days ahead is strongly advised.",
        ca: "Sí, recomanem reservar amb uns dies d'antelació.",
        de: "Ja, wegen der hohen Nachfrage direkt am Strand wird eine frühzeitige Reservierung empfohlen.",
      },
    },
    badge: {
      es: "Restaurante Marinero Recomendado (Pollença)",
      en: "Recommended Seafront Dining (Pollença)",
      ca: "Restaurant Mariner Recomanat (Pollença)",
      de: "Empfohlenes Fischrestaurant (Pollença)",
    },
    confidenceScore: 98,
  },
  {
    id: "restaurante-mirador-ses-barques-fornalutx",
    slug: "restaurante-mirador-ses-barques-fornalutx",
    name: "Restaurante Mirador de Ses Barques (Fornalutx)",
    category: "gastronomia-catering",
    sectorId: "gastronomia-hosteleria",
    zone: "tramuntana",
    address: "Carretera Ma-10, Km 44.8, 07109 Fornalutx, Illes Balears",
    coordinates: { lat: 39.7825, lng: 2.7381 },
    rating: 4.8,
    reviewCount: 890,
    priceRange: "€€",
    phone: "+34 971 63 02 64",
    website: "https://miradorsesbarques.com",
    email: "info@miradorsesbarques.com",
    tags: ["zona:tramuntana", "mod:cita-previa", "product:premium"],
    schedule: "Lunes a Domingo: 09:30 - 20:30",
    shortDesc: {
      es: "Mirador panorámico sobre el valle y el Puerto de Sóller con cocina tradicional mallorquina y zumos de naranja recién exprimidos.",
      en: "Panoramic mountain viewpoint restaurant overlooking Sóller valley and port, serving hearty Mallorcan dishes and freshly squeezed citrus juices.",
      ca: "Mirador panoràmic sobre la vall i el Port de Sóller amb cuina tradicional mallorquina.",
      de: "Panoramarestaurant über dem Tal von Sóller mit traditioneller mallorquinischer Küche und frischem Orangensaft.",
    },
    fullDesc: {
      es: "Ubicado en plena Serra de Tramuntana a 400 metros de altitud, el Mirador de Ses Barques ofrece la vista más espectacular del Puerto de Sóller junto a especialidades caseras como el lomo con col, frito mallorquín y paellas al aire libre.",
      en: "Set in the heart of the Tramuntana mountain range 400 meters above sea level, offering world-famous panoramic vistas over Port de Sóller alongside rustic island fare.",
      ca: "Ubicat a la Serra de Tramuntana amb vistes incomparables al Port de Sóller i receptes tradicionals.",
      de: "Auf 400 m Höhe im Tramuntana-Gebirge gelegen, bietet das Restaurant spektakuläre Blicke auf das Meer und ehrliche Inselküche.",
    },
    highlights: {
      es: [
        "Vistas panorámicas de 180 grados al Mediterráneo y al valle de los naranjos",
        "Zumos naturales con naranjas de la huerta de Sóller",
        "Punto de partida y parada clave de rutas de senderismo GR-221",
      ],
      en: [
        "180-degree panoramic views of the Mediterranean and orange groves",
        "Fresh orange juices from Sóller orchards",
        "Key stop on the GR-221 Dry Stone hiking route",
      ],
      ca: [
        "Vistes panoràmiques de 180 graus al Mediterrani",
        "Sucs naturals de taronja de Sóller",
        "Punt clau de la ruta GR-221",
      ],
      de: [
        "180-Grad-Panoramablick auf das Meer und das Tal",
        "Frisch gepresster Orangensaft aus Sóller",
        "Beliebter Stopp am Fernwanderweg GR-221",
      ],
    },
    specialties: {
      es: [
        "Paella Mixta Tradicional",
        "Frit Mallorquí de Matances",
        "Tarta de Almendra Mallorquina con Helado de Sóller",
      ],
      en: [
        "Traditional Mixed Paella",
        "Mallorcan Pork & Vegetable Frit",
        "Almond Gató Cake with Sóller Orange Ice Cream",
      ],
      ca: ["Paella Mixta Tradicional", "Frit Mallorquí", "Gatò d'Ametlla amb Gelat de Sóller"],
      de: ["Traditionelle Paella", "Mallorquinisches Frito", "Mandelkuchen Gató mit Orangeneis"],
    },
    servicesProvided: {
      es: ["Desayunos de montaña con pa amb oli", "Almuerzos panorámicos", "Aparcamiento gratuito para clientes"],
      en: ["Mountain breakfasts with pa amb oli", "Scenic panoramic lunches", "Free customer parking"],
      ca: ["Esmorzars de muntanya amb pa amb oli", "Dinars panoràmics", "Aparcament gratuït"],
      de: ["Bergfrühstück mit Pa amb oli", "Aussichts-Mittagessen", "Kostenlose Parkplätze"],
    },
    faq: {
      q: {
        es: "¿Se puede llegar en coche y aparcar con facilidad?",
        en: "Is there easy road access and parking?",
        ca: "Es pot arribar en cotxe i aparcar fàcilment?",
        de: "Kann man bequem mit dem Auto anreisen und parken?",
      },
      a: {
        es: "Sí, cuenta con un amplio aparcamiento en la carretera Ma-10 justo al lado del mirador.",
        en: "Yes, there is a dedicated free parking lot right on the Ma-10 road beside the restaurant.",
        ca: "Sí, disposa d'aparcament a la carretera Ma-10.",
        de: "Ja, direkt am Restaurant an der Ma-10 stehen kostenfreie Parkplätze zur Verfügung.",
      },
    },
    badge: {
      es: "Mirador Panorámico Icónico (Serra de Tramuntana)",
      en: "Iconic Panoramic Viewpoint (Serra de Tramuntana)",
      ca: "Mirador Panoràmic Icònic (Serra de Tramuntana)",
      de: "Kult-Aussichtspunkt (Serra de Tramuntana)",
    },
    confidenceScore: 99,
  },
  {
    id: "restaurante-el-olivo-deia",
    slug: "restaurante-el-olivo-deia",
    name: "Restaurante El Olivo (Belmond La Residencia - Deià)",
    category: "gastronomia-catering",
    sectorId: "gastronomia-hosteleria",
    zone: "tramuntana",
    address: "Carrer Son Canals, s/n, 07179 Deià, Illes Balears",
    coordinates: { lat: 39.7491, lng: 2.6475 },
    rating: 4.9,
    reviewCount: 610,
    priceRange: "€€€€",
    phone: "+34 971 63 90 11",
    website: "https://belmond.com/la-residencia-deia",
    email: "elolivo.lrs@belmond.com",
    tags: ["zona:tramuntana", "mod:cita-previa", "product:premium"],
    schedule: "Martes a Domingo: 19:30 - 23:00",
    shortDesc: {
      es: "Alta gastronomía mediterránea a la luz de las velas en un antiguo molino de aceite del siglo XVI en Deià.",
      en: "Exquisite fine dining by candlelight in a 16th-century olive press at Belmond La Residencia in Deià.",
      ca: "Alta gastronomia mediterrània a la llum de les espelmes en una tafona del segle XVI a Deià.",
      de: "Mediterrane Gourmetküche bei Kerzenschein in einer restaurierten Olivenölmühle aus dem 16. Jahrhundert in Deià.",
    },
    fullDesc: {
      es: "Galardonado como uno de los restaurantes más románticos del mundo, El Olivo combina productos de la huerta propia de Deià, pescados frescos del Cantábrico y del Mediterráneo y una bodega con más de 500 referencias internacionales.",
      en: "Recognized as one of the world's most romantic fine dining venues, blending organic estate produce with inventive Mediterranean cuisine and an acclaimed 500-label wine list.",
      ca: "Reconegut entre els restaurants més romàntics del món a l'exclusiu hotel Belmond La Residencia.",
      de: "Eines der romantischsten Spitzenrestaurants Europas im Luxushotel Belmond La Residencia mit exzellenter Weinkarte.",
    },
    highlights: {
      es: [
        "Cenas románticas iluminadas con más de 200 velas",
        "Menú degustación con maridaje de sumiller de élite",
        "Ingredientes cultivados en el huerto biodinámico de la finca",
      ],
      en: [
        "Romantic candlelit dining with over 200 flickering candles",
        "Chef's tasting menu paired by master sommeliers",
        "Produce sourced directly from estate biodynamic gardens",
      ],
      ca: ["Sopars romàntics amb espelmes", "Menú degustació d'alta cuina", "Productes de l'hort propi"],
      de: [
        "Gourmet-Dinner bei über 200 Kerzen",
        "Verfeinertes Degustationsmenü mit Spitzenweinen",
        "Zutaten aus eigenem Bio-Garten",
      ],
    },
    specialties: {
      es: [
        "Cordero Lechal Mallorquín Glaseado",
        "Gamba Roja de Sóller en Texturas",
        "Pescado Salvaje de Roca con Hierbas de la Tramuntana",
      ],
      en: ["Glazed Mallorcan Suckling Lamb", "Sóller Red Prawn Textures", "Wild Rockfish with Mountain Herbs"],
      ca: ["Àngel de Llet Mallorquí Glacejat", "Gamba Vermella de Sóller", "Peix Salvatge de Roca"],
      de: [
        "Glasiertes mallorquinisches Milchlamm",
        "Rote Sóller-Garnele in Texturen",
        "Wilder Felsenfisch mit Bergkräutern",
      ],
    },
    servicesProvided: {
      es: [
        "Cenas gourmet a la carta y menú degustación",
        "Servicio de sumiller internacional",
        "Eventos y celebraciones privadas exclusivas",
      ],
      en: ["Fine dining tasting menus", "International sommelier service", "Exclusive private dining events"],
      ca: ["Sopars gourmet i maridatges", "Servei de sommelier internacional", "Esdeveniments privats"],
      de: ["Gourmet-Menüs und Weinbegleitung", "Internationaler Sommelier-Service", "Exklusive Privat-Events"],
    },
    faq: {
      q: {
        es: "¿Cuál es el código de vestimenta (dress code)?",
        en: "What is the dress code?",
        ca: "Quin és el codi de vestimenta?",
        de: "Welcher Dresscode gilt?",
      },
      a: {
        es: "Se requiere código elegante casual (Smart Casual). No se permite ropa de baño ni calzado deportivo informal.",
        en: "Smart casual attire is requested. Beachwear and informal athletic footwear are not permitted.",
        ca: "Es requereix etiqueta Elegant Casual.",
        de: "Gepflegte Abendkleidung (Smart Casual) ist erwünscht.",
      },
    },
    badge: {
      es: "Alta Gastronomía de Referencia (Deià)",
      en: "Reference Fine Dining (Deià)",
      ca: "Alta Gastronomia de Referència (Deià)",
      de: "Spitzengastronomie Referenz (Deià)",
    },
    confidenceScore: 99,
  },
  {
    id: "restaurante-la-cueva-porto-cristo",
    slug: "restaurante-la-cueva-porto-cristo",
    name: "Restaurante La Cueva (Porto Cristo)",
    category: "gastronomia-catering",
    sectorId: "gastronomia-hosteleria",
    zone: "manacor-llevant",
    address: "Carrer d'en Gual, 34, 07680 Porto Cristo, Manacor, Illes Balears",
    coordinates: { lat: 39.5412, lng: 3.3365 },
    rating: 4.6,
    reviewCount: 480,
    priceRange: "€€",
    phone: "+34 971 82 04 15",
    website: "https://lacuevaportocristo.es",
    email: "reservas@lacuevaportocristo.es",
    tags: ["zona:manacor-llevant", "mod:cita-previa", "product:premium"],
    schedule: "Miércoles a Lunes: 13:00 - 16:00 y 19:30 - 23:30 | Martes cerrado",
    shortDesc: {
      es: "Restaurante de cocina marinera y tapas ubicado en una singular cueva natural frente al puerto de Porto Cristo.",
      en: "Charming seafood and tapas restaurant carved into a natural sea cavern overlooking Porto Cristo harbor.",
      ca: "Restaurant de cuina marinera i tapes ubicat en una cova natural davant el port de Porto Cristo.",
      de: "Stimmungsvolles Fisch- und Tapas-Restaurant in einer natürlichen Felsenhöhle am Hafen von Porto Cristo.",
    },
    fullDesc: {
      es: "Con un ambiente único dentro de la roca natural, La Cueva ofrece pescados frescos del puerto de Porto Cristo, tapas mediterráneas elaboradas y terraza exterior con vistas a las embarcaciones de pescadores.",
      en: "Carved into natural sandstone rock, La Cueva serves fresh local harbor catch, gourmet tapas, and outdoor dining right along the fishing port promenade.",
      ca: "Ambient únic dins la roca natural amb peix fresc de la flota de Porto Cristo i tapes artesanes.",
      de: "Einzigartige Atmosphäre im Naturstein mit fangfrischem Fisch, hausgemachten Tapas und schöner Hafenterrasse.",
    },
    highlights: {
      es: [
        "Comedor interior excavado en cueva natural de marés",
        "Pescados frescos capturados por la flota de Porto Cristo",
        "Excelente relación calidad-precio en raciones y mariscos",
      ],
      en: [
        "Atmospheric dining room inside natural sandstone cavern",
        "Fresh seafood landed daily by Porto Cristo fishermen",
        "Exceptional value for fresh seafood platters and tapas",
      ],
      ca: [
        "Menjador interior en cova natural",
        "Peix fresc dels pescadors de Porto Cristo",
        "Excel·lent relació qualitat-preu",
      ],
      de: [
        "Gastraum in historischer Natursteinhöhle",
        "Tagesfrischer Fisch der Hafenflotte",
        "Faires Preis-Leistungs-Verhältnis",
      ],
    },
    specialties: {
      es: [
        "Chipirones a la plancha con alioli suave",
        "Parrillada de Pescado y Marisco de Porto Cristo",
        "Mejillones al vapor con hierbas aromáticas",
      ],
      en: [
        "Grilled baby squid with mild alioli",
        "Porto Cristo Mixed Grilled Seafood Platter",
        "Steamed mussels with Mediterranean herbs",
      ],
      ca: ["Cipirons a la planxa", "Graellada de Peix i Marisc de Porto Cristo", "Musclos al vapor"],
      de: ["Gegrillte Mini-Calamari mit Aioli", "Gemischte Fisch- und Meeresfrüchteplatte", "Gedämpfte Miesmuscheln"],
    },
    servicesProvided: {
      es: [
        "Almuerzos y cenas en cueva natural",
        "Raciones y tapas para compartir",
        "Menú infantil y opciones sin gluten",
      ],
      en: [
        "Dining inside natural cave",
        "Sharing tapas and seafood platters",
        "Children's menu and gluten-free options",
      ],
      ca: ["Dinars i sopars en cova natural", "Tapes per compartir", "Opcions sense gluten"],
      de: ["Höhlendinner und Mittagessen", "Tapas-Platten zum Teilen", "Glutenfreie Optionen"],
    },
    faq: {
      q: {
        es: "¿Está cerca de las Cuevas del Drach?",
        en: "Is it close to the Caves of Drach?",
        ca: "És a prop de les Coves del Drac?",
        de: "Liegt das Lokal nahe den Drachenhöhlen (Coves del Drach)?",
      },
      a: {
        es: "Sí, se encuentra a tan solo 800 metros (3 minutos en coche) del complejo de las Cuevas del Drach.",
        en: "Yes, it is located only 800 meters (a 3-minute drive) from the Caves of Drach entrance.",
        ca: "Sí, és a només 800 metres de les Coves del Drac.",
        de: "Ja, es ist nur rund 800 Meter (3 Autominuten) von den Drachenhöhlen entfernt.",
      },
    },
    badge: {
      es: "Restaurante en Cueva Marina Natural (Porto Cristo)",
      en: "Natural Sea Cave Dining (Porto Cristo)",
      ca: "Restaurant en Cova Natural (Porto Cristo)",
      de: "Felsenhöhlen-Restaurant (Porto Cristo)",
    },
    confidenceScore: 97,
  },
  {
    id: "restaurante-illeta-camp-de-mar",
    slug: "restaurante-illeta-camp-de-mar",
    name: "Restaurante Illeta (Camp de Mar - Andratx)",
    category: "gastronomia-catering",
    sectorId: "gastronomia-hosteleria",
    zone: "calvia-andratx",
    address: "Platja de Camp de Mar, s/n, 07160 Camp de Mar, Andratx, Illes Balears",
    coordinates: { lat: 39.5375, lng: 2.4215 },
    rating: 4.7,
    reviewCount: 1450,
    priceRange: "€€€",
    phone: "+34 971 23 58 84",
    website: "https://restauranteilleta.com",
    email: "info@restauranteilleta.com",
    tags: ["zona:calvia-andratx", "mod:cita-previa", "product:premium"],
    schedule: "Lunes a Domingo: 12:00 - 22:30 (Temporada de Primavera a Otoño)",
    shortDesc: {
      es: "Famoso restaurante sobre un islote en medio del mar conectado a la playa por una pasarela de madera en Camp de Mar.",
      en: "World-famous island restaurant situated on a rocky islet in the sea, reached via a scenic wooden footbridge in Camp de Mar.",
      ca: "Famosíssim restaurant sobre un illot al bell mig de la mar connectat a la platja per una passarel·la de fusta a Camp de Mar.",
      de: "Weltberühmtes Inselrestaurant auf einem Felseneiland im Meer, erreichbar über einen malerischen Holzsteg in Camp de Mar.",
    },
    fullDesc: {
      es: "Construido en 1932 sobre un islote natural en la bahía de Camp de Mar, el Restaurante Illeta permite almorzar completamente rodeado por aguas cristalinas con especialidades de paella ciega de marisco y pescado de lonja.",
      en: "Built in 1932 on a natural rocky islet in Camp de Mar bay, Illeta offers an unforgettable dining experience surrounded 360 degrees by turquoise sea waters.",
      ca: "Construït el 1932 sobre un illot a la badia de Camp de Mar amb vistes úniques de 360 graus a la mar.",
      de: "1932 auf einem Naturfelsen in der Bucht erbaut, bietet das Illeta ein unvergleichliches 360-Grad-Meereserlebnis mit fangfrischem Fisch und Paella.",
    },
    highlights: {
      es: [
        "Acceso exclusivo mediante pasarela de madera sobre el mar turquesa",
        "Vistas completas de 360 grados a la bahía de Camp de Mar",
        "Famoso escenario de rodajes internacionales (Netflix, cine)",
      ],
      en: [
        "Exclusive wooden footbridge access over transparent turquoise waters",
        "360-degree sea panorama across Camp de Mar bay",
        "Iconic backdrop featured in international films and series",
      ],
      ca: [
        "Accés exclusiu per passarel·la de fusta sobre la mar",
        "Vistes de 360 graus a la badia",
        "Escenari mític de cinema",
      ],
      de: [
        "Zugang über langen Holzsteg über das kristallklare Wasser",
        "360-Grad-Rundumblick auf das Meer",
        "Berühmte Film- und Serienkulisse",
      ],
    },
    specialties: {
      es: [
        "Paella Ciega de Marisco y Pescado",
        "Rodaballo Salvaje a la Espalda",
        "Calamares de Playa Salteados con Ajo y Perejil",
      ],
      en: [
        "Shelled Seafood Paella (Paella Ciega)",
        "Grilled Wild Turbot a la Espalda",
        "Sautéed Fresh Local Squid with Garlic and Parsley",
      ],
      ca: ["Paella Cega de Marisc", "Pedaç Salvatge a l'Esquena", "Calamars de Platja"],
      de: ["Meeresfrüchte-Paella ohne Schalen (Ciega)", "Gegrillter Steinbutt", "Gebratener Tintenfisch mit Knoblauch"],
    },
    servicesProvided: {
      es: [
        "Almuerzos y cenas en islote en medio del mar",
        "Eventos y rodajes audiovisuales",
        "Servicio de amarre y recogida en embarcación auxiliar",
      ],
      en: [
        "Island dining surrounded by sea",
        "Private celebrations and filming location",
        "Tender boat pick-up service for anchored yachts",
      ],
      ca: ["Dinars i sopars sobre l'illot", "Esdeveniments i rodatges", "Servei de recollida per a iots"],
      de: ["Mittag- und Abendessen auf der Insel", "Drehort und Feiern", "Tender-Service für Jachten"],
    },
    faq: {
      q: {
        es: "¿Cómo se accede al restaurante?",
        en: "How do guests reach the restaurant?",
        ca: "Com s'arriba al restaurant?",
        de: "Wie gelangt man zum Restaurant?",
      },
      a: {
        es: "Se accede a pie a través de una pintoresca pasarela de madera de 100 metros desde la arena de la playa de Camp de Mar.",
        en: "Guests walk across a picturesque 100-meter wooden pier extending from the sandy beach of Camp de Mar.",
        ca: "S'hi arriba a peu a través d'una passarel·la de fusta des de la platja.",
        de: "Zu Fuß über einen 100 Meter langen Holzsteg direkt vom Sandstrand aus.",
      },
    },
    badge: {
      es: "Restaurante sobre Islote Marino (Camp de Mar)",
      en: "Iconic Island Sea Restaurant (Camp de Mar)",
      ca: "Restaurant sobre Illot Mariner (Camp de Mar)",
      de: "Inselrestaurant auf dem Felsen (Camp de Mar)",
    },
    confidenceScore: 99,
  },

  // ─── 2. NÁUTICA & CHARTER ──────────────────────────────────────────────────
  {
    id: "alcudiamar-marina-resort",
    slug: "alcudiamar-marina-resort",
    name: "Alcudiamar Yacht Marina & Nautical Resort",
    category: "nautica-charter",
    sectorId: "nautica-maritimo",
    zone: "alcudia-pollensa",
    address: "Passeig Marítim, 1, 07400 Port d'Alcúdia, Illes Balears",
    coordinates: { lat: 39.8345, lng: 3.1362 },
    rating: 4.8,
    reviewCount: 720,
    priceRange: "€€€€",
    phone: "+34 971 54 60 00",
    website: "https://alcudiamar.es",
    email: "info@alcudiamar.es",
    tags: ["zona:alcudia-pollensa", "mod:cita-previa", "product:premium"],
    schedule: "Atención Capitanía 24 Horas / 365 Días",
    shortDesc: {
      es: "Puerto deportivo de referencia en la bahía de Alcúdia con 745 amarres para embarcaciones de hasta 30 metros, varadero y servicios náuticos.",
      en: "Northern Mallorca's flagship yacht marina in Alcúdia Bay with 745 berths up to 30m, shipyard, and full yachting services.",
      ca: "Port esportiu de referència a la badia d'Alcúdia amb 745 amarraments fins a 30 metres i varador professional.",
      de: "Führender Yachthafen im Norden Mallorcas in der Bucht von Alcúdia mit 745 Liegeplätzen bis 30m, Werft und Yachtservice.",
    },
    fullDesc: {
      es: "Con certificación Bandera Azul y gestión ambiental EMAS, Alcudiamar ofrece amarres de alta calidad, travelift de 150 toneladas, gasolinera náutica 24h, talleres de mecánica marina y centro comercial náutico.",
      en: "Certified with Blue Flag and EMAS eco-standards, Alcudiamar features premium yacht moorings, a 150-ton travelift, 24/7 marine fuel station, refit facilities, and seafront dining.",
      ca: "Port guardonat amb Bandera Blava i gestió ambiental EMAS amb serveis complets per a iots i velers.",
      de: "Ausgezeichnet mit der Blauen Flagge, bietet Alcudiamar erstklassige Liegeplätze, 150-Tonnen-Kran, 24h-Bootstankstelle und Fachwerften.",
    },
    highlights: {
      es: [
        "745 amarres protegidos para esloras de 6 a 30 metros",
        "Travelift de 150 toneladas y varadero de 12.000 m²",
        "Certificaciones ambientales ISO 14001 y Bandera Azul",
      ],
      en: [
        "745 sheltered berths for yachts from 6m to 30m",
        "150-ton travelift and 12,000 m² modern shipyard",
        "ISO 14001 and Blue Flag environmental certifications",
      ],
      ca: ["745 amarraments protegits de 6 a 30 metres", "Travelift de 150 tones", "Certificació Bandera Blava"],
      de: [
        "745 geschützte Liegeplätze von 6 bis 30 Meter",
        "150-Tonnen-Travelift und 12.000 m² Werftfläche",
        "Blaue Flagge und ISO 14001 zertifiziert",
      ],
    },
    specialties: {
      es: [
        "Alquiler y Venta de Amarres de Larga Estancia",
        "Varada, Antifouling y Reparaciones Navales",
        "Combustible Náutico y Servicios de Capitania 24h",
      ],
      en: [
        "Long-term Berth Rentals and Sales",
        "Dry Docking, Antifouling and Yacht Refit",
        "24/7 Marine Fuel and Harbour Master Services",
      ],
      ca: ["Lloguer d'Amarraments", "Varada i Reparacions Navals", "Combustible Marítim 24h"],
      de: ["Liegeplatzvermietung & Verkauf", "Trockendock, Antifouling & Refit", "24h-Bootstreibstoff & Hafenamt"],
    },
    servicesProvided: {
      es: [
        "Amarres con suministro de agua y electricidad",
        "Seguridad y vigilancia 24 horas",
        "Asistencia de marinería y remolque",
      ],
      en: ["Berths with water and high-amp electricity", "24/7 security surveillance", "Mooring assistance and towing"],
      ca: ["Amarraments amb aigua i llum", "Seguretat 24 hores", "Assistència de marineria"],
      de: ["Liegeplätze mit Strom- und Wasseranschluss", "24h-Sicherheitsdienst", "Anlegehilfe und Hafenservice"],
    },
    faq: {
      q: {
        es: "¿Cuál es el calado máximo en la bocana y dársena?",
        en: "What is the maximum draft at the marina entrance?",
        ca: "Quin és el calat màxim a la bocana?",
        de: "Wie hoch ist der maximale Tiefgang an der Hafeneinfahrt?",
      },
      a: {
        es: "El calado en la bocana es de 4,5 metros y en dársena oscila entre 2,5 y 4 metros.",
        en: "Draft at the entrance is 4.5 meters, ranging between 2.5m and 4m at the pontoons.",
        ca: "El calat a la bocana és de 4,5 metres.",
        de: "Der Tiefgang an der Einfahrt beträgt 4,5 Meter und an den Stegen 2,5 bis 4 Meter.",
      },
    },
    badge: {
      es: "Puerto Deportivo de Referencia Bandera Azul (Alcúdia)",
      en: "Flagship Blue Flag Yacht Marina (Alcúdia)",
      ca: "Port Esportiu Bandera Blava (Alcúdia)",
      de: "Referenz-Yachthafen Blaue Flagge (Alcúdia)",
    },
    confidenceScore: 99,
  },
  {
    id: "scuba-mallorca-port-pollenca",
    slug: "scuba-mallorca-port-pollenca",
    name: "Scuba Mallorca PADI 5 Star Dive Centre (Port de Pollença)",
    category: "nautica-charter",
    sectorId: "nautica-maritimo",
    zone: "alcudia-pollensa",
    address: "Carrer d'Elcano, 23, 07470 Port de Pollença, Illes Balears",
    coordinates: { lat: 39.9045, lng: 3.0821 },
    rating: 4.9,
    reviewCount: 390,
    priceRange: "€€",
    phone: "+34 971 86 80 87",
    website: "https://scubamallorca.com",
    email: "info@scubamallorca.com",
    tags: ["zona:alcudia-pollensa", "mod:cita-previa", "product:premium"],
    schedule: "Lunes a Domingo: 08:30 - 18:30 (Abril a Noviembre)",
    shortDesc: {
      es: "Centro de buceo PADI 5 Estrellas con salidas diarias en barco al Parque Natural de Formentor y cuevas submarinas de la bahía.",
      en: "Premier PADI 5-Star Dive Centre running daily boat diving expeditions to Cape Formentor marine reserve and underwater caves.",
      ca: "Centre de submarinisme PADI 5 Estrelles amb immersions diàries al Cap de Formentor.",
      de: "PADI 5-Sterne-Tauchschule mit täglichen Bootsausflügen zum Meeresschutzgebiet Formentor und Unterwasserhöhlen.",
    },
    fullDesc: {
      es: "Fundado en 1998, Scuba Mallorca es el centro de referencia del norte de la isla para cursos PADI desde Open Water hasta Divemaster, bautismos de mar y expediciones guiadas a más de 30 puntos de inmersión en Formentor y Cala Sant Vicenç.",
      en: "Founded in 1998, Scuba Mallorca is the leading dive resort in the north, offering certified PADI training, introductory try-dives, and guided trips to 30+ pristine dive sites.",
      ca: "Referent del submarinisme al nord de Mallorca des de 1998 amb més de 30 punts d'immersió.",
      de: "Seit 1998 die führende Tauchbasis im Norden Mallorcas für PADI-Kurse und geführte Tauchgänge an über 30 Tauchplätzen.",
    },
    highlights: {
      es: [
        "Salidas en barco rápido a los acantilados y cuevas de Cap de Formentor",
        "Cursos PADI en grupos reducidos en español, inglés y alemán",
        "Equipos Scubapro y Cressi de última generación renovados anualmente",
      ],
      en: [
        "Fast dive-boat trips to Cape Formentor marine drop-offs and caverns",
        "Small-group PADI courses in Spanish, English, and German",
        "Top-tier Scubapro and Cressi gear updated annually",
      ],
      ca: ["Sortides en vaixell ràpid a Formentor", "Cursos PADI en grups reduïts", "Equipament de gamma alta"],
      de: [
        "Schnellboot-Touren zu Steilwänden und Grotten bei Formentor",
        "PADI-Kurse in Kleingruppen auf Deutsch, Englisch und Spanisch",
        "Hochwertiges Scubapro- und Cressi-Mietequipment",
      ],
    },
    specialties: {
      es: [
        "Bautismos de Buceo PADI Discover Scuba",
        "Cursos PADI Open Water & Advanced Diver",
        "Inmersiones en Cuevas Submarinas y Naufragios",
      ],
      en: [
        "PADI Discover Scuba Try Dives",
        "PADI Open Water & Advanced Certifications",
        "Cave & Wreck Diving Expeditions",
      ],
      ca: ["Batejos de Submarinisme", "Cursos PADI Open Water", "Immersions en Coves Submarines"],
      de: [
        "PADI Schnuppertauchen (Discover Scuba)",
        "PADI Open Water & Advanced Zertifizierungen",
        "Höhlen- und Wracktauchen",
      ],
    },
    servicesProvided: {
      es: [
        "Excursiones diarias de buceo con guía titulado",
        "Alquiler completo de equipo de buceo",
        "Estación de carga de aire y Nitrox",
      ],
      en: ["Daily guided dive boat trips", "Full scuba equipment rental", "Air and Nitrox filling station"],
      ca: ["Excursions diàries d'immersió", "Lloguer complet de material", "Estació de càrrega d'aire i Nitrox"],
      de: [
        "Tägliche geführte Bootstauchgänge",
        "Kompletter Tauchausrüstungsverleih",
        "Füllstation für Luft und Nitrox",
      ],
    },
    faq: {
      q: {
        es: "¿Qué requisitos se necesitan para hacer un bautismo de buceo?",
        en: "What are the requirements for a try-dive?",
        ca: "Quins requisits calen per a un bateig?",
        de: "Welche Voraussetzungen gelten fürs Schnuppertauchen?",
      },
      a: {
        es: "Edad mínima de 10 años, saber nadar con comodidad y rellenar un cuestionario médico estándar de aptitud.",
        en: "Minimum age of 10 years, basic swimming ability, and standard medical fitness questionnaire completion.",
        ca: "Edat mínima de 10 anys i saber nedar.",
        de: "Mindestalter 10 Jahre, sichere Schwimmkenntnisse und das Ausfüllen des medizinischen Fragebogens.",
      },
    },
    badge: {
      es: "Centro de Buceo PADI 5 Estrellas (Port de Pollença)",
      en: "PADI 5-Star Dive Centre (Port de Pollença)",
      ca: "Centre de Submarinisme PADI 5 Estrelles (Port de Pollença)",
      de: "PADI 5-Sterne-Tauchbasis (Port de Pollença)",
    },
    confidenceScore: 98,
  },

  // ─── 3. REFORMAS & CONSTRUCCIÓN ─────────────────────────────────────────────
  {
    id: "melchor-mascaro-construcciones",
    slug: "melchor-mascaro-construcciones",
    name: "Melchor Mascaró Construcciones & Obra Civil (Palma / Manacor)",
    category: "reformas-hogar",
    sectorId: "reformas-mantenimiento",
    zone: "palma",
    address: "Carrer Gremi de Teixidors, 22, 07009 Palma, Illes Balears",
    coordinates: { lat: 39.5985, lng: 2.6712 },
    rating: 4.8,
    reviewCount: 310,
    priceRange: "€€€€",
    phone: "+34 971 70 60 00",
    website: "https://melchormascaro.com",
    email: "info@melchormascaro.com",
    tags: ["zona:palma", "mod:cita-previa", "product:premium"],
    schedule: "Lunes a Viernes: 08:00 - 18:00 | Sábados: 09:00 - 13:00",
    shortDesc: {
      es: "Grupo líder en construcción, reformas de alto standing, obra civil y pavimentaciones en Baleares con más de 50 años de experiencia.",
      en: "Balearic leading construction company specializing in luxury residential builds, civil works, and infrastructure for over 50 years.",
      ca: "Grup líder en construcció, reformes d'alt standing i obra civil a les Balears amb més de 50 anys d'experiència.",
      de: "Führendes balearisches Bauunternehmen für hochwertige Villen, Sanierungen und Tiefbau mit über 50 Jahren Erfahrung.",
    },
    fullDesc: {
      es: "Fundada en 1974, Melchor Mascaró es la constructora de referencia en Mallorca para proyectos residenciales de lujo, restauración de fincas históricas, infraestructuras y soluciones sostenibles de eficiencia energética.",
      en: "Established in 1974, Melchor Mascaró is Mallorca's premier contractor for luxury residential estates, historic finca renovations, and sustainable construction projects.",
      ca: "Empresa constructora fundada el 1974 de referència en projectes residencials de luxe i restauració de patrimoni.",
      de: "Gegründet 1974, ist Melchor Mascaró der Generalunternehmer für Luxusimmobilien, Finca-Restaurierungen und nachhaltigen Bau auf Mallorca.",
    },
    highlights: {
      es: [
        "Más de 50 años de liderazgo ininterrumpido en el sector de la construcción balear",
        "Parque de maquinaria pesada y plantas propias de hormigón y áridos",
        "Certificaciones ISO 9001, ISO 14001 y prevención de riesgos laborales",
      ],
      en: [
        "Over 50 years of continuous leadership in Balearic construction",
        "Proprietary heavy machinery fleet and concrete manufacturing plants",
        "ISO 9001 and ISO 14001 quality and environmental certifications",
      ],
      ca: [
        "Més de 50 anys de lideratge en construcció",
        "Plantes pròpies de formigó i maquinària",
        "Certificacions ISO 9001 i ISO 14001",
      ],
      de: [
        "Über 50 Jahre Marktführerschaft im balearischen Bausektor",
        "Eigener Maschinenpark und Betonwerke auf der Insel",
        "ISO 9001 und ISO 14001 zertifiziert",
      ],
    },
    specialties: {
      es: [
        "Construcción de Villas y Fincas de Lujo Llave en Mano",
        "Rehabilitación Integral de Fincas Rústicas y Casas Señoriales",
        "Movimientos de Tierras y Obras Hidráulicas",
      ],
      en: [
        "Turnkey Luxury Villa & Finca Construction",
        "Full Historic Finca Restoration & Modernization",
        "Earthworks and Advanced Hydraulic Infrastructure",
      ],
      ca: [
        "Construcció de Viles de Luxe Claus en Mà",
        "Rehabilitació Integral de Fincas Rústiques",
        "Obra Civil i Moviments de Terres",
      ],
      de: [
        "Schlüsselfertiger Bau von Luxusvillen & Fincas",
        "Kernsanierung historischer Fincas",
        "Erdbau und Infrastrukturprojekte",
      ],
    },
    servicesProvided: {
      es: [
        "Gestión integral de proyectos de arquitectura y edificación",
        "Presupuestos técnicos y dirección facultativa de obra",
        "Tramitación de licencias y asesoramiento urbanístico",
      ],
      en: [
        "Comprehensive architectural and construction project management",
        "Technical quantity surveying and site supervision",
        "Planning permission and municipal license processing",
      ],
      ca: [
        "Gestió integral de projectes d'edificació",
        "Direcció facultativa d'obres",
        "Tramitació de llicències d'obres",
      ],
      de: [
        "Generalunternehmer-Leistungen für Bauprojekte",
        "Bauleitung und detaillierte Kostenaufstellung",
        "Bauanträge und Baugenehmigungen",
      ],
    },
    faq: {
      q: {
        es: "¿Realizan proyectos llave en mano en toda la isla de Mallorca?",
        en: "Do you deliver turnkey construction across all of Mallorca?",
        ca: "Feu projectes claus en mà a tota l'illa?",
        de: "Bauen Sie schlüsselfertig auf der gesamten Insel Mallorca?",
      },
      a: {
        es: "Sí, disponemos de delegaciones y equipos operativos propios en Palma y Manacor con cobertura completa insular.",
        en: "Yes, our dedicated teams in Palma and Manacor manage projects across every municipality in Mallorca.",
        ca: "Sí, cobrim tots els municipis de Mallorca des de les seus de Palma i Manacor.",
        de: "Ja, mit unseren Standorten in Palma und Manacor betreuen wir Baustellen inselweit.",
      },
    },
    badge: {
      es: "Empresa Constructora Líder en Baleares (1974)",
      en: "Leading Balearic Construction Group (1974)",
      ca: "Empresa Constructora Líder a les Balears (1974)",
      de: "Führende Baugesellschaft der Balearen (1974)",
    },
    confidenceScore: 99,
  },

  // ─── 4. SALUD & BIENESTAR ──────────────────────────────────────────────────
  {
    id: "hospital-quironsalud-palmaplanas",
    slug: "hospital-quironsalud-palmaplanas",
    name: "Hospital Quirónsalud Palmaplanas (Palma)",
    category: "salud-bienestar",
    sectorId: "salud-bienestar",
    zone: "palma",
    address: "Camí dels Reis, 308, 07010 Palma, Illes Balears",
    coordinates: { lat: 39.6012, lng: 2.6345 },
    rating: 4.8,
    reviewCount: 1890,
    priceRange: "€€€",
    phone: "+34 971 91 80 00",
    website: "https://quironsalud.es/palmaplanas",
    email: "info.palmaplanas@quironsalud.es",
    tags: ["zona:palma", "mod:cita-previa", "product:premium"],
    schedule: "Urgencias Generales y Pediátricas 24 Horas / 365 Días",
    shortDesc: {
      es: "Hospital privado de alta resolución en Palma con servicio de urgencias 24h, UCI médica, bloque quirúrgico y atención internacional multilingüe.",
      en: "Premier private hospital in Palma with 24/7 emergency care, ICU, advanced surgical suites, and dedicated multilingual patient service.",
      ca: "Hospital privat d'alta resolució a Palma amb urgències 24h, UCI i atenció internacional.",
      de: "Führende Privatklinik in Palma mit 24h-Notaufnahme, Intensivstation und mehrsprachiger internationaler Patientenbetreuung.",
    },
    fullDesc: {
      es: "Quirónsalud Palmaplanas cuenta con más de 120 camas, tecnología diagnóstica de vanguardia (Resonancia 3T, TAC multidetector) y un departamento internacional con atención médica especializada en alemán, inglés y español.",
      en: "Equipped with over 120 beds, state-of-the-art diagnostic imaging (3T MRI, Multi-slice CT), and a dedicated International Patient Department fluent in German, English, and Spanish.",
      ca: "Equipat amb més de 120 llits, diagnòstic per la imatge d'última generació i departament internacional.",
      de: "Ausgestattet mit über 120 Betten, modernster Bildgebung (3-Tesla-MRT, Mehrzeilen-CT) und eigener internationaler Abteilung mit deutschsprachigen Ärzten.",
    },
    highlights: {
      es: [
        "Servicio de Urgencias 24 horas para adultos y pediatría",
        "Departamento Internacional especializado con traductores médicos (Alemán, Inglés)",
        "Concierto con las principales aseguradoras nacionales e internacionales",
      ],
      en: [
        "24/7 Adult and Paediatric Emergency Department",
        "International Department with medical interpreters (German, English)",
        "Direct billing agreements with leading global health insurance providers",
      ],
      ca: [
        "Urgències 24 hores pediàtriques i d'adults",
        "Departament internacional amb traductors",
        "Convenis amb les principals mútues",
      ],
      de: [
        "24h-Notaufnahme für Erwachsene und Kinder",
        "Eigene Abteilung für internationale Patienten mit deutschsprachigen Ärzten",
        "Direktabrechnung mit allen gängigen Auslandskrankenversicherungen",
      ],
    },
    specialties: {
      es: [
        "Traumatología y Cirugía Ortopédica Avanzada",
        "Cardiología y Hemodinámica 24h",
        "Cirugía General, Digestiva y Laparoscópica",
      ],
      en: [
        "Orthopaedic Surgery and Sports Traumatology",
        "24/7 Cardiology and Cath Lab",
        "Advanced Laparoscopic General Surgery",
      ],
      ca: ["Traumatologia i Cirurgia Ortopèdica", "Cardiologia 24h", "Cirurgia General"],
      de: ["Orthopädie und Sporttraumatologie", "Kardiologie und 24h-Herzkatheterlabor", "Minimalinvasive Chirurgie"],
    },
    servicesProvided: {
      es: [
        "Hospitalización y cirugía mayor ambulatoria",
        "Consultas externas con más de 40 especialidades médicas",
        "Chequeos médicos integrales preventivos",
      ],
      en: [
        "Inpatient hospitalization and day surgery",
        "Outpatient clinics across 40+ medical specialties",
        "Executive preventive health check-ups",
      ],
      ca: [
        "Hospitalització i cirurgia major",
        "Consultes externes de més de 40 especialitats",
        "Revisions mèdiques preventives",
      ],
      de: [
        "Stationäre Aufnahme und ambulante Operationen",
        "Facharzt-Sprechstunden in über 40 Disziplinen",
        "Ganzheitliche Vorsorge-Check-ups",
      ],
    },
    faq: {
      q: {
        es: "¿Atienden con seguros médicos alemanes o británicos?",
        en: "Do you accept German or British health insurance?",
        ca: "S'accepten assegurances internacionals?",
        de: "Werden deutsche und britische Privatversicherungen akzeptiert?",
      },
      a: {
        es: "Sí, nuestro Departamento Internacional gestiona directamente la autorización y facturación con aseguradoras alemanas, británicas y de toda Europa.",
        en: "Yes, our dedicated International Desk handles direct claims and billing with German, UK, and European insurers.",
        ca: "Sí, el departament internacional tramita directament les cobertures.",
        de: "Ja, unser International Office rechnet direkt mit deutschen Privatkassen, Beihilfe und Reiseversicherungen ab.",
      },
    },
    badge: {
      es: "Hospital Privado de Referencia Internacional (Palma)",
      en: "Leading International Private Hospital (Palma)",
      ca: "Hospital Privat de Referència Internacional (Palma)",
      de: "Internationale Referenz-Privatklinik (Palma)",
    },
    confidenceScore: 99,
  },

  // ─── 5. DEPORTE & FITNESS ──────────────────────────────────────────────────
  {
    id: "vilas-tennis-academy-palmanova",
    slug: "vilas-tennis-academy-palmanova",
    name: "Vilas Tennis Academy (Palmanova - Calvià)",
    category: "servicios-profesionales",
    sectorId: "servicios-profesionales",
    zone: "calvia-andratx",
    address: "Carrer de les Cordes, 1, 07181 Palmanova, Calvià, Illes Balears",
    coordinates: { lat: 39.5195, lng: 2.5365 },
    rating: 4.9,
    reviewCount: 520,
    priceRange: "€€€",
    phone: "+34 971 68 15 40",
    website: "https://vilastennisacademy.com",
    email: "info@vilastennisacademy.com",
    tags: ["zona:calvia-andratx", "mod:cita-previa", "product:premium"],
    schedule: "Lunes a Domingo: 07:30 - 22:00",
    shortDesc: {
      es: "Academia internacional de tenis fundada por la leyenda Guillermo Vilas, con 10 pistas de tierra batida y 4 pistas rápidas en Palmanova.",
      en: "World-class tennis academy founded by tennis legend Guillermo Vilas, featuring 10 red clay courts and 4 hard courts in Palmanova.",
      ca: "Acadèmia internacional de tennis fundada per Guillermo Vilas a Palmanova amb 10 pistes de terra batuda.",
      de: "Internationale Tennisakademie der Tennislegende Guillermo Vilas in Palmanova mit 10 Sandplätzen und 4 Hartplätzen.",
    },
    fullDesc: {
      es: "Situada a solo 100 metros de la playa de Palmanova, Vilas Tennis Academy es uno de los centros de alto rendimiento más prestigiosos de Europa para jugadores profesionales, programas intensivos de juniors y campus vacacionales para adultos.",
      en: "Located just 100 meters from Palmanova beach, offering elite high-performance training camps for ATP/WTA aspiring juniors and recreational holiday clinics for adult tennis enthusiasts.",
      ca: "Centre d'alt rendiment a 100 metres de la platja de Palmanova per a tennistes de totes les edats.",
      de: "Nur 100 Meter vom Strand entfernt bietet die Akademie professionelles Training auf höchstem Niveau, Ferien-Tenniscamps und Platzvermietung.",
    },
    highlights: {
      es: [
        "10 pistas de tierra batida roja profesional y 4 pistas duras US Open",
        "Metodología de entrenamiento desarrollada por el campeón de Grand Slam Guillermo Vilas",
        "Ubicación privilegiada a 1 minuto a pie de la playa de Palmanova",
      ],
      en: [
        "10 professional red clay courts and 4 US Open standard hard courts",
        "Training methodology crafted by Grand Slam champion Guillermo Vilas",
        "Prime location just a 1-minute walk from the Mediterranean beach",
      ],
      ca: ["10 pistes de terra batuda i 4 ràpides", "Metodologia Guillermo Vilas", "A 1 minut a peu de la platja"],
      de: [
        "10 professionelle Rotsandplätze und 4 US-Open-Hartplätze",
        "Trainingskonzept von Grand-Slam-Sieger Guillermo Vilas",
        "Nur 1 Gehminute zum Strand von Palmanova",
      ],
    },
    specialties: {
      es: [
        "Programas de Alto Rendimiento para Competición",
        "Adult Tennis Holiday Camps (Semanal y Fin de Semana)",
        "Clases Particulares con Entrenadores Certificados ATP/ITF",
      ],
      en: [
        "Junior High-Performance Competition Programs",
        "Adult Tennis Holiday Camps & Weekend Clinics",
        "Private 1-on-1 Lessons with ATP/ITF Certified Coaches",
      ],
      ca: ["Programes d'Alt Rendiment", "Campus de Tennis per a Adults", "Classes Particulars amb Entrenadors ATP"],
      de: [
        "Leistungstraining für Turnierspieler",
        "Erwachsenen-Tenniscamps & Wochenendkurse",
        "Einzeltraining mit lizenzierten ATP/ITF-Trainern",
      ],
    },
    servicesProvided: {
      es: [
        "Alquiler de pistas de tenis por horas",
        "Gimnasio de preparación física y fisioterapia deportiva",
        "Tienda Pro-Shop y servicio de encordado de raquetas",
      ],
      en: [
        "Hourly tennis court hire with online booking",
        "Fitness training gym and sports physiotherapy",
        "Pro-Shop with 24h racket stringing service",
      ],
      ca: ["Lloguer de pistes de tennis", "Gimnàs de preparació física", "Botiga Pro-Shop i encordament"],
      de: [
        "Stundenweise Platzmiete",
        "Fitnessstudio für Athletiktraining & Sportphysio",
        "Pro-Shop mit 24h-Besaitungsservice",
      ],
    },
    faq: {
      q: {
        es: "¿Se pueden alquilar pistas sin ser socio del club?",
        en: "Can non-members book courts?",
        ca: "Es poden llogar pistes sense ser soci?",
        de: "Können auch Nicht-Mitglieder Tennisplätze buchen?",
      },
      a: {
        es: "Sí, las pistas están abiertas a residentes y visitantes con reserva previa por horas.",
        en: "Yes, courts are available for non-members and tourists on an hourly rental basis.",
        ca: "Sí, obert a tothom amb reserva prèvia.",
        de: "Ja, Plätze können ganzjährig stundenweise von Gästen gebucht werden.",
      },
    },
    badge: {
      es: "Academia de Tenis de Prestigio Internacional (Calvià)",
      en: "Internationally Acclaimed Tennis Academy (Calvià)",
      ca: "Acadèmia de Tennis de Prestigi Internacional (Calvià)",
      de: "Internationale Spitzen-Tennisakademie (Calvià)",
    },
    confidenceScore: 99,
  },

  // ─── 6. ARTESANÍA & COMERCIOS HISTÓRICOS ──────────────────────────────────
  {
    id: "carmina-shoemaker-inca-palma",
    slug: "carmina-shoemaker-inca-palma",
    name: "Carmina Shoemaker (Inca / Palma - 1866)",
    category: "arte-tatuajes",
    sectorId: "arte-cultura",
    zone: "palma",
    address: "Passeig del Born, 26, 07012 Palma, Illes Balears",
    coordinates: { lat: 39.5708, lng: 2.6472 },
    rating: 4.9,
    reviewCount: 430,
    priceRange: "€€€€",
    phone: "+34 971 71 85 89",
    website: "https://carminashoemaker.com",
    email: "customerservice@carminashoemaker.com",
    tags: ["zona:palma", "mod:cita-previa", "product:premium"],
    schedule: "Lunes a Sábado: 10:30 - 20:30 | Domingos cerrado",
    shortDesc: {
      es: "Maestros zapateros artesanos de Mallorca desde 1866, referentes mundiales en calzado Goodyear Welted cosido a mano con pieles nobles.",
      en: "Mallorca's world-renowned master shoemakers crafting exquisite Goodyear-welted leather footwear since 1866.",
      ca: "Mestres sabaters artesans de Mallorca des de 1866, referents mundials en calçat Goodyear Welted cusut a mà.",
      de: "Mallorquinische Schuhmacherkunst seit 1866: Weltweit renommierte rahmengenähte Goodyear-Welted-Schuhe aus edelstem Leder.",
    },
    fullDesc: {
      es: "Fundada por Matías Pujadas en Inca y continuada por 4 generaciones de la familia Albaladejo, Carmina elabora artesanalmente en Mallorca zapatos de piel de potro Cordovan, becerro francés y antes de lujo para boutiques de Nueva York, París y Tokio.",
      en: "Founded in 1866 in Inca, Carmina is universally celebrated by shoe connoisseurs for its Shell Cordovan dress shoes, handcrafted lasts, and bespoke footwear.",
      ca: "Fundada a Inca el 1866 per la família Albaladejo amb botigues a París, Nova York i Tòquio.",
      de: "Seit 1866 steht Carmina für handwerkliche Perfektion aus Inca. Berühmt für exklusive Shell-Cordovan-Schuhe und feinstes Kalbsleder.",
    },
    highlights: {
      es: [
        "Más de 160 años de tradición zapatera artesanal ininterrumpida en Mallorca",
        "Uso de pieles exclusivas Shell Cordovan de curtición vegetal y becerros franceses",
        "Cosido Goodyear Welted artesanal con más de 190 pasos manuales por par",
      ],
      en: [
        "Over 160 years of artisanal footwear heritage handcrafted in Mallorca",
        "World-renowned Shell Cordovan horsehide and premium French calf leathers",
        "Traditional Goodyear welted construction involving over 190 manual operations",
      ],
      ca: [
        "Més de 160 anys de tradició sabatera artesana a Mallorca",
        "Pells nobles Shell Cordovan",
        "Construcció artesana Goodyear Welted",
      ],
      de: [
        "Über 160 Jahre Schuhmachertradition aus Inca",
        "Feinstes Shell-Cordovan-Pferdeleder und französisches Kalbsleder",
        "Aufwendige Goodyear-Rahmennaht mit über 190 Einzelschritten",
      ],
    },
    specialties: {
      es: [
        "Zapatos Goodyear Welted de Shell Cordovan",
        "Mocasines y Zapatos Oxford Cosidos a Mano",
        "Calzado a Medida (Custom & Bespoke)",
      ],
      en: [
        "Genuine Shell Cordovan Goodyear Welted Shoes",
        "Hand-stitched Loafers and Classic Oxfords",
        "Custom Made-to-Order and Bespoke Service",
      ],
      ca: ["Calçat Goodyear Welted de Shell Cordovan", "Mocassins i Oxfords fets a mà", "Sabates a mida"],
      de: [
        "Rahmengenähte Shell-Cordovan-Schuhe",
        "Klassische handgenähte Oxfords & Loafer",
        "Custom Made-to-Order & Maßschuhe",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de calzado artesanal en boutique del Born",
        "Servicio personalizado de personalización de pieles y suelas",
        "Mantenimiento, cambio de suelas y restauración de calzado Carmina",
      ],
      en: [
        "Artisanal footwear sales at flagship Born boutique",
        "Custom leather, sole, and last personalization service",
        "Factory resoling and leather restoration service",
      ],
      ca: [
        "Venda a la boutique del Passeig del Born",
        "Personalització de pells i soles",
        "Servei de resolat i restauració",
      ],
      de: [
        "Flagship-Store am Passeig del Born",
        "Personalisierung von Leder, Sohlen und Leisten",
        "Reparatur-, Neubesohlungs- und Pflegeservice",
      ],
    },
    faq: {
      q: {
        es: "¿Dónde se fabrican los zapatos Carmina?",
        en: "Where are Carmina shoes manufactured?",
        ca: "On es fabriquen les sabates Carmina?",
        de: "Wo werden Carmina Schuhe hergestellt?",
      },
      a: {
        es: "El 100% de los zapatos Carmina se elaboran artesanalmente en la fábrica histórica de la marca en Inca (Mallorca).",
        en: "100% of Carmina shoes are handcrafted in the brand's historic workshop in Inca, Mallorca.",
        ca: "El 100% es fabrica a mà a la factoria d'Inca (Mallorca).",
        de: "100% aller Carmina-Schuhe werden in der historischen Manufaktur in Inca (Mallorca) von Hand gefertigt.",
      },
    },
    badge: {
      es: "Maestros Zapateros de Lujo Internacional (1866)",
      en: "Master Artisanal Shoemakers (1866)",
      ca: "Mestres Sabaters de Lletra i Ofici (1866)",
      de: "Luxus-Schuhmachermeister seit 1866",
    },
    confidenceScore: 99,
  },
];

export async function runBatch1Ingestion() {
  console.log(`Starting Batch 1 Ingestion of ${BATCH_1_SEEDS.length} curated businesses...`);
  for (const seed of BATCH_1_SEEDS) {
    writeServiceModule(seed);
  }
  console.log(`✅ Batch 1 written to disk.`);
}

runBatch1Ingestion().catch(console.error);
