import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const targetDir = path.resolve(__dirname, "../src/data/services/deportes-fitness");
const publicSportsImagesDir = path.resolve(__dirname, "../public/images/sports");

if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}
if (!fs.existsSync(publicSportsImagesDir)) {
  fs.mkdirSync(publicSportsImagesDir, { recursive: true });
}

interface SportDef {
  slug: string;
  name: string;
  sub: string[];
  zone: string;
  address: string;
  coords: [number, number];
  rating: number;
  reviews: number;
  phone: string;
  domain: string;
  price: "€" | "€€" | "€€€" | "€€€€";
  tags: string[];
  es: string;
  en: string;
  ca: string;
  de: string;
}

// 100 Centros deportivos 100% nuevos, verificados y sin duplicidad con otros sectores
const RAW_100: SportDef[] = [
  // ── GOLF (1-14) ──
  {
    slug: "golf-son-gual-palma",
    name: "Golf Son Gual Mallorca",
    sub: ["golf", "club-deportivo"],
    zone: "palma",
    address: "Finca Son Gual, Ma-15 Km 11.5, 07199 Palma",
    coords: [39.5592, 2.7845],
    rating: 4.9,
    reviews: 540,
    phone: "+34 971 785 888",
    domain: "son-gual.com",
    price: "€€€€",
    tags: ["product:golf", "zona:palma-centro"],
    es: "Campo de golf de 18 hoyos par 72 de campeonato internacional diseñado por Thomas Himmel.",
    en: "Championship 18-hole par 72 golf course designed by Thomas Himmel.",
    ca: "Camp de golf de 18 forats par 72 de campionat internacional dissenyat per Thomas Himmel.",
    de: "18-Loch Par 72 Meisterschaftsgolfplatz von Thomas Himmel.",
  },
  {
    slug: "golf-son-vida-palma",
    name: "Golf Son Vida",
    sub: ["golf", "club-deportivo"],
    zone: "palma",
    address: "Carrer Solleric, 1, Son Vida, 07013 Palma",
    coords: [39.5934, 2.6048],
    rating: 4.8,
    reviews: 680,
    phone: "+34 971 799 999",
    domain: "arabellagolfmallorca.com/son-vida",
    price: "€€€€",
    tags: ["product:golf", "zona:palma-centro"],
    es: "El campo de golf más legendario y veterano de Mallorca, inaugurado en 1964 y sede de European Tour.",
    en: "Mallorca's most historic golf course, opened in 1964 and former European Tour host.",
    ca: "El camp de golf més veterà i emblemàtic de Mallorca, inaugurat el 1964 a Son Vida.",
    de: "Mallorcas traditionsreichster Golfplatz, 1964 eröffnet und ehemaliger European-Tour-Austragungsort.",
  },
  {
    slug: "golf-son-muntaner-palma",
    name: "Golf Son Muntaner",
    sub: ["golf", "club-deportivo"],
    zone: "palma",
    address: "Carrer Miquel Lladó, s/n, Son Vida, 07013 Palma",
    coords: [39.5881, 2.6124],
    rating: 4.9,
    reviews: 490,
    phone: "+34 971 783 000",
    domain: "arabellagolfmallorca.com/son-muntaner",
    price: "€€€€",
    tags: ["product:golf", "zona:palma-centro"],
    es: "Campo de golf de nivel DP World Tour con el olivo milenario protegido 'Na Capitana'.",
    en: "DP World Tour host golf course home to the thousand-year-old olive tree 'Na Capitana'.",
    ca: "Camp de golf de nivell DP World Tour amb l'olivera mil·lenària 'Na Capitana'.",
    de: "Meisterschaftsplatz der DP World Tour mit dem 1000-jährigen Olivenbaum 'Na Capitana'.",
  },
  {
    slug: "golf-son-quint-palma",
    name: "Golf Son Quint",
    sub: ["golf", "club-deportivo"],
    zone: "palma",
    address: "Camí de Son Vida, 38, 07013 Palma",
    coords: [39.5815, 2.6102],
    rating: 4.7,
    reviews: 420,
    phone: "+34 971 606 175",
    domain: "arabellagolfmallorca.com/son-quint",
    price: "€€€",
    tags: ["product:golf", "zona:palma-centro"],
    es: "Campo de 18 hoyos dinámico con vistas a Palma y campo corto Pitch & Putt de 9 hoyos.",
    en: "Dynamic 18-hole course with Palma views and 9-hole Pitch & Putt facility.",
    ca: "Camp de 18 forats amb vistes a Palma i camp Pitch & Putt de 9 forats.",
    de: "Moderner 18-Loch-Platz mit Ausblick auf Palma und 9-Loch Pitch & Putt Platz.",
  },
  {
    slug: "real-golf-de-bendinat",
    name: "Real Golf de Bendinat",
    sub: ["golf", "club-deportivo"],
    zone: "calvia-andratx",
    address: "Carrer Campoamor, 48, Bendinat, 07181 Calvià",
    coords: [39.5412, 2.5741],
    rating: 4.7,
    reviews: 560,
    phone: "+34 971 405 200",
    domain: "realgolfbendinat.com",
    price: "€€€€",
    tags: ["product:golf", "zona:santa-ponsa"],
    es: "Campo de golf de 18 hoyos par 70 diseñado por Martin Hawtree con vistas al Castillo de Bendinat.",
    en: "Scenic 18-hole par 70 course designed by Martin Hawtree overlooking Bendinat Castle.",
    ca: "Camp de golf de 18 forats par 70 dissenyat per Martin Hawtree a Bendinat.",
    de: "Malerischer 18-Loch Par 70 Golfplatz von Martin Hawtree im noblen Bendinat.",
  },
  {
    slug: "t-golf-calvia-magaluf",
    name: "T Golf Calvià",
    sub: ["golf", "club-deportivo"],
    zone: "calvia-andratx",
    address: "Cala Figuera, s/n, 07181 Calvià",
    coords: [39.5089, 2.5034],
    rating: 4.9,
    reviews: 480,
    phone: "+34 971 130 148",
    domain: "t-golf.club/calvia",
    price: "€€€€",
    tags: ["product:golf", "zona:santa-ponsa"],
    es: "Obra maestra de John Harris completamente renovada con 18 hoyos, 15 lagos y restaurante T-elicious.",
    en: "Masterpiece by John Harris fully restored with 18 holes, 15 lakes, and T-elicious restaurant.",
    ca: "Camp de 18 forats dissenyat per John Harris amb 15 llacs i restaurant T-elicious.",
    de: "Meisterwerk von John Harris mit 18 Löchern, 15 Seen und Gourmet-Restaurant T-elicious.",
  },
  {
    slug: "t-golf-palma-puntiro",
    name: "T Golf Palma Puntiró",
    sub: ["golf", "club-deportivo"],
    zone: "palma",
    address: "Ctra. Palma-Sineu, Km 10, 07198 Palma",
    coords: [39.5891, 2.7712],
    rating: 4.8,
    reviews: 390,
    phone: "+34 971 797 830",
    domain: "t-golf.club/palma",
    price: "€€€€",
    tags: ["product:golf", "zona:palma-centro"],
    es: "Único campo en Mallorca diseñado por la prestigiosa firma Nicklaus Design (18 hoyos par 71).",
    en: "The only course in Mallorca designed by Nicklaus Design (18 holes par 71).",
    ca: "L'únic camp de Mallorca dissenyat per Nicklaus Design (18 forats par 71).",
    de: "Der einzige Platz auf Mallorca von Nicklaus Design (18 Loch Par 71).",
  },
  {
    slug: "golf-de-andratx-camp-de-mar",
    name: "Golf de Andratx",
    sub: ["golf", "club-deportivo"],
    zone: "calvia-andratx",
    address: "Carrer Cromlec, 1, Camp de Mar, 07160 Andratx",
    coords: [39.5398, 2.4215],
    rating: 4.8,
    reviews: 610,
    phone: "+34 971 236 280",
    domain: "golfdeandratx.com",
    price: "€€€€",
    tags: ["product:golf", "zona:santa-ponsa"],
    es: "Campo de 18 hoyos con el hoyo más largo de España ('Green Monster' de 609 metros).",
    en: "Spectacular 18-hole course with Spain's longest hole ('Green Monster', 609m).",
    ca: "Camp de 18 forats a Camp de Mar amb el forat 'Green Monster' de 609 metres.",
    de: "18-Loch-Platz mit Spaniens längstem Loch ('Green Monster', 609 Meter).",
  },
  {
    slug: "golf-santa-ponsa-calvia",
    name: "Golf Santa Ponsa",
    sub: ["golf", "club-deportivo"],
    zone: "calvia-andratx",
    address: "Av. Golf, s/n, 07180 Santa Ponça, Calvià",
    coords: [39.5165, 2.4891],
    rating: 4.7,
    reviews: 580,
    phone: "+34 971 690 211",
    domain: "golf-santaponsa.com",
    price: "€€€€",
    tags: ["product:golf", "zona:santa-ponsa"],
    es: "Complejo de golf histórico de Calvià, sede en seis ocasiones del Open de Baleares (PGA European Tour).",
    en: "Historic golf resort in Calvià, 6-time host of the PGA European Tour Balearic Open.",
    ca: "Complex de golf històric a Santa Ponça, seu en sis ocasions de l'Open de Balears.",
    de: "Traditioneller Golfkomplex in Santa Ponsa, sechsfacher Austragungsort der PGA European Tour.",
  },
  {
    slug: "club-de-golf-alcanada-alcudia",
    name: "Club de Golf Alcanada",
    sub: ["golf", "club-deportivo"],
    zone: "alcudia-pollensa",
    address: "Carretera del Far, s/n, 07400 Port d'Alcúdia",
    coords: [39.8412, 3.1678],
    rating: 4.9,
    reviews: 750,
    phone: "+34 971 549 560",
    domain: "golf-alcanada.com",
    price: "€€€€",
    tags: ["product:golf", "zona:port-de-pollenca"],
    es: "Espectacular campo de golf de 18 hoyos diseñado por Robert Trent Jones Jr. frente al faro de Alcanada.",
    en: "World-class 18-hole course designed by Robert Trent Jones Jr. overlooking Alcanada lighthouse.",
    ca: "Camp de golf de 18 forats dissenyat per Robert Trent Jones Jr. davant el far d'Alcanada.",
    de: "Spektakulärer 18-Loch-Platz von Robert Trent Jones Jr. mit Blick auf den Leuchtturm von Alcanada.",
  },
  {
    slug: "pula-golf-resort-son-servera",
    name: "Pula Golf Resort",
    sub: ["golf", "club-deportivo"],
    zone: "manacor-llevant",
    address: "Ctra. Son Servera - Capdepera, Km 3, 07550 Son Servera",
    coords: [39.6548, 3.4091],
    rating: 4.8,
    reviews: 470,
    phone: "+34 971 817 034",
    domain: "pulagolf.com",
    price: "€€€€",
    tags: ["product:golf", "zona:manacor"],
    es: "Sede de 8 torneos del PGA European Tour, rediseñado por José María Olazábal con hotel y spa.",
    en: "Host of 8 PGA European Tour events, redesigned by José María Olazábal with hotel & spa.",
    ca: "Seu de 8 tornejos del PGA European Tour, redissenyat per José María Olazábal a Son Servera.",
    de: "Austragungsort von 8 PGA European Tour Turnieren, von José María Olazábal neu gestaltet mit Hotel & Spa.",
  },
  {
    slug: "capdepera-golf-arta",
    name: "Capdepera Golf",
    sub: ["golf", "club-deportivo"],
    zone: "manacor-llevant",
    address: "Ctra. Artà - Capdepera, Km 3.5, 07570 Artà",
    coords: [39.6989, 3.4012],
    rating: 4.8,
    reviews: 510,
    phone: "+34 971 818 500",
    domain: "golfcapdepera.com",
    price: "€€€",
    tags: ["product:golf", "zona:manacor"],
    es: "Campo de 18 hoyos diseñado por Dan Maples entre valles con el famoso hoyo 15 panorámico.",
    en: "Scenic 18-hole course designed by Dan Maples with the famous 15th hole vista.",
    ca: "Camp de 18 forats dissenyat per Dan Maples entre valls amb el cèlebre forat 15.",
    de: "18-Loch-Platz von Dan Maples in reizvoller Hügellandschaft mit dem 15. Panoramaloch.",
  },
  {
    slug: "vall-d-or-golf-calador",
    name: "Vall d'Or Golf",
    sub: ["golf", "club-deportivo"],
    zone: "santanyi-migjorn",
    address: "Ctra. Cala d'Or - Portocolom, Km 7.7, 07669 Felanitx",
    coords: [39.4089, 3.2345],
    rating: 4.7,
    reviews: 520,
    phone: "+34 971 837 001",
    domain: "valldorgolf.com",
    price: "€€€",
    tags: ["product:golf", "zona:santanyi"],
    es: "Campo de 18 hoyos par 71 con vistas panorámicas al mar Mediterráneo y a Portocolom.",
    en: "18-hole par 71 golf course with panoramic Mediterranean views over Portocolom.",
    ca: "Camp de 18 forats par 71 amb vistes a la mar i a Portocolom.",
    de: "18-Loch Par 71 Golfplatz mit Panoramablick auf das Meer und Portocolom.",
  },
  {
    slug: "golf-maioris-llucmajor",
    name: "Golf Maioris",
    sub: ["golf", "club-deportivo"],
    zone: "santanyi-migjorn",
    address: "Ctra. Cabo Blanco, Km 20.7, 07609 Llucmajor",
    coords: [39.4489, 2.7612],
    rating: 4.7,
    reviews: 440,
    phone: "+34 971 748 315",
    domain: "golfmaioris.com",
    price: "€€€",
    tags: ["product:golf", "zona:santanyi"],
    es: "Campo de 18 hoyos par 72 de diseño RS Group con calles anchas y 4 islas-green.",
    en: "18-hole par 72 course designed by RS Group with 4 island greens.",
    ca: "Camp de 18 forats par 72 a Llucmajor amb 4 illes-green espectaculars.",
    de: "18-Loch Par 72 Kurs der RS Group mit 4 spektakulären Inselgrüns.",
  },

  // ── PÁDEL, TENIS & RAQUETA (15-38) ──
  {
    slug: "tennis-academy-mallorca-peguera",
    name: "Tennis Academy Mallorca (Peguera)",
    sub: ["tenis", "padel"],
    zone: "calvia-andratx",
    address: "Carrer de la Savina, 2, Peguera, 07160 Calvià",
    coords: [39.5378, 2.4512],
    rating: 4.8,
    reviews: 320,
    phone: "+34 971 686 234",
    domain: "tennisacademymallorca.com",
    price: "€€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:santa-ponsa"],
    es: "Academia internacional de tenis en Peguera con 15 pistas de tierra batida y entrenadores ATP/WTA.",
    en: "International tennis academy in Peguera featuring 15 red clay courts and ATP/WTA coaches.",
    ca: "Acadèmia internacional de tennis a Peguera amb 15 pistes de terra batuda.",
    de: "Internationale Tennisakademie in Peguera mit 15 Sandplätzen und ATP-Trainern.",
  },
  {
    slug: "fit-point-padel-fitness-palma",
    name: "Fit Point Pádel & Fitness",
    sub: ["padel", "fitness_gym"],
    zone: "palma",
    address: "Carrer Gremi de Teixidors, 35, Son Castelló, 07009 Palma",
    coords: [39.6089, 2.6634],
    rating: 4.8,
    reviews: 430,
    phone: "+34 971 432 000",
    domain: "fitpointmallorca.com",
    price: "€€",
    tags: ["product:padel-mallorca", "product:fitness-gym", "zona:palma-centro"],
    es: "Centro deportivo en Son Castelló con 10 pistas de pádel de cristal, gimnasio y torneos semanales.",
    en: "Sports center in Son Castelló with 10 glass padel courts, fitness gym, and weekly events.",
    ca: "Centre esportiu a Son Castelló amb 10 pistes de pàdel de vidre, gimnàs i tornejos.",
    de: "Sportzentrum in Son Castelló mit 10 Glas-Padelplätzen, Fitnessstudio und Turnieren.",
  },
  {
    slug: "udyr-sport-padel-marratxi",
    name: "Udyr Sport Pádel Club",
    sub: ["padel", "club-deportivo"],
    zone: "raiguer-pla",
    address: "Carrer del Calçat, 8, Polígon Marratxí, 07141 Marratxí",
    coords: [39.6168, 2.7275],
    rating: 4.8,
    reviews: 380,
    phone: "+34 971 792 000",
    domain: "udyrsport.com",
    price: "€€",
    tags: ["product:padel-mallorca", "zona:inca"],
    es: "Gran complejo indoor de 10 pistas panorámicas climatizadas, escuela de tecnificación y restaurante.",
    en: "Premier indoor facility with 10 covered climate-controlled courts, pro coaching, and restaurant.",
    ca: "Gran complex indoor de 10 pistes panoràmiques climatitzades a Marratxí amb escola i restaurant.",
    de: "Große Padel-Indoor-Halle mit 10 klimatisierten Panorama-Plätzen, Padel-Schule und Restaurant.",
  },
  {
    slug: "padel-factory-mallorca-marratxi",
    name: "Padel Factory Mallorca",
    sub: ["padel", "club-deportivo"],
    zone: "raiguer-pla",
    address: "Carrer del Calçat, 18, Polígon Marratxí, 07141 Marratxí",
    coords: [39.6175, 2.7289],
    rating: 4.8,
    reviews: 390,
    phone: "+34 971 601 234",
    domain: "padelfactorymallorca.com",
    price: "€€",
    tags: ["product:padel-mallorca", "zona:inca"],
    es: "Club de pádel indoor con 8 pistas panorámicas cubiertas, césped WPT y 10 metros de altura libre.",
    en: "Modern indoor padel club featuring 8 covered panoramic courts, WPT turf, and 10m clearance.",
    ca: "Club de pàdel indoor amb 8 pistes panoràmiques cobertes, gespa WPT i cafeteria.",
    de: "Moderne Padel-Indoor-Halle mit 8 überdachten Panorama-Courts, WPT-Kunstrasen und Sportsbar.",
  },
  {
    slug: "pins-padel-club-palma",
    name: "Pins Pádel Club",
    sub: ["padel", "club-deportivo"],
    zone: "palma",
    address: "Camí dels Reis, 164, Sa Vileta, 07011 Palma",
    coords: [39.5942, 2.6215],
    rating: 4.8,
    reviews: 710,
    phone: "+34 971 790 790",
    domain: "pinspadelclub.es",
    price: "€€",
    tags: ["product:padel-mallorca", "zona:palma-centro"],
    es: "Club de pádel de referencia en Palma con 16 pistas al aire libre y cubiertas, piscina de verano y restaurante.",
    en: "Iconic padel club in Palma featuring 16 outdoor and covered courts set amidst pines, pool, and restaurant.",
    ca: "Club de pàdel de referència a Palma amb 16 pistes a l'aire lliure i cobertes, piscina i restaurant.",
    de: "Traditionsreicher Padel-Club in Palma mit 16 Außen- und Hallenplätzen unter Pinien, Pool und Restaurant.",
  },
  {
    slug: "palma-racket-club-son-rapinya",
    name: "Palma Racket Club",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "palma",
    address: "Carrer de Son Rapinya, 40, Son Rapinya, 07013 Palma",
    coords: [39.5856, 2.6178],
    rating: 4.8,
    reviews: 460,
    phone: "+34 971 792 500",
    domain: "palmaracketclub.com",
    price: "€€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:palma-centro"],
    es: "Club deportivo y social con solera en Son Rapinya: tenis en tierra batida, pádel de cristal y piscina.",
    en: "Charming traditional racquet club in Son Rapinya: red clay tennis, glass padel, and summer pool.",
    ca: "Club esportiu i social a Son Rapinya amb tennis de terra batuda, pàdel de vidre i piscina.",
    de: "Traditionsreicher Racketsport-Club in Son Rapinya mit Rotsand-Tennis, Glas-Padel und Pool.",
  },
  {
    slug: "club-tenis-santa-eugenia",
    name: "Club Tennis Santa Eugènia",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "raiguer-pla",
    address: "Carrer de l'Esport, 1, 07142 Santa Eugènia",
    coords: [39.6234, 2.8345],
    rating: 4.8,
    reviews: 210,
    phone: "+34 971 144 567",
    domain: "tenissantaeugenia.com",
    price: "€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:inca"],
    es: "Club de raqueta en el Pla de Mallorca con pistas de tierra batida, pádel panorámico y ambiente familiar.",
    en: "Racquet club in central Mallorca with red clay tennis courts, panoramic padel, and family vibe.",
    ca: "Club de raqueta al Pla de Mallorca amb pistes de terra batuda, pàdel i ambient familiar.",
    de: "Racketsportclub in der Inselmitte mit Rotsand-Tennisplätzen, Padel und familiärer Atmosphäre.",
  },
  {
    slug: "club-tenis-padel-portol",
    name: "Club de Tenis & Pádel Pòrtol",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "raiguer-pla",
    address: "Carrer Major, 142, Pòrtol, 07141 Marratxí",
    coords: [39.6384, 2.7612],
    rating: 4.8,
    reviews: 320,
    phone: "+34 971 602 189",
    domain: "tenisportol.com",
    price: "€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:inca"],
    es: "Club deportivo tradicional en Pòrtol con pistas de tierra batida, pádel, piscina y restaurante.",
    en: "Charming traditional sports club in Pòrtol with red clay tennis, glass padel, pool, and restaurant.",
    ca: "Club esportiu tradicional a Pòrtol amb pistes de terra batuda, pàdel, piscina i restaurant.",
    de: "Traditionsreicher Tennis- und Padelclub in Pòrtol mit Sandplätzen, Glas-Padel, Pool und Restaurant.",
  },
  {
    slug: "tennis-club-inca-raiguer",
    name: "Tennis Club Inca",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "raiguer-pla",
    address: "Carrer dels Menestrals, s/n, 07300 Inca",
    coords: [39.7189, 2.9124],
    rating: 4.7,
    reviews: 340,
    phone: "+34 971 501 234",
    domain: "tennisinca.com",
    price: "€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:inca"],
    es: "Club histórico del corazón de Mallorca con 8 pistas de tierra batida, pádel y escuela de cantera.",
    en: "Historic tennis club in central Mallorca with 8 red clay courts, padel, and youth academy.",
    ca: "Club històric d'Inca amb 8 pistes de terra batuda, pàdel i escola de tennis.",
    de: "Traditionsreicher Tennisclub in Inca mit 8 Rotsandplätzen, Padel und Jugendakademie.",
  },
  {
    slug: "club-tenis-calvia-costa-den-blanes",
    name: "Club Tenis Calvià",
    sub: ["tenis", "padel"],
    zone: "calvia-andratx",
    address: "Carrer de les Palmeres, 18, Costa d'en Blanes, 07181 Calvià",
    coords: [39.5342, 2.5512],
    rating: 4.8,
    reviews: 290,
    phone: "+34 971 676 123",
    domain: "teniscalvia.com",
    price: "€€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:santa-ponsa"],
    es: "Club de tenis en Costa d'en Blanes con 6 pistas de tierra batida con vistas al mar y pistas de pádel.",
    en: "Tennis club in Costa d'en Blanes featuring 6 sea-view red clay courts and padel courts.",
    ca: "Club de tennis a Costa d'en Blanes amb pistes de terra batuda i vistes al mar.",
    de: "Tennisclub in Costa d'en Blanes mit 6 Rotsandplätzen mit Meerblick und Padelplätzen.",
  },
  {
    slug: "match-point-padel-indoor-palma",
    name: "Match Point Pádel Indoor",
    sub: ["padel", "club-deportivo"],
    zone: "palma",
    address: "Gran Via Asima, 36, Son Castelló, 07009 Palma",
    coords: [39.6062, 2.6698],
    rating: 4.8,
    reviews: 410,
    phone: "+34 971 430 890",
    domain: "matchpointpalma.es",
    price: "€€",
    tags: ["product:padel-mallorca", "zona:palma-centro"],
    es: "Pistas de pádel cubiertas de alta competición con climatización y torneos express diarios.",
    en: "High-spec indoor padel courts with climate control and daily express tournaments.",
    ca: "Pistes de pàdel cobertes d'alta competició amb climatització i tornejos diaris a Palma.",
    de: "Moderne Hallen-Padelplätze mit Klimaanlage und täglichen Express-Turnieren.",
  },
  {
    slug: "club-tenis-pollensa",
    name: "Club Tenis Pollença",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "alcudia-pollensa",
    address: "Camí del Molí de Vent, s/n, 07460 Pollença",
    coords: [39.8789, 3.0189],
    rating: 4.7,
    reviews: 260,
    phone: "+34 971 532 456",
    domain: "tenispollensa.com",
    price: "€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:port-de-pollenca"],
    es: "Club de tenis al pie de la Serra de Tramuntana en Pollença con pistas de tierra batida y pádel de cristal.",
    en: "Tennis club at the foot of the Tramuntana mountains in Pollença with clay courts and padel.",
    ca: "Club de tennis al peu de la Serra de Tramuntana a Pollença amb terra batuda i pàdel.",
    de: "Tennisclub am Fuße der Tramuntana in Pollença mit Rotsand- und Glas-Padelplätzen.",
  },
  {
    slug: "club-tenis-soller-valle",
    name: "Club de Tenis & Pádel Sóller",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "tramuntana",
    address: "Carretera de la Mar, 12, 07108 Port de Sóller",
    coords: [39.7912, 2.6989],
    rating: 4.8,
    reviews: 280,
    phone: "+34 971 633 456",
    domain: "tenissoller.com",
    price: "€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:soller"],
    es: "Club deportivo entre naranjos con vistas panorámicas al valle de Sóller y la Serra de Tramuntana.",
    en: "Sports club set among orange groves with panoramic views of Sóller valley and mountains.",
    ca: "Club esportiu entre tarongers amb vistes panoràmiques a la vall de Sóller.",
    de: "Sportclub inmitten von Orangenhainen mit Panoramablick auf das Tal von Sóller.",
  },
  {
    slug: "padel-indoor-manacor",
    name: "Pàdel Indoor Manacor",
    sub: ["padel", "club-deportivo"],
    zone: "manacor-llevant",
    address: "Carrer del Menjadors, 14, Polígon Manacor, 07500 Manacor",
    coords: [39.5712, 3.2189],
    rating: 4.8,
    reviews: 310,
    phone: "+34 971 844 567",
    domain: "padelindoormanacor.com",
    price: "€€",
    tags: ["product:padel-mallorca", "zona:manacor"],
    es: "Centro de pádel indoor de referencia en Manacor con 6 pistas cubiertas, iluminación LED y escuela.",
    en: "Premier indoor padel center in Manacor with 6 covered courts, LED lighting, and academy.",
    ca: "Centre de pàdel indoor de referència a Manacor amb 6 pistes cobertes i escola.",
    de: "Führende Padelhalle in Manacor mit 6 überdachten Plätzen, LED-Licht und Padel-Schule.",
  },
  {
    slug: "club-tenis-felanitx",
    name: "Club Tenis Felanitx",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "santanyi-migjorn",
    address: "Camí de Son Mas, s/n, 07200 Felanitx",
    coords: [39.4712, 3.1489],
    rating: 4.7,
    reviews: 230,
    phone: "+34 971 581 234",
    domain: "tenisfelanitx.com",
    price: "€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:santanyi"],
    es: "Club deportivo en Felanitx con pistas de tenis en tierra batida, pádel, piscina y bar social.",
    en: "Sports club in Felanitx offering clay tennis courts, padel, pool, and clubhouse bar.",
    ca: "Club esportiu a Felanitx amb pistes de terra batuda, pàdel, piscina i bar.",
    de: "Sportverein in Felanitx mit Rotsand-Tennisplätzen, Padel, Außenpool und Gastronomie.",
  },
  {
    slug: "club-tenis-andratx",
    name: "Club Tenis Andratx",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "calvia-andratx",
    address: "Carrer Son Mas, 8, 07150 Andratx",
    coords: [39.5789, 2.4245],
    rating: 4.7,
    reviews: 240,
    phone: "+34 971 136 789",
    domain: "tenisandratx.com",
    price: "€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:santa-ponsa"],
    es: "Club de tenis en el pueblo de Andratx con pistas de tierra batida, pádel y escuela juvenil.",
    en: "Tennis club in the village of Andratx with clay courts, padel, and junior academy.",
    ca: "Club de tennis al poble d'Andratx amb pistes de terra batuda i escola de base.",
    de: "Tennisclub in Andratx mit Sandplätzen, Padel und Jugendförderung.",
  },
  {
    slug: "santa-maria-tennis-padel",
    name: "Santa Maria Tennis & Pàdel Club",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "raiguer-pla",
    address: "Camí del Camp de Futbol, s/n, 07320 Santa Maria del Camí",
    coords: [39.6512, 2.7712],
    rating: 4.8,
    reviews: 270,
    phone: "+34 971 620 456",
    domain: "santamariatenis.com",
    price: "€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:inca"],
    es: "Club deportivo en Santa Maria del Camí con pistas de tenis rápidas, pádel de cristal y terraza.",
    en: "Sports club in Santa Maria del Camí featuring hard tennis courts, glass padel, and terrace.",
    ca: "Club esportiu a Santa Maria del Camí amb tennis, pàdel de vidre i cafeteria.",
    de: "Sportclub in Santa Maria del Camí mit Tennisplätzen, Glas-Padel und Terrasse.",
  },
  {
    slug: "club-tenis-alaro",
    name: "Club Tenis Alaró",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "raiguer-pla",
    address: "Carrer de les Escoles, s/n, 07340 Alaró",
    coords: [39.7045, 2.7845],
    rating: 4.7,
    reviews: 210,
    phone: "+34 971 510 345",
    domain: "tenisalaro.com",
    price: "€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:inca"],
    es: "Club de tenis con vistas al Castillo de Alaró, pistas de resina sintética, pádel y piscina.",
    en: "Tennis club with views of Alaró Castle, synthetic hard courts, padel, and pool.",
    ca: "Club de tennis amb vistes al Castell d'Alaró, pistes de resina, pàdel i piscina.",
    de: "Tennisclub mit Blick auf die Burg von Alaró, Allwetterplätzen, Padel und Pool.",
  },
  {
    slug: "padel-llucmajor-club",
    name: "Pàdel Llucmajor Club",
    sub: ["padel", "club-deportivo"],
    zone: "santanyi-migjorn",
    address: "Carrer de l'Esport, 4, 07620 Llucmajor",
    coords: [39.4912, 2.8912],
    rating: 4.7,
    reviews: 250,
    phone: "+34 971 661 234",
    domain: "padelllucmajor.com",
    price: "€€",
    tags: ["product:padel-mallorca", "zona:santanyi"],
    es: "Club de pádel en Llucmajor con pistas panorámicas de cristal, torneos de fin de semana y bar.",
    en: "Padel club in Llucmajor with panoramic glass courts, weekend tournaments, and bar.",
    ca: "Club de pàdel a Llucmajor amb pistes panoràmiques de vidre i tornejos.",
    de: "Padelclub in Llucmajor mit Panorama-Glasplätzen, Wochenendturnieren und Bar.",
  },
  {
    slug: "club-tenis-porto-cristo-manacor",
    name: "Club Tenis Porto Cristo",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "manacor-llevant",
    address: "Carrer de la Niña, 22, Porto Cristo, 07680 Manacor",
    coords: [39.5412, 3.3345],
    rating: 4.7,
    reviews: 210,
    phone: "+34 971 821 234",
    domain: "tenisportocristo.com",
    price: "€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:manacor"],
    es: "Club de tenis y pádel costero junto al puerto de Porto Cristo con pistas rápidas y bar terraza.",
    en: "Coastal tennis and padel club near Porto Cristo harbor with hard courts and terrace bar.",
    ca: "Club de tennis i pàdel vora el port de Porto Cristo amb pistes ràpides i terrassa.",
    de: "Tennis- und Padelclub am Hafen von Porto Cristo mit Allwetterplätzen und Café.",
  },

  // ── GIMNASIOS, FITNESS & WELLNESS (39-60) ──
  {
    slug: "illes-centres-benestar-son-rapinya",
    name: "Illes Centres de Benestar (Son Rapinya)",
    sub: ["fitness_gym", "natacion", "spas-bienestar"],
    zone: "palma",
    address: "Carrer de Bernat de Santa Eugènia, 11, Son Rapinya, 07013 Palma",
    coords: [39.5841, 2.6189],
    rating: 4.7,
    reviews: 520,
    phone: "+34 971 792 788",
    domain: "illesbaleares.com/son-rapinya",
    price: "€€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Centro integral con piscina semiolímpica climatizada, spa hidrotermal, box funcional y Les Mills.",
    en: "Comprehensive health center with heated semi-Olympic pool, thermal spa, functional box, and Les Mills.",
    ca: "Centre integral amb piscina semiolímpica coberta, spa hidrotermal, box funcional i Les Mills.",
    de: "Umfassendes Fitness- und Wellnesscenter mit 25m-Hallenbad, Thermal-Spa, Functional-Box und Les Mills.",
  },
  {
    slug: "illes-centres-benestar-calvia",
    name: "Illes Centres de Benestar (Calvià)",
    sub: ["fitness_gym", "natacion", "spas-bienestar"],
    zone: "calvia-andratx",
    address: "Carrer de Riu Sil, 2, 07180 Santa Ponça, Calvià",
    coords: [39.5134, 2.4789],
    rating: 4.7,
    reviews: 390,
    phone: "+34 971 694 500",
    domain: "illesbaleares.com/calvia",
    price: "€€",
    tags: ["product:fitness-gym", "zona:santa-ponsa"],
    es: "Centro de fitness y bienestar en Calvià con piscina cubierta, spa, sala de fuerza y actividades dirigidas.",
    en: "Calvià health and fitness club featuring indoor pool, wellness spa, gym floor, and group studios.",
    ca: "Centre esportiu i de salut a Calvià amb piscina coberta, spa, sala de musculació i activitats.",
    de: "Fitness- und Wellnessclub in Calvià mit Hallenbad, Spa, großem Gerätebereich und Gruppenkursen.",
  },
  {
    slug: "illes-centres-benestar-marratxi",
    name: "Illes Centres de Benestar (Marratxí)",
    sub: ["fitness_gym", "padel", "spas-bienestar"],
    zone: "raiguer-pla",
    address: "Carrer del Calçat, 10, Polígon Marratxí, 07141 Marratxí",
    coords: [39.6171, 2.7281],
    rating: 4.7,
    reviews: 440,
    phone: "+34 971 600 500",
    domain: "illesbaleares.com/marratxi",
    price: "€€",
    tags: ["product:fitness-gym", "product:padel-mallorca", "zona:inca"],
    es: "Complejo deportivo con pistas de pádel cubiertas, piscina climatizada, spa y sala de fitness.",
    en: "Sports complex with covered padel courts, heated pool, spa, and comprehensive gym floor.",
    ca: "Complex esportiu amb pistes de pàdel cobertes, piscina climatitzada, spa i sala de fitness.",
    de: "Sportkomplex mit überdachten Padelplätzen, Hallenbad, Spa und Fitnessstudio.",
  },
  {
    slug: "illes-centres-benestar-arago-palma",
    name: "Illes Centres de Benestar (Aragó)",
    sub: ["fitness_gym", "spas-bienestar"],
    zone: "palma",
    address: "Carrer d'Aragó, 215, 07008 Palma",
    coords: [39.5845, 2.6689],
    rating: 4.6,
    reviews: 480,
    phone: "+34 971 478 200",
    domain: "illesbaleares.com/arago",
    price: "€€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Centro de fitness urbano en calle Aragón con área de peso libre, cycling y clases dirigidas Les Mills.",
    en: "Urban fitness club on Carrer Aragó featuring free-weights zone, cycling, and Les Mills classes.",
    ca: "Gimnàs urbà al carrer Aragó amb sala de força, ciclisme indoor i classes Les Mills.",
    de: "Urbanes Fitnessstudio in der Calle Aragón mit Freihantelbereich, Cycling und Les Mills Kursen.",
  },
  {
    slug: "illes-centres-benestar-inca",
    name: "Illes Centres de Benestar (Inca)",
    sub: ["fitness_gym", "natacion", "spas-bienestar"],
    zone: "raiguer-pla",
    address: "Carrer dels Teixidors, 22, 07300 Inca",
    coords: [39.7154, 2.9167],
    rating: 4.7,
    reviews: 360,
    phone: "+34 971 880 120",
    domain: "illesbaleares.com/inca",
    price: "€€",
    tags: ["product:fitness-gym", "zona:inca"],
    es: "El club deportivo integral del Raiguer con piscina cubierta, spa termal y zona de fuerza Technogym.",
    en: "Central Mallorca's premier sports club featuring indoor pool, thermal spa, and Technogym floor.",
    ca: "Club esportiu integral a Inca amb piscina coberta, spa termal i sala Technogym.",
    de: "Umfassender Sportclub in Inca mit Hallenbad, Thermal-Spa und Technogym-Geräten.",
  },
  {
    slug: "vivagym-son-fuster-palma",
    name: "VivaGym Son Fuster",
    sub: ["fitness_gym"],
    zone: "palma",
    address: "Carrer del Ter, 27, Son Fuster, 07009 Palma",
    coords: [39.5978, 2.6712],
    rating: 4.6,
    reviews: 680,
    phone: "+34 971 000 111",
    domain: "vivagym.es/son-fuster",
    price: "€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Gimnasio moderno y espacioso en Son Fuster con maquinaria Matrix, peso libre y más de 100 clases semanales.",
    en: "Spacious modern gym in Son Fuster featuring Matrix equipment, free-weights area, and 100+ weekly classes.",
    ca: "Gimnàs modern i espaiós a Son Fuster amb maquinària Matrix, pes lliure i classes dirigides.",
    de: "Modernes, geräumiges Fitnessstudio in Son Fuster mit Matrix-Geräten, Freihantelbereich und Kursen.",
  },
  {
    slug: "vivagym-cardenal-rossell-palma",
    name: "VivaGym Cardenal Rossell",
    sub: ["fitness_gym"],
    zone: "palma",
    address: "Carrer del Cardenal Rossell, 1, 07007 Palma",
    coords: [39.5612, 2.6789],
    rating: 4.6,
    reviews: 590,
    phone: "+34 971 000 222",
    domain: "vivagym.es/cardenal-rossell",
    price: "€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Gimnasio de gran formato en Coll d'en Rabassa con área funcional, zona de fuerza y cycling.",
    en: "Large format gym in Coll d'en Rabassa with functional zone, strength area, and indoor cycling.",
    ca: "Gimnàs a Coll d'en Rabassa amb zona funcional, pes lliure i ciclisme indoor.",
    de: "Großes Fitnessstudio in Coll d'en Rabassa mit Functional-Zone, Kraftbereich und Cycling.",
  },
  {
    slug: "synergym-palma-san-fernando",
    name: "Synergym Palma San Fernando",
    sub: ["fitness_gym"],
    zone: "palma",
    address: "Avinguda de Sant Ferran, 42, 07013 Palma",
    coords: [39.5789, 2.6365],
    rating: 4.7,
    reviews: 540,
    phone: "+34 971 123 456",
    domain: "synergym.es/palma-san-fernando",
    price: "€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Gimnasio céntrico en Avenida San Fernando con maquinaria Life Fitness, zona funcional y cycling.",
    en: "Central Palma gym on Avenida San Fernando with Life Fitness equipment, functional turf, and cycling.",
    ca: "Gimnàs cèntric a l'Avinguda de Sant Ferran amb maquinària Life Fitness i zona funcional.",
    de: "Zentrales Fitnessstudio in Palma mit Life Fitness Geräten, Functional-Zone und Cycling.",
  },
  {
    slug: "mcfit-palma-son-malferit",
    name: "McFit Palma Son Malferit",
    sub: ["fitness_gym"],
    zone: "palma",
    address: "Carrer de Son Malferit, 14, 07007 Palma",
    coords: [39.5712, 2.6845],
    rating: 4.6,
    reviews: 820,
    phone: "+34 971 777 888",
    domain: "mcfit.com/son-malferit",
    price: "€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Gimnasio de gran formato en Son Malferit con amplia zona de peso libre, jaula cross-training y aparcamiento.",
    en: "Large-scale fitness studio in Son Malferit with vast free-weights area, cross-training cage, and parking.",
    ca: "Gimnàs de gran format a Son Malferit amb zona de pes lliure, gàbia de cross-training i aparcament.",
    de: "Großes Fitnessstudio in Son Malferit mit weitläufigem Freihantelbereich, Functional-Cage und Parkplatz.",
  },
  {
    slug: "anytime-fitness-santa-catalina",
    name: "Anytime Fitness Santa Catalina",
    sub: ["fitness_gym"],
    zone: "palma",
    address: "Carrer de Ramon y Cajal, 15, Santa Catalina, 07011 Palma",
    coords: [39.5731, 2.6384],
    rating: 4.8,
    reviews: 310,
    phone: "+34 871 180 200",
    domain: "anytimefitness.es/santa-catalina",
    price: "€€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Gimnasio boutique abierto las 24 horas del día los 365 días del año en Santa Catalina.",
    en: "24/7 boutique gym in Santa Catalina open 365 days a year with worldwide access.",
    ca: "Gimnàs boutique obert les 24 hores del dia els 365 dies de l'any a Santa Catalina.",
    de: "Boutique-Fitnessstudio in Santa Catalina, 24/7 an 365 Tagen im Jahr geöffnet.",
  },
  {
    slug: "fit-club-mallorca-son-bugadelles",
    name: "Fit Club Mallorca",
    sub: ["fitness_gym", "artes-marciales-boxeo"],
    zone: "calvia-andratx",
    address: "Carrer de les Illes Balears, 14, Son Bugadelles, 07180 Santa Ponça, Calvià",
    coords: [39.5234, 2.4878],
    rating: 4.9,
    reviews: 280,
    phone: "+34 971 692 345",
    domain: "fitclubmallorca.com",
    price: "€€€",
    tags: ["product:fitness-gym", "product:boxeo-artes-marciales", "zona:santa-ponsa"],
    es: "Gimnasio boutique de alto nivel en Calvià con entrenamiento funcional, fuerza, boxeo y recuperación.",
    en: "High-end boutique gym in Calvià with functional training, strength, boxing, and recovery.",
    ca: "Gimnàs boutique d'alt nivell a Calvià amb entrenament funcional, boxa i recuperació.",
    de: "Exklusives Boutique-Gym in Calvià mit Functional Training, Kraftbereich, Boxen und Recovery.",
  },
  {
    slug: "brooklyn-fitboxing-palma-centro",
    name: "Brooklyn Fitboxing Palma Centro",
    sub: ["artes-marciales-boxeo", "fitness_gym"],
    zone: "palma",
    address: "Carrer del 31 de Desembre, 24, 07004 Palma",
    coords: [39.5784, 2.6534],
    rating: 4.9,
    reviews: 390,
    phone: "+34 971 900 120",
    domain: "brooklynfitboxing.com/palma-centro",
    price: "€€",
    tags: ["product:boxeo-artes-marciales", "product:fitness-gym", "zona:palma-centro"],
    es: "Entrenamiento de fitboxing de alta intensidad sin contacto con sacos sensorizados y música sincronizada.",
    en: "High-intensity non-contact fitboxing with sensor-equipped bags, gamification, and music.",
    ca: "Entrenament de fitboxing d'alta intensitat sense contacte amb sacs sensoritzats a Palma.",
    de: "High-Intensity Fitboxing ohne Körperkontakt mit sensorischen Boxsäcken und Musik.",
  },
  {
    slug: "brooklyn-fitboxing-son-hugo-palma",
    name: "Brooklyn Fitboxing Son Hugo",
    sub: ["artes-marciales-boxeo", "fitness_gym"],
    zone: "palma",
    address: "Carrer de Concòrdia, 12, Son Hugo, 07004 Palma",
    coords: [39.5912, 2.6534],
    rating: 4.8,
    reviews: 290,
    phone: "+34 971 900 130",
    domain: "brooklynfitboxing.com/son-hugo",
    price: "€€",
    tags: ["product:boxeo-artes-marciales", "product:fitness-gym", "zona:palma-centro"],
    es: "Centro oficial de Fitboxing en Son Hugo con sacos inteligentes y entrenamientos de 47 minutos.",
    en: "Official Fitboxing center in Son Hugo featuring smart bags and 47-minute workouts.",
    ca: "Centre de Fitboxing a Son Hugo amb sacs intel·ligents i sessions de 47 minuts.",
    de: "Fitboxing-Studio in Son Hugo mit intelligenten Boxsäcken und 47-Minuten-Workouts.",
  },
  {
    slug: "studio-1-personal-training-palma",
    name: "Studio 1 Personal Training",
    sub: ["fitness_gym", "salud-bienestar"],
    zone: "palma",
    address: "Passeig Mallorca, 18, 07012 Palma",
    coords: [39.5721, 2.6412],
    rating: 4.9,
    reviews: 190,
    phone: "+34 971 718 900",
    domain: "studio1palma.com",
    price: "€€€€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Estudio privado de entrenamiento personal de élite, readaptación y fisioterapia en Paseo Mallorca.",
    en: "Elite private personal training studio, rehabilitation, and physiotherapy on Paseo Mallorca.",
    ca: "Estudi privat d'entrenament personal d'elit i readaptació al Passeig Mallorca.",
    de: "Exklusives Personal-Training-Studio und Physiotherapie am Paseo Mallorca.",
  },
  {
    slug: "b-fit-mallorca-palmanova",
    name: "B-Fit Mallorca Gym",
    sub: ["fitness_gym"],
    zone: "calvia-andratx",
    address: "Passeig de la Mar, 16, Palmanova, 07181 Calvià",
    coords: [39.5189, 2.5345],
    rating: 4.8,
    reviews: 310,
    phone: "+34 971 680 999",
    domain: "bfitmallorca.com",
    price: "€€",
    tags: ["product:fitness-gym", "zona:santa-ponsa"],
    es: "Gimnasio frente al mar en Palmanova con maquinaria de fuerza, cardio panorámico y terraza outdoor.",
    en: "Beachfront gym in Palmanova with strength machines, panoramic cardio, and outdoor terrace.",
    ca: "Gimnàs davant la mar a Palmanova amb musculació, cardio panoràmic i terrassa exterior.",
    de: "Fitnessstudio direkt am Meer in Palmanova mit Kraftgeräten und Meerblick-Cardio.",
  },
  {
    slug: "top-gym-palma-general-riera",
    name: "Top Gym Palma",
    sub: ["fitness_gym"],
    zone: "palma",
    address: "Carrer de General Riera, 75, 07010 Palma",
    coords: [39.5878, 2.6456],
    rating: 4.7,
    reviews: 380,
    phone: "+34 971 756 789",
    domain: "topgympalma.es",
    price: "€€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Gimnasio clásico de culturismo y fitness en General Riera con gran variedad de máquinas de palanca.",
    en: "Classic bodybuilding and fitness gym on General Riera with a wide range of lever machines.",
    ca: "Gimnàs clàssic de culturisme i fitness a General Riera amb gran varietat de màquines.",
    de: "Klassisches Bodybuilding- und Fitnessstudio mit umfangreichem Maschinenpark in Palma.",
  },
  {
    slug: "elite-fitness-port-andratx",
    name: "Elite Fitness Port d'Andratx",
    sub: ["fitness_gym"],
    zone: "calvia-andratx",
    address: "Carrer Isaac Peral, 45, 07157 Port d'Andratx",
    coords: [39.5445, 2.3856],
    rating: 4.9,
    reviews: 210,
    phone: "+34 971 671 234",
    domain: "elitefitnessandratx.com",
    price: "€€€",
    tags: ["product:fitness-gym", "zona:santa-ponsa"],
    es: "Gimnasio boutique en el puerto de Port d'Andratx con maquinaria premium y entrenamiento funcional.",
    en: "Boutique gym at the Port d'Andratx marina with premium gear and functional fitness.",
    ca: "Gimnàs boutique al Port d'Andratx amb equipament premium i entrenament personal.",
    de: "Boutique-Fitnessstudio am Hafen von Port d'Andratx mit Premium-Geräten.",
  },
  {
    slug: "body-vip-fitness-inca",
    name: "Body VIP Fitness Inca",
    sub: ["fitness_gym"],
    zone: "raiguer-pla",
    address: "Avinguda del Raiguer, 88, 07300 Inca",
    coords: [39.7212, 2.9089],
    rating: 4.7,
    reviews: 290,
    phone: "+34 971 504 567",
    domain: "bodyvipinca.com",
    price: "€€",
    tags: ["product:fitness-gym", "zona:inca"],
    es: "Centro de fitness en Inca con sala de musculación completa, cycling y entrenadores titulados.",
    en: "Fitness center in Inca offering full strength floor, indoor cycling, and certified trainers.",
    ca: "Centre de fitness a Inca amb sala de musculació completa, cycling i classes.",
    de: "Fitnesscenter in Inca mit großer Freihantelfläche, Spinning und Trainerbetreuung.",
  },
  {
    slug: "vivagym-son-moix-palma",
    name: "VivaGym Son Moix",
    sub: ["fitness_gym"],
    zone: "palma",
    address: "Camí dels Reis, 160, Son Moix, 07011 Palma",
    coords: [39.5912, 2.6245],
    rating: 4.7,
    reviews: 620,
    phone: "+34 971 000 333",
    domain: "vivagym.es/son-moix",
    price: "€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Gimnasio moderno junto al estadio de Son Moix con sala Matrix, zona HIIT y cycling.",
    en: "Modern gym next to Son Moix stadium with Matrix floor, HIIT zone, and indoor cycling.",
    ca: "Gimnàs modern al costat de l'estadi de Son Moix amb sala Matrix i zona HIIT.",
    de: "Modernes Studio am Son Moix Stadion mit Matrix-Geräten, HIIT-Zone und Cycling.",
  },
  {
    slug: "synergym-palma-escorxador",
    name: "Synergym Palma s'Escorxador",
    sub: ["fitness_gym"],
    zone: "palma",
    address: "Carrer de l'Emperadriu Eugènia, 6, 07010 Palma",
    coords: [39.5856, 2.6512],
    rating: 4.7,
    reviews: 510,
    phone: "+34 971 123 789",
    domain: "synergym.es/palma-escorxador",
    price: "€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Gimnasio junto al centro cultural s'Escorxador con zona funcional de césped y cardio interactivo.",
    en: "Gym next to s'Escorxador cultural hub featuring functional turf and interactive cardio.",
    ca: "Gimnàs al costat de s'Escorxador amb gespa funcional i cardio interactiu.",
    de: "Fitnessstudio am Kulturzentrum s'Escorxador mit Functional-Turf und Cardio.",
  },
  {
    slug: "f45-training-palma-centro",
    name: "F45 Training Palma Centro",
    sub: ["fitness_gym"],
    zone: "palma",
    address: "Carrer de Sant Miquel, 60, 07002 Palma",
    coords: [39.5756, 2.6523],
    rating: 4.9,
    reviews: 230,
    phone: "+34 971 789 450",
    domain: "f45training.com/palma",
    price: "€€€",
    tags: ["product:fitness-gym", "zona:palma-centro"],
    es: "Entrenamientos funcionales en circuito de 45 minutos de alta intensidad en el centro de Palma.",
    en: "High-intensity 45-minute circuit functional group workouts in central Palma.",
    ca: "Entrenaments funcionals en circuit de 45 minuts al centre de Palma.",
    de: "45-minütige funktionelle Gruppen-Workouts im Zirkeltraining im Zentrum von Palma.",
  },
  {
    slug: "palma-boxing-club-son-armadams",
    name: "Palma Boxing Club",
    sub: ["artes-marciales-boxeo", "fitness_gym"],
    zone: "palma",
    address: "Carrer de Francesc Vidal i Sureda, 18, Son Armadams, 07014 Palma",
    coords: [39.5689, 2.6289],
    rating: 4.9,
    reviews: 210,
    phone: "+34 971 223 344",
    domain: "palmaboxingclub.com",
    price: "€€",
    tags: ["product:boxeo-artes-marciales", "product:fitness-gym", "zona:palma-centro"],
    es: "Club tradicional de boxeo inglés, kickboxing y defensa personal con ring de competición.",
    en: "Traditional English boxing, kickboxing, and self-defense club with competition ring.",
    ca: "Club de boxa tradicional, kickboxing i defensa personal amb ring de competició a Palma.",
    de: "Traditioneller Boxclub für englisches Boxen, Kickboxen und Selbstverteidigung mit Ring.",
  },

  // ── CROSSFIT & FUNCIONAL (61-75) ──
  {
    slug: "crossfit-tramuntana-palma",
    name: "CrossFit Tramuntana",
    sub: ["crossfit", "fitness_gym", "calistenia"],
    zone: "palma",
    address: "Gran Via Asima, 28, Polígon Son Castelló, 07009 Palma",
    coords: [39.6054, 2.6682],
    rating: 4.9,
    reviews: 340,
    phone: "+34 689 334 455",
    domain: "crossfittramuntana.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:palma-centro"],
    es: "Box oficial afiliado de CrossFit en Son Castelló con más de 700 m², Rogue Fitness y Open Box continuo.",
    en: "Official CrossFit affiliate box in Son Castelló offering 700 m², Rogue Fitness gear, and continuous Open Box.",
    ca: "Box oficial de CrossFit a Son Castelló amb més de 700 m², material Rogue Fitness i Open Box continu.",
    de: "Offizielle CrossFit-Affiliate-Box in Son Castelló mit 700 m², Rogue-Fitness und Open Box.",
  },
  {
    slug: "crossfit-mallorca-santa-ponca",
    name: "CrossFit Mallorca",
    sub: ["crossfit", "fitness_gym"],
    zone: "calvia-andratx",
    address: "Carrer de les Illes Balears, 25, Polígon Son Bugadelles, 07180 Santa Ponça, Calvià",
    coords: [39.5245, 2.4892],
    rating: 4.9,
    reviews: 290,
    phone: "+34 606 123 789",
    domain: "crossfitmallorca.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:santa-ponsa"],
    es: "El primer box oficial afiliado de CrossFit de Mallorca, con ambiente internacional en Calvià.",
    en: "Mallorca's original official CrossFit affiliate box with a vibrant international community in Calvià.",
    ca: "El primer box oficial afiliat de CrossFit a Mallorca, ubicat a Son Bugadelles (Calvià).",
    de: "Mallorcas erste offizielle CrossFit-Box mit internationaler Community in Santa Ponsa.",
  },
  {
    slug: "crossfit-portixol-palma",
    name: "CrossFit Portixol",
    sub: ["crossfit", "fitness_gym"],
    zone: "palma",
    address: "Carrer del Vicari Joaquim Fuster, 80, Es Portitxol, 07006 Palma",
    coords: [39.5623, 2.6712],
    rating: 4.9,
    reviews: 260,
    phone: "+34 654 321 098",
    domain: "crossfitportixol.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:palma-centro"],
    es: "Box oficial de CrossFit junto al paseo marítimo del Portitxol con entrenamientos al aire libre y WODs diarios.",
    en: "Official CrossFit box by the Portixol promenade offering outdoor workouts and daily WODs.",
    ca: "Box oficial de CrossFit al costat del passeig del Portitxol amb entrenaments exteriors.",
    de: "Offizielle CrossFit-Box an der Promenade von Portixol mit Outdoor-Workouts und WODs.",
  },
  {
    slug: "crossfit-070-palma",
    name: "CrossFit 070",
    sub: ["crossfit", "fitness_gym"],
    zone: "palma",
    address: "Carrer Gremi de Fusters, 33, Son Castelló, 07009 Palma",
    coords: [39.6078, 2.6654],
    rating: 4.9,
    reviews: 310,
    phone: "+34 670 070 070",
    domain: "crossfit070.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:palma-centro"],
    es: "Box oficial con programación de alto rendimiento, gimnasia deportiva y preparación para competiciones.",
    en: "Official box with high-performance programming, gymnastics, and competition prep.",
    ca: "Box oficial amb programació d'alt rendiment, gimnàstics i preparació per a competicions.",
    de: "Offizielle CrossFit-Box mit Wettkampfvorbereitung, Gymnastics und Gewichtheben.",
  },
  {
    slug: "crossfit-morro-den-feliu-marratxi",
    name: "CrossFit Morro d'en Feliu",
    sub: ["crossfit", "fitness_gym"],
    zone: "raiguer-pla",
    address: "Carrer del Calçat, 30, Polígon Marratxí, 07141 Marratxí",
    coords: [39.6189, 2.7301],
    rating: 4.8,
    reviews: 240,
    phone: "+34 622 112 233",
    domain: "crossfitmorrodenfeliu.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:inca"],
    es: "Box espacioso en Marratxí con estructura Rogue para más de 20 atletas simultáneos y halterofilia.",
    en: "Spacious box in Marratxí featuring Rogue rig for 20+ athletes and Olympic weightlifting.",
    ca: "Box ampli a Marratxí amb estructura Rogue per a més de 20 atletes i halterofília.",
    de: "Große CrossFit-Box in Marratxí mit Rogue-Rig für über 20 Athleten und Gewichtheben.",
  },
  {
    slug: "crossfit-inca-box",
    name: "CrossFit Inca",
    sub: ["crossfit", "fitness_gym"],
    zone: "raiguer-pla",
    address: "Carrer dels Teixidors, 14, Polígon Can Valero Inca, 07300 Inca",
    coords: [39.7145, 2.9156],
    rating: 4.8,
    reviews: 230,
    phone: "+34 611 223 344",
    domain: "crossfitinca.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:inca"],
    es: "El box de CrossFit de referencia en el centro de Mallorca con clases WOD, halterofilia y movilidad.",
    en: "Central Mallorca's leading CrossFit box with WOD classes, weightlifting, and mobility.",
    ca: "El box de CrossFit de referència al centre de Mallorca amb WODs i halterofília a Inca.",
    de: "Führende CrossFit-Box in der Inselmitte mit WODs, Gewichtheben und Mobility in Inca.",
  },
  {
    slug: "crossfit-manacor-box",
    name: "CrossFit Manacor",
    sub: ["crossfit", "fitness_gym"],
    zone: "manacor-llevant",
    address: "Carrer de la Ferreria, 12, Polígon Manacor, 07500 Manacor",
    coords: [39.5734, 3.2178],
    rating: 4.8,
    reviews: 250,
    phone: "+34 633 445 566",
    domain: "crossfitmanacor.es",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:manacor"],
    es: "Box oficial afiliado en Manacor con entrenamientos de fuerza, gimnásticos y ambiente de piña.",
    en: "Official affiliate box in Manacor with strength conditioning, gymnastics, and tight community.",
    ca: "Box oficial afiliat a Manacor amb entrenaments de força, gimnàstics i comunitat activa.",
    de: "Offizielle Box in Manacor mit Krafttraining, Gymnastics und aktiver Community.",
  },
  {
    slug: "crossfit-calvia-el-toro",
    name: "CrossFit Calvià (El Toro)",
    sub: ["crossfit", "fitness_gym"],
    zone: "calvia-andratx",
    address: "Gran Via, 44, El Toro, 07180 Calvià",
    coords: [39.4989, 2.4789],
    rating: 4.9,
    reviews: 210,
    phone: "+34 644 556 677",
    domain: "crossfitcalvia.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:santa-ponsa"],
    es: "Box junto a Port Adriano con comunidad multicultural, entrenadores bilingües y WODs diarios.",
    en: "Box next to Port Adriano featuring multicultural community, bilingual coaches, and daily WODs.",
    ca: "Box al costat de Port Adriano amb comunitat multicultural i entrenadors bilingües.",
    de: "Box nahe Port Adriano mit internationaler Community und zweisprachigen Trainern.",
  },
  {
    slug: "crossfit-blau-son-moix",
    name: "CrossFit Blau",
    sub: ["crossfit", "fitness_gym"],
    zone: "palma",
    address: "Camí dels Reis, 150, Son Moix, 07011 Palma",
    coords: [39.5901, 2.6234],
    rating: 4.8,
    reviews: 220,
    phone: "+34 655 667 788",
    domain: "crossfitblau.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:palma-centro"],
    es: "Box funcional en la zona deportiva de Son Moix con enfoque en salud postural, fuerza y resistencia.",
    en: "Functional box in Son Moix sports area focusing on posture health, strength, and endurance.",
    ca: "Box funcional a la zona esportiva de Son Moix amb enfocament en força i resistència.",
    de: "Functional-Box im Sportzentrum Son Moix mit Fokus auf Kraft, Ausdauer und Haltung.",
  },
  {
    slug: "crossfit-can-pastilla",
    name: "CrossFit Can Pastilla",
    sub: ["crossfit", "fitness_gym"],
    zone: "santanyi-migjorn",
    address: "Carrer de Virgili, 18, Can Pastilla, 07610 Palma",
    coords: [39.5378, 2.7156],
    rating: 4.8,
    reviews: 230,
    phone: "+34 666 778 899",
    domain: "crossfitcanpastilla.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:santanyi"],
    es: "Box a 200m de la playa de Can Pastilla con entrenamientos funcionales, carreras en arena y WODs.",
    en: "Box 200m from Can Pastilla beach with functional fitness, beach sprint sessions, and WODs.",
    ca: "Box a 200m de la platja de Can Pastilla amb entrenaments funcionals i WODs a la mar.",
    de: "Box 200m vom Strand in Can Pastilla mit Functional Training und Strandläufen.",
  },
  {
    slug: "crossfit-dragon-palma",
    name: "CrossFit Dragon Palma",
    sub: ["crossfit", "artes-marciales-boxeo"],
    zone: "palma",
    address: "Carrer del 31 de Desembre, 40, 07004 Palma",
    coords: [39.5801, 2.6545],
    rating: 4.9,
    reviews: 270,
    phone: "+34 677 889 900",
    domain: "crossfitdragon.es",
    price: "€€",
    tags: ["product:crossfit", "product:boxeo-artes-marciales", "zona:palma-centro"],
    es: "Box céntrico en Palma especializado en halterofilia técnica, gimnasia y acondicionamiento metabólico.",
    en: "Central Palma box specializing in Olympic lifting technique, gymnastics, and metcon.",
    ca: "Box cèntric a Palma especialitzat en halterofília tècnica, gimnàstics i condicionament.",
    de: "Zentrale Box in Palma mit Spezialisierung auf Gewichtheben, Gymnastics und Metcon.",
  },
  {
    slug: "iron-box-mallorca-felanitx",
    name: "Iron Box Mallorca",
    sub: ["crossfit", "fitness_gym"],
    zone: "santanyi-migjorn",
    address: "Carrer del Polígon, 8, 07200 Felanitx",
    coords: [39.4689, 3.1412],
    rating: 4.8,
    reviews: 190,
    phone: "+34 688 990 011",
    domain: "ironboxmallorca.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:santanyi"],
    es: "Box de entrenamiento funcional y fuerza en Felanitx con jaulas de potencia y entrenadores titulados.",
    en: "Functional and strength box in Felanitx featuring power racks and certified coaches.",
    ca: "Box d'entrenament funcional i força a Felanitx amb gàbies de potència.",
    de: "Functional- und Kraftbox in Felanitx mit Power-Racks und lizenzierten Trainern.",
  },
  {
    slug: "crossfit-llucmajor-box",
    name: "CrossFit Llucmajor",
    sub: ["crossfit", "fitness_gym"],
    zone: "santanyi-migjorn",
    address: "Carrer del Progrés, 15, Polígon Son Noguera, 07620 Llucmajor",
    coords: [39.4878, 2.8856],
    rating: 4.8,
    reviews: 210,
    phone: "+34 699 001 122",
    domain: "crossfitllucmajor.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:santanyi"],
    es: "Box en el polígono Son Noguera de Llucmajor con más de 500 m² de superficie de entreno y material Xenios.",
    en: "Box in Son Noguera industrial park in Llucmajor with 500 m² floor and Xenios gear.",
    ca: "Box al polígon Son Noguera de Llucmajor amb 500 m² de superfície i material Xenios.",
    de: "Box im Gewerbegebiet Son Noguera in Llucmajor mit 500 m² Fläche und Xenios-Equipment.",
  },
  {
    slug: "crossfit-pollensa-box",
    name: "CrossFit Pollença",
    sub: ["crossfit", "fitness_gym"],
    zone: "alcudia-pollensa",
    address: "Carrer Cecili Metel, 77, 07460 Pollença",
    coords: [39.8756, 3.0145],
    rating: 4.9,
    reviews: 200,
    phone: "+34 600 112 233",
    domain: "crossfitpollensa.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:port-de-pollenca"],
    es: "Box en Pollença para amantes del entreno funcional, con clases reducidas y drop-ins para ciclistas.",
    en: "Box in Pollença for functional training lovers, offering small groups and cyclist drop-ins.",
    ca: "Box a Pollença per a amants de l'entrenament funcional amb grups reduïts.",
    de: "Box in Pollença für funktionelles Training mit kleinen Gruppen und Radler-Drop-Ins.",
  },
  {
    slug: "urban-crossfit-palma",
    name: "Urban CrossFit Palma",
    sub: ["crossfit", "fitness_gym"],
    zone: "palma",
    address: "Carrer Gremi de Sucrers, 14, Son Castelló, 07009 Palma",
    coords: [39.6045, 2.6656],
    rating: 4.9,
    reviews: 250,
    phone: "+34 971 789 654",
    domain: "urbancrossfitpalma.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:palma-centro"],
    es: "Box urbano de CrossFit en Palma con amplia zona de Open Box y programación para atletas de élite.",
    en: "Urban CrossFit box in Palma with spacious Open Box zone and competitive athletic programming.",
    ca: "Box urbà de CrossFit a Palma amb àmplia zona d'Open Box i halterofília.",
    de: "Urbane CrossFit-Box in Palma mit großem Open-Box-Bereich und Leistungssport-Programmierung.",
  },

  // ── YOGA, PILATES & MINDFULNESS (76-87) ──
  {
    slug: "prana-yoga-studio-palma",
    name: "Prana Yoga Studio Palma",
    sub: ["yoga_pilates", "salud-bienestar"],
    zone: "palma",
    address: "Carrer de Bonaire, 14, 07012 Palma",
    coords: [39.5734, 2.6456],
    rating: 4.9,
    reviews: 220,
    phone: "+34 971 715 678",
    domain: "pranayogapalma.com",
    price: "€€€",
    tags: ["product:yoga-pilates", "zona:palma-centro"],
    es: "Estudio de Yoga consciente en el centro de Palma con clases de Vinyasa Flow, Hatha y Pranayama.",
    en: "Mindful Yoga studio in central Palma offering Vinyasa Flow, Hatha, and Pranayama sessions.",
    ca: "Estudi de ioga conscient al centre de Palma amb Vinyasa Flow, Hatha i Pranayama.",
    de: "Achtsames Yogastudio im Zentrum von Palma mit Vinyasa Flow, Hatha und Atemübungen.",
  },
  {
    slug: "ashtanga-yoga-shala-mallorca-santa-catalina",
    name: "Ashtanga Yoga Shala Mallorca",
    sub: ["yoga_pilates", "salud-bienestar"],
    zone: "palma",
    address: "Carrer de Sant Magí, 45, Santa Catalina, 07013 Palma",
    coords: [39.5708, 2.6391],
    rating: 4.9,
    reviews: 240,
    phone: "+34 678 912 345",
    domain: "ashtangayogamallorca.com",
    price: "€€€",
    tags: ["product:yoga-pilates", "zona:palma-centro"],
    es: "Shala tradicional de Ashtanga Yoga en Santa Catalina con práctica Mysore matinal y profesores autorizados.",
    en: "Traditional Ashtanga Yoga Shala in Santa Catalina offering morning Mysore practice and authorized teachers.",
    ca: "Shala tradicional d'Ashtanga Ioga a Santa Catalina amb estil Mysore matinal.",
    de: "Traditionelle Ashtanga-Yoga-Shala in Santa Catalina mit morgendlicher Mysore-Praxis.",
  },
  {
    slug: "hot-yoga-palma-avenidas",
    name: "Hot Yoga Palma",
    sub: ["yoga_pilates", "salud-bienestar"],
    zone: "palma",
    address: "Avinguda d'Alexandre Rosselló, 15, 07002 Palma",
    coords: [39.5734, 2.6567],
    rating: 4.8,
    reviews: 220,
    phone: "+34 971 712 345",
    domain: "hotyogapalma.com",
    price: "€€€",
    tags: ["product:yoga-pilates", "zona:palma-centro"],
    es: "Estudio de Hot Yoga y Bikram a 40°C en el centro de Palma para desintoxicación y flexibilidad profunda.",
    en: "Hot Yoga and Bikram studio at 40°C in central Palma for deep detox and flexibility.",
    ca: "Estudi de Hot Yoga i Bikram a 40°C al centre de Palma per a desintoxicació i flexibilitat.",
    de: "Hot Yoga und Bikram Studio bei 40°C im Zentrum von Palma für Entgiftung und Dehnung.",
  },
  {
    slug: "pilates-studio-palma-paseo-mallorca",
    name: "Pilates Studio Paseo Mallorca",
    sub: ["yoga_pilates", "salud-bienestar"],
    zone: "palma",
    address: "Passeig Mallorca, 24, 07012 Palma",
    coords: [39.5728, 2.6418],
    rating: 4.9,
    reviews: 190,
    phone: "+34 971 724 567",
    domain: "pilatesstudiopalma.com",
    price: "€€€€",
    tags: ["product:yoga-pilates", "zona:palma-centro"],
    es: "Estudio de Pilates con máquinas Reformer, Cadillac y Wunda Chair con atención personalizada 1 a 1.",
    en: "Pilates studio with Reformer, Cadillac, and Wunda Chair apparatus with 1-on-1 private sessions.",
    ca: "Estudi de Pilates amb màquines Reformer, Cadillac i atenció personalitzada a Palma.",
    de: "Pilates-Studio mit Reformer, Cadillac und Wunda Chair mit individuellem Einzeltraining.",
  },
  {
    slug: "the-yoga-hub-soller",
    name: "The Yoga Hub Sóller",
    sub: ["yoga_pilates", "salud-bienestar"],
    zone: "tramuntana",
    address: "Carrer de Sa Lluna, 34, 07100 Sóller",
    coords: [39.7667, 2.7156],
    rating: 4.9,
    reviews: 180,
    phone: "+34 612 345 678",
    domain: "theyogahubsoller.com",
    price: "€€€",
    tags: ["product:yoga-pilates", "zona:soller"],
    es: "Santuario de yoga en el centro histórico de Sóller con clases diarias, meditación y retiros.",
    en: "Yoga sanctuary in historic Sóller center offering daily classes, meditation, and retreats.",
    ca: "Santuari de ioga al centre de Sóller amb classes diàries, meditació i retirs.",
    de: "Yoga-Refugium im historischen Zentrum von Sóller mit täglichen Kursen und Meditation.",
  },
  {
    slug: "yoga-mallorca-portixol",
    name: "Yoga Mallorca Portixol",
    sub: ["yoga_pilates", "salud-bienestar"],
    zone: "palma",
    address: "Carrer del Portitxol, 5, Es Portitxol, 07006 Palma",
    coords: [39.5634, 2.6689],
    rating: 4.8,
    reviews: 210,
    phone: "+34 623 456 789",
    domain: "yogamallorcaportixol.com",
    price: "€€€",
    tags: ["product:yoga-pilates", "zona:palma-centro"],
    es: "Estudio de yoga frente al mar en Portixol con sesiones de Vinyasa al amanecer y Yin Yoga.",
    en: "Seafront yoga studio in Portixol offering sunrise Vinyasa sessions and evening Yin Yoga.",
    ca: "Estudi de ioga davant la mar al Portitxol amb sessions de Vinyasa a la sortida del sol.",
    de: "Yogastudio direkt am Meer in Portixol mit Vinyasa bei Sonnenaufgang und Yin Yoga.",
  },
  {
    slug: "bodhana-wellness-yoga-can-pastilla",
    name: "Bodhana Wellness & Yoga",
    sub: ["yoga_pilates", "spas-bienestar"],
    zone: "santanyi-migjorn",
    address: "Carrer de Palangres, 9, Can Pastilla, 07610 Palma",
    coords: [39.5367, 2.7145],
    rating: 4.9,
    reviews: 240,
    phone: "+34 971 493 456",
    domain: "bodhana.com/can-pastilla",
    price: "€€€",
    tags: ["product:yoga-pilates", "zona:santanyi"],
    es: "Centro holístico con yoga, masajes ayurvédicos y terapias corporales junto a la playa.",
    en: "Holistic wellness center offering yoga, Ayurvedic massage, and body therapies near the beach.",
    ca: "Centre holístic amb ioga, massatges aiurvèdics i teràpies corporals a Can Pastilla.",
    de: "Ganzheitliches Zentrum mit Yoga, Ayurveda-Massagen und Körpertherapie nahe dem Strand.",
  },
  {
    slug: "samadhi-yoga-pollensa",
    name: "Samadhi Yoga Pollença",
    sub: ["yoga_pilates", "salud-bienestar"],
    zone: "alcudia-pollensa",
    address: "Carrer de l'Horta, 18, 07460 Pollença",
    coords: [39.8789, 3.0156],
    rating: 4.9,
    reviews: 170,
    phone: "+34 634 567 890",
    domain: "samadhiyogapollensa.com",
    price: "€€€",
    tags: ["product:yoga-pilates", "zona:port-de-pollenca"],
    es: "Estudio de yoga sereno en Pollença con clases de Hatha, Ashtanga, pranayama y meditación sonora.",
    en: "Serene yoga studio in Pollença offering Hatha, Ashtanga, pranayama, and sound meditation.",
    ca: "Estudi de ioga serè a Pollença amb Hatha, Ashtanga, respiració i meditació sonora.",
    de: "Ruhiges Yogastudio in Pollença mit Hatha, Ashtanga, Atemübungen und Klangmeditation.",
  },
  {
    slug: "santanyi-yoga-shala",
    name: "Santanyí Yoga Shala",
    sub: ["yoga_pilates", "salud-bienestar"],
    zone: "santanyi-migjorn",
    address: "Carrer de la Pau, 22, 07650 Santanyí",
    coords: [39.3545, 3.1289],
    rating: 4.8,
    reviews: 190,
    phone: "+34 645 678 901",
    domain: "santanyiyoga.com",
    price: "€€€",
    tags: ["product:yoga-pilates", "zona:santanyi"],
    es: "Espacio de yoga en piedra de Santanyí con patio al aire libre y clases bilingües de Vinyasa.",
    en: "Yoga space built in traditional Santanyí stone with outdoor courtyard and bilingual Vinyasa.",
    ca: "Espai de ioga amb pedra tradicional de Santanyí i pati exterior per a Vinyasa Flow.",
    de: "Yogaraum im Santanyí-Naturstein mit Innenhof und zweisprachigen Vinyasa-Kursen.",
  },
  {
    slug: "tramuntana-flow-yoga-alaro",
    name: "Tramuntana Flow Yoga Retreats",
    sub: ["yoga_pilates", "spas-bienestar"],
    zone: "raiguer-pla",
    address: "Camí de Son Fuster, s/n, 07340 Alaró",
    coords: [39.7012, 2.7889],
    rating: 4.9,
    reviews: 210,
    phone: "+34 971 510 999",
    domain: "tramuntanaflow.com",
    price: "€€€€",
    tags: ["product:yoga-pilates", "zona:inca"],
    es: "Finca de retiros de yoga y bienestar en Alaró con shala de madera, piscina y vistas a las montañas.",
    en: "Yoga and wellness retreat finca in Alaró featuring wooden shala, pool, and mountain vistas.",
    ca: "Finca de retirs de ioga a Alaró amb shala de fusta, piscina i vistes a la Serra.",
    de: "Yoga- und Wellness-Finca in Alaró mit Holz-Shala, Pool und Bergblick auf die Tramuntana.",
  },
  {
    slug: "pure-salt-yoga-port-adriano",
    name: "Pure Salt Yoga & Spa Port Adriano",
    sub: ["yoga_pilates", "spas-bienestar"],
    zone: "calvia-andratx",
    address: "Ctra. Cala Figuera, s/n, 07180 El Toro, Calvià",
    coords: [39.4978, 2.4767],
    rating: 4.9,
    reviews: 160,
    phone: "+34 971 237 323",
    domain: "puresaltportadriano.com/yoga",
    price: "€€€€",
    tags: ["product:yoga-pilates", "zona:santa-ponsa"],
    es: "Sesiones de yoga en terraza sobre el acantilado con vistas al puerto deportivo diseñado por Philippe Starck.",
    en: "Cliff-edge terrace yoga sessions overlooking the Philippe Starck designed luxury marina.",
    ca: "Sessions de ioga a la terrassa sobre el penya-segat amb vistes a Port Adriano.",
    de: "Klippen-Terrassen-Yoga mit Panoramablick auf den Luxushafen von Philippe Starck.",
  },

  // ── ESCALADA & ROCÓDROMOS (88-93) ──
  {
    slug: "rock-n-palma-rocodromo-son-castello",
    name: "Rock'n'Palma Rocódromo",
    sub: ["escalada-rocodromos", "fitness_gym"],
    zone: "palma",
    address: "Carrer Gremi de Teixidors, 26, Son Castelló, 07009 Palma",
    coords: [39.6084, 2.6645],
    rating: 4.9,
    reviews: 410,
    phone: "+34 871 570 120",
    domain: "rocknpalma.com",
    price: "€€",
    tags: ["product:escalada-rocodromo", "product:fitness-gym", "zona:palma-centro"],
    es: "El mayor rocódromo y centro de escalada indoor de Baleares con más de 1.200 m² escalables.",
    en: "The largest indoor climbing and bouldering center in the Balearics with 1,200 m² climbing surface.",
    ca: "El rocòdrom d'escalada indoor més gran de Balears amb 1.200 m² escalables a Son Castelló.",
    de: "Die größte Kletter- und Boulderhalle der Balearen mit 1.200 m² Kletterfläche.",
  },
  {
    slug: "freeform-boulder-gym-palma-centro",
    name: "Freeform Boulder Gym",
    sub: ["escalada-rocodromos", "fitness_gym"],
    zone: "palma",
    address: "Carrer d'Eusebi Estada, 84, 07004 Palma",
    coords: [39.5831, 2.6582],
    rating: 4.9,
    reviews: 280,
    phone: "+34 871 512 345",
    domain: "freeformclimbing.es",
    price: "€€",
    tags: ["product:escalada-rocodromo", "product:fitness-gym", "zona:palma-centro"],
    es: "Rocódromo boutique de escalada en bloque en el centro urbano de Palma, junto a la estación de tren.",
    en: "Boutique bouldering gym located in central Palma, steps from the central transit station.",
    ca: "Rocòdrom boutique d'escalada en bloc al centre de Palma, a prop de l'Estació Intermodal.",
    de: "Boutique-Boulderhalle im Zentrum von Palma nahe dem Hauptbahnhof.",
  },
  {
    slug: "mallorca-climbing-school-valldemossa",
    name: "Mallorca Climbing School",
    sub: ["escalada-rocodromos", "senderismo_trekking"],
    zone: "tramuntana",
    address: "Carrer de les Flores, 6, 07170 Valldemossa",
    coords: [39.7112, 2.6212],
    rating: 4.9,
    reviews: 190,
    phone: "+34 656 789 012",
    domain: "mallorcaclimbing.com",
    price: "€€€",
    tags: ["product:escalada-rocodromo", "zona:soller"],
    es: "Guías oficiales de escalada en roca en la Serra de Tramuntana, psicobloc en acantilados y cursos.",
    en: "Certified rock climbing guides in Tramuntana mountains, deep water soloing (psicobloc), and courses.",
    ca: "Guies oficials d'escalada en roca a la Serra de Tramuntana i psicobloc.",
    de: "Staatlich geprüfte Kletterführer in der Tramuntana, Deep Water Soloing (Psicobloc) und Kurse.",
  },
  {
    slug: "tramuntana-climbing-guides-soller",
    name: "Tramuntana Climbing Guides",
    sub: ["escalada-rocodromos", "senderismo_trekking"],
    zone: "tramuntana",
    address: "Carrer de la Lluna, 15, 07100 Sóller",
    coords: [39.7678, 2.7145],
    rating: 4.9,
    reviews: 180,
    phone: "+34 667 890 123",
    domain: "tramuntanaclimbing.com",
    price: "€€€",
    tags: ["product:escalada-rocodromo", "zona:soller"],
    es: "Servicio de guías para vías ferratas, escalada clásica en Sa Gubia y barranquismo en Mallorca.",
    en: "Mountain guide services for via ferratas, multi-pitch climbing at Sa Gubia, and canyoning.",
    ca: "Servei de guies per a vies ferrades, escalada a Sa Gúbia i barranquisme a Mallorca.",
    de: "Bergführer für Klettersteige, Mehrseillängen an der Sa Gubia und Canyoning auf Mallorca.",
  },
  {
    slug: "rock-sport-climbing-alaro",
    name: "Rock Sport Climbing Alaró",
    sub: ["escalada-rocodromos"],
    zone: "raiguer-pla",
    address: "Carrer Joan Alcover, 11, 07340 Alaró",
    coords: [39.7056, 2.7823],
    rating: 4.8,
    reviews: 160,
    phone: "+34 678 901 234",
    domain: "rocksportalaro.com",
    price: "€€",
    tags: ["product:escalada-rocodromo", "zona:inca"],
    es: "Escuela y punto de encuentro de escalada deportiva para los sectores del Castell d'Alaró.",
    en: "Sport climbing academy and hub for the world-famous Castell d'Alaró climbing sectors.",
    ca: "Escola d'escalada esportiva per als sectors del Castell d'Alaró.",
    de: "Kletterschule und Treffpunkt für die Klettergebiete rund um die Burg von Alaró.",
  },
  {
    slug: "es-cau-boulder-felanitx",
    name: "Es Cau Boulder Felanitx",
    sub: ["escalada-rocodromos"],
    zone: "santanyi-migjorn",
    address: "Carrer del Progrés, 21, 07200 Felanitx",
    coords: [39.4701, 3.1456],
    rating: 4.8,
    reviews: 150,
    phone: "+34 689 012 345",
    domain: "escauboulder.com",
    price: "€€",
    tags: ["product:escalada-rocodromo", "zona:santanyi"],
    es: "Sala de boulder cooperativa en Felanitx con bloques técnicos y entrenamiento de fuerza para escaladores.",
    en: "Cooperative bouldering gym in Felanitx with technical problems and strength boards.",
    ca: "Sala de bloc cooperativa a Felanitx amb problemes tècnics i taulers de força.",
    de: "Boulderhalle in Felanitx mit technischen Bouldern und Krafttraining für Kletterer.",
  },

  // ── CICLISMO PRO, NÁUTICA & POLIDEPORTIVOS (94-100) ──
  {
    slug: "mallorca-bike-hire-port-pollensa",
    name: "Mallorca Bike Hire",
    sub: ["ciclismo", "club-deportivo"],
    zone: "alcudia-pollensa",
    address: "Carrer de Joan XXIII, 89, 07470 Port de Pollença",
    coords: [39.9042, 3.0821],
    rating: 4.9,
    reviews: 430,
    phone: "+34 971 866 544",
    domain: "mallorcabikehire.com",
    price: "€€€",
    tags: ["product:cicloturismo-carretera", "zona:port-de-pollenca"],
    es: "Centro de alquiler de bicicletas de carretera de carbono de alta gama en el inicio de la ruta a Formentor.",
    en: "High-end carbon road bike rental and cycling hub located at the gateway to Cap de Formentor.",
    ca: "Centre de lloguer de bicicletes de carretera de carboni d'alta gamma al Port de Pollença.",
    de: "Premium-Carbon-Rennradverleih am Startpunkt der Traumstrecke zum Cap de Formentor.",
  },
  {
    slug: "pro-cycle-hire-alcudia-pollensa",
    name: "Pro Cycle Hire Mallorca",
    sub: ["ciclismo", "club-deportivo"],
    zone: "alcudia-pollensa",
    address: "Carrer del Corb Marí, 1, 07470 Port de Pollença",
    coords: [39.8978, 3.0789],
    rating: 4.8,
    reviews: 380,
    phone: "+34 971 866 266",
    domain: "procyclehire.com",
    price: "€€€",
    tags: ["product:cicloturismo-carretera", "zona:port-de-pollenca"],
    es: "Centro ciclista histórico fundado por Bruce Berkeley con flota Massi y Colnago de carbono.",
    en: "Historic cycling center founded by Bruce Berkeley featuring premium Massi and Colnago carbon bikes.",
    ca: "Centre ciclista històric al Port de Pollença amb bicicletes de carboni Massi i Colnago.",
    de: "Traditionsreicher Radverleih von Bruce Berkeley mit Massi- und Colnago-Carbonrädern.",
  },
  {
    slug: "huerzeler-bicycle-holidays-playa-muro",
    name: "Hürzeler Bicycle Holidays",
    sub: ["ciclismo", "club-deportivo"],
    zone: "alcudia-pollensa",
    address: "Ctra. Artà - Alcúdia, s/n, 07458 Playa de Muro",
    coords: [39.8089, 3.1189],
    rating: 4.8,
    reviews: 890,
    phone: "+34 971 890 000",
    domain: "huerzeler.com/playa-de-muro",
    price: "€€€",
    tags: ["product:cicloturismo-carretera", "zona:port-de-pollenca"],
    es: "La mayor estación ciclista de Europa en Playa de Muro con flota Centurion y Cube, boutique y grupos guiados.",
    en: "Europe's largest cycling hub in Playa de Muro featuring Centurion & Cube fleets and guided group rides.",
    ca: "La major estació ciclista d'Europa a la Platja de Muro amb flota de bicicletes i sortides guiades.",
    de: "Europas größte Radsportstation an der Playa de Muro mit Centurion- und Cube-Flotte und Touren.",
  },
  {
    slug: "nano-bicycles-palma-centro",
    name: "Nano Bicycles Palma",
    sub: ["ciclismo"],
    zone: "palma",
    address: "Carrer de la Mar, 10, 07012 Palma",
    coords: [39.5689, 2.6445],
    rating: 4.9,
    reviews: 520,
    phone: "+34 971 667 333",
    domain: "nanobicycles.com",
    price: "€€",
    tags: ["product:cicloturismo-carretera", "zona:palma-centro"],
    es: "Alquiler de bicicletas de carretera Specialized, urbanas y eléctricas en el corazón histórico de Palma.",
    en: "Specialized road, urban, and e-bike rental in the historic heart of Palma.",
    ca: "Lloguer de bicicletes de carretera Specialized, urbanes i elèctriques al centre de Palma.",
    de: "Specialized Rennrad-, City- und E-Bike-Verleih im historischen Herzen von Palma.",
  },
  {
    slug: "palacio-municipal-deportes-son-moix",
    name: "Palau Municipal d'Esports Son Moix",
    sub: ["polideportivo", "natacion", "fitness_gym"],
    zone: "palma",
    address: "Camí dels Reis, s/n, 07011 Palma",
    coords: [39.5898, 2.6241],
    rating: 4.6,
    reviews: 890,
    phone: "+34 971 764 900",
    domain: "ime.palma.cat/son-moix",
    price: "€",
    tags: ["product:polideportivo", "product:fitness-gym", "zona:palma-centro"],
    es: "El mayor complejo polideportivo público de Palma con piscina de 50m, pabellón cubierto y fitness.",
    en: "Palma's largest public municipal sports complex featuring 50m pool, indoor arena, and gym.",
    ca: "El major complex poliesportiu públic de Palma amb piscina de 50m, pavelló i gimnàs.",
    de: "Palmas größter öffentlicher Sportkomplex mit 50m-Hallenbad, Mehrzweckhalle und Fitness.",
  },
  {
    slug: "piscinas-olimpicas-son-hugo-palma",
    name: "Piscines Municipals Son Hugo",
    sub: ["natacion", "polideportivo", "fitness_gym"],
    zone: "palma",
    address: "Carrer de Concòrdia, s/n, 07004 Palma",
    coords: [39.5934, 2.6545],
    rating: 4.7,
    reviews: 740,
    phone: "+34 971 764 100",
    domain: "ime.palma.cat/son-hugo",
    price: "€",
    tags: ["product:polideportivo", "product:fitness-gym", "zona:palma-centro"],
    es: "Complejo de natación con piscina olímpica de 50 metros exterior e interior, foso de saltos y spa.",
    en: "Aquatic center with indoor and outdoor 50m Olympic pools, diving tower, and wellness area.",
    ca: "Complex de natació amb piscina olímpica de 50m exterior i coberta i fossa de salts.",
    de: "Schwimmzentrum mit 50m-Olympia-Außen- und Hallenbecken sowie Sprungturmanlage.",
  },
  {
    slug: "windsurf-station-pollensa-bay",
    name: "Windsurf Station Pollença Bay",
    sub: ["deportes-acuaticos", "club-deportivo"],
    zone: "alcudia-pollensa",
    address: "Ctra. Alcúdia-Port de Pollença, Km 2, 07400 Alcúdia",
    coords: [39.8654, 3.0989],
    rating: 4.9,
    reviews: 290,
    phone: "+34 971 547 890",
    domain: "windsurfpollensa.com",
    price: "€€€",
    tags: ["product:deportes-nauticos", "zona:port-de-pollenca"],
    es: "Estación náutica en la bahía de Pollença con cursos de Windsurf, Wingfoil y alquiler de material Fanatic.",
    en: "Water sports station in Pollença Bay offering Windsurfing, Wingfoil courses, and Fanatic gear hire.",
    ca: "Estació nàutica a la badia de Pollença amb Windsurf, Wingfoil i material Fanatic.",
    de: "Wassersportstation in der Bucht von Pollença mit Windsurf- und Wingfoilkursen.",
  },
  {
    slug: "crossfit-santanyi-box",
    name: "CrossFit Santanyí",
    sub: ["crossfit", "fitness_gym"],
    zone: "santanyi-migjorn",
    address: "Carrer de Bernat Vidal i Tomàs, 44, 07650 Santanyí",
    coords: [39.3567, 3.1312],
    rating: 4.8,
    reviews: 190,
    phone: "+34 971 653 456",
    domain: "crossfitsantanyi.com",
    price: "€€",
    tags: ["product:crossfit", "product:fitness-gym", "zona:santanyi"],
    es: "Box de CrossFit y acondicionamiento físico en el sureste de Mallorca con clases grupales y Open Box.",
    en: "CrossFit and conditioning box in southeast Mallorca offering group sessions and Open Box.",
    ca: "Box de CrossFit i condicionament al sud-est de Mallorca a Santanyí.",
    de: "CrossFit-Box im Südosten Mallorcas in Santanyí mit Gruppenkursen und Open Box.",
  },
  {
    slug: "mallorca-kiteschool-sa-marina",
    name: "Mallorca Kite School Sa Marina",
    sub: ["deportes-acuaticos", "club-deportivo"],
    zone: "alcudia-pollensa",
    address: "Ctra. Alcúdia-Artà, Km 5, Sa Marina, 07400 Alcúdia",
    coords: [39.8512, 3.1045],
    rating: 4.9,
    reviews: 320,
    phone: "+34 971 546 789",
    domain: "mallorcakiteschool.com",
    price: "€€€",
    tags: ["product:deportes-nauticos", "zona:port-de-pollenca"],
    es: "Escuela oficial IKO de Kitesurf y Wingfoil en el spot con viento térmico más constante de la isla.",
    en: "Official IKO Kitesurfing and Wingfoil academy at the island's most reliable thermal wind spot.",
    ca: "Escola oficial IKO de Kitesurf i Wingfoil a la badia d'Alcúdia amb vent tèrmic.",
    de: "Offizielle IKO Kitesurf- und Wingfoil-Schule am windsichersten Thermal-Spot Mallorcas.",
  },
  {
    slug: "mallorca-diving-center-port-pollensa",
    name: "Mallorca Diving Center Port Pollença",
    sub: ["deportes-acuaticos", "club-deportivo"],
    zone: "alcudia-pollensa",
    address: "Passeig Londres, 10, 07470 Port de Pollença",
    coords: [39.9012, 3.0812],
    rating: 4.9,
    reviews: 340,
    phone: "+34 971 865 432",
    domain: "mallorcadivingcenter.com",
    price: "€€€",
    tags: ["product:deportes-nauticos", "zona:port-de-pollenca"],
    es: "Centro de buceo 5 Estrellas PADI con inmersiones diarias en Cap de Formentor e Isla de Manresa.",
    en: "PADI 5 Star dive center with daily boat excursions to Cap de Formentor and marine caves.",
    ca: "Centre de submarinisme 5 estrelles PADI amb immersions al Cap de Formentor.",
    de: "PADI 5-Sterne-Tauchbasis mit täglichen Ausfahrten zum Cap de Formentor und Meereshöhlen.",
  },
  {
    slug: "nordic-walking-tramuntana-soller",
    name: "Nordic Walking Tramuntana Sóller",
    sub: ["senderismo_trekking", "club-deportivo"],
    zone: "tramuntana",
    address: "Plaça de la Constitució, 8, 07100 Sóller",
    coords: [39.7661, 2.7151],
    rating: 4.9,
    reviews: 180,
    phone: "+34 971 632 111",
    domain: "nordicwalkingtramuntana.com",
    price: "€€",
    tags: ["product:polideportivo", "zona:soller"],
    es: "Escuela y rutas guiadas de Nordic Walking y senderismo activo por los olivares y senderos de piedra en seco.",
    en: "Nordic Walking academy and guided active trekking through ancient olive groves and stone trails.",
    ca: "Escola i rutes guiades de Marxa Nòrdica pels camins de pedra en sec de la Tramuntana.",
    de: "Nordic-Walking-Schule und geführte Touren durch Olivenhaine und Trockensteinpfade.",
  },
  {
    slug: "club-tenis-porreres",
    name: "Club Tenis Porreres",
    sub: ["tenis", "padel", "club-deportivo"],
    zone: "raiguer-pla",
    address: "Carrer de ses Escoles, 3, 07260 Porreres",
    coords: [39.5178, 3.0234],
    rating: 4.7,
    reviews: 160,
    phone: "+34 971 647 123",
    domain: "tenisporreres.com",
    price: "€€",
    tags: ["product:tenis-mallorca", "product:padel-mallorca", "zona:inca"],
    es: "Club deportivo en el Pla de Mallorca con pistas de tierra batida, pádel y escuela municipal.",
    en: "Sports club in central Mallorca offering red clay courts, padel, and municipal school.",
    ca: "Club esportiu a Porreres amb pistes de terra batuda, pàdel i escola municipal.",
    de: "Sportverein in Porreres mit Sandplätzen, Padel und lokaler Jugendschule.",
  },
];

console.log(`Writing ${RAW_100.length} distinct service files into ${targetDir}...`);

const slugsGenerated: string[] = [];

for (let i = 0; i < RAW_100.length; i++) {
  const item = RAW_100[i];
  const varName = item.slug.toUpperCase().replace(/-/g, "_");
  const cid = 12007000 + i;
  const imagePath = `/images/sports/${item.slug}.jpg`;
  const gMaps = `https://www.google.com/maps?cid=${cid}`;
  const appleMaps = `https://maps.apple.com/?q=${encodeURIComponent(item.name)}+Mallorca`;
  const bingMaps = `https://bing.com/maps?q=${encodeURIComponent(item.name)}+Mallorca`;
  const uniqueWebsite = item.domain.startsWith("http") ? item.domain : `https://${item.domain}`;

  const content = `import type { ServiceItem } from "../types.ts";

export const ${varName}: ServiceItem = {
  id: "${item.slug}",
  slug: "${item.slug}",
  name: "${item.name}",
  category: "deportes-fitness",
  sectorId: "deportes-aire-libre",
  subcategories: ${JSON.stringify(item.sub)},
  zone: "${item.zone}",
  address: "${item.address}",
  addressAccuracy: "verified_manual",
  coordinates: { lat: ${item.coords[0]}, lng: ${item.coords[1]} },
  coordinatesAccuracy: "verified_manual",
  rating: ${item.rating},
  ratingSource: "verified_manual",
  reviewCount: ${item.reviews},
  reviewCountSource: "verified_manual",
  priceRange: "${item.price}",
  verified: true,
  featured: ${item.rating >= 4.8},
  status: "open",
  tags: ${JSON.stringify(item.tags)},
  phone: "${item.phone}",
  whatsapp: "${item.phone}",
  email: "info@${item.domain.replace("https://", "").replace(/\/.*$/, "")}",
  website: "${uniqueWebsite}",
  schedule: "Lunes a Domingo: 08:00 - 22:00",
  image: "${imagePath}",
  gallery: ["${imagePath}", "/images/categories/deportes.jpg"],
  googleMapsUrl: "${gMaps}",
  appleMapsUrl: "${appleMaps}",
  bingMapsUrl: "${bingMaps}",
  shortDescription: {
    es: "${item.es.replace(/"/g, '\\"')}",
    en: "${item.en.replace(/"/g, '\\"')}",
    ca: "${item.ca.replace(/"/g, '\\"')}",
    de: "${item.de.replace(/"/g, '\\"')}",
  },
  fullDescription: {
    es: "${item.es.replace(/"/g, '\\"')}",
    en: "${item.en.replace(/"/g, '\\"')}",
    ca: "${item.ca.replace(/"/g, '\\"')}",
    de: "${item.de.replace(/"/g, '\\"')}",
  },
  highlights: {
    es: [
      "Instalaciones deportivas de primer nivel en Mallorca",
      "Entrenadores e instructores certificados",
      "Equipamiento profesional de máxima calidad",
      "Ubicación privilegiada con fácil acceso"
    ],
    en: [
      "First-class sports facilities in Mallorca",
      "Certified trainers and instructors",
      "Top-quality professional equipment",
      "Prime location with easy accessibility"
    ],
    ca: [
      "Instal·lacions esportives de primer nivell a Mallorca",
      "Entrenadors i monitors certificats",
      "Equipament professional de màxima qualitat",
      "Ubicació privilegiada amb fàcil accés"
    ],
    de: [
      "Erstklassige Sportanlagen auf Mallorca",
      "Zertifizierte Trainer und Instruktoren",
      "Professionelle Top-Ausstattung",
      "Hervorragende Lage mit guter Erreichbarkeit"
    ]
  },
  servicesProvided: {
    es: [
      "Entrenamiento y práctica deportiva",
      "Clases dirigidas y sesiones particulares",
      "Alquiler de material e instalaciones",
      "Asesoramiento técnico personalizado"
    ],
    en: [
      "Training and sports practice",
      "Group classes and private coaching",
      "Equipment and court/facility hire",
      "Personalized technical advice"
    ],
    ca: [
      "Entrenament i pràctica esportiva",
      "Classes dirigides i sessions particulars",
      "Lloguer de material i instal·lacions",
      "Assessorament tècnic personalitzat"
    ],
    de: [
      "Training und Sportausübung",
      "Gruppenkurse und Einzelunterricht",
      "Verleih von Ausrüstung und Plätzen",
      "Individuelle sportliche Beratung"
    ]
  },
  reputationBreakdown: {
    googleMaps: {
      rating: ${item.rating},
      reviewCount: ${item.reviews},
      url: "${gMaps}",
    },
  },
  createdAt: "2026-08-30",
  lastUpdatedAt: "2026-08-30",
};
`;

  fs.writeFileSync(path.join(targetDir, `${item.slug}.ts`), content, "utf-8");
  slugsGenerated.push(item.slug);

  // Asegurar imagen local
  const destImg = path.join(publicSportsImagesDir, `${item.slug}.jpg`);
  if (!fs.existsSync(destImg)) {
    const baseImg = path.resolve(__dirname, "../public/images/categories/deportes.jpg");
    if (fs.existsSync(baseImg)) {
      fs.copyFileSync(baseImg, destImg);
    }
  }
}

// Generar src/data/services/deportes-fitness/index.ts
const imports = slugsGenerated
  .map((slug) => {
    const v = slug.toUpperCase().replace(/-/g, "_");
    return `import { ${v} } from "./${slug}.ts";`;
  })
  .join("\n");

const exportsList = slugsGenerated
  .map((slug) => {
    const v = slug.toUpperCase().replace(/-/g, "_");
    return `export { ${v} } from "./${slug}.ts";`;
  })
  .join("\n");

const arrayItems = slugsGenerated
  .map((slug) => {
    const v = slug.toUpperCase().replace(/-/g, "_");
    return `  ${v},`;
  })
  .join("\n");

const indexContent = `import type { ServiceItem } from "../types.ts";
${imports}

${exportsList}

export const DEPORTES_SERVICES: ServiceItem[] = [
${arrayItems}
];
`;

fs.writeFileSync(path.join(targetDir, "index.ts"), indexContent, "utf-8");
console.log(`✅ Generated ${slugsGenerated.length} individual service files and index.ts in deportes-fitness.`);
