import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

const BATCH_1: BusinessDataInput[] = [
  // ── JARDINERÍA & PAISAJISMO ──
  {
    slug: "jardineria-paisajismo-balear-inca",
    name: "Jardinería & Paisajismo Balear Inca",
    category: "jardineria-piscinas",
    sectorFolder: "jardineria-piscinas",
    sectorArrayName: "JARDINERIA_SERVICES",
    subcategories: ["paisajismo-mediterraneo", "mantenimiento-jardines", "riego-eficiente"],
    zone: "raiguer-pla",
    address: "Avinguda del Raiguer, 45, 07300 Inca",
    coordinates: { lat: 39.7189, lng: 2.9112 },
    rating: 4.8,
    reviewCount: 115,
    priceRange: "€€",
    phone: "+34 971 502 344",
    website: "https://jardineriabalearinca.com",
    schedule: "Lunes a Viernes: 08:00 - 18:00, Sábados: 08:30 - 13:30",
    tags: ["zona:inca", "product:premium", "mod:cita-previa"],
    shortDescription: {
      es: "Especialistas en diseño de jardines mediterráneos de bajo consumo hídrico, poda de palmeras y sistemas de riego.",
      en: "Specialists in low-water Mediterranean garden design, palm tree pruning, and smart irrigation systems.",
      ca: "Especialistes en disseny de jardins mediterranis de baix consum d'aigua, poda de palmeres i reg intel·ligent.",
      de: "Spezialisten für mediterrane Gartengestaltung mit geringem Wasserverbrauch, Palmenschnitt und Bewässerung.",
    },
    fullDescription: {
      es: "Empresa familiar con más de 20 años de experiencia en el Raiguer, dedicada a la creación de espacios exteriores sostenibles, recuperación de flora autóctona balear y mantenimiento integral de fincas rústicas.",
      en: "Family business with over 20 years of experience in Raiguer, specializing in sustainable outdoor spaces, native Balearic flora, and full estate maintenance.",
      ca: "Empresa familiar amb més de 20 anys d'experiència al Raiguer, dedicada a la creació d'espais exteriors sostenibles i manteniment integral de finques.",
      de: "Familienbetrieb mit über 20 Jahren Erfahrung in Raiguer, spezialisiert auf nachhaltige Außenanlagen, balearische Flora und Fincapflege.",
    },
    highlights: {
      es: [
        "Diseño de xerojardines de bajo consumo hídrico",
        "Tratamiento y prevención contra el picudo rojo",
        "Instalación de césped natural y tepes",
        "Mantenimiento periódico para fincas y villas",
      ],
      en: [
        "Low-water xeriscape garden design",
        "Red palm weevil treatment and prevention",
        "Natural turf and sod installation",
        "Regular maintenance for villas and estates",
      ],
      ca: [
        "Disseny de xerojardins de baix consum d'aigua",
        "Tractament contra el morrut de la palmera",
        "Instal·lació de gespa natural",
        "Manteniment periòdic per a finques i vil·les",
      ],
      de: [
        "Wassersparende Xeriscape-Gartengestaltung",
        "Behandlung gegen den Roten Palmenrüssler",
        "Rollrasenverlegung und Naturrasen",
        "Regelmäßige Pflege für Fincas und Villen",
      ],
    },
    servicesProvided: {
      es: [
        "Diseño y ejecución paisajística",
        "Poda en altura y tala controlada",
        "Sistemas de riego por goteo automatizado",
        "Tratamientos fitosanitarios ecológicos",
      ],
      en: [
        "Landscape design and execution",
        "High-altitude tree pruning and felling",
        "Automated drip irrigation systems",
        "Eco-friendly phytosanitary treatments",
      ],
      ca: [
        "Disseny i execució paisatgística",
        "Poda en alçada i tala controlada",
        "Sistemes de reg per degoteig automatitzat",
        "Tractaments fitosanitaris ecològics",
      ],
      de: [
        "Garten- und Landschaftsbau",
        "Baumpflege und Fällarbeiten",
        "Automatische Tröpfchenbewässerung",
        "Ökologischer Pflanzenschutz",
      ],
    },
  },
  {
    slug: "viveros-llevant-manacor",
    name: "Viveros Llevant Manacor",
    category: "jardineria-piscinas",
    sectorFolder: "jardineria-piscinas",
    sectorArrayName: "JARDINERIA_SERVICES",
    subcategories: ["plantas-autoctonas", "arboles-frutales", "decoracion-exterior"],
    zone: "manacor-llevant",
    address: "Ctra. Manacor-Porto Cristo Km 2.2, 07500 Manacor",
    coordinates: { lat: 39.5695, lng: 3.2356 },
    rating: 4.7,
    reviewCount: 240,
    priceRange: "€€",
    phone: "+34 971 845 670",
    website: "https://viverosllevantmanacor.es",
    schedule: "Lunes a Sábado: 08:30 - 19:30, Domingos: 09:30 - 14:00",
    tags: ["zona:manacor", "product:accesible", "mod:en-local"],
    shortDescription: {
      es: "Gran centro de jardinería y vivero con amplia variedad de olivos centenarios, cítricos, plantas mediterráneas y macetería.",
      en: "Large garden center and nursery offering ancient olive trees, citrus, Mediterranean plants, and pottery.",
      ca: "Gran centre de jardineria i viver amb oliveres centenàries, cítrics, plantes mediterrànies i testos.",
      de: "Großes Gartencenter und Baumschule mit alten Olivenbäumen, Zitrusbäumen, mediterranen Pflanzen und Pflanzgefäßen.",
    },
    fullDescription: {
      es: "Viveros Llevant es un centro de referencia en el este de Mallorca, con miles de metros cuadrados de exposición de plantas ornamentales, frutales, sustratos ecológicos y asesoramiento botánico profesional.",
      en: "Viveros Llevant is Eastern Mallorca's premier plant nursery, with extensive displays of ornamental plants, fruit trees, organic soils, and botanical advice.",
      ca: "Viveros Llevant és un centre de referència al llevant de Mallorca, amb milers de metres quadrats d'exposició de plantes ornamentals i fruiters.",
      de: "Viveros Llevant ist eine führende Baumschule im Osten Mallorcas mit riesiger Auswahl an Zierpflanzen, Obstbäumen und Fachberatung.",
    },
    highlights: {
      es: [
        "Olivos centenarios y ejemplares singulares",
        "Plantas autóctonas de bajo mantenimiento",
        "Servicio de transporte y plantación",
        "Macetería de barro cocido y diseño",
      ],
      en: [
        "Centenary olive trees and specimen plants",
        "Low-maintenance native flora",
        "Delivery and planting services",
        "Terracotta and designer planters",
      ],
      ca: [
        "Oliveres centenàries i exemplars singulars",
        "Plantes autòctones de baix manteniment",
        "Servei de transport i plantació",
        "Testos de fang cuit",
      ],
      de: [
        "Hundertjährige Olivenbäume und Solitärpflanzen",
        "Pflegeleichte einheimische Pflanzen",
        "Liefer- und Pflanzservice",
        "Terrakotta- und Designergefäße",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de plantas y árboles al por mayor y menor",
        "Transporte con camión pluma",
        "Asesoramiento botánico in situ",
        "Suministro de tierras y abonos",
      ],
      en: [
        "Retail and wholesale plant supply",
        "Crane truck delivery",
        "On-site botanical consulting",
        "Soil and organic fertilizer supply",
      ],
      ca: [
        "Venda de plantes i arbres al detall i major",
        "Transport amb camió ploma",
        "Assessorament botànic in situ",
        "Subministrament de terres i adobs",
      ],
      de: [
        "Pflanzen- und Baumverkauf (Einzel-/Großhandel)",
        "Kranwagen-Lieferung",
        "Botanische Beratung vor Ort",
        "Erden und organische Düngemittel",
      ],
    },
  },
  {
    slug: "piscinas-cristal-santanyi",
    name: "Piscinas Cristal Santanyí",
    category: "jardineria-piscinas",
    sectorFolder: "jardineria-piscinas",
    sectorArrayName: "JARDINERIA_SERVICES",
    subcategories: ["construccion-piscinas", "cloracion-salina", "climatizacion-piscinas"],
    zone: "santanyi-migjorn",
    address: "Carrer de Bernat Vidal i Tomàs, 72, 07650 Santanyí",
    coordinates: { lat: 39.3562, lng: 3.1284 },
    rating: 4.9,
    reviewCount: 98,
    priceRange: "€€€",
    phone: "+34 971 653 219",
    website: "https://piscinascristalsantanyi.com",
    schedule: "Lunes a Viernes: 08:00 - 17:00",
    tags: ["zona:santanyi", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Construcción y rehabilitación de piscinas desbordantes infinity con gresite vitrificado y sistemas de electrolisis salina.",
      en: "Construction and renovation of luxury infinity pools with vitrified mosaic tile and saltwater chlorination.",
      ca: "Construcció i rehabilitació de piscines desbordants infinity amb gresit i electròlisi salina.",
      de: "Bau und Sanierung von Infinity-Pools mit Glasmosaik und Salzelektrolyse-Systemen.",
    },
    fullDescription: {
      es: "Especialistas en piscinas de diseño integradas en el paisaje del sureste de Mallorca. Creamos láminas de agua únicas con tecnología de depuración avanzada, cubiertas automáticas y climatización por bomba de calor.",
      en: "Specialists in designer pools seamlessly integrated into Southeastern Mallorca's landscape, featuring smart filtration, automatic covers, and heat pumps.",
      ca: "Especialistes en piscines de disseny integrades en el paisatge del sud-est de Mallorca amb depuració avançada i climatització.",
      de: "Spezialisiert auf Designer-Pools im Südosten Mallorcas mit fortschrittlicher Filtertechnik, Abdeckungen und Wärmepumpen.",
    },
    highlights: {
      es: [
        "Piscinas infinity y de borde desbordante",
        "Electrolisis salina y control domótico Ph/Cloro",
        "Climatización para uso todo el año",
        "Garantía de estanqueidad de 10 años",
      ],
      en: [
        "Infinity and vanishing-edge swimming pools",
        "Salt chlorination and smart chemical control",
        "Year-round heating systems",
        "10-year waterproofing warranty",
      ],
      ca: [
        "Piscines infinity i desbordants",
        "Electròlisi salina i control domòtic",
        "Climatització per a tot l'any",
        "Garantia d'estanquitat de 10 anys",
      ],
      de: [
        "Infinity- und Überlaufbecken",
        "Salzelektrolyse und automatische Wasserpflege",
        "Ganzjährige Poolheizung",
        "10 Jahre Dichtigkeitsgarantie",
      ],
    },
    servicesProvided: {
      es: [
        "Construcción de piscinas de obra nueva",
        "Revestimiento de gresite y lámina armada",
        "Instalación de bombas de calor y domótica",
        "Mantenimiento integral del agua",
      ],
      en: [
        "New build pool construction",
        "Glass mosaic and reinforced liner tiling",
        "Heat pump and home automation install",
        "Full chemical water maintenance",
      ],
      ca: [
        "Construcció de piscines d'obra nova",
        "Revestiment de gresit i làmina armada",
        "Instal·lació de bombes de calor",
        "Manteniment integral de l'aigua",
      ],
      de: [
        "Neubau von Schwimmbecken",
        "Glasmosaik- und Folienauskleidung",
        "Wärmepumpen und Smart-Pool-Technik",
        "Kompletter Wasserpflegeservice",
      ],
    },
  },

  // ── RETAIL & COMERCIO ──
  {
    slug: "boutique-rialto-living-palma",
    name: "Rialto Living Lifestyle Concept Store",
    category: "boutiques-moda-mallorca",
    sectorFolder: "retail-comercio",
    sectorArrayName: "RETAIL_SERVICES",
    subcategories: ["moda-lujo", "decoracion-interiores", "lifestyle-concept"],
    zone: "palma",
    address: "Carrer de Sant Feliu, 3, 07012 Palma",
    coordinates: { lat: 39.5706, lng: 2.6455 },
    rating: 4.8,
    reviewCount: 780,
    priceRange: "€€€€",
    phone: "+34 971 713 331",
    website: "https://rialtoliving.com",
    schedule: "Lunes a Sábado: 10:00 - 19:30",
    tags: ["zona:palma-centro", "product:lujo", "mod:en-local"],
    shortDescription: {
      es: "Icono del estilo de vida mediterráneo en un palacio del siglo XV con moda internacional, arte, libros y decoración selecta.",
      en: "Iconic Mediterranean lifestyle concept store inside a 15th-century palace offering fashion, art, books, and home décor.",
      ca: "Icona de l'estil de vida mediterrani en un palau del segle XV amb moda internacional, art i decoració selecta.",
      de: "Ikonischer Lifestyle Concept Store im Palast aus dem 15. Jahrhundert mit internationaler Mode, Kunst und Wohnkultur.",
    },
    fullDescription: {
      es: "Rialto Living combina moda de alta costura, textiles exclusivos, mobiliario de diseño, galería de arte y un café gourmet en el corazón del casco antiguo de Palma, atrayendo a clientes cosmopolitas de todo el mundo.",
      en: "Rialto Living blends luxury fashion, exclusive fabrics, designer furniture, an art gallery, and a gourmet courtyard cafe in Palma's Old Town.",
      ca: "Rialto Living combina moda selecta, tèxtils exclusius, mobiliari de disseny i cafeteria gourmet al centre històric de Palma.",
      de: "Rialto Living vereint Premium-Mode, erlesene Heimtextilien, Designermöbel, eine Kunstgalerie und ein Gourmet-Café in Palmas Altstadt.",
    },
    highlights: {
      es: [
        "Ubicado en un majestuoso palacio gótico",
        "Colecciones exclusivas de moda y accesorios",
        "Estudio propio de interiorismo y proyectos",
        "Café-bistró en el patio interior",
      ],
      en: [
        "Set in a grand historic gothic palace",
        "Exclusive fashion and accessories",
        "In-house interior design studio",
        "Charming courtyard cafe bistro",
      ],
      ca: [
        "Situat en un majestuós palau gòtic",
        "Col·leccions exclusives de moda",
        "Estudi d'interiorisme propi",
        "Cafè al pati interior",
      ],
      de: [
        "In einem gotischen Stadtpalais gelegen",
        "Exklusive Modekollektionen und Accessoires",
        "Eigenes Innenarchitektur-Studio",
        "Café-Bistro im Innenhof",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de moda, calzado y joyería",
        "Consultoría y proyectos de interiorismo",
        "Venta de arte y piezas de colección",
        "Envíos internacionales a toda Europa",
      ],
      en: [
        "Fashion, footwear, and jewelry retail",
        "Interior design consulting and sourcing",
        "Fine art sales and exhibitions",
        "Worldwide European shipping",
      ],
      ca: [
        "Venda de moda, calçat i joieria",
        "Projectes d'interiorisme",
        "Venda d'art i peces de col·lecció",
        "Enviaments internacionals",
      ],
      de: [
        "Verkauf von Mode, Schuhen und Schmuck",
        "Einrichtungsberatung und Raumkonzepte",
        "Kunsthandel und Ausstellungen",
        "Europaweiter Versandservice",
      ],
    },
  },
  {
    slug: "camper-store-palma-jaime-iii",
    name: "Camper Flagship Store Jaume III",
    category: "boutiques-moda-mallorca",
    sectorFolder: "retail-comercio",
    sectorArrayName: "RETAIL_SERVICES",
    subcategories: ["calzado-diseno", "marca-mallorquina", "moda-sostenible"],
    zone: "palma",
    address: "Avinguda de Jaume III, 23, 07012 Palma",
    coordinates: { lat: 39.5718, lng: 2.6438 },
    rating: 4.6,
    reviewCount: 410,
    priceRange: "€€€",
    phone: "+34 971 716 525",
    website: "https://camper.com/es_ES/palma-jaume-iii",
    schedule: "Lunes a Sábado: 10:00 - 20:30",
    tags: ["zona:palma-centro", "product:premium", "mod:walk-in"],
    shortDescription: {
      es: "Tienda insignia de la legendaria marca balear de calzado de diseño contemporáneo, confort y sostenibilidad.",
      en: "Flagship store of Mallorca's globally renowned contemporary footwear brand combining style and ergonomic comfort.",
      ca: "Botiga insígnia de la prestigiosa marca mallorquina de calçat de disseny contemporani i comoditat.",
      de: "Flagship-Store der mallorquinischen Kult-Schuhmarke für zeitgenössisches Design und ergonomischen Komfort.",
    },
    fullDescription: {
      es: "Nacida en Inca (Mallorca) en 1975, Camper es un referente internacional del diseño de calzado. Esta tienda insignia en la avenida Jaume III exhibe sus modelos icónicos como Pelotas y Runner, junto a colaboraciones exclusivas.",
      en: "Founded in Inca in 1975, Camper is a world-renowned pioneer in creative footwear design. The Jaume III flagship presents iconic models alongside limited collaborations.",
      ca: "Fundada a Inca el 1975, Camper és un referent mundial del disseny de calçat amb models emblemàtics com Pelotas.",
      de: "1975 in Inca gegründet, ist Camper weltweit bekannt für innovatives Schuhdesign. Der Store zeigt Klassiker und Designerkooperationen.",
    },
    highlights: {
      es: [
        "Marca nacida y diseñada en Mallorca",
        "Iconos mundiales como Pelotas y Peu",
        "Diseño de tienda Together por arquitectos de renombre",
        "Compromiso con materiales reciclados y durabilidad",
      ],
      en: [
        "Born and designed in Mallorca",
        "Global icons including Pelotas and Peu",
        "Camper Together store design concept",
        "Commitment to sustainable craftsmanship",
      ],
      ca: [
        "Marca nascuda i dissenyada a Mallorca",
        "Models icònics mundials com Pelotas",
        "Disseny de botiga innovador",
        "Compromís amb la sostenibilitat",
      ],
      de: [
        "Auf Mallorca gegründete Weltmarke",
        "Globale Ikonen wie Pelotas und Peu",
        "Einzigartiges Together-Architekturkonzept",
        "Nachhaltige Materialien und Langlebigkeit",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de calzado para hombre, mujer e infantil",
        "Asesoramiento ergonómico y hormas especiales",
        "Garantía oficial y servicio de reparación",
        "Reserva online y recogida en tienda",
      ],
      en: [
        "Men's, women's, and kids' footwear",
        "Ergonomic fit guidance",
        "Official warranty and repair care",
        "Click & collect in store",
      ],
      ca: [
        "Venda de calçat per a home, dona i infants",
        "Assessorament ergonòmic",
        "Garantia oficial i reparacions",
        "Recollida a botiga",
      ],
      de: [
        "Herren-, Damen- und Kinderschuhe",
        "Ergonomische Passformberatung",
        "Offizielle Garantie und Reparaturservice",
        "Click & Collect im Store",
      ],
    },
  },
  {
    slug: "arquitectura-del-mueble-manacor",
    name: "Arquitectura del Mueble Manacor",
    category: "decoracion-muebles-diseno",
    sectorFolder: "retail-comercio",
    sectorArrayName: "RETAIL_SERVICES",
    subcategories: ["muebles-diseno", "interiorismo-fincas", "iluminacion-autor"],
    zone: "manacor-llevant",
    address: "Vía Palma, 68, 07500 Manacor",
    coordinates: { lat: 39.5711, lng: 3.2084 },
    rating: 4.8,
    reviewCount: 160,
    priceRange: "€€€",
    phone: "+34 971 550 420",
    website: "https://arquitecturadelmueble.com",
    schedule: "Lunes a Viernes: 09:30 - 13:30 y 16:30 - 20:00, Sábados: 10:00 - 13:30",
    tags: ["zona:manacor", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Showroom de mobiliario contemporáneo de primeras firmas europeas, sofás a medida y proyectos de decoración de villas.",
      en: "Showroom featuring top European contemporary furniture brands, custom sofas, and villa interior design.",
      ca: "Showroom de mobiliari contemporani de primeres marques europees i projectes de decoració de vil·les.",
      de: "Showroom für zeitgenössische Designermöbel europäischer Premium-Marken und Villeneinrichtung.",
    },
    fullDescription: {
      es: "En la histórica capital del mueble de Mallorca, este showroom ofrece una cuidada selección de marcas internacionales de mobiliario, iluminación de diseño y servicio integral de interiorismo con renders 3D para proyectos residenciales.",
      en: "Located in Mallorca's furniture capital Manacor, this showroom provides top international brands, architectural lighting, and 3D interior design services for luxury residences.",
      ca: "A la capital del moble de Mallorca, oferim marques internacionals de mobiliari, il·luminació de disseny i projectes 3D.",
      de: "In der Möbelstadt Manacor bietet dieser Showroom internationale Marken, Designleuchten und 3D-Innenarchitekturkonzepte.",
    },
    highlights: {
      es: [
        "Más de 1.500 m² de exposición de diseño",
        "Marcas líderes italianas, escandinavas y españolas",
        "Proyectos de interiorismo integral con visualización 3D",
        "Entrega, montaje y posventa con equipo propio",
      ],
      en: [
        "Over 1,500 m² of designer furniture display",
        "Leading Italian, Scandinavian, and Spanish brands",
        "Complete 3D interior design rendering",
        "In-house white-glove delivery and assembly",
      ],
      ca: [
        "Més de 1.500 m² d'exposició",
        "Primeres marques internacionals",
        "Projectes d'interiorisme amb 3D",
        "Muntatge i transport propi",
      ],
      de: [
        "Über 1.500 m² Ausstellungsfläche",
        "Führende italienische und skandinavische Marken",
        "Komplette 3D-Raumplanung",
        "Eigener Liefer- und Montageservice",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de mobiliario de salón, comedor y dormitorio",
        "Mobiliario exterior de alta resistencia",
        "Proyectos de interiorismo residencial y contract",
        "Instalación de iluminación técnica y decorativa",
      ],
      en: [
        "Living, dining, and bedroom furniture",
        "Weather-resistant outdoor luxury furniture",
        "Residential and contract interior design",
        "Architectural and decorative lighting setup",
      ],
      ca: [
        "Mobiliari de saló, menjador i dormitori",
        "Mobiliari exterior resistent",
        "Projectes d'interiorisme residencial",
        "Instal·lació d'il·luminació",
      ],
      de: [
        "Wohn-, Ess- und Schlafzimmermöbel",
        "Wetterfeste Luxus-Outdoor-Möbel",
        "Innenarchitektur für Wohnen und Gewerbe",
        "Lichtplanung und Leuchtenmontage",
      ],
    },
  },

  // ── ARTESANÍA & MANUFACTURA ──
  {
    slug: "vidrios-de-arte-gordiola-algaida",
    name: "Vidrios Gordiola Algaida (1719)",
    category: "vidrio-ceramica-artesanal",
    sectorFolder: "artesania-manufactura",
    sectorArrayName: "ARTESANIA_SERVICES",
    subcategories: ["vidrio-soplado", "artesania-historica", "patrimonio-inmaterial"],
    zone: "raiguer-pla",
    address: "Ctra. Palma-Manacor Km 19, 07210 Algaida",
    coordinates: { lat: 39.5584, lng: 2.8945 },
    rating: 4.8,
    reviewCount: 1650,
    priceRange: "€€€",
    phone: "+34 971 665 080",
    website: "https://gordiola.com",
    schedule: "Lunes a Sábado: 09:00 - 19:00, Domingos: 09:00 - 13:30",
    tags: ["zona:algaida", "product:lujo", "mod:walk-in"],
    shortDescription: {
      es: "La fábrica de vidrio soplado artesanal más antigua de España (1719), reconocida por la UNESCO como Patrimonio Inmaterial.",
      en: "Spain's oldest artisanal blown glass atelier (founded 1719), recognized by UNESCO as Intangible Cultural Heritage.",
      ca: "La fàbrica de vidre bufat artesanal més antiga d'Espanya (1719), reconeguda per la UNESCO.",
      de: "Spaniens traditionsreichste Glasbläserei (gegründet 1719), von der UNESCO als Immaterielles Weltkulturerbe anerkannt.",
    },
    fullDescription: {
      es: "Con más de 300 años de maestría ininterrumpida, Gordiola es un emblema mundial del vidrio soplado a mano. En su castillo-museo de Algaida, los maestros artesanos moldean el vidrio fundido ante los visitantes creando lámparas venecianas, copas y esculturas únicas.",
      en: "With over 300 years of unbroken craftsmanship, Gordiola is a world-renowned master of hand-blown glass. In its castle-museum in Algaida, master artisans shape glowing molten glass into chandeliers and sculptures.",
      ca: "Amb més de 300 anys d'història, Gordiola és un emblema del vidre bufat a mà. Al seu castell d'Algaida es poden veure els mestres vidriers en acció.",
      de: "Seit über 300 Jahren fertigt Gordiola kunstvolles mundgeblasenes Glas. In der Schlossmanufaktur in Algaida erleben Besucher traditionelle Glaskunst live am Schmelzofen.",
    },
    highlights: {
      es: [
        "Fundada en 1719: más de tres siglos de historia",
        "Demostraciones en vivo de vidrio soplado al horno",
        "Museo del vidrio histórico con piezas de todo el mundo",
        "Lámparas de araña mallorquinas y cristalería de autor",
      ],
      en: [
        "Founded in 1719: over 3 centuries of heritage",
        "Live hand-blown glass furnace demonstrations",
        "Historic glass museum with worldwide collections",
        "Mallorcan chandeliers and custom glassware",
      ],
      ca: [
        "Fundada el 1719: més de tres segles d'història",
        "Demostracions en viu de vidre bufat",
        "Museu del vidre amb peces històriques",
        "Llumeneres tradicionals i cristalleria",
      ],
      de: [
        "Gegründet 1719: über drei Jahrhunderte Tradition",
        "Live-Vorführungen am Glasbläserofen",
        "Historisches Glasmuseum",
        "Traditionelle Kronleuchter und Glaskunst",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de cristalería, lámparas y piezas artísticas",
        "Fabricación de encargos a medida y restauración",
        "Visitas culturales y escolares guiadas",
        "Embalaje especializado para envíos aéreos",
      ],
      en: [
        "Art glass, chandeliers, and stemware sales",
        "Custom commissions and antique restoration",
        "Guided museum and workshop visits",
        "Specialized air-travel protective packaging",
      ],
      ca: [
        "Venda de cristalleria, làmpades i peces artístiques",
        "Comandes a mida i restauració",
        "Visites guiades al museu i taller",
        "Embalatge protegit per a viatges",
      ],
      de: [
        "Verkauf von Glaskunst, Leuchten und Gläsern",
        "Sonderanfertigungen und Glasrestaurierung",
        "Führungen durch Werkstatt und Museum",
        "Sicherer Spezialversand für Flugreisende",
      ],
    },
  },
  {
    slug: "ceramicas-lafiore-sencelles",
    name: "Lafiore Vidrio & Artesanía Mediterránea",
    category: "vidrio-ceramica-artesanal",
    sectorFolder: "artesania-manufactura",
    sectorArrayName: "ARTESANIA_SERVICES",
    subcategories: ["vidrio-reciclado", "ceramica-contemporanea", "diseno-mediterraneo"],
    zone: "tramuntana",
    address: "Ctra. Palma-Valldemossa Km 11, 07190 Esporles",
    coordinates: { lat: 39.6384, lng: 2.6021 },
    rating: 4.7,
    reviewCount: 890,
    priceRange: "€€€",
    phone: "+34 971 610 014",
    website: "https://lafiore.com",
    schedule: "Lunes a Viernes: 09:00 - 18:00, Sábados: 09:00 - 14:00",
    tags: ["zona:esporles", "product:premium", "mod:walk-in"],
    shortDescription: {
      es: "Fábrica artesanal de vidrio soplado 100% reciclado y cerámica de vanguardia con colores vivos mediterráneos.",
      en: "Artisanal factory crafting 100% recycled hand-blown glass and vibrant contemporary Mediterranean ceramics.",
      ca: "Fàbrica artesanal de vidre bufat 100% reciclat i ceràmica de disseny amb colors mediterranis.",
      de: "Handwerkliche Manufaktur für 100% recyceltes mundgeblasenes Glas und moderne mediterrane Keramik.",
    },
    fullDescription: {
      es: "Lafiore reinventa la tradición del vidrio soplado en Mallorca apostando por el ecodiseño y el reciclaje integral. Sus aceiteras antigoteo, vajillas y esculturas destacan por su dinamismo cromático y su compromiso ambiental.",
      en: "Lafiore reinterprets Mallorca's glassblowing heritage through eco-design and recycled materials, creating iconic oil cruets, tableware, and colorful decorative pieces.",
      ca: "Lafiore reinventa la tradició del vidre bufat a Mallorca apostant pel disseny ecològic i el reciclatge.",
      de: "Lafiore verbindet mallorquinische Glasbläsertradition mit Ökodesign. Berühmt für tropffreie Ölkännchen und farbenfrohe Glaskunst.",
    },
    highlights: {
      es: [
        "Vidrio 100% reciclado y producción sostenible",
        "Aceiteras marquina y vajillas de diseño propio",
        "Demostraciones de soplado en directo",
        "Tienda de productos gourmet y telas mallorquinas",
      ],
      en: [
        "100% recycled glass and sustainable production",
        "Signature drip-free oil cruets and tableware",
        "Live glassblowing furnace shows",
        "Gourmet local products and Mallorcan fabrics",
      ],
      ca: [
        "Vidre 100% reciclat i producció sostenible",
        "Setrills antigoteig i vaixelles exclusives",
        "Demostracions de bufat en directe",
        "Botiga gourmet i teles mallorquines",
      ],
      de: [
        "100% Recyclingglas und nachhaltige Fertigung",
        "Tropffreie Menagen und Design-Geschirr",
        "Live-Vorführungen am Glasofen",
        "Gourmet-Ecke und traditionelle Stoffe",
      ],
    },
    servicesProvided: {
      es: [
        "Venta directa de cristalería y vajillas",
        "Talleres participativos de soplado de vidrio",
        "Encargos corporativos y regalos de boda",
        "Envíos directos a domicilio",
      ],
      en: [
        "Direct retail of glassware and tableware",
        "Hands-on glassblowing workshops",
        "Corporate gifts and bespoke wedding favors",
        "Direct home delivery worldwide",
      ],
      ca: [
        "Venda directa de cristalleria i vaixelles",
        "Tallers de vidre bufat",
        "Regals d'empresa i casaments",
        "Enviaments a domicili",
      ],
      de: [
        "Verkauf von Gläsern und Tischkultur",
        "Mitmach-Workshops im Glasblasen",
        "Firmengeschenke und Hochzeitspräsente",
        "Weltweiter Versand",
      ],
    },
  },
  {
    slug: "teixits-vicens-pollensa",
    name: "Teixits Vicens Roba de Llengües Pollença (1854)",
    category: "carpinteria-piedra-tradicional",
    sectorFolder: "artesania-manufactura",
    sectorArrayName: "ARTESANIA_SERVICES",
    subcategories: ["telas-de-lenguas", "telar-artesanal", "patrimonio-textil"],
    zone: "alcudia-pollensa",
    address: "Rotonda Can Berenguer, s/n, 07460 Pollença",
    coordinates: { lat: 39.8785, lng: 3.0245 },
    rating: 4.9,
    reviewCount: 920,
    priceRange: "€€€",
    phone: "+34 971 530 450",
    website: "https://teixitsvicens.com",
    schedule: "Lunes a Viernes: 09:00 - 20:00, Sábados: 09:00 - 14:00",
    tags: ["zona:pollenca", "product:lujo", "mod:walk-in"],
    shortDescription: {
      es: "Taller artesano textil fundado en 1854 que mantiene vivo el arte del ikat mallorquín con tintes naturales y telares tradicionales.",
      en: "Artisan textile workshop founded in 1854 preserving authentic Mallorcan ikat cloth ('roba de llengües') on antique looms.",
      ca: "Taller artesà tèxtil fundat el 1854 que manté viu l'art del teixit de llengües mallorquí en telers tradicionals.",
      de: "1854 gegründete Weberei, die den traditionellen mallorquinischen Ikat-Stoff ('Roba de Llengües') auf historischen Webstühlen fertigt.",
    },
    fullDescription: {
      es: "Teixits Vicens es una de las tres únicas fábricas en Europa que conservan la técnica ancestral del Ikat. Desde hace cinco generaciones, la familia Vicens confecciona telas de lenguas de lino y algodón para decoración de interiores, cortinas, tapicerías y complementos de moda.",
      en: "Teixits Vicens is one of only three workshops in Europe still practicing traditional Ikat dyeing. For five generations, the Vicens family has woven cotton-linen fabrics for luxury interiors and fashion.",
      ca: "Teixits Vicens és una de les tres úniques fàbriques a Europa que conserven la tècnica ancestral de l'Ikat. Cinc generacions creant robes tradicionals.",
      de: "Teixits Vicens ist eine der letzten Webereien Europas, die echte Ikat-Färbetechnik nutzt. Fünf Generationen feinste Leinen-Baumwollstoffe für Interieurs.",
    },
    highlights: {
      es: [
        "Taller textil centenario activo desde 1854",
        "Técnica ancestral de Ikat con tintes indelebles",
        "Tejidos 100% naturales de lino y algodón",
        "Visitas gratuitas al taller de tejedores",
      ],
      en: [
        "Centenary textile workshop operating since 1854",
        "Ancestral Ikat resist-dyeing technique",
        "100% natural linen and cotton fabrics",
        "Free tours of the historic weaving floor",
      ],
      ca: [
        "Taller tèxtil centenari actiu des de 1854",
        "Tècnica ancestral d'Ikat",
        "Teixits 100% naturals de lli i cotó",
        "Visites gratuïtes al taller",
      ],
      de: [
        "Traditionelle Weberei seit 1854 aktiv",
        "Echte Ikat-Handfärbetechnik",
        "100% natürliche Leinen-Baumwollstoffe",
        "Kostenlose Besichtigung der Webstühle",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de telas al metro y por piezas",
        "Confección a medida de cortinas, cojines y mantelerías",
        "Tapicería de muebles y cabeceros de cama",
        "Bolsos, calzado y complementos artesanales",
      ],
      en: [
        "Fabric by the meter and rolled lengths",
        "Custom drapery, cushions, and table linens",
        "Upholstery for furniture and headboards",
        "Handcrafted bags, espadrilles, and accessories",
      ],
      ca: [
        "Venda de teles per metres",
        "Confecció a mida de cortines i coixins",
        "Tapisseria de mobles i capçals",
        "Bosses i complements artesanals",
      ],
      de: [
        "Stoffverkauf als Meterware",
        "Maßanfertigung von Vorhängen und Kissen",
        "Polsterarbeiten für Möbel und Betthäupter",
        "Taschen, Espadrilles und Wohnaccessoires",
      ],
    },
  },

  // ── AGRICULTURA & PRODUCTORES (BODEGAS & KM0) ──
  {
    slug: "bodega-macia-batle-santa-maria",
    name: "Bodegues Macià Batle Santa Maria (1856)",
    category: "bodegas-enoturismo",
    sectorFolder: "agricultura-productores",
    sectorArrayName: "AGRICULTURA_SERVICES",
    subcategories: ["enoturismo-catas", "vinos-do-binissalem", "aceite-oliva-virgen"],
    zone: "raiguer-pla",
    address: "Camí de Coanegra, s/n, 07320 Santa Maria del Camí",
    coordinates: { lat: 39.6542, lng: 2.7758 },
    rating: 4.8,
    reviewCount: 1420,
    priceRange: "€€",
    phone: "+34 971 140 014",
    website: "https://maciabatle.com",
    schedule: "Lunes a Viernes: 09:00 - 18:30, Sábados: 09:30 - 14:00",
    tags: ["zona:santa-maria-del-cami", "product:premium", "mod:walk-in"],
    shortDescription: {
      es: "Bodega emblemática fundada en 1856 elaboradora de vinos tintos y blancos de uva autóctona Manto Negro y Prensal Blanc.",
      en: "Historic winery founded in 1856 crafting fine red and white wines from native Manto Negro and Prensal grapes.",
      ca: "Celler emblemàtic fundat el 1856 que elabora vins de varietats autòctones Manto Negro i Moll.",
      de: "1856 gegründetes Traditionsweingut für Spitzenweine aus den einheimischen Rebsorten Manto Negro und Prensal Blanc.",
    },
    fullDescription: {
      es: "Macià Batle es un referente del vino balear con Denominación de Origen Binissalem. Ofrece visitas guiadas a sus cavas, catas maridadas con embutidos artesanos y patés mallorquines, y exposiciones de artistas que diseñan sus etiquetas.",
      en: "Macià Batle is a flagship Balearic winery in the DO Binissalem region, offering cellar tours, wine tastings paired with local delicacies, and art exhibitions.",
      ca: "Macià Batle és un referent del vi mallorquí amb DO Binissalem. Ofereix visites guiades a les caves i tasts maridats.",
      de: "Macià Batle ist eines der renommiertesten Weingüter der DO Binissalem mit Kellerführungen, Weinproben mit mallorquinischen Tapas und Kunstgalerie.",
    },
    highlights: {
      es: [
        "Bodega histórica activa desde 1856",
        "Vinos premiados internacionalmente con DO Binissalem",
        "Visita guiada por viñedos y sala de barricas",
        "Cata maridada con productos gourmet de Mallorca",
      ],
      en: [
        "Historic winery operating since 1856",
        "Internationally awarded DO Binissalem wines",
        "Guided tour through vineyards and barrel cellars",
        "Wine tasting paired with local artisan delicacies",
      ],
      ca: [
        "Celler històric actiu des de 1856",
        "Vins premiats amb DO Binissalem",
        "Visita als vinyes i sala de bótes",
        "Tast maridat amb productes gourmet",
      ],
      de: [
        "Traditionskellerei seit 1856",
        "Prämierte Weine mit Herkunftsbezeichnung DO Binissalem",
        "Führungen durch Weinberge und Fasskeller",
        "Weinprobe mit mallorquinischen Delikatessen",
      ],
    },
    servicesProvided: {
      es: [
        "Visitas enoturísticas guiadas y catas",
        "Venta directa de vinos y aceites de oliva virgen extra",
        "Eventos corporativos y celebraciones en bodega",
        "Envíos de vino a cualquier país de la UE",
      ],
      en: [
        "Guided winery tours and tasting sessions",
        "Direct sales of wines and extra virgin olive oils",
        "Private corporate events in wine cellars",
        "Direct wine case shipping across the EU",
      ],
      ca: [
        "Visites enoturístiques i tasts de vins",
        "Venda directa de vins i oli d'oliva verge extra",
        "Esdeveniments corporatius",
        "Enviaments a la Unió Europea",
      ],
      de: [
        "Geführte Weintouren und Degustationen",
        "Direktverkauf von Weinen und nativem Olivenöl",
        "Firmenevents und private Feiern im Weinkeller",
        "Direktversand in die gesamte EU",
      ],
    },
  },
  {
    slug: "bodega-jose-l-ferrer-binissalem",
    name: "Bodegas José L. Ferrer Binissalem (1931)",
    category: "bodegas-enoturismo",
    sectorFolder: "agricultura-productores",
    sectorArrayName: "AGRICULTURA_SERVICES",
    subcategories: ["enoturismo-catas", "vinos-do-binissalem", "visitas-viñedo"],
    zone: "raiguer-pla",
    address: "Carrer del Conquistador, 103, 07350 Binissalem",
    coordinates: { lat: 39.6892, lng: 2.8421 },
    rating: 4.8,
    reviewCount: 1100,
    priceRange: "€€",
    phone: "+34 971 511 050",
    website: "https://vinosferrer.com/bodega-binissalem",
    schedule: "Lunes a Viernes: 09:00 - 19:00, Sábados: 10:00 - 14:00",
    tags: ["zona:binissalem", "product:premium", "mod:walk-in"],
    shortDescription: {
      es: "Bodega pionera de Binissalem fundada en 1931, cuna del vino embotellado y de las grandes reservas mallorquinas.",
      en: "Pioneering Binissalem winery founded in 1931, cradle of fine bottled wines and aged reservas in Mallorca.",
      ca: "Celler pioner de Binissalem fundat el 1931, bressol del vi embotellat i de les grans reserves.",
      de: "Pionier-Weingut in Binissalem aus dem Jahr 1931, Wiege der ersten Flaschenabfüllungen und edlen Gran Reservas.",
    },
    fullDescription: {
      es: "Cuatro generaciones de la familia Ferrer han liderado la modernización del vino en Mallorca. Sus instalaciones aúnan tradición vinícola centenaria y arquitectura contemporánea, ofreciendo experiencias enológicas inmersivas.",
      en: "Four generations of the Ferrer family have championed winemaking excellence in Mallorca, blending heritage stone cellars with contemporary architecture for immersive wine tours.",
      ca: "Quatre generacions de la família Ferrer liderant la qualitat del vi a Mallorca amb instal·lacions històriques i modernes.",
      de: "Vier Generationen der Familie Ferrer bürgen für Spitzenweine. Historische Felsenkeller und moderne Architektur laden zu unvergesslichen Weinreisen ein.",
    },
    highlights: {
      es: [
        "Fundada en 1931 por José Luis Ferrer",
        "Pioneros en la crianza en roble de la variedad Manto Negro",
        "Cavas subterráneas históricas y viñedo experimental",
        "Catas prémium con quesos curados y embutidos",
      ],
      en: [
        "Founded in 1931 by José Luis Ferrer",
        "Pioneers in oak barrel aging of native Manto Negro",
        "Historic underground cellars and tasting rooms",
        "Premium tastings paired with artisan cheeses",
      ],
      ca: [
        "Fundat el 1931 per José Luis Ferrer",
        "Pioners en la criança en roure de Manto Negro",
        "Caves subterrànies històriques",
        "Tasts amb formatges curats de l'illa",
      ],
      de: [
        "Gegründet 1931 von José Luis Ferrer",
        "Pioniere im Eichenfassausbau der Manto-Negro-Traube",
        "Historische unterirdische Weinkeller",
        "Premium-Verkostungen mit Käsespezialitäten",
      ],
    },
    servicesProvided: {
      es: [
        "Visitas a viñedos y salas de fermentación",
        "Catas comentadas por sumilleres titulados",
        "Tienda enológica y venta de cosechas exclusivas",
        "Club de barricas y reservas privadas",
      ],
      en: [
        "Vineyard and fermentation room tours",
        "Sommelier-guided professional tastings",
        "Wine shop with exclusive limited releases",
        "Private barrel club allocations",
      ],
      ca: [
        "Visites a les vinyes i instal·lacions",
        "Tasts comentats per sommeliers",
        "Botiga enològica amb edicions limitades",
        "Club de bótes privades",
      ],
      de: [
        "Touren durch Weinberge und Gärkeller",
        "Fachkundig geführte Sommelier-Verkostungen",
        "Vinothek mit limitierten Jahrgängen",
        "Fasskauf und Reserven für Mitglieder",
      ],
    },
  },
  {
    slug: "oli-de-jornets-sencelles",
    name: "Oli de Jornets Tafona & Finca Sencelles (1998)",
    category: "aceite-oliva-almazaras",
    sectorFolder: "agricultura-productores",
    sectorArrayName: "AGRICULTURA_SERVICES",
    subcategories: ["aceite-oliva-virgen-extra", "denominacion-origen-mallorca", "almazara-artesanal"],
    zone: "raiguer-pla",
    address: "Llogaret de Jornets, s/n, 07140 Sencelles",
    coordinates: { lat: 39.6458, lng: 2.8984 },
    rating: 4.9,
    reviewCount: 220,
    priceRange: "€€€",
    phone: "+34 971 872 100",
    website: "https://olidejornets.es",
    schedule: "Lunes a Viernes: 09:00 - 15:00 (Citas previas para catas)",
    tags: ["zona:sencelles", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Finca olivarera y almazara de alta gama galardonada internacionalmente por su Aceite de Oliva Virgen Extra DO Oli de Mallorca.",
      en: "Award-winning boutique olive estate and mill producing internationally acclaimed Extra Virgin Olive Oil DO Oli de Mallorca.",
      ca: "Finca i tafona d'alta gamma guardonada internacionalment pel seu Oli d'Oliva Verge Extra DO Oli de Mallorca.",
      de: "Preisgekröntes Olivenöl-Gut mit eigener Ölmühle für international prämiertes natives Olivenöl extra DO Oli de Mallorca.",
    },
    fullDescription: {
      es: "Situada en el idílico llogaret de Jornets, esta almazara familiar recolecta aceitunas arbequina y picual en su punto óptimo de maduración y las extrae en frío en menos de 3 horas, logrando un aceite de bajísima acidez y aromas frutados excepcionales.",
      en: "Located in the hamlet of Jornets, this family mill harvests Arbequina and Picual olives at peak maturity and cold-presses them within 3 hours for ultra-low acidity and intense fruit aromas.",
      ca: "Situada al llogaret de Jornets, aquesta tafona familiar elabora oli verge extra d'olives arbequines amb extracció en fred immediata.",
      de: "Im idyllischen Dorf Jornets gelegen, presst dieses Familiengut Arbequina- und Picual-Oliven binnen 3 Stunden kalt zu Spitzen-Olivenöl.",
    },
    highlights: {
      es: [
        "Denominación de Origen Protegida Oli de Mallorca",
        "Extracción en frío (< 22°C) en menos de 3 horas",
        "Medallas de Oro en concursos internacionales de Nueva York y Tokio",
        "Olivar ecológico cuidado con técnicas tradicionales",
      ],
      en: [
        "Protected DO Oli de Mallorca certification",
        "Cold extraction (< 22°C) within 3 hours of harvest",
        "Gold medals in New York and Tokyo olive oil competitions",
        "Organic olive grove tended with traditional care",
      ],
      ca: [
        "Denominació d'Origen Protegida Oli de Mallorca",
        "Extracció en fred (< 22°C)",
        "Medalles d'Or internacionals a Nova York i Tòquio",
        "Olivar ecològic",
      ],
      de: [
        "Geschützte Herkunftsbezeichnung DO Oli de Mallorca",
        "Kaltextraktion (< 22°C) binnen 3 Stunden",
        "Goldmedaillen bei Wettbewerben in New York und Tokio",
        "Ökologischer Olivenanbau",
      ],
    },
    servicesProvided: {
      es: [
        "Venta directa de botellas y latas de AOVE prémium",
        "Visitas guiadas al olivar y tafona con cata técnica",
        "Packs gourmet y regalos corporativos para empresas",
        "Envíos directos a cualquier punto de Europa",
      ],
      en: [
        "Direct sales of premium EVOO bottles and tins",
        "Guided grove and mill tours with olive oil tasting",
        "Gourmet gift packs and corporate hampers",
        "Direct delivery across Europe",
      ],
      ca: [
        "Venda directa d'oli verge extra prémium",
        "Visites guiades i tasts tècnics",
        "Lots gourmet per a regals",
        "Enviaments a tota Europa",
      ],
      de: [
        "Verkauf von Premium-Olivenöl in Flaschen und Kanistern",
        "Führungen durch Olivenhaine mit Verkostung",
        "Gourmet-Geschenkboxen für Firmen",
        "Direktversand nach Deutschland und ganz Europa",
      ],
    },
  },

  // ── SERVICIOS SOCIALES & ASISTENCIA ──
  {
    slug: "asistencia-domiciliaria-mallorca-canguros-palma",
    name: "Mallorca Care & Nanny Services Palma",
    category: "cuidado-mayores-asistencia",
    sectorFolder: "servicios-sociales",
    sectorArrayName: "SOCIALES_SERVICES",
    subcategories: ["cuidado-mayores", "asistencia-domiciliaria", "nanny-bilingue"],
    zone: "palma",
    address: "Carrer d'Aragó, 78, 07005 Palma",
    coordinates: { lat: 39.5789, lng: 2.6598 },
    rating: 4.9,
    reviewCount: 175,
    priceRange: "€€",
    phone: "+34 971 460 300",
    website: "https://mallorcacare.es",
    schedule: "Atención Telefónica 24 Horas / 365 Días (Oficina: L-V 09:00 - 18:00)",
    tags: ["zona:palma-centro", "product:premium", "mod:cita-previa"],
    shortDescription: {
      es: "Agencia oficial de cuidados asistenciales a domicilio para mayores, acompañamiento hospitalario y nannies bilingües en Mallorca.",
      en: "Certified agency providing in-home elder care, hospital companionship, and multilingual professional nannies across Mallorca.",
      ca: "Agència oficial d'atenció domiciliària a la gent gran, acompanyament hospitalari i cuidadores bilingües.",
      de: "Zertifizierte Agentur für häusliche Seniorenbetreuung, Krankenhausbegleitung und mehrsprachige Nannies auf Mallorca.",
    },
    fullDescription: {
      es: "Mallorca Care ofrece personal sanitario y cuidadores titulados con verificación de antecedentes penales y formación continua. Brinda servicios flexibles por horas, régimen interno o nocturno, tanto a familias residentes como a visitantes en villas u hoteles.",
      en: "Mallorca Care provides fully vetted, certified caregivers and nurses offering hourly, overnight, and live-in assistance for resident families and holidaymakers in private villas.",
      ca: "Mallorca Care ofereix personal sanitari titulat i cuidadores de confiança per hores o règim intern per a residents i visitants.",
      de: "Mallorca Care vermittelt qualifizierte Pflegekräfte und Nannies auf Stundenbasis oder 24h-Betreuung für Einheimische und Villengäste.",
    },
    highlights: {
      es: [
        "Personal sociosanitario titulado y verificado",
        "Atención multilingüe en español, inglés y alemán",
        "Cobertura 24 horas y fines de semana",
        "Servicio en domicilios particulares, villas y hospitales",
      ],
      en: [
        "Vetted, certified healthcare and childcare staff",
        "Multilingual care in English, Spanish, and German",
        "24/7 round-the-clock availability",
        "Services at private homes, villas, and hospitals",
      ],
      ca: [
        "Personal titulat i certificat",
        "Atenció multilingüe (català, castellà, anglès, alemany)",
        "Cobertura 24 hores",
        "Serveis a domicilis, vil·les i hospitals",
      ],
      de: [
        "Qualifiziertes und geprüftes Pflegepersonal",
        "Mehrsprachige Betreuung (Deutsch, Englisch, Spanisch)",
        "24/7 Notfall- und Wochenendbereitschaft",
        "Einsatz in Privathaushalten, Fincas und Kliniken",
      ],
    },
    servicesProvided: {
      es: [
        "Acompañamiento y cuidado de personas mayores",
        "Auxiliares de enfermería y control de medicación",
        "Servicio de nannies y canguros bilingües para niños",
        "Acompañamiento hospitalario nocturno y diurno",
      ],
      en: [
        "Elderly companionship and daily living support",
        "Nursing aides and medication management",
        "Bilingual nannies and childcare for villas",
        "Hospital bedside support day and night",
      ],
      ca: [
        "Acompanyament i cura de persones grans",
        "Auxiliars d'infermeria i medicació",
        "Cangurs i nannies bilingües per a infants",
        "Acompanyament a hospitals",
      ],
      de: [
        "Seniorenbegleitung und Alltagshilfe",
        "Grundpflege und Medikamentengabe",
        "Mehrsprachige Kinderbetreuung und Hotel-Babysitter",
        "Krankenhaus-Sitzwachen Tag und Nacht",
      ],
    },
  },
  {
    slug: "escoleta-infantil-bilingue-palma-son-espanyolet",
    name: "Escoleta Infantil Bilingüe Son Espanyolet",
    category: "guarderias-infantil-canguros",
    sectorFolder: "servicios-sociales",
    sectorArrayName: "SOCIALES_SERVICES",
    subcategories: ["educacion-infantil", "guarderia-bilingue", "estimulacion-temprana"],
    zone: "palma",
    address: "Carrer de Joan Crespí, 42, 07014 Palma",
    coordinates: { lat: 39.5742, lng: 2.6321 },
    rating: 4.9,
    reviewCount: 94,
    priceRange: "€€",
    phone: "+34 971 738 910",
    website: "https://escoletasonespanyolet.com",
    schedule: "Lunes a Viernes: 07:30 - 17:30",
    tags: ["zona:palma-centro", "product:familiar", "mod:en-local"],
    shortDescription: {
      es: "Centro de educación infantil de 0 a 3 años con inmersión lingüística en inglés y catalán, pedagogía activa y cocina propia ecológica.",
      en: "Early childhood center (ages 0-3) with English and Catalan language immersion, active pedagogy, and organic in-house kitchen.",
      ca: "Centre d'educació infantil de 0 a 3 anys amb immersió en anglès i català, pedagogia activa i cuina pròpia ecològica.",
      de: "Frühkindliche bilinguale Kita (0-3 Jahre) mit Englisch- und Katalanisch-Immersion, aktiver Pädagogik und Bio-Küche.",
    },
    fullDescription: {
      es: "Situada en el tranquilo barrio de Son Espanyolet, esta escuela infantil cuenta con amplias aulas luminosas, patio exterior ajardinado de 200 m² con huerto escolar y un proyecto educativo centrado en el respeto a los ritmos madurativos y la estimulación sensorial.",
      en: "Located in the quiet Son Espanyolet neighborhood, this nursery features bright classrooms, a 200 m² garden playground with educational veggie patch, and a child-centered emotional pedagogy.",
      ca: "Situada a Son Espanyolet, aquesta escoleta disposa d'aules àmplies, pati enjardinat de 200 m² amb hortet i cuina ecològica.",
      de: "In Son Espanyolet gelegen, bietet diese Kita helle Räume, einen 200 m² großen Garten mit Kinderbeet und bio-zertifizierte Küche.",
    },
    highlights: {
      es: [
        "Educadoras infantiles tituladas y nativas en inglés",
        "Patio exterior soleado de 200 m² con arena y huerto",
        "Comedor con menús ecológicos Km 0 elaborados a diario",
        "Horario flexible de 07:30 a 17:30 para conciliación",
      ],
      en: [
        "Certified early childhood teachers with native English staff",
        "Sunny 200 m² garden with sandbox and veggie plot",
        "Daily organic farm-to-table lunch prepared on site",
        "Flexible hours from 07:30 to 17:30 for working parents",
      ],
      ca: [
        "Educadores titulades i personal natiu en anglès",
        "Pati exterior de 200 m² amb hort escolar",
        "Menjador ecològic Km 0 cuinat al centre",
        "Horari flexible de 07:30 a 17:30",
      ],
      de: [
        "Qualifizierte Erzieherinnen und englische Muttersprachler",
        "200 m² sonniger Garten mit Sandbereich und Beet",
        "Täglich frisch gekochtes Bio-Essen aus der Region",
        "Flexible Öffnungszeiten von 07:30 bis 17:30",
      ],
    },
    servicesProvided: {
      es: [
        "Aulas de bebés (0-1 años), medianos (1-2) y mayores (2-3)",
        "Comedor y meriendas con productos ecológicos",
        "Escola d'estiu (campamento de verano en julio y agosto)",
        "Talleres de psicomotricidad y música para familias",
      ],
      en: [
        "Infant (0-1), toddler (1-2), and pre-K (2-3) classrooms",
        "Organic daily meals and afternoon healthy snacks",
        "Summer camp program during July and August",
        "Music and psychomotor workshops for families",
      ],
      ca: [
        "Aules de nadons, mitjans i grans",
        "Menjador amb productes ecològics",
        "Escola d'estiu al juliol i agost",
        "Tallers de psicomotricitat i música",
      ],
      de: [
        "Baby- (0-1), Kleinkind- (1-2) und Vorschulgruppen (2-3)",
        "Bio-Mittagessen und gesunde Nachmittagsjause",
        "Sommercamp im Juli und August",
        "Psychomotorik- und Musikkurse",
      ],
    },
  },
];

ingestBatch(BATCH_1);
