import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_6: BusinessDataInput[] = [
  // ── 1. ALOJAMIENTO & TURISMO ──
  {
    slug: "hotel-boutique-sa-pedrissa-deia",
    name: "Hotel Boutique & Restaurant Sa Pedrissa Deià",
    category: "hoteles-boutique-agroturismo",
    sectorFolder: "alojamiento-turismo",
    sectorArrayName: "ALOJAMIENTO_SERVICES",
    subcategories: ["hotel-adults-only", "vistas-mar-tramuntana", "restaurante-gastronomico"],
    zone: "tramuntana",
    address: "Ctra. Valldemossa-Deià Km 64.5, 07179 Deià",
    coordinates: { lat: 39.7548, lng: 2.6378 },
    rating: 4.9,
    reviewCount: 380,
    priceRange: "€€€€",
    phone: "+34 971 639 111",
    website: "https://sapedrissaboutiquehotel.com",
    schedule: "Recepción 24 horas (Temporada de Marzo a Noviembre)",
    tags: ["zona:deia", "product:lujo", "product:adultos"],
    shortDescription: {
      es: "Antigua posesión del siglo XVII convertida en hotel boutique 'Adults Only' encaramada sobre los acantilados de Deià con vistas a Sa Foradada.",
      en: "17th-century historic cliffside estate transformed into an Adults-Only boutique hotel overlooking Deià and Sa Foradada sunsets.",
      ca: "Antiga possessió del segle XVII convertida en hotel boutique només per a adults sobre els penya-segats de Deià.",
      de: "Historisches Landgut aus dem 17. Jh. als Adults-Only Boutique-Hotel auf den Klippen von Deià mit Blick auf Sa Foradada.",
    },
    fullDescription: {
      es: "Sa Pedrissa fue una torre de defensa y residencia señorial con vistas infinitas al mar Mediterráneo. Dispone de piscina desbordante sobre el acantilado, suites de ensueño con terraza privada y un restaurante de alta cocina mallorquina contemporánea.",
      en: "Historically a coastal defense estate with endless Mediterranean views, featuring a cliff-edge infinity pool, private suites, and refined local gastronomy.",
      ca: "Amb vistes infinites a la mar, ofereix piscina desbordant sobre el penya-segat, suites exclusives i cuina mallorquina d'autor.",
      de: "Einst herrschaftlicher Verteidigungssitz mit Traumblick: Infinity-Pool an der Steilküste, exklusive Suiten und gehobene Inselküche.",
    },
    highlights: {
      es: [
        "Exclusividad 'Adults Only' para máxima tranquilidad y relax",
        "Vistas panorámicas directas a la puesta de sol de Sa Foradada",
        "Piscina infinity sobre el mar rodeada de olivos centenarios",
        "Restaurante gastronómico con productos de huerto propio",
      ],
      en: [
        "Adults-Only exclusivity for ultimate peace and privacy",
        "Direct panoramic sunset views of iconic Sa Foradada rock",
        "Cliff-edge infinity swimming pool among centenary olives",
        "Fine dining restaurant with estate-grown produce",
      ],
      ca: [
        "Exclusivitat per a adults",
        "Vistes directes a la posta de sol de Sa Foradada",
        "Piscina infinity sobre la mar",
        "Restaurant gastronòmic",
      ],
      de: [
        "Adults-Only Konzept für ungestörte Ruhe",
        "Panoramablick auf die legendären Sonnenuntergänge von Sa Foradada",
        "Klippen-Infinity-Pool inmitten alter Olivenbäume",
        "Gourmetrestaurant mit Finca-eigenem Gemüseanbau",
      ],
    },
    servicesProvided: {
      es: [
        "Alojamiento en suites con vistas al mar y piscina privada en selectas habitaciones",
        "Almuerzos y cenas gourmet en la terraza panorámica",
        "Masajes en el jardín exterior con aromaterapia mediterránea",
        "Organización de traslados VIP en helicóptero o chófer privado",
      ],
      en: [
        "Sea-view suites with private plunge pools in select units",
        "Gourmet lunch and dinner dining on the scenic terrace",
        "Outdoor garden massages with Mediterranean aromatherapy",
        "Helicopter transfers and private chauffeured island tours",
      ],
      ca: [
        "Allotjament en suites amb vistes a la mar",
        "Dinars i sopars gourmet a la terrassa",
        "Massatges a l'aire lliure",
        "Trasllats privats",
      ],
      de: [
        "Übernachtung in Suiten mit Meerblick (teils mit Privatpool)",
        "Gourmet-Menüs auf der Panoramaterrasse",
        "Garten-Massagen mit mediterranen Ölen",
        "Helikopter-Transfers und Chauffeurdienste",
      ],
    },
  },

  // ── 2. GASTRONOMÍA TRADICIONAL & CELLERS ──
  {
    slug: "celler-son-sant-marti-muro-tradicional",
    name: "Celler Son Sant Martí Cuina Mallorquina Muro",
    category: "gastronomia-catering",
    sectorFolder: "gastronomia-restaurantes",
    sectorArrayName: "RESTAURANT_SERVICES",
    subcategories: ["celler-tradicional", "cocina-mallorquina-casera", "arroz-brut-caracoles"],
    zone: "alcudia-pollensa",
    address: "Carrer de Santa Anna, 28, 07440 Muro",
    coordinates: { lat: 39.7345, lng: 3.0567 },
    rating: 4.8,
    reviewCount: 920,
    priceRange: "€€",
    phone: "+34 971 537 440",
    website: "https://sonsantmartimuro.es",
    schedule: "Martes a Domingo: 13:00 - 16:00 y 20:00 - 23:30",
    tags: ["zona:muro", "product:cocina-mallorquina", "mod:walk-in"],
    shortDescription: {
      es: "Celler emblemático en una casa señorial de Muro especializado en platos de cuchara mallorquines: caracoles con alioli, arròs brut y frito de matanzas.",
      en: "Emblematic celler inside a historic Muro manor house serving traditional Mallorcan spoon dishes: braised snails with aioli, arròs brut, and frito.",
      ca: "Celler emblemàtic en un casal senyorial de Muro especialitzat en caragols amb allioli, arròs brut i frit de matances.",
      de: "Traditioneller Weinkeller in einem Herrenhaus in Muro: Landschnecken mit Aioli, Arròs Brut und hausgemachtes Frito Mallorquín.",
    },
    fullDescription: {
      es: "Ubicado en el pueblo de Muro, este celler rústico con techos altos de vigas vistas y tinajas tradicionales ofrece la gastronomía más reconfortante del norte de Mallorca. Caracoles aromatizados con hierbabuena e hinojo, lechona crujiente y vinos de la tierra.",
      en: "Set in rural Muro with exposed timber beams and terracotta wine vats, serving soul-warming heritage recipes from northern Mallorca.",
      ca: "A Muro, aquest celler rústic ofereix cuina tradicional mallorquina amb caragols, porcella i sopes mallorquines.",
      de: "Im Dorf Muro bietet dieses gemütliche Traditionslokal authentische Inselküche mit Kräuterschnecken, knusprigem Spanferkel und Hausweinen.",
    },
    highlights: {
      es: [
        "Casa señorial de piedra con bóvedas de marés y tinajas históricas",
        "Famosos caracoles mallorquines cocinados con hierbabuena e hinojo",
        "Arròs brut con pichón, conejo y níscalos de la comarca",
        "Menú del día tradicional y carta de temporada",
      ],
      en: [
        "Historic stone manor with sandstone vaults and antique wine casks",
        "Famous Mallorcan snails slow-simmered with mint and wild fennel",
        "Rich Arròs Brut broth rice with rabbit and seasonal wild mushrooms",
        "Traditional weekday lunch menu and seasonal specialties",
      ],
      ca: [
        "Casal de pedra amb voltes de marès",
        "Caragols amb herba-sana i fonoll",
        "Arròs brut de temporada",
        "Menú del dia tradicional",
      ],
      de: [
        "Historisches Natursteinhaus mit Sandsteingewölben",
        "Berühmte Landschnecken mit Minze und wildem Fenchel",
        "Würziger Arròs Brut mit Kaninchen und Waldpilzen",
        "Traditionelles Tagesmenü und saisonale Empfehlungen",
      ],
    },
    servicesProvided: {
      es: [
        "Almuerzos y cenas de cocina tradicional mallorquina",
        "Comedores privados para reuniones familiares y celebraciones",
        "Raciones y frito mallorquín para llevar (Take Away)",
        "Postres tradicionales caseros (tarta de requesón, gató)",
      ],
      en: [
        "Traditional Mallorcan lunch and dinner service",
        "Private dining rooms for family gatherings and celebrations",
        "Takeaway portions of signature frito and snails",
        "Homemade traditional desserts (almond gató, cottage cheesecake)",
      ],
      ca: [
        "Dinars i sopars de cuina tradicional",
        "Menjadors privats per a grups",
        "Menjar per emportar",
        "Postres casolanes",
      ],
      de: [
        "Mittag- und Abendessen mit traditioneller Küche",
        "Private Gasträume für Familienfeiern und Vereine",
        "Traditionelle Gerichte zum Mitnehmen",
        "Hausgemachte Desserts (Mandelkuchen, Quarkkuchen)",
      ],
    },
  },

  // ── 3. MOTOR, SCOOTERS & MOVILIDAD ──
  {
    slug: "vintage-motors-mallorca-scooter-vespa-palma",
    name: "Vintage Motors Scooter & Vespa Rental Palma (2012)",
    category: "motor-transporte",
    sectorFolder: "motor-transporte",
    sectorArrayName: "TRANSPORTE_SERVICES",
    subcategories: ["alquiler-vespa-palma", "scooters-125cc", "motos-trail-bmw"],
    zone: "palma",
    address: "Carrer de Camilo José Cela, 3, 07014 Palma",
    coordinates: { lat: 39.5668, lng: 2.6295 },
    rating: 4.9,
    reviewCount: 950,
    priceRange: "€€",
    phone: "+34 971 736 845",
    website: "https://vintagemotorsmallorca.com",
    schedule: "Lunes a Domingo: 09:00 - 20:00",
    tags: ["zona:palma-centro", "product:accesible", "mod:walk-in"],
    shortDescription: {
      es: "Alquiler de Vespas italianas icónicas y scooters de 125cc a 750cc en Palma para recorrer playas y carreteras panorámicas sin atascos ni problemas de aparcamiento.",
      en: "Iconic Italian Vespa and 125cc-750cc scooter hire in Palma for effortless coastal cruising and easy city parking.",
      ca: "Lloguer de Vespes italianes i scooters de 125cc a Palma per moure's per l'illa sense embossos.",
      de: "Verleih kultiger italienischer Vespa-Roller und 125cc-750cc Motorräder in Palma für entspannte Inseltouren.",
    },
    fullDescription: {
      es: "Vintage Motors ofrece la flota más estilosa y moderna de Vespas Primavera y GTS, scooters urbanos de 125cc (convalidables con carnet de coche B) y motos trail para explorar calas recónditas y pueblos de la Tramuntana con total libertad.",
      en: "Vintage Motors operates a premium fleet of Vespa Primavera & GTS scooters (drivable with standard car driving licenses) and touring bikes in Palma.",
      ca: "Disposa d'una flota de Vespes Primavera i scooters de 125cc amb cascos, assegurança i suport en carretera inclòs.",
      de: "Große Auswahl an Vespa Primavera & GTS (fahrbar mit Pkw-Führerschein B) sowie Reise-Enduros inklusive Helmen und Versicherung.",
    },
    highlights: {
      es: [
        "Flota moderna de Vespa Primavera y Vespa GTS 125cc y 300cc",
        "Aptas para conducir con carnet de coche B (mínimo 3 años)",
        "Incluye 2 cascos homologados, baúl portaequipajes y candado",
        "Asistencia en carretera 24 horas y kilometraje ilimitado",
      ],
      en: [
        "Modern fleet of iconic Vespa Primavera and GTS 125/300cc",
        "Driveable with standard B car driver's license (3+ years held)",
        "Includes 2 certified helmets, top box, and heavy-duty lock",
        "24/7 roadside assistance and unlimited mileage",
      ],
      ca: [
        "Flota de Vespa Primavera i GTS",
        "Condueix amb carnet de cotxe B",
        "Inclou 2 cascos i bagul",
        "Assistència 24 hores i quilometratge il·limitat",
      ],
      de: [
        "Top-gepflegte Vespa Primavera & GTS 125/300cc Flotte",
        "Fahrbar mit normalem Pkw-Führerschein Klasse B (ab 3 Jahren Besitz)",
        "Inklusive 2 Helmen, Topcase und Schloss",
        "24h-Pannenhilfe und unbegrenzte Freikilometer",
      ],
    },
    servicesProvided: {
      es: [
        "Alquiler por días, fines de semana y larga duración",
        "Servicio de entrega y recogida en hoteles y aeropuerto de Palma",
        "Rutas recomendadas en mapas digitales para smartphone",
        "Alquiler de soportes de móvil con cargador USB integrado",
      ],
      en: [
        "Daily, weekend, and weekly scooter hire",
        "Delivery and collection at hotels and Palma airport",
        "Curated digital smartphone route guides",
        "Phone holder with integrated fast USB charging",
      ],
      ca: [
        "Lloguer diari i setmanal",
        "Entrega a hotels i aeroport",
        "Rutes digitals per a mòbil",
        "Accessoris i suport GPS",
      ],
      de: [
        "Tages-, Wochenend- und Langzeitmiete",
        "Lieferung und Abholung am Hotel oder Flughafen Palma",
        "Digitale Routenempfehlungen für Smartphone",
        "Handyhalterung mit USB-Ladeanschluss",
      ],
    },
  },

  // ── 4. RETAIL & CALZADO ARTESANAL DE INCA ──
  {
    slug: "calzados-bestard-mountain-boots-lloseta-inca",
    name: "Bestard Mountain Boots Calçat de Muntanya Lloseta (1940)",
    category: "calzado-piel-inca-artesania",
    sectorFolder: "retail-comercio",
    sectorArrayName: "RETAIL_SERVICES",
    subcategories: ["botas-montana-goretex", "calzado-artesanal-piel", "botas-senderismo-tramuntana"],
    zone: "raiguer-pla",
    address: "Carrer d'Estellencs, s/n, 07360 Lloseta (Inca)",
    coordinates: { lat: 39.7168, lng: 2.8712 },
    rating: 4.9,
    reviewCount: 1420,
    priceRange: "€€€",
    phone: "+34 971 514 044",
    website: "https://bestardbootsmallorca.com",
    schedule: "Lunes a Viernes: 09:30 - 13:30 y 16:00 - 20:00, Sábados: 09:30 - 13:30",
    tags: ["zona:lloseta", "product:calzado-artesanal", "mod:en-local"],
    shortDescription: {
      es: "Fábrica y tienda emblemática de calzado de montaña fundada en 1940 en Lloseta: botas de senderismo y alpinismo con Gore-Tex y suelas Vibram.",
      en: "Legendary handcrafted mountain bootmaker established in 1940 in Lloseta: technical hiking boots with Gore-Tex and Vibram soles.",
      ca: "Fàbrica històrica de calçat de muntanya fundada el 1940 a Lloseta: botes de senderisme amb Gore-Tex i sola Vibram.",
      de: "Traditionsreiche Bergschuh-Manufaktur seit 1940 in Lloseta: technische Wanderschuhe mit Gore-Tex und Vibram-Sohlen.",
    },
    fullDescription: {
      es: "Bestard es un referente internacional en la fabricación artesanal de botas técnicas para trekking, alpinismo, barranquismo y caza. Pieles nobles hidrofugadas de máxima calidad cosidas a mano por zapateros de la comarca del Raiguer, combinadas con membranas impermeables Gore-Tex.",
      en: "Bestard is a world-renowned handcrafted boot manufacturer from Mallorca, crafting premium mountaineering, trekking, and outdoor footwear.",
      ca: "Bestard és una marca de prestigi mundial en calçat tècnic de muntanya fabricat amb pells nobles a Mallorca.",
      de: "Bestard steht weltweit für erstklassige, handwerklich gefertigte Wanderschuhe aus bestem Leder mit Gore-Tex-Membran und Vibram-Profil.",
    },
    highlights: {
      es: [
        "Empresa familiar fundada en 1940 con fábrica propia en Mallorca",
        "Calzado técnico con membrana impermeable y transpirable Gore-Tex",
        "Suelas de alta adherencia Vibram para senderos de piedra de la Tramuntana",
        "Servicio oficial de resolado y reparación artesanal de botas",
      ],
      en: [
        "Family-owned shoemaker founded in 1940 with in-house Balearic factory",
        "Official Gore-Tex breathable waterproof membrane technology",
        "High-traction Vibram outsoles designed for rocky limestone trails",
        "Official boot resoling and restoration repair service",
      ],
      ca: [
        "Empresa familiar fundada el 1940 a Lloseta",
        "Membrana Gore-Tex impermeable",
        "Soles Vibram d'alta adherència",
        "Servei de resolat de botes",
      ],
      de: [
        "Gegründet 1940 mit eigener Fertigung auf Mallorca",
        "Wasserdichte & atmungsaktive Gore-Tex-Technologie",
        "Griffige Vibram-Sohlen für kalkige Gebirgspfade",
        "Offizieller Neubesohlungs- und Reparaturservice",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de botas de trekking, senderismo, aproximación y calzado urbano outdoor",
        "Asesoramiento biométrico de horma y ajuste del pie por zapateros expertos",
        "Servicio de resolado con suelas Vibram originales y sustitución de ganchos",
        "Línea de calcetines técnicos y productos hidrófugos de cuidado de la piel",
      ],
      en: [
        "Technical hiking, trekking, canyoning, and casual outdoor shoes",
        "Biometric boot fitting and custom width advice by master shoemakers",
        "Official resoling with original Vibram outsoles and hardware replacement",
        "Technical moisture-wicking socks and waterproofing leather balms",
      ],
      ca: [
        "Venda de botes de senderisme i muntanya",
        "Assessorament de talla i forma del peu",
        "Servei oficial de resolat Vibram",
        "Cures de la pell",
      ],
      de: [
        "Verkauf von Wander-, Trekking- und Alpinschuhen",
        "Fachberatung zu Passform und Fußanatomie",
        "Neubesohlung mit Original-Vibram-Sohlen",
        "Pflegemittel und Imprägniersprays",
      ],
    },
  },

  // ── 5. TECNOLOGÍA & SEGURIDAD INTEGRAL ──
  {
    slug: "seguridad-alarmas-baleares-mallorca-secure",
    name: "Mallorca Secure Alarmas & CCTV Fincas Palma",
    category: "tecnologia-seguridad",
    sectorFolder: "tecnologia-seguridad",
    sectorArrayName: "SEGURIDAD_SERVICES",
    subcategories: ["alarmas-chalets-villas", "videovigilancia-cctv-ia", "central-receptora-24h"],
    zone: "palma",
    address: "Carrer del Gremi d'Hortelans, 11, Son Malferit, 07007 Palma",
    coordinates: { lat: 39.5812, lng: 2.6845 },
    rating: 4.8,
    reviewCount: 220,
    priceRange: "€€€",
    phone: "+34 971 773 450",
    website: "https://mallorcasecurealarmas.es",
    schedule: "Lunes a Viernes: 08:30 - 19:00 (CRA y Asistencia Técnica 24/365)",
    tags: ["zona:palma-centro", "product:domotica-smart-home", "mod:cita-previa"],
    shortDescription: {
      es: "Sistemas de seguridad de alta tecnología para villas y fincas en Mallorca: detección perimetral anticipada por radar, CCTV con IA y conexión a CRA.",
      en: "High-tech security systems for luxury villas and country estates in Mallorca: perimeter radar, AI CCTV, and 24/7 alarm monitoring.",
      ca: "Sistemes de seguretat per a vil·les i finques a Mallorca amb detecció perimetral per radar, càmeres d'IA i CRA 24h.",
      de: "High-Tech-Sicherheitssysteme für Villen und Fincas auf Mallorca: Radar-Perimeterüberwachung, KI-Kameras und 24h-Leitstelle.",
    },
    fullDescription: {
      es: "Empresa de seguridad privada autorizada por la Dirección General de la Policía (DGP). Especializada en la protección perimetral exterior de grandes fincas rústicas y villas unifamiliares, impidiendo intrusiones antes de que se acceda a la vivienda.",
      en: "Licensed private security provider (DGP) specializing in exterior perimeter protection for expansive rural fincas and luxury villas.",
      ca: "Empresa de seguretat homologada per la Policia especialitzada en protecció perimetral de parcel·les i vil·les.",
      de: "Staatlich zugelassener Sicherheitsfachbetrieb (DGP) für Perimeterschutz, Videoanalytik und Aufschaltung auf 24h-Alarmzentrale.",
    },
    highlights: {
      es: [
        "Homologación oficial DGP para instalación y conexión de alarmas de Grado 2 y 3",
        "Barreras perimetrales por microondas y cámaras térmicas anti-falsas alarmas",
        "Control total desde smartphone con visualización de vídeo en directo",
        "Respuesta inmediata con aviso a Policía y servicio de acudida y custodia de llaves",
      ],
      en: [
        "Official DGP police certification for Grade 2 and Grade 3 alarm installations",
        "Microwave perimeter barriers and thermal cameras eliminating false alarms",
        "Smartphone app with live high-definition video streaming",
        "Immediate response with police dispatch and keyholding patrols",
      ],
      ca: [
        "Homologació oficial de seguretat de Grau 2 i 3",
        "Càmeres tèrmiques perimetrals d'IA",
        "App mòbil de control remot",
        "Servei de custòdia de claus",
      ],
      de: [
        "Offizielle Zulassung für Alarmanlagen Grad 2 und Grad 3",
        "Mikrowellen-Lichtschranken & Wärmebildkameras ohne Fehlalarme",
        "Smartphone-App für Live-Video und Scharfschaltung",
        "Sofortige Interventions- und Schlüsseldienste",
      ],
    },
    servicesProvided: {
      es: [
        "Instalación de alarmas cableadas e inalámbricas con doble vía de comunicación 4G/IP",
        "Circuito cerrado de televisión (CCTV) con reconocimiento inteligente de personas y vehículos",
        "Control de accesos por biometría, teclado y apertura remota de verjas",
        "Mantenimiento preventivo anual y soporte técnico de guardia 24h",
      ],
      en: [
        "Wired and wireless alarm installs with dual 4G/IP communication paths",
        "CCTV video surveillance with smart human and vehicle recognition",
        "Biometric access control and remote gate automation integration",
        "Annual preventative maintenance and 24/7 on-call technical support",
      ],
      ca: [
        "Instal·lació d'alarmes amb doble via 4G/IP",
        "Càmeres CCTV amb reconeixement d'IA",
        "Control d'accessos i obertura de barreres",
        "Manteniment 24h",
      ],
      de: [
        "Kabel- und Funkalarmanlagen mit dualer 4G/IP-Übertragung",
        "Videoüberwachung mit KI-Erkennung für Personen & Kfz",
        "Biometrische Zutrittskontrolle & Torfernsteuerung",
        "Regelmäßige Wartung und 24/7 technischer Bereitschaftsdienst",
      ],
    },
  },
];

console.log("Ingesting Batch 6 of 5 verified businesses...");
ingestBatch(BATCH_6);
