import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_13: BusinessDataInput[] = [
  // ── 1. ALOJAMIENTO & AGROTURISMO ──
  {
    slug: "agroturismo-sa-talaia-blanca-muro-playa",
    name: "Agroturismo Sa Talaia Blanca Muro & Playa de Muro",
    category: "hoteles-boutique-agroturismo",
    sectorFolder: "alojamiento-turismo",
    sectorArrayName: "ALOJAMIENTO_SERVICES",
    subcategories: ["agroturismo-ecologico-mallorca", "hotel-rural-vistas-mar", "finca-agroturistica-muro"],
    zone: "alcudia-pollensa",
    address: "Camí de sa Talaia, s/n, 07440 Muro",
    coordinates: { lat: 39.7512, lng: 3.1098 },
    rating: 4.9,
    reviewCount: 340,
    priceRange: "€€€",
    phone: "+34 971 537 012",
    website: "https://satalaiablanca.com",
    schedule: "Recepción: 08:30 - 21:30 (Abierto todo el año)",
    tags: ["zona:muro", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Agroturismo ecológico con vistas al mar entre los naranjos de Muro y la bahía de Alcúdia: piscina de agua salada, desayunos KM0 con productos de la finca y alquiler de bicicletas.",
      en: "Eco-agrotourism estate between Muro orange groves and Alcúdia Bay: saltwater pool, farm-to-table KM0 breakfasts, and bicycle hire.",
      ca: "Agroturisme ecològic entre els tarongers de Muro i la badia d'Alcúdia amb piscina d'aigua salada i esmorzars KM0 de la finca.",
      de: "Öko-Agritourismus inmitten der Orangenhaine von Muro nahe der Bucht von Alcúdia: Salzwasserpool, KM0-Frühstück aus eigener Landwirtschaft und Fahrradverleih.",
    },
    fullDescription: {
      es: "Sa Talaia Blanca es una finca agrícola de 15 hectáreas dedicada al cultivo ecológico de naranjos, limones y hortalizas de temporada en Muro. Ofrece 12 suites independientes diseñadas con materiales naturales (piedra de marés, madera de pino mallorquín y barro cocido) a solo 5 minutos de la Playa de Muro.",
      en: "A 15-hectare organic citrus estate in Muro offering 12 independent suites built with natural local materials (marés stone, Mallorcan pine, terracotta) just 5 minutes from Playa de Muro.",
      ca: "Finca agrícola de 15 hectàrees dedicada al cultiu de tarongers i hortalisses a Muro amb 12 suites independents a 5 minuts de la Platja de Muro.",
      de: "15 Hektar großes Bio-Zitrusgut in Muro mit 12 unabhängigen Suiten aus Naturstein (Marés), Kiefernholz und Terrakotta, nur 5 Minuten vom Strand Muro entfernt.",
    },
    highlights: {
      es: [
        "Finca agrícola ecológica de 15 hectáreas con producción propia de cítricos",
        "Piscina de cloración salina rodeada de jardines de lavanda y hamacas",
        "Desayuno gourmet KM0 con huevos de gallinas criadas en libertad y zumo de naranja recién exprimido",
        "Ubicación estratégica a 3 km de la Playa de Muro y Parque Natural de s'Albufera",
      ],
      en: [
        "15-hectare organic farm with proprietary citrus fruit production",
        "Saline swimming pool surrounded by lavender gardens and sun loungers",
        "Gourmet KM0 breakfast featuring free-range eggs and freshly squeezed orange juice",
        "Prime location 3 km from Playa de Muro and s'Albufera Nature Reserve",
      ],
      ca: [
        "Finca de 15 hectàrees amb producció pròpia de cítrics",
        "Piscina salina envoltada de jardins de lavanda",
        "Esmorzar gourmet KM0 amb ous de gallines en llibertat i suc natural",
        "A 3 km de la Platja de Muro i s'Albufera",
      ],
      de: [
        "15-Hektar-Biofarm mit eigener Zitrusfrüchte-Produktion",
        "Salzwasserpool umgeben von Lavendelgärten und Sonnenliegen",
        "Gourmet-KM0-Frühstück mit Eiern freilaufender Hühner und frisch gepresstem Orangen-Saft",
        "Top-Lage: 3 km zum Strand Muro und Naturpark s'Albufera",
      ],
    },
    servicesProvided: {
      es: [
        "Alojamiento en suites rústicas con terraza privada y cocina equipada",
        "Desayuno buffet frío y caliente elaborado al momento con ingredientes de la finca",
        "Alquiler de bicicletas de carretera y eléctricas para rutas por el Pla de Mallorca",
        "Masajes relajantes al aire libre en la glorieta del jardín bajo reserva",
      ],
      en: [
        "Rustic suite accommodation with private terrace and kitchenette",
        "Hot and cold freshly made buffet breakfast featuring farm ingredients",
        "Road and e-bike rental for cycling routes across Pla de Mallorca",
        "Outdoor relaxation massages in the garden gazebo upon reservation",
      ],
      ca: [
        "Allotjament en suites rústiques amb terrassa privada",
        "Esmorzar bufet elaborat al moment amb productes de la finca",
        "Lloguer de bicicletes de carretera i elèctriques",
        "Massatges a l'aire lliure al jardí",
      ],
      de: [
        "Übernachtung in rustikalen Suiten mit privater Terrasse und Küchenzeile",
        "Frisch zubereitetes Frühstücksbuffet mit Hofprodukten",
        "Verleih von Rennrädern und E-Bikes für Touren durch die Ebene von Mallorca",
        "Freiluft-Massagen im Gartenpavillon nach Voranmeldung",
      ],
    },
  },

  // ── 2. FINANZAS & SEGUROS ──
  {
    slug: "banca-march-sede-central-palma-banca-privada",
    name: "Banca March S.A. Sede Central & Banca Privada Palma (1926)",
    category: "asesoria-financiera-hipotecas",
    sectorFolder: "finanzas-seguros",
    sectorArrayName: "FINANZAS_SERVICES",
    subcategories: [
      "banca-privada-mallorca",
      "gestion-patrimonial-family-office",
      "hipotecas-residentes-no-residentes",
    ],
    zone: "palma",
    address: "Carrer de Sant Miquel, 17, 07002 Palma",
    coordinates: { lat: 39.5732, lng: 2.6512 },
    rating: 4.9,
    reviewCount: 420,
    priceRange: "€€€€",
    phone: "+34 971 779 100",
    website: "https://bancamarch.es",
    schedule: "Lunes a Viernes: 08:30 - 14:00 (Gestión de Banca Privada con cita previa hasta 18:00)",
    tags: ["zona:palma-centro", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Banco familiar balear fundado en Palma en 1926: especialista en banca privada, gestión de grandes patrimonios, asesoramiento a empresas e hipotecas para no residentes.",
      en: "Family-owned Balearic private bank founded in Palma in 1926: private banking, wealth management, corporate advisory, and non-resident mortgages.",
      ca: "Banc familiar balear fundat a Palma el 1926: especialista en banca privada, gestió de patrimonis i hipoteques per a no residents.",
      de: "Balearische Familien-Privatbank seit 1926 in Palma: Vermögensverwaltung, Family-Office-Beratung, Firmenkunden und Hypotheken für Nicht-Residenten.",
    },
    fullDescription: {
      es: "Banca March es el único banco de propiedad 100% familiar de España. Con ratios de solvencia líderes en Europa (CET1 superior al 18%), su sede histórica en Palma ofrece servicios de banca privada, family office y banca corporativa con gestores personales dedicados.",
      en: "Spain's only 100% family-owned bank with Europe-leading solvency ratios (CET1 >18%). Its historic Palma headquarters provides private banking, family office, and corporate services.",
      ca: "L'únic banc de propietat 100% familiar d'Espanya amb el millor ràtio de solvència d'Europa (CET1 >18%). La seva seu històrica a Palma ofereix gestors personals dedicats.",
      de: "Spaniens einzige Bank in 100% Familienbesitz mit europäischer Spitzen-Solvenzquote (CET1 >18%). Der Hauptsitz in Palma bietet dedizierte Private-Banking-Betreuung.",
    },
    highlights: {
      es: [
        "Única entidad bancaria de propiedad 100% familiar de España",
        "Mayor ratio de solvencia CET1 del sistema financiero español (>18%)",
        "Premio Best Private Bank in Spain por la revista World Finance",
        "Gestores personales multilingües dedicados para clientes de Banca Privada",
      ],
      en: [
        "Spain's only 100% family-owned banking institution",
        "Highest CET1 solvency ratio in the Spanish banking sector (>18%)",
        "Best Private Bank in Spain award by World Finance Magazine",
        "Dedicated multilingual personal relationship managers for Private Banking clients",
      ],
      ca: [
        "Única entitat bancària de propietat 100% familiar d'Espanya",
        "Màxim ràtio de solvència CET1 a Espanya (>18%)",
        "Premi Best Private Bank in Spain per World Finance",
        "Gestors personals multilingües dedicats",
      ],
      de: [
        "Spaniens einzige 100%-ige Familienbank",
        "Höchste Solvenzquote CET1 im spanischen Bankensektor (>18%)",
        "Auszeichnung als Best Private Bank in Spain durch World Finance",
        "Dedizierte zweisprachige Kundenbetreuer für Private-Banking-Kunden",
      ],
    },
    servicesProvided: {
      es: [
        "Banca Privada y gestión de patrimonios familiares (Family Office)",
        "Hipotecas a medida para la compra de viviendas y villas por no residentes",
        "Asesoramiento en inversiones, fondos de renta fija y cotizados (ETFs)",
        "Financiación corporativa y comercio internacional para empresas balears",
      ],
      en: [
        "Private Banking and family office wealth management services",
        "Tailored mortgage structures for non-resident property purchases",
        "Investment advisory, fixed income funds, and ETF portfolios",
        "Corporate financing and international trade services for Balearic businesses",
      ],
      ca: [
        "Banca Privada i gestió de patrimonis familiars (Family Office)",
        "Hipoteques a mida per a compradors no residents",
        "Assessorament en inversions, fons i ETFs",
        "Finançament corporatiu per a empreses de les illes",
      ],
      de: [
        "Private Banking und Family-Office-Vermögensverwaltung",
        "Maßgeschneiderte Hypothekenfinanzierung für Immobilienkäufer ohne Wohnsitz",
        "Anlageberatung, Anleihefonds und ETF-Portfolio-Management",
        "Firmenkundenfinanzierung und Auslandsgeschäft für Inselunternehmen",
      ],
    },
  },

  // ── 3. GASTRONOMÍA & TRADICIÓN ──
  {
    slug: "restaurante-sa-llobatera-sineu-celler",
    name: "Celler Sa Llobatera Restaurante Tradicional Sineu",
    category: "gastronomia-catering",
    sectorFolder: "gastronomia-restaurantes",
    sectorArrayName: "GASTRONOMIA_SERVICES",
    subcategories: ["cocina-mallorquina-tradicional", "celler-historico-sineu", "frito-mallorquin-cochinillo"],
    zone: "raiguer-pla",
    address: "Carrer de les Parres, 12, 07300 Sineu",
    coordinates: { lat: 39.6432, lng: 2.9512 },
    rating: 4.8,
    reviewCount: 654,
    priceRange: "€€",
    phone: "+34 971 520 114",
    website: "https://salllobaterasineu.es",
    schedule: "Miércoles a Domingo: 12:30 - 16:00 y 19:30 - 23:00; Lunes y Martes: Cerrado",
    tags: ["zona:raiguer-pla", "product:cocina-mallorquina", "mod:walk-in"],
    shortDescription: {
      es: "Celler tradicional en el centro histórico de Sineu: cocina mallorquina auténtica elaborada en horno de leña, lechona asada, frito mallorquín y sopas secas en una antigua bodega del siglo XVI.",
      en: "Traditional celler in Sineu's historic centre: authentic Mallorcan wood-fired cuisine, roast suckling pig, frito mallorquín, and dry vegetable soups in a 16th-century wine cellar.",
      ca: "Celler tradicional al centre històric de Sineu: cuina mallorquina autèntica en forn de llenya, porcella rostida, frit mallorquí i sopes seques.",
      de: "Traditioneller Celler im historischen Zentrum von Sineu: Authentische holzofengebackene mallorquinische Küche, Spanferkel und Frito Mallorquín im Keller aus dem 16. Jahrhundert.",
    },
    fullDescription: {
      es: "Sa Llobatera ocupa una antigua bodega de vino del siglo XVI restaurada preservando las bóvedas de marés y las tinajas de fermentación de barro originales. Es célebre en Sineu por su lechona de cerdo negro mallorquín asada lentamente en horno de leña de olivo.",
      en: "Occupying a restored 16th-century wine cellar with original marés vaults and clay fermentation vats. Famous in Sineu for slow-roasted black pig suckling pig in olive wood furnaces.",
      ca: "Ocupa un antic celler de vi del segle XVI restaurat amb volta de marès i tines originals. Famosa per la porcella de porc negre rostida a la llenya d'olivera.",
      de: "Eingebettet in einen restaurierten Weinkeller aus dem 16. Jahrhundert mit Gewölben und Tonkrügen. Berühmt für langsam im Olivenholzofen gebratenes Spanferkel vom schwarzen Insel-Schwein.",
    },
    highlights: {
      es: [
        "Bodega histórica del siglo XVI con bóvedas de marés originales",
        "Especialidad en lechona de cerdo negro mallorquín al horno de leña",
        "Frito mallorquín tradicional con asaduras de cordero de Sineu",
        "Vinos locales de Binissalem y Pla i Llevant servidos en jarra de barro tradicional",
      ],
      en: [
        "Historic 16th-century wine cellar with original sandstone vaults",
        "Specialist in slow-roasted native black pig suckling pig in timber oven",
        "Traditional Sineu lamb offal 'frito mallorquín' recipe",
        "Local Binissalem and Pla i Llevant wines served in traditional clay pitchers",
      ],
      ca: [
        "Celler històric del segle XVI amb voltes de marès originals",
        "Especialitat en porcella de porc negre al forn de llenya",
        "Frit mallorquí tradicional amb me de Sineu",
        "Vins locals servits en gerra de terra cuita",
      ],
      de: [
        "Historischer Weinkeller aus dem 16. Jh. mit originalen Marés-Gewölben",
        "Spezialität: Holzofengebratenes Spanferkel vom Roten/Schwarzen Mallorquiner Schwein",
        "Traditionelles Frito Mallorquín nach Sineu-Art",
        "Lokale Weine aus Binissalem in Tonkrügen serviert",
      ],
    },
    servicesProvided: {
      es: [
        "Almuerzos y cenas a la carta con especialidades de la cocina de interior de Mallorca",
        "Menú especial del día del mercado de los miércoles en Sineu",
        "Comedores privados en antiguas cubas de vino para grupos de hasta 25 personas",
        "Reservas para eventos familiares, comuniones y comidas de empresa",
      ],
      en: [
        "À la carte lunches and dinners featuring inland Mallorcan regional dishes",
        "Special Wednesday Sineu Market-day lunch menu",
        "Private dining inside restored giant wine vats for groups up to 25",
        "Family gatherings, communion, and corporate celebration bookings",
      ],
      ca: [
        "Dinars i sopars a la carta amb especialitats de l'interior de Mallorca",
        "Menú especial del dia del mercat dels dimecres a Sineu",
        "Menjadors privats en antigues tines de vi per a grups de fins a 25 persones",
        "Reserves per a celebracions familiars i dinars d'empresa",
      ],
      de: [
        "À-la-carte-Mittags- und Abendessen mit Binnenland-Spezialitäten",
        "Spezial-Menü am traditionellen Mittwochs-Markttag in Sineu",
        "Private Speiseräume in umgebauten Riesengärfässern für bis zu 25 Personen",
        "Feiern für Familienfeste, Kommunionen und Firmenessen",
      ],
    },
  },

  // ── 4. MOTOR & TRASLADOS AEROPUERTO ──
  {
    slug: "mallorca-taxi-transfer-aeropuerto-palma-service",
    name: "Mallorca Taxi Transfer Aeropuerto Palma & VIP Private Shuttle",
    category: "motor-transporte",
    sectorFolder: "motor-transporte",
    sectorArrayName: "TRANSPORTE_SERVICES",
    subcategories: ["transfer-aeropuerto-palma", "taxi-privado-villas-mallorca", "minivan-grupos-transfer"],
    zone: "palma",
    address: "Aeropuerto de Palma de Mallorca (PMI), Salidas/Llegadas, 07071 Palma",
    coordinates: { lat: 39.5512, lng: 2.7389 },
    rating: 4.9,
    reviewCount: 1450,
    priceRange: "€€",
    phone: "+34 971 880 220",
    website: "https://mallorcataxitransfer.es",
    schedule: "Servicio 24 horas / 365 días (Reserva previa online o telefónica)",
    tags: ["zona:palma-centro", "product:accesible", "mod:online"],
    shortDescription: {
      es: "Servicio oficial de traslados privados en taxi, minivans y vehículos ejecutivos desde el Aeropuerto de Palma (PMI) a cualquier villa, hotel o puerto de Mallorca.",
      en: "Official private taxi, minivan, and executive vehicle transfer service from Palma Airport (PMI) to any villa, hotel, or port in Mallorca.",
      ca: "Servei oficial de trasllats privats en taxi, minivans i vehicles executius des de l'Aeroport de Palma (PMI) a qualsevol punt de l'illa.",
      de: "Offizieller Privat-Taxi-, Minivan- und Executive-Transfer-Service vom Flughafen Palma (PMI) zu jeder Villa, jedem Hotel oder Hafen auf Mallorca.",
    },
    fullDescription: {
      es: "Mallorca Taxi Transfer ofrece traslados directos sin esperas desde la terminal de llegadas del Aeropuerto Son Sant Joan (PMI). Flota de más de 80 vehículos privados (Mercedes Clase E, Clase V de 7 plazas y minibuses). Seguimiento de vuelos en tiempo real para ajustar recogidas por retrasos sin cargos extra.",
      en: "Direct non-stop private transfers from Son Sant Joan Airport (PMI) arrivals terminal. Fleet of 80+ vehicles including Mercedes E-Class, 7-seater V-Class, and minibuses. Real-time flight tracking.",
      ca: "Trasllats directes sense esperes des de l'arribada de l'Aeroport de Palma (PMI). Flota de més de 80 vehicles privats amb seguiment de vols en temps real.",
      de: "Direkte Privat-Transfers ohne Wartezeit ab Ankunftsterminal Son Sant Joan (PMI). Flotte aus 80+ Fahrzeugen mit Echtzeit-Flugverfolgung ohne Verspätungsaufschlag.",
    },
    highlights: {
      es: [
        "Monitorización de vuelos en tiempo real: el chófer espera en llegadas aunque el vuelo se retrase",
        "Precios fijos cerrados sin sorpresas ni suplementos nocturnos o de equipaje",
        "Flota moderna con aire acondicionado: turismos Mercedes, minivans V-Class de 7-8 plazas",
        "Sillas de bebé e infantiles homologadas disponibles de forma gratuita bajo petición",
      ],
      en: [
        "Real-time flight monitoring: drivers wait in arrivals even if flights are delayed",
        "Fixed transparent pricing with zero luggage or night surcharges",
        "Modern air-conditioned Mercedes saloons, V-Class 7-8 seat minivans",
        "Free certified child and baby safety seats upon advance request",
      ],
      ca: [
        "Monitoratge de vols en temps real: el xofer s'espera si el vol es retarda",
        "Preus mefosos fijos sense suplements de nocturnitat o equipatge",
        "Flota moderna Mercedes i minivans de 7-8 places",
        "Cadiretes de bebè gratuïtes sota petició",
      ],
      de: [
        "Echtzeit-Flugüberwachung: Fahrer wartet in der Ankunftshalle auch bei Verspätung",
        "Festpreise ohne Nacht- oder Gepäckzuschläge",
        "Moderne Mercedes-Flotte und V-Klasse-Minivans (7-8 Sitze)",
        "Kostenlose zertifizierte Kinder- und Babysitze auf Anfrage",
      ],
    },
    servicesProvided: {
      es: [
        "Traslados privados aeropuerto-hotel o villa en cualquier punto de Mallorca",
        "Transfer para ciclistas con remolque homologado para bicicletas de carreras",
        "Traslados ejecutivos VIP para congresos y eventos en Palma de Mallorca",
        "Servicio de transporte nocturno para cenas y bodas en fincas rústicas",
      ],
      en: [
        "Private airport-to-hotel or villa transfers anywhere across Mallorca",
        "Cyclist transfer packages with dedicated enclosed bicycle trailers",
        "Executive VIP transportation for conferences and events in Palma",
        "Night transfer service for dinner outings and rustic finca wedding celebrations",
      ],
      ca: [
        "Trasllats privats aeroport-hotel o vil·la a qualsevol punt de Mallorca",
        "Transfer per a ciclistes amb remolc per a bicicletes",
        "Trasllats executius VIP per a congressos i esdeveniments",
        "Transport nocturn per a sopars i casaments a finques",
      ],
      de: [
        "Privattransfers Flughafen-Hotel/Villa auf ganz Mallorca",
        "Radtouristen-Transfers mit geschlossenem Fahrrad-Anhänger",
        "VIP-Executive-Fahrten für Kongresse und Events in Palma",
        "Nacht-Shuttleservice für Restaurantabende und Finca-Hochzeiten",
      ],
    },
  },

  // ── 5. REFORMAS & AEROTERMIA ──
  {
    slug: "climatizacion-aerotermia-balear-inca-calefaccion",
    name: "Climatización & Aerotermia Balear Inca (Daikin & Mitsubishi)",
    category: "reformas-hogar",
    sectorFolder: "reformas-construccion",
    sectorArrayName: "REFORMAS_SERVICES",
    subcategories: ["aerotermia-suelo-radiante", "aire-acondicionado-inverter", "bombas-calor-eficiencia"],
    zone: "raiguer-pla",
    address: "Gran Via de Colom, 142, 07300 Inca",
    coordinates: { lat: 39.7198, lng: 2.9124 },
    rating: 4.9,
    reviewCount: 312,
    priceRange: "€€€",
    phone: "+34 971 502 440",
    website: "https://climatizacionbalear.es",
    schedule: "Lunes a Viernes: 08:00 - 18:00",
    tags: ["zona:inca", "product:energia-solar-fotovoltaica", "mod:cita-previa"],
    shortDescription: {
      es: "Ingeniería e instalación de aerotermia, suelo radiante y aire acondicionado inverter en Mallorca: servicio técnico oficial Daikin, Mitsubishi Electric y Panasonic para villas y edificios.",
      en: "Air-source heat pump, underfloor heating, and inverter AC engineering in Mallorca: official Daikin, Mitsubishi Electric, and Panasonic installer for villas.",
      ca: "Enginyeria i instal·lació d'aerotèrmia, terra radiant i aire condicionat inverter a Mallorca: servei tècnic oficial Daikin i Mitsubishi.",
      de: "Wärmepumpen-, Fußbodenheizungs- und Inverter-Klimaanlagen-Fachbetrieb auf Mallorca: offizieller Partner von Daikin, Mitsubishi Electric und Panasonic.",
    },
    fullDescription: {
      es: "Empresa de climatización ecológica con más de 20 años de experiencia en Inca. Instaladores autorizados de sistemas de aerotermia para calefacción por suelo radiante, refrigeración fancoil y agua caliente sanitaria (ACS). Reducción de hasta un 70% en la factura eléctrica de las viviendas.",
      en: "Ecological climate control installer with 20+ years of experience in Inca. Licensed installers of air-to-water heat pumps for underfloor heating, fancoil cooling, and domestic hot water, achieving up to 70% energy bill savings.",
      ca: "Empresa de climatització ecològica amb més de 20 anys d'experiència a Inca. Instal·ladors autoritzats d'aerotèrmia per a terra radiant i aigua calenta.",
      de: "Klima-Fachbetrieb mit 20+ Jahren Erfahrung in Inca. Zertifizierter Partner für Wärmepumpen-Systeme, Fußbodenheizung, Fancoil-Kühlung und Warmwasser mit bis zu 70% Energieeinsparung.",
    },
    highlights: {
      es: [
        "Servicio técnico e instalador oficial Daikin Altherma y Mitsubishi Ecodan",
        "Especialistas en suelo radiante hidráulico para villas de nueva construcción y reformas",
        "Ahorro energético de hasta el 70% respecto a calderas tradicionales de gasoil",
        "Tramitación gratuita de ayudas públicas y subvenciones del Govern Balear",
      ],
      en: [
        "Official installer and technical service for Daikin Altherma and Mitsubishi Ecodan",
        "Specialists in hydraulic underfloor heating for new-build villas and major refits",
        "Up to 70% energy savings compared to conventional diesel heating oil boilers",
        "Free processing of Balearic Government green-energy subsidies",
      ],
      ca: [
        "Servei tècnic i instal·lador oficial Daikin i Mitsubishi Ecodan",
        "Especialistes en terra radiant hidràulic per a vil·les",
        "Estalvi energètic de fins al 70% respecte al gasoli",
        "Tramitació gratuïta de subvencions del Govern Balear",
      ],
      de: [
        "Offizieller Fachpartner für Daikin Altherma und Mitsubishi Ecodan",
        "Spezialisten für wasserführende Fußbodenheizungen in Villen und Fincas",
        "Bis zu 70% Energieeinsparung gegenüber alten Heizöl-Kesseln",
        "Kostenlose Beantragung balearischer Fördergelder für Wärmepumpen",
      ],
    },
    servicesProvided: {
      es: [
        "Estudio térmico y cálculo de cargas sin compromiso para viviendas en Mallorca",
        "Instalación de bombas de calor por aerotermia para suelo radiante y fancoils",
        "Sustitución de calderas antiguas de gasoil por aerotermia de alta eficiencia",
        "Mantenimiento preventivo anual y servicio técnico de urgencias 24h",
      ],
      en: [
        "Complimentary thermal load assessment and heat loss calculations",
        "Air-to-water heat pump installation for underfloor heating and fancoil units",
        "Replacement of outdated diesel boilers with high-efficiency heat pumps",
        "Annual preventive maintenance and 24h emergency technical service",
      ],
      ca: [
        "Estudi tèrmic i càlcul de càrregues sense compromís",
        "Instal·lació de bombes de calor d'aerotèrmia per a terra radiant",
        "Substitució de calderes antigues de gasoli per aerotèrmia",
        "Manteniment preventiu anual i servei tècnic 24h",
      ],
      de: [
        "Kostenlose Heizlastberechnung und Ertragsanalyse für Wohnhäuser",
        "Installation von Wärmepumpen für Fußbodenheizung und Gebläse-Konvektoren",
        "Umrüstung alter Ölheizungen auf hocheffiziente Luft-Wasser-Wärmepumpen",
        "Jährliche Wartung und 24h-Notdienst für Klimatechnik",
      ],
    },
  },
];

console.log("Ingesting Batch 13 of 5 verified businesses...");
ingestBatch(BATCH_13);
