import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_9: BusinessDataInput[] = [
  // ── 1. NÁUTICA & ESCUELAS DE VELA ──
  {
    slug: "escola-de-vela-balear-escola-nàutica-palma",
    name: "Escola de Vela Balear & Náutica Palma",
    category: "nautica-charter",
    sectorFolder: "nautica-charter",
    sectorArrayName: "NAUTICA_SERVICES",
    subcategories: ["cursos-patron-embarcacion", "escuela-vela-catamaran", "licencias-nauticas-palma"],
    zone: "palma",
    address: "Club de Mar Palma, Moll Pelaires s/n, 07015 Palma",
    coordinates: { lat: 39.5517, lng: 2.6215 },
    rating: 4.9,
    reviewCount: 398,
    priceRange: "€€€",
    phone: "+34 971 402 512",
    website: "https://escoladevelabalear.com",
    schedule: "Lunes a Domingo: 08:30 - 19:30 (Temporada Abril – Octubre)",
    tags: ["zona:palma-centro", "product:vela-ligera", "mod:cita-previa"],
    shortDescription: {
      es: "Escuela náutica oficial homologada en el Club de Mar Palma: titulaciones PER, PNB, Patrón de Yate, cursos de vela ligera en Optimist y Laser y navegación a vela oceánica.",
      en: "Official government-approved nautical school at Club de Mar Palma: PER, PNB, Yacht Skipper licensing, dinghy sailing classes (Optimist & Laser) and offshore ocean sailing.",
      ca: "Escola nàutica oficial al Club de Mar de Palma: titulacions PER, PNB, Patró de Iot i cursos de vela lleugera amb Optimist i Làser.",
      de: "Staatlich zugelassene Segelschule im Club de Mar Palma: Sportbootführerschein (PER/PNB), Yachtkapitän-Prüfung, Optimist- und Laser-Dinghysegeln.",
    },
    fullDescription: {
      es: "Centro de formación náutica integrado en el Club de Mar con una flota propia de más de 20 embarcaciones de vela y motor. Imparte los títulos oficiales de la DGMM: PER (Patrón de Embarcación de Recreo), PNB, Patrón de Yate y Capitán de Yate. Cursos en catalán, castellano, inglés y alemán.",
      en: "Fully integrated nautical training centre within Club de Mar with a fleet of 20+ sail and motor vessels. Official DGMM titles: PER, PNB, Yacht Skipper, Yacht Captain. Multilingual instruction available.",
      ca: "Centre de formació nàutica integrat al Club de Mar amb una flota de més de 20 embarcacions. Titulacions oficials DGMM en quatre idiomes.",
      de: "Vollständiges nautisches Trainingszentrum im Club de Mar mit einer Flotte von über 20 Segel- und Motorbooten. Offizielle DGMM-Führerscheine auf Spanisch, Katalanisch, Englisch und Deutsch.",
    },
    highlights: {
      es: [
        "Centro de examen oficial homologado por la DGMM para todos los títulos náuticos",
        "Flota propia de más de 20 embarcaciones (veleros, catamarán, zodiac)",
        "Cursos en castellano, catalán, inglés y alemán",
        "Convenio con el Real Club Náutico de Palma para prácticas avanzadas",
      ],
      en: [
        "Official DGMM-approved examination centre for all Spanish nautical licenses",
        "Fleet of 20+ training vessels including monohulls, catamaran, and RIBs",
        "Courses delivered in Spanish, Catalan, English, and German",
        "Partnership with Real Club Náutico de Palma for advanced bluewater practice",
      ],
      ca: [
        "Centre d'examen oficial DGMM per a tots els títols nàutics",
        "Flota pròpia de més de 20 embarcacions",
        "Cursos en quatre idiomes",
        "Conveni amb el Reial Club Nàutic de Palma",
      ],
      de: [
        "Staatlich zugelassenes DGMM-Prüfungszentrum für alle nautischen Führerscheine",
        "Eigene Flotte aus 20+ Segelbooten, Katamaran und Schlauchbooten",
        "Unterricht auf Spanisch, Katalanisch, Englisch und Deutsch",
        "Kooperation mit dem Real Club Náutico de Palma für Offshore-Übungen",
      ],
    },
    servicesProvided: {
      es: [
        "Preparación y examen para PER (Patrón de Embarcación de Recreo)",
        "Preparación y examen para PNB (Patrón de Navegación Básica)",
        "Preparación y examen para Patrón de Yate y Capitán de Yate",
        "Cursos de vela ligera para niños y adultos en Optimist, Laser y 420",
      ],
      en: [
        "PER (Inshore Recreational Skipper) licence preparation and official exam",
        "PNB (Basic Navigation Skipper) licence preparation and exam",
        "Yacht Skipper and Yacht Captain advanced qualification courses",
        "Youth and adult dinghy sailing courses in Optimist, Laser, and 420",
      ],
      ca: [
        "Preparació i examen per al PER",
        "Preparació i examen per al PNB",
        "Patró de Iot i Capità de Iot",
        "Cursos de vela lleugera per a infants i adults",
      ],
      de: [
        "Vorbereitung und Prüfung für den PER (Sportbootführerschein Binnen+Küste)",
        "Vorbereitung und Prüfung für den PNB (Grundnavigation)",
        "Yachtkapitän-Kurs (Patrón de Yate & Capitán de Yate)",
        "Kinder- und Erwachsenensegelkurse in Optimist, Laser und 420",
      ],
    },
  },

  // ── 2. AGRICULTURA & ALMAZARAS KM0 ──
  {
    slug: "almazara-ecologica-oli-de-santanyi",
    name: "Oli de Santanyí Almazara Ecológica & Olivar Santanyi",
    category: "aceite-oliva-almazaras",
    sectorFolder: "agricultura-productores",
    sectorArrayName: "AGRICULTURA_SERVICES",
    subcategories: ["aceite-oliva-virgen-extra-dop", "variedad-arbequina", "almazara-ecologica"],
    zone: "santanyi-migjorn",
    address: "Camí de sa Marina, s/n, 07650 Santanyí",
    coordinates: { lat: 39.3562, lng: 3.1312 },
    rating: 4.9,
    reviewCount: 215,
    priceRange: "€€€",
    phone: "+34 971 163 204",
    website: "https://olisantanyi.es",
    schedule: "Lunes a Sábado: 09:30 - 14:00 y 16:00 - 19:00",
    tags: ["zona:santanyi-migjorn", "product:enoturismo", "mod:cita-previa"],
    shortDescription: {
      es: "Almazara artesana y olivar ecológico en Santanyí: aceite de oliva virgen extra de extracción en frío con sello DOP Oli de Mallorca y catas en finca.",
      en: "Artisan olive oil mill and organic grove in Santanyí: cold-extracted extra virgin olive oil with DOP Oli de Mallorca seal and estate tastings.",
      ca: "Almazara artesana i olivar ecològic a Santanyí: oli d'oliva verge extra d'extracció en fred amb segell DOP Oli de Mallorca.",
      de: "Handwerkliche Ölmühle und Bio-Olivenhain in Santanyí: Kaltgepresstes natives Olivenöl extra mit DOP Oli de Mallorca-Siegel und Verkostungen.",
    },
    fullDescription: {
      es: "Oli de Santanyí es una almazara familiar dedicada al cultivo ecológico de las variedades Arbequina y Picual en el migjorn mallorquín. Producción artesanal embotellada en vidrio ultravioleta con notas a tomatera y almendra fresca.",
      en: "Family-run organic olive estate in southern Mallorca cultivating Arbequina and Picual varieties, bottled in UV-protected glass with notes of fresh tomato vine and almond.",
      ca: "Almazara familiar dedicada al cultiu ecològic d'Arbequina i Picual al migjorn mallorquí amb ampolla de vidre ultraviolat.",
      de: "Familien-Bio-Ölmühle im Süden Mallorcas für Arbequina und Picual, abgefüllt in UV-geschützten Flaschen mit Noten von Tomatenstrunk und frischer Mandel.",
    },
    highlights: {
      es: [
        "Certificación ecológica oficial de las Islas Baleares (CBPAE)",
        "Denominación de Origen Protegida DOP Oli de Mallorca",
        "Extracción en frío por debajo de 22°C en el mismo día de cosecha",
        "Catas maridadas con flor de sal de Es Trenc y pan artesano de xeixa",
      ],
      en: [
        "Official Balearic organic certification (CBPAE)",
        "DOP Oli de Mallorca protected designation of origin",
        "Cold extraction under 22°C within hours of harvesting",
        "Paired tastings with Es Trenc sea salt and artisan xeixa bread",
      ],
      ca: [
        "Certificació ecològica oficial de les Illes Balears (CBPAE)",
        "Denominació d'Origen Protegida DOP Oli de Mallorca",
        "Extracció en fred a menys de 22°C el mateix dia",
        "Tasts maridats amb flor de sal d'Es Trenc",
      ],
      de: [
        "Offizielle Bio-Zertifizierung der Balearen (CBPAE)",
        "g.U.-Siegel DOP Oli de Mallorca",
        "Kaltextraktion unter 22°C am Erntetag",
        "Verkostungen mit Es Trenc Meersalz und Xeixa-Brot",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de aceite virgen extra ecológico DOP Oli de Mallorca en varios formatos",
        "Visitas guiadas al olivar y almazara con degustación explicada",
        "Cestas de regalo gourmet con sal marina y productos locales de Santanyí",
        "Envíos asegurados a domicilio en España y resto de Europa",
      ],
      en: [
        "Organic DOP extra virgin olive oil sales in multiple sizes",
        "Guided grove and mill tours with sensory tasting session",
        "Gourmet gift baskets with sea salt and local Santanyí products",
        "Insured courier shipping across Spain and Europe",
      ],
      ca: [
        "Venda d'oli verge extra ecològic DOP Oli de Mallorca",
        "Visites guiades a l'olivar i molí amb degustació",
        "Cistells de regal gourmet amb sal marina i productes de Santanyí",
        "Enviaments assegurats a domicili a Europa",
      ],
      de: [
        "Verkauf von Bio-DOP-Olivenöl extra in verschiedenen Größen",
        "Geführte Führungen durch Hain und Mühle mit Verkostung",
        "Gourmet-Geschenkkörbe mit Meersalz und lokalen Santanyí-Produkten",
        "Gesicherter Versand nach Spanien und Europa",
      ],
    },
  },

  // ── 3. SALUD, FISIOTERAPIA & PILATES CLÍNICO ──
  {
    slug: "clinica-fisioterapia-pilates-clinico-palma-badia",
    name: "Clínica FisioMar Fisioterapia & Pilates Clínico Palma",
    category: "salud-bienestar",
    sectorFolder: "servicios-profesionales",
    sectorArrayName: "SERVICIOS_PROFESIONALES",
    subcategories: ["fisioterapia-deportiva", "pilates-terapeutico", "osteopatia-estructura"],
    zone: "palma",
    address: "Carrer de Blanquerna, 14, Baixos, 07003 Palma",
    coordinates: { lat: 39.5699, lng: 2.6516 },
    rating: 4.9,
    reviewCount: 520,
    priceRange: "€€€",
    phone: "+34 971 723 345",
    website: "https://fisiomarsalud.es",
    schedule: "Lunes a Viernes: 08:00 - 20:30; Sábado: 09:00 - 14:00",
    tags: ["zona:palma-centro", "product:fisioterapia", "mod:cita-previa"],
    shortDescription: {
      es: "Clínica de fisioterapia, osteopatía y pilates terapéutico en Palma con fisioterapeutas especializados en deporte, suelo pélvico, neurología y lesiones crónicas del aparato locomotor.",
      en: "Palma physiotherapy clinic specializing in sports rehab, pelvic floor, neurology, and chronic musculoskeletal conditions, with clinical Pilates studio.",
      ca: "Clínica de fisioteràpia, osteopatia i pilates clínic a Palma especialitzada en esport, terra pelvià i neurologia.",
      de: "Physiotherapie-Klinik in Palma für Sportrehabilitation, Beckenboden, Neurologie und chronische Bewegungsapparat-Beschwerden mit Klinischem Pilates-Studio.",
    },
    fullDescription: {
      es: "FisioMar cuenta con un equipo de 8 fisioterapeutas colegiados especializados en diferentes áreas: fisioterapia deportiva, osteopatía parietal y visceral, fisioterapia neurológica, rehabilitación vestibular, fisioterapia de suelo pélvico, terapia manual avanzada y pilates clínico con Reformer.",
      en: "FisioMar's team of 8 registered physiotherapists covers sports rehab, visceral osteopathy, neurological physiotherapy, vestibular rehab, pelvic floor therapy, advanced manual therapy, and clinical Reformer Pilates.",
      ca: "Equip de 8 fisioterapeutes col·legiats especialitzats en esport, osteopatia visceral, neurologia, rehabilitació vestibular, terra pelvià i pilates amb Reformer.",
      de: "8-köpfiges Team zugelassener Physiotherapeuten, spezialisiert auf Sportrehabilitation, Viszerale Osteopathie, Neurologie, Vestibulär-Rehabilitation, Beckenboden und Klinisches Reformer-Pilates.",
    },
    highlights: {
      es: [
        "8 fisioterapeutas colegiados con masters y postgrados especializados",
        "Unidad de suelo pélvico con fisioterapeuta exclusiva para mujer y hombre",
        "Studio de pilates clínico con Reformer, Cadillac y accesorios Balanced Body",
        "Convenio con 15 mutuas aseguradoras y facturación directa a seguros privados",
      ],
      en: [
        "8 registered specialist physiotherapists with postgraduate masters degrees",
        "Dedicated pelvic floor therapy unit for both male and female patients",
        "Clinical Pilates studio with Balanced Body Reformer, Cadillac, and accessories",
        "Direct billing with 15 insurance companies for cashless treatment",
      ],
      ca: [
        "8 fisioterapeutes amb màsters especialitzats",
        "Unitat de terra pelvià",
        "Studio de pilates clínic amb Reformer Balanced Body",
        "Conveni amb 15 mútues asseguradores",
      ],
      de: [
        "8 Fachphysiotherapeuten mit akademischen Masterabschlüssen",
        "Dedizierte Beckenbodentherapie-Einheit für Damen und Herren",
        "Klinisches Pilates-Studio mit Balanced Body Reformer und Cadillac",
        "Direktabrechnung mit 15 Versicherungsgesellschaften",
      ],
    },
    servicesProvided: {
      es: [
        "Fisioterapia deportiva y rehabilitación post-quirúrgica de rodilla, hombro y columna",
        "Osteopatía parietal, visceral y craneal (terapia manual avanzada)",
        "Fisioterapia de suelo pélvico: incontinencia, diastasis abdominal y preparación al parto",
        "Sesiones individuales y grupales de pilates clínico con Reformer",
      ],
      en: [
        "Sports physiotherapy and post-surgical rehabilitation of knee, shoulder, and spine",
        "Parietal, visceral, and cranial osteopathy with advanced manual therapy",
        "Pelvic floor physiotherapy: incontinence, diastasis recti, and birth preparation",
        "Individual and small-group clinical Reformer Pilates sessions",
      ],
      ca: [
        "Fisioteràpia esportiva i rehabilitació postquirúrgica",
        "Osteopatia parietal, visceral i cranial",
        "Fisioteràpia de terra pelvià",
        "Sessions individuals i grupals de pilates clínic amb Reformer",
      ],
      de: [
        "Sportphysiotherapie und postoperative Reha für Knie, Schulter und Wirbelsäule",
        "Parietale, viszerale und kraniale Osteopathie",
        "Beckenbodentherapie: Inkontinenz, Diastase und Geburtsvorbereitung",
        "Einzel- und Kleingruppentraining im Klinischen Reformer-Pilates",
      ],
    },
  },

  // ── 4. DEPORTES & BUCEO PROFESIONAL ──
  {
    slug: "centro-buceo-padi-dive-mallorca-port-andratx",
    name: "Dive Mallorca PADI 5* Centre Port d'Andratx",
    category: "deportes-fitness",
    sectorFolder: "deportes-fitness",
    sectorArrayName: "DEPORTES_SERVICES",
    subcategories: ["cursos-buceo-padi", "buceo-open-water", "diving-mallorca"],
    zone: "calvia-andratx",
    address: "Carrer de Isaac Peral, 5, 07157 Port d'Andratx",
    coordinates: { lat: 39.5381, lng: 2.3812 },
    rating: 4.9,
    reviewCount: 465,
    priceRange: "€€€",
    phone: "+34 971 672 584",
    website: "https://divemallorca.com",
    schedule: "Diario: 08:00 - 19:00 (Temporada: Abril – Noviembre)",
    tags: ["zona:andratx", "product:buceo", "mod:cita-previa"],
    shortDescription: {
      es: "Centro de buceo PADI 5 Star Instructor Development Centre en Port d'Andratx: cursos Open Water, Divemaster, Rescue Diver y expediciones de buceo técnico en la reserva marina de Cabrera.",
      en: "PADI 5-Star Instructor Development Centre in Port d'Andratx: Open Water courses, Divemaster training, Rescue Diver, and technical diving expeditions to Cabrera Marine Reserve.",
      ca: "Centre de busseig PADI 5 Star a Port d'Andratx: cursos Open Water, Divemaster i busseig tècnic a la reserva marina de Cabrera.",
      de: "PADI 5-Star Tauchzentrum in Port d'Andratx: Open Water Kurse, Divemaster-Ausbildung, Rescue Diver und Technisch-Tauchen in der Meeresschutzzone Cabrera.",
    },
    fullDescription: {
      es: "Dive Mallorca es el único PADI IDC en el suroeste de Mallorca. Sus instructores multilingües guían inmersiones en los puntos más espectaculares: la gruta del Delfín (Andratx), el pecio del Sever (naufragio Siglo XIX), los arrecifes de posidonia de s'Estanyol y la Reserva Marina del Archipiélago de Cabrera.",
      en: "The only PADI IDC in southwest Mallorca, its multilingual instructors lead dives to top sites: Dolphin Cave (Andratx), wreck of the Sever (19th-century shipwreck), s'Estanyol posidonia reefs, and the Cabrera Archipelago Marine Reserve.",
      ca: "L'únic PADI IDC al sud-oest de Mallorca. Instructors multilingües en els millors punts de busseig: Cova del Dofí, el vaixell Sever i la Reserva Marina de Cabrera.",
      de: "Einziges PADI IDC im Südwesten Mallorcas mit mehrsprachigen Instructoren für Top-Tauchplätze: Delfin-Grotte, 19.-Jh.-Wrack 'Sever', Posidonia-Riffe und Cabrera-Meeresschutzgebiet.",
    },
    highlights: {
      es: [
        "Centro PADI 5 Star IDC – el mayor reconocimiento PADI a nivel mundial",
        "Acceso exclusivo a los mejores puntos del SW de Mallorca y Cabrera",
        "Instructores certificados en español, inglés, alemán y francés",
        "Equipos reguladores Aqualung, trajes 5mm, DPVs y cámaras subacuáticas para alquiler",
      ],
      en: [
        "PADI 5-Star IDC Centre – the highest PADI global distinction",
        "Exclusive access to the best dive sites in SW Mallorca and Cabrera Reserve",
        "Certified instructors in Spanish, English, German, and French",
        "Aqualung regulators, 5mm wetsuits, DPVs, and underwater cameras for hire",
      ],
      ca: [
        "Centre PADI 5 Star IDC",
        "Accés exclusiu als millors punts del SW de Mallorca i Cabrera",
        "Instructors en espanyol, anglès, alemany i francès",
        "Material de lloguer d'alta qualitat",
      ],
      de: [
        "PADI 5-Star IDC – höchste PADI-Auszeichnung weltweit",
        "Exklusiver Zugang zu den besten Tauchspots SW-Mallorcas und Cabreras",
        "Zertifizierte Tauchlehrer auf Spanisch, Englisch, Deutsch und Französisch",
        "Aqualung-Ausrüstung, 5mm-Neoprenanzüge, DPVs und Unterwasserkameras",
      ],
    },
    servicesProvided: {
      es: [
        "Bautismo de buceo para principiantes sin experiencia previa (Discover Scuba)",
        "Cursos PADI Open Water Diver en 3-4 días con titulación internacional",
        "Inmersiones guiadas de aventura en Cabrera, Andratx y s'Estanyol",
        "Cursos PADI Divemaster, Rescue Diver e IDC de Instructor",
      ],
      en: [
        "Discover Scuba Diving try-dive experience for absolute beginners",
        "3-4 day PADI Open Water Diver course with internationally recognised certification",
        "Guided adventure dives at Cabrera, Andratx, and s'Estanyol reefs",
        "PADI Divemaster, Rescue Diver, and IDC Instructor training courses",
      ],
      ca: [
        "Baptisme de busseig per a principiants (Discover Scuba)",
        "Curs PADI Open Water Diver en 3-4 dies",
        "Immersions guiades a Cabrera, Andratx i s'Estanyol",
        "Cursos PADI Divemaster, Rescue Diver i IDC",
      ],
      de: [
        "Schnupperkurs Discover Scuba für absolute Anfänger",
        "PADI Open Water Diver Kurs in 3-4 Tagen mit internationalem Patent",
        "Geführte Abenteuer-Tauchgänge in Cabrera, Andratx und s'Estanyol",
        "PADI Divemaster, Rescue Diver und IDC-Instructorkurs",
      ],
    },
  },

  // ── 5. BODEGA ECOLÓGICA & VINO ──
  {
    slug: "celler-can-verdura-binissalem-vins-autoctons",
    name: "Celler Ca n'Verdura Binissalem Vins d'Autor",
    category: "gastronomia-catering",
    sectorFolder: "gastronomia-restaurantes",
    sectorArrayName: "GASTRONOMIA_SERVICES",
    subcategories: ["vino-do-binissalem", "variedades-recuperadas-giró-ros", "catas-vino-binissalem"],
    zone: "raiguer-pla",
    address: "Carrer de sa Siquia, 3, 07350 Binissalem",
    coordinates: { lat: 39.6872, lng: 2.8431 },
    rating: 4.9,
    reviewCount: 310,
    priceRange: "€€€",
    phone: "+34 971 870 120",
    website: "https://canverdura.com",
    schedule: "Lunes a Viernes: 09:00 - 17:00. Catas con reserva previa.",
    tags: ["zona:raiguer-pla", "product:enoturismo", "mod:cita-previa"],
    shortDescription: {
      es: "Celler de autor en Binissalem especializado en la recuperación de variedades autóctonas mallorquinas olvidadas: Mantonegro, Moll, Escursac y Giró Ros.",
      en: "Signature micro-winery in Binissalem dedicated to reviving forgotten native Mallorcan grape varieties: Mantonegro, Moll, Escursac, and Giró Ros.",
      ca: "Celler d'autor a Binissalem especialitzat en la recuperació de varietats autòctones mallorquines oblidades.",
      de: "Autoren-Micro-Weingut in Binissalem zur Wiederbelebung vergessener einheimischer mallorquinischer Rebsorten.",
    },
    fullDescription: {
      es: "El enólogo Tomeu Llabrés dirige Ca n'Verdura en el corazón de la DO Binissalem, vinificando parcelas micro-locales de cepas viejas trabajadas a mano sin pesticidas sintéticos.",
      en: "Winemaker Tomeu Llabrés leads Ca n'Verdura in the heart of DO Binissalem, vinifying micro-plots of old vines worked manually without synthetic pesticides.",
      ca: "L'enòleg Tomeu Llabrés dirigeix Ca n'Verdura al cor de la DO Binissalem vinificant parcel·les de vinyes velles a mà.",
      de: "Winzer Tomeu Llabrés leitet Ca n'Verdura im Herzen der DO Binissalem und vinifiziert Kleinstparzellen alter Reben in Handarbeit.",
    },
    highlights: {
      es: [
        "Pionero en la recuperación de varietales pre-filoxera de Mallorca",
        "Producción artesana de micro-vinificaciones por parcela",
        "Reconocimiento en Guía Peñín con 93+ puntos en vinos de finca",
        "Catas exclusivas en bodega histórica del centro de Binissalem",
      ],
      en: [
        "Pioneer in recovering pre-phylloxera native Mallorcan varietals",
        "Artisan single-parcel micro-vinification production",
        "Awarded 93+ points in Guía Peñín for single-estate cuvées",
        "Exclusive tastings in historic cellars in central Binissalem",
      ],
      ca: [
        "Pioner en la recuperació de varietats pre-fil·loxera",
        "Micro-vinificacions artesanals per parcel·la",
        "93+ punts a la Guia Peñín",
        "Tasts exclusius al celler històric de Binissalem",
      ],
      de: [
        "Pionier bei der Rettung historischer mallorquinischer Rebsorten",
        "Handwerkliche Mikro-Vinifikation nach einzelnen Parzellen",
        "93+ Punkte im Guía Peñín für Einzellagen-Cuvées",
        "Exklusive Verkostungen im historischen Keller in Binissalem",
      ],
    },
    servicesProvided: {
      es: [
        "Catas privadas guiadas por el enólogo con maridaje de cocos artesanales",
        "Venta de vinos de edición limitada numerada",
        "Visita técnica a los viñedos viejos de la DO Binissalem",
        "Envíos internacionales directos desde bodega",
      ],
      en: [
        "Private winemaker-guided tastings paired with local artisan pastries",
        "Limited numbered-edition wine sales",
        "Technical viticulture tours of old-vine DO Binissalem plots",
        "Direct international winery shipping",
      ],
      ca: [
        "Tasts privats dirigits per l'enòleg amb coces artesanals",
        "Venda de vins d'edició limitada numerada",
        "Visita tècnica a les vinyes velles",
        "Enviaments internacionals directes",
      ],
      de: [
        "Private Winzer-Verkostungen mit lokalen Gebäckspezialitäten",
        "Verkauf limitierter nummerierter Editionen",
        "Fachführungen durch alte DO Binissalem Weinberge",
        "Direkter internationaler Weingutversand",
      ],
    },
  },
];

console.log("Ingesting Batch 9 with Ca n'Verdura...");
ingestBatch(BATCH_9);
