import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_4: BusinessDataInput[] = [
  // ── 1. GASTRONOMÍA & RESTAURANTES ──
  {
    slug: "forn-fondo-pasteleria-historica-palma",
    name: "Forn Fondo Pastelería Tradicional Palma (1911)",
    category: "gastronomia-catering",
    sectorFolder: "gastronomia-restaurantes",
    sectorArrayName: "RESTAURANT_SERVICES",
    subcategories: ["ensaimadas-tradicionales", "pasteleria-artesana", "hornos-historicos"],
    zone: "palma",
    address: "Carrer del Caputxins, 13, 07002 Palma",
    coordinates: { lat: 39.5724, lng: 2.6515 },
    rating: 4.8,
    reviewCount: 1850,
    priceRange: "€€",
    phone: "+34 971 711 306",
    website: "https://fornfondopalma.com",
    schedule: "Lunes a Sábado: 07:30 - 20:00, Domingos: 08:00 - 14:00",
    tags: ["zona:palma-centro", "product:forns-ensaimadas", "mod:walk-in"],
    shortDescription: {
      es: "Horno y pastelería modernista centenaria fundada en 1911 famosa por sus ensaimadas de manteca de cerdo negro, cremadillos y cuartos.",
      en: "Century-old modernist bakery founded in 1911 celebrated for its authentic black pig lard ensaimadas and traditional pastries.",
      ca: "Forn i pastisseria modernista centenària fundada el 1911 famosa per les seves ensaïmades tradicionals i cremadillos.",
      de: "Traditionsreiche Jugendstil-Bäckerei von 1911, berühmt für Ensaimadas vom schwarzen Schwein und traditionelles Gebäck.",
    },
    fullDescription: {
      es: "Dirigido por la cuarta generación de la familia Llull, el Forn Fondo conserva la fachada modernista original y el obrador artesanal. Elaboran ensaimadas tradicionales con Indicación Geográfica Protegida, empanadas de cordero y gató de almendra de Mallorca.",
      en: "Run by the fourth generation of the Llull family, preserving its original Art Nouveau facade and master baking ovens with PGI Ensaimada de Mallorca.",
      ca: "Dirigit per la quarta generació de la família Llull, conserva la façana modernista i elabora ensaïmades amb IGP Ensaïmada de Mallorca.",
      de: "In vierter Generation geführt, backt Forn Fondo original geschützte Ensaimadas de Mallorca, Mandelkuchen Gató und Empanadas.",
    },
    highlights: {
      es: [
        "Establecimiento emblemático centenario fundado en 1911",
        "Ensaimadas con sello oficial IGP Ensaïmada de Mallorca",
        "Fachada modernista de hierro forjado y azulejos",
        "Envasado especial octogonal para transporte en avión",
      ],
      en: [
        "Historic centenary shop founded in 1911",
        "PGI Protected Geographical Indication Ensaimada seal",
        "Historic Art Nouveau facade with forged iron",
        "Special octagonal travel boxes for flight transport",
      ],
      ca: [
        "Comerç emblemàtic centenari fundat el 1911",
        "Ensaïmades amb segell oficial IGP",
        "Façana modernista històrica",
        "Envasat especial per a viatges",
      ],
      de: [
        "Traditionsgeschäft seit 1911",
        "Offiziell geschützte Ensaimadas mit Herkunftssiegel",
        "Historische Jugendstilfassade",
        "Flugreise-sichere achteckige Transportkartons",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de ensaimadas lisas, de cabello de ángel, crema y chocolate",
        "Pastelería salada (empanadas de carne, cocarrois y cocas de verduras)",
        "Cafetería y degustación en barra histórica",
        "Encargos para recogida previa y envíos a hoteles",
      ],
      en: [
        "Classic, pumpkin jam, cream, and chocolate ensaimadas",
        "Savory bakes (meat empanadas, cocarrois, vegetable cocas)",
        "Historic counter coffee and pastry tasting",
        "Pre-order pickup and direct hotel deliveries",
      ],
      ca: [
        "Venda d'ensaïmades llises i farcides",
        "Pastisseria salada tradicional (panades, cocarrois)",
        "Cafeteria tradicional",
        "Comandes per a viatges",
      ],
      de: [
        "Verkauf klassischer und gefüllter Ensaimadas",
        "Herzhafte Spezialitäten (Panades, Cocarrois, Gemüsekuchen)",
        "Traditionelles Café mit Thekenausschank",
        "Vorbestellungen für den Abflug",
      ],
    },
  },
  {
    slug: "restaurante-arrosseria-sa-cranca-palma-paseo-maritimo",
    name: "Restaurante Arroseria Sa Cranca Palma",
    category: "gastronomia-catering",
    sectorFolder: "gastronomia-restaurantes",
    sectorArrayName: "RESTAURANT_SERVICES",
    subcategories: ["arroces-paellas", "mariscos-frescos", "cocina-mediterranea"],
    zone: "palma",
    address: "Avinguda de Gabriel Roca, 37, 07014 Palma",
    coordinates: { lat: 39.5638, lng: 2.6289 },
    rating: 4.7,
    reviewCount: 2100,
    priceRange: "€€€",
    phone: "+34 971 737 447",
    website: "https://sacrancapalma.com",
    schedule: "Martes a Domingo: 13:00 - 16:00 y 20:00 - 23:30",
    tags: ["zona:palma-centro", "product:paellas-arroces", "mod:walk-in"],
    shortDescription: {
      es: "Arrocería emblemática en el Paseo Marítimo de Palma especializada en paellas de marisco, arroz caldoso de bogavante y fideuàs.",
      en: "Iconic rice specialty restaurant on Palma's seafront promenade famous for seafood paella, lobster soupy rice, and fideuà.",
      ca: "Arrosseria emblemàtica al Passeig Marítim de Palma especialitzada en paelles de marisc i arròs caldós de llamàntol.",
      de: "Renommiertes Reisspezialitäten-Restaurant an der Uferpromenade von Palma für Meeresfrüchte-Paella und Hummerreis.",
    },
    fullDescription: {
      es: "Sa Cranca es una institución del buen arroz en Palma desde hace más de tres décadas. Con vistas a la bahía y a los yates, elabora más de 20 variedades de arroces secos y caldosos cocinados al punto con fumets de pescado de roca de la lonja de Palma.",
      en: "For over 30 years, Sa Cranca has been Palma's landmark rice restaurant, serving 20+ varieties of paella crafted with fresh local fish stock.",
      ca: "Més de tres dècades oferint els millors arrossos a Palma amb brou de peix fresc de la llotja i vistes a la marina.",
      de: "Seit über 30 Jahren eine Institution für Paella in Palma: über 20 Reisspezialitäten mit frischem Fischfond aus der Fischauktionshalle.",
    },
    highlights: {
      es: [
        "Más de 30 años de maestría arrocera frente al puerto",
        "Arroz ciego de marisco pelado y arroz negro con sepia",
        "Terraza exterior climatizada con vistas a la marina",
        "Pescados frescos del día a la sal y a la plancha",
      ],
      en: [
        "30+ years of authentic paella mastery on the waterfront",
        "Specialties include peeled seafood paella and squid ink rice",
        "Heated outdoor terrace with marina views",
        "Daily fresh catch baked in sea salt or grilled",
      ],
      ca: [
        "Més de 30 anys d'experiència arrossera",
        "Arròs cec de marisc i arròs negre",
        "Terrassa climatitzada amb vistes",
        "Peix fresc a la sal",
      ],
      de: [
        "Über 30 Jahre Paella-Tradition an der Marina",
        "Spezialitäten: Meeresfrüchtereis und schwarzer Tintenfischreis",
        "Klimatisierte Terrasse mit Hafenblick",
        "Tagesfrischer Edelfisch in der Salzkruste",
      ],
    },
    servicesProvided: {
      es: [
        "Servicio de almuerzos y cenas frente al mar",
        "Arroces y paellas por encargo para llevar (Take Away)",
        "Menús para grupos, celebraciones y eventos de empresa",
        "Carta de vinos de la tierra de Mallorca y cavas",
      ],
      en: [
        "Waterfront lunch and dinner dining",
        "Paella takeaway service in traditional pans",
        "Group menus for private and corporate gatherings",
        "Extensive local Balearic wine and cava list",
      ],
      ca: [
        "Dinars i sopars davant la mar",
        "Paelles per emportar",
        "Menús per a grups i esdeveniments",
        "Carta de vins mallorquins",
      ],
      de: [
        "Mittag- und Abendessen am Wasser",
        "Paella-Abholservice in traditionellen Pfannen",
        "Gruppenmenüs für Feierlichkeiten",
        "Ausgewählte Weine von Mallorca und Cavas",
      ],
    },
  },

  // ── 2. DEPORTES & ACTIVIDADES (deportes-aire-libre) ──
  {
    slug: "open-marratxi-padel-indoor-club",
    name: "Open Marratxí Pádel Indoor Club",
    category: "padel-tenis-clubs",
    sectorFolder: "deportes-fitness",
    sectorArrayName: "DEPORTES_SERVICES",
    subcategories: ["pistas-padel-indoor", "escuela-padel-menores", "torneos-ranking-padel"],
    zone: "raiguer-pla",
    address: "Carrer del Gremi de Sabaters, 14, Polígon Marratxí, 07141 Marratxí",
    coordinates: { lat: 39.6234, lng: 2.7112 },
    rating: 4.8,
    reviewCount: 310,
    priceRange: "€€",
    phone: "+34 971 794 560",
    website: "https://openpadelmarratxi.com",
    schedule: "Lunes a Domingo: 08:00 - 23:30",
    tags: ["zona:raiguer-pla", "product:padel-mallorca", "mod:walk-in"],
    shortDescription: {
      es: "El club indoor de pádel de referencia en Mallorca con pistas climatizadas panorámicas, césped Mondo WPT, escuela y bar-cafetería.",
      en: "Premier indoor padel club in Mallorca featuring climate-controlled panoramic courts, Mondo WPT turf, academy, and clubhouse café.",
      ca: "El club indoor de pàdel de referència a Mallorca amb pistes climatitzades panoràmiques, escola i cafeteria.",
      de: "Führender Indoor-Padelclub auf Mallorca mit klimatisierten Panoramaplätzen, Mondo-WPT-Rasen, Akademie und Club-Café.",
    },
    fullDescription: {
      es: "Open Marratxí ofrece la mayor comodidad para jugar al pádel los 365 días del año sin preocuparse por el viento, la lluvia o el calor del verano. Con iluminación LED de competición, tienda especializada y ligas periódicas de todos los niveles.",
      en: "Open Marratxí offers year-round indoor padel protected from wind, rain, and summer heat, featuring tournament LED lighting and pro shop.",
      ca: "Ofereix el màxim confort per jugar a pàdel tot l'any sense vent ni pluja amb il·luminació LED de competició i botiga especialitzada.",
      de: "Open Marratxí bietet ganzjähriges wetterunabhängiges Padel-Spiel mit blendfreier LED-Beleuchtung, Pro-Shop und Turnieren.",
    },
    highlights: {
      es: [
        "Pistas indoor panorámicas climatizadas con altura reglamentaria",
        "Césped oficial Mondo Supercourt World Padel Tour",
        "App móvil para reserva de pistas y partidos abiertos (MeApunto)",
        "Zona social climatizada con terraza y retransmisión de partidos",
      ],
      en: [
        "Climate-controlled panoramic indoor courts with official height",
        "Official Mondo Supercourt World Padel Tour turf",
        "Mobile app for court booking and open matchmaking",
        "Clubhouse lounge with terrace and live match broadcasts",
      ],
      ca: [
        "Pistes indoor panoràmiques climatitzades",
        "Gespa oficial Mondo World Padel Tour",
        "App mòbil de reserves",
        "Zona social amb cafeteria",
      ],
      de: [
        "Klimatisierte Indoor-Panoramaplätze mit Turnierhöhe",
        "Offizieller Mondo Supercourt WPT-Kunstrasen",
        "Smartphone-App für Platzbuchung und Matchmaking",
        "Clublounge mit Café und Live-Sportübertragungen",
      ],
    },
    servicesProvided: {
      es: [
        "Alquiler de pistas individuales y dobles por tramos de 60, 90 y 120 min",
        "Escuela de pádel para adultos y menores con monitores FEP",
        "Organización de torneos 'Americanas', ligas y eventos de empresa",
        "Alquiler y test de palas de primeras marcas (Bullpadel, Nox, Babolat)",
      ],
      en: [
        "Court hire (60, 90, 120 min slots)",
        "Adult and junior padel coaching by certified FEP coaches",
        "Weekly 'Americana' mixer tournaments and corporate days",
        "Pro racket testing and equipment rental (Bullpadel, Nox, Babolat)",
      ],
      ca: [
        "Lloguer de pistes de 60, 90 i 120 min",
        "Escola de pàdel per a infants i adults",
        "Tornejos de cap de setmana i 'Americanes'",
        "Lloguer i venda de pales",
      ],
      de: [
        "Platzmiete für 60, 90 oder 120 Minuten",
        "Padel-Unterricht für Anfänger und Fortgeschrittene",
        "Wöchentliche Schleifchenturniere und Firmenevents",
        "Testcenter und Schlägerverleih führender Marken",
      ],
    },
  },
  {
    slug: "diving-scuba-mallorca-port-pollensa-center",
    name: "Scuba Mallorca PADI 5 Star Dive Resort Port de Pollença",
    category: "deportes-fitness",
    sectorFolder: "deportes-fitness",
    sectorArrayName: "DEPORTES_SERVICES",
    subcategories: ["buceo-padi-5-star", "inmersiones-formentor", "bautismo-submarino"],
    zone: "alcudia-pollensa",
    address: "Carrer d'Elcano, 23, 07470 Port de Pollença",
    coordinates: { lat: 39.9078, lng: 3.0812 },
    rating: 4.9,
    reviewCount: 430,
    priceRange: "€€€",
    phone: "+34 971 868 087",
    website: "https://scubamallorcapollensa.com",
    schedule: "Lunes a Domingo: 08:30 - 19:00 (Temporada Abril - Noviembre)",
    tags: ["zona:port-de-pollenca", "product:buceo", "mod:walk-in"],
    shortDescription: {
      es: "Centro de buceo PADI 5 Star en el Puerto de Pollensa con salidas diarias en barco al Cabo Formentor, cuevas marinas y pecios.",
      en: "PADI 5 Star Dive Resort in Port de Pollença offering daily boat diving trips to Cap de Formentor, sea caves, and marine reserves.",
      ca: "Centre de submarinisme PADI 5 Star al Port de Pollença amb sortides en vaixell al Cap de Formentor i coves marines.",
      de: "PADI 5-Star Dive Center in Port de Pollença mit täglichen Bootsausfahrten zum Cap de Formentor und Meereshöhlen.",
    },
    fullDescription: {
      es: "Con más de 20 años explorando las aguas cristalinas del norte de Mallorca, Scuba Mallorca opera barcos de buceo rápidos hacia más de 30 puntos de inmersión protegidos alrededor del Cap de Formentor y Cala Sant Vicenç, con instructores multilingües PADI.",
      en: "Operating for 20+ years, offering fast dive boats to over 30 dive sites around dramatic Cap de Formentor cliffs with multilingual PADI instructors.",
      ca: "Més de 20 anys oferint immersions a més de 30 punts protegits al voltant de Formentor amb instructors PADI multilingües.",
      de: "Seit über 20 Jahren PADI 5-Star Tauchbasis mit Schnellbooten zu über 30 Tauchplätzen am spektakulären Cap de Formentor.",
    },
    highlights: {
      es: [
        "Centro PADI 5 Star Dive Resort autorizado",
        "Inmersiones espectaculares en las reservas del Cap de Formentor",
        "Embarcación rígida de buceo de 12 metros equipada",
        "Cursos PADI desde Open Water hasta Divemaster en varios idiomas",
      ],
      en: [
        "Authorized PADI 5 Star Dive Resort",
        "Spectacular diving at Cap de Formentor marine reserves",
        "Custom 12-meter hard-hull dive boat",
        "PADI courses from Open Water to Divemaster in multiple languages",
      ],
      ca: [
        "Centre PADI 5 Star autoritzat",
        "Immersions a Formentor",
        "Vaixell de busseig de 12 metres",
        "Cursos PADI des d'Open Water",
      ],
      de: [
        "Autorisiertes PADI 5 Star Dive Resort",
        "Spektakuläre Steilwand- und Höhlentauchgänge am Cap Formentor",
        "Eigenes 12-Meter-Tauchboot",
        "PADI-Tauchkurse vom Anfänger bis zum Divemaster",
      ],
    },
    servicesProvided: {
      es: [
        "Salidas diarias de 2 inmersiones en barco (Double Tank)",
        "Bautismos de buceo Discover Scuba Diving desde barco o playa",
        "Cursos oficiales de certificación PADI (Open Water, Advanced)",
        "Alquiler y mantenimiento de equipos completos Scubapro y Aqualung",
      ],
      en: [
        "Daily 2-tank boat diving excursions",
        "Discover Scuba Diving try-dives for beginners",
        "Full PADI certification courses (Open Water, Advanced, Rescue)",
        "Scubapro and Aqualung rental gear and tank fills",
      ],
      ca: [
        "Sortides de busseig en vaixell",
        "Baptismes de submarinisme",
        "Cursos oficials PADI",
        "Lloguer d'equips Scubapro",
      ],
      de: [
        "Tägliche 2-Tank-Bootsausfahrten",
        "Schnuppertauchen (Discover Scuba) für Einsteiger",
        "PADI-Tauchscheine (Open Water, Advanced, Nitrox)",
        "Verleih von Scubapro- & Aqualung-Ausrüstung",
      ],
    },
  },
];

console.log("Ingesting Batch 4 of verified businesses...");
ingestBatch(BATCH_4);
