import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_12: BusinessDataInput[] = [
  // ── 1. GASTRONOMÍA & ALTA COCINA ──
  {
    slug: "restaurante-tierra-palma-cocina-mallorquina-contemporanea",
    name: "Tierra Restaurante Cocina Mallorquina Contemporánea Palma",
    category: "gastronomia-catering",
    sectorFolder: "gastronomia-restaurantes",
    sectorArrayName: "GASTRONOMIA_SERVICES",
    subcategories: ["cocina-mallorquina-autor", "fine-dining-mallorca", "producto-local-km0"],
    zone: "palma",
    address: "Carrer dels Apuntadors, 5, 07012 Palma",
    coordinates: { lat: 39.5686, lng: 2.6481 },
    rating: 4.9,
    reviewCount: 598,
    priceRange: "€€€€",
    phone: "+34 971 712 306",
    website: "https://tierramallorca.com",
    schedule: "Martes a Sábado: 13:00 - 15:30 y 19:30 - 23:00; Lunes y Domingo: Cerrado",
    tags: ["zona:palma-centro", "product:cocina-mallorquina", "mod:cita-previa"],
    shortDescription: {
      es: "Restaurante de cocina mallorquina contemporánea en el barrio de La Llonja de Palma: menú degustación de producto local KM0 con técnicas actuales y referentes en la Guía Michelin.",
      en: "Contemporary Mallorcan cuisine restaurant in Palma's La Llonja quarter: KM0 local product tasting menu with modern techniques, recommended in the Michelin Guide.",
      ca: "Restaurant de cuina mallorquina contemporània al barri de La Llonja de Palma: menú degustació de producte local KM0 amb tècniques actuals i recomanat a la Guia Michelin.",
      de: "Restaurant für zeitgenössische mallorquinische Küche im Viertel La Llonja in Palma: KM0-Degustationsmenü mit modernen Techniken, im Michelin-Guide empfohlen.",
    },
    fullDescription: {
      es: "El chef Marc Fosh inspiró una generación de cocineros insulares que hoy impulsan una cocina que celebra los sabores de Mallorca con técnicas culinarias modernas. Tierra trabaja con más de 30 productores locales de la isla: queso de oveja roja Son Jover, aceite de Son Moragues, cerdo negro de Sa Calobra y verduras de l'Hort de Ca n'Amer.",
      en: "Working with 30+ local island producers including Son Jover sheep cheese, Son Moragues olive oil, Sa Calobra black pork, and Ca n'Amer market garden vegetables, Tierra elevates Mallorcan flavour with contemporary culinary technique.",
      ca: "Treballen amb més de 30 productors locals: formatge d'ovella roja Son Jover, oli de Son Moragues, porc negre de Sa Calobra i verdures de Ca n'Amer.",
      de: "Zusammenarbeit mit 30+ lokalen Erzeugern: Son-Jover-Schafskäse, Son-Moragues-Olivenöl, schwarzes Sa-Calobra-Schwein und Ca-n'Amer-Gartengemüse.",
    },
    highlights: {
      es: [
        "Recomendado en la Guía Michelin y Top 50 restaurantes de España",
        "Menú degustación de 10 pasos con maridaje de vinos mallorquines de autor",
        "Más de 30 productores locales de Mallorca verificados KM0",
        "Carta de vinos con las mejores añadas de las bodegas DO Binissalem y DO Pla i Llevant",
      ],
      en: [
        "Michelin Guide recommended and Top 50 Restaurants in Spain",
        "10-course tasting menu with Mallorcan artisan wine pairing",
        "30+ verified KM0 local Mallorcan producers",
        "Wine list featuring the finest vintages of DO Binissalem and DO Pla i Llevant",
      ],
      ca: [
        "Recomanat a la Guia Michelin i Top 50 restaurants d'Espanya",
        "Menú degustació de 10 passos amb maridatge de vins mallorquins",
        "Més de 30 productors KM0 locals",
        "Carta de vins amb les millors anyades de les DO de Mallorca",
      ],
      de: [
        "Michelin-Guide empfohlen und Top 50 Restaurants Spaniens",
        "10-Gang-Degustationsmenü mit mallorquinischem Weinbegleitung",
        "30+ verifizierte KM0-Produzenten aus Mallorca",
        "Weinkarte mit den besten Jahrgängen der DO Binissalem und DO Pla i Llevant",
      ],
    },
    servicesProvided: {
      es: [
        "Menú degustación de 10 pasos con ingredientes locales KM0 de Mallorca",
        "Carta de restaurante con platos a la carta de cocina mallorquina contemporánea",
        "Maridaje de vinos mallorquines seleccionados por el sumiller con cada menú",
        "Cenas privadas y eventos gastronómicos en el comedor reservado (hasta 16 personas)",
      ],
      en: [
        "10-course tasting menu with local KM0 Mallorcan ingredients",
        "À la carte menu of contemporary Mallorcan cuisine dishes",
        "Mallorcan wine pairing selected by the sommelier for each menu",
        "Private dinners and gastronomic events in the private dining room (up to 16 guests)",
      ],
      ca: [
        "Menú degustació de 10 passos amb producte KM0 de Mallorca",
        "Carta a la carta de cuina mallorquina contemporània",
        "Maridatge de vins mallorquins seleccionats pel sommelier",
        "Sopars privats i esdeveniments gastronòmics (fins a 16 persones)",
      ],
      de: [
        "10-Gang-Degustationsmenü mit lokalen KM0-Zutaten aus Mallorca",
        "À-la-carte-Karte zeitgenössischer mallorquinischer Küche",
        "Mallorquinische Weinbegleitung durch den Sommelier",
        "Privatessen und gastronomische Events im Separee (bis 16 Personen)",
      ],
    },
  },

  // ── 2. SERVICIOS SOCIALES & ATENCIÓN MAYORES ──
  {
    slug: "residencia-mayores-can-bibiloni-palma-ancians",
    name: "Residència Can Bibiloni Atenció a la Gent Gran Palma",
    category: "cuidado-mayores-asistencia",
    sectorFolder: "servicios-sociales",
    sectorArrayName: "SERVICIOS_SOCIALES",
    subcategories: ["residencia-mayores-mallorca", "centro-dia-mayores", "asistencia-domicilio-palma"],
    zone: "palma",
    address: "Carrer de Caro, 25, 07013 Palma",
    coordinates: { lat: 39.5892, lng: 2.6356 },
    rating: 4.8,
    reviewCount: 198,
    priceRange: "€€€",
    phone: "+34 971 737 400",
    website: "https://residenciacanbibiloni.com",
    schedule: "Recepción: 08:00 - 20:00. Centro de Día: 07:30 - 20:30 (Lunes a Viernes)",
    tags: ["zona:palma-centro", "product:accesible", "mod:cita-previa"],
    shortDescription: {
      es: "Residencia de mayores y centro de día en Palma con atención especializada en demencia, Alzheimer y cuidados paliativos: habitaciones individuales, fisioterapia propia y actividades de estimulación cognitiva.",
      en: "Care home and day centre in Palma specialising in dementia, Alzheimer's, and palliative care: private rooms, in-house physiotherapy, and cognitive stimulation activities.",
      ca: "Residència de gent gran i centre de dia a Palma especialitzada en demència, Alzheimer i cures pal·liatives: habitacions individuals i fisioteràpia pròpia.",
      de: "Seniorenheim und Tagesstätte in Palma mit Spezialisierung auf Demenz, Alzheimer und Palliativversorgung: Einzelzimmer, hauseigene Physiotherapie und kognitive Stimulierung.",
    },
    fullDescription: {
      es: "Can Bibiloni dispone de 120 plazas residenciales y 40 plazas de centro de día homologadas por la Conselleria de Serveis Socials del Govern Balear. Cuenta con un equipo de 85 profesionales entre médicos gerontólogos, enfermeras, auxiliares, psicólogos, fisioterapeutas y trabajadores sociales. Instalaciones diseñadas por especialistas en arquitectura para personas con deterioro cognitivo.",
      en: "120 residential places and 40 day centre places accredited by the Balearic Government's Social Services Department. Team of 85 professionals including gerontologist physicians, nurses, care assistants, psychologists, physiotherapists, and social workers.",
      ca: "120 places residencials i 40 de centre de dia homologades per la Conselleria de Serveis Socials. Equip de 85 professionals entre metges, infermeres, psicòlegs i fisioterapeutes.",
      de: "120 Heimplätze und 40 Tagespflegeplätze, akkreditiert vom Balearischen Sozialministerium. 85-köpfiges Fachteam aus Gerontologen, Pflegern, Psychologen, Physiotherapeuten und Sozialarbeitern.",
    },
    highlights: {
      es: [
        "Centro homologado por la Conselleria de Serveis Socials del Govern Balear",
        "Unidad especializada de Alzheimer y demencia con seguridad perimetral",
        "Fisioterapeuta y terapeuta ocupacional en plantilla propia a tiempo completo",
        "Programa de estimulación cognitiva y reminiscencia con psicólogo clínico",
      ],
      en: [
        "Accredited by the Balearic Government Department of Social Services",
        "Specialist Alzheimer's and dementia unit with perimeter security",
        "Full-time in-house physiotherapist and occupational therapist on staff",
        "Clinical psychologist-led cognitive stimulation and reminiscence programme",
      ],
      ca: [
        "Centre homologat per la Conselleria de Serveis Socials",
        "Unitat d'Alzheimer i demència amb seguretat perimetral",
        "Fisioterapeuta i terapeuta ocupacional en plantilla",
        "Programa d'estimulació cognitiva amb psicòleg clínic",
      ],
      de: [
        "Akkreditiert vom Balearischen Sozialministerium",
        "Spezialisierte Alzheimer- und Demenz-Einheit mit Perimetersicherung",
        "Vollzeitbeschäftigte Physiotherapeutin und Ergotherapeutin im Haus",
        "Kognitive Stimulationstherapie mit Klinischem Psychologen",
      ],
    },
    servicesProvided: {
      es: [
        "Residencia 24 horas con habitaciones individuales y dobles adaptadas para personas mayores",
        "Centro de día con transporte propio para mayores que viven en su domicilio",
        "Servicio de atención a domicilio (SAD) con auxiliares de geriatría tituladas",
        "Tramitación de la ley de dependencia y gestión de ayudas públicas de la Comunitat",
      ],
      en: [
        "24-hour care home with adapted individual and double rooms for the elderly",
        "Day centre with own transport for elderly living at home",
        "Home care service (SAD) with qualified geriatric care assistants",
        "Dependency Law processing and management of public care benefits",
      ],
      ca: [
        "Residència 24 hores amb habitacions individuals i dobles adaptades",
        "Centre de dia amb transport propi per a gent gran que viu al domicili",
        "Servei d'atenció a domicili (SAD) amb auxiliars de geriatria titulades",
        "Tramitació de la llei de dependència i ajuts públics",
      ],
      de: [
        "24h-Pflegeheim mit adaptierten Einzel- und Doppelzimmern",
        "Tagesstätte mit eigenem Transport für zu Hause lebende Senioren",
        "Häuslicher Pflegedienst (SAD) mit qualifizierten Geriatrie-Pflegekräften",
        "Bearbeitung des Pflegegrades und Verwaltung öffentlicher Pflegeleistungen",
      ],
    },
  },

  // ── 3. PADEL & TENIS ──
  {
    slug: "padelindoor-mallorca-club-son-hugo-palma",
    name: "Pàdel Indoor Son Hugo Club & Academia Palma",
    category: "padel-tenis-clubs",
    sectorFolder: "deportes-fitness",
    sectorArrayName: "DEPORTES_SERVICES",
    subcategories: ["club-padel-palma", "academia-padel-mallorquina", "torneos-padel-mallorca"],
    zone: "palma",
    address: "Carrer de Gremi Hortolans, 18, Son Hugo, 07009 Palma",
    coordinates: { lat: 39.5956, lng: 2.6742 },
    rating: 4.9,
    reviewCount: 1124,
    priceRange: "€€",
    phone: "+34 971 431 170",
    website: "https://padelinsonhugo.com",
    schedule: "Lunes a Viernes: 07:00 - 23:00; Sábado y Domingo: 08:00 - 22:00",
    tags: ["zona:palma-centro", "product:padel-mallorca", "mod:cita-previa"],
    shortDescription: {
      es: "Mayor club de pádel indoor de Mallorca en Son Hugo, Palma: 24 pistas de pádel cubiertas con césped artificial de última generación, academia con entrenadores federados FBP y tienda de material.",
      en: "Mallorca's largest indoor padel club at Son Hugo, Palma: 24 covered padel courts with latest-generation artificial turf, FBP-federated coaches academy, and pro equipment shop.",
      ca: "El club de pàdel indoor més gran de Mallorca a Son Hugo, Palma: 24 pistes cobertes amb gespa artificial d'última generació i acadèmia amb entrenadors federats FBP.",
      de: "Mallorcas größter Indoor-Padelclub in Son Hugo, Palma: 24 überdachte Padelfelder mit Kunstrasen neuester Generation, FBP-lizenzierte Trainer-Akademie und Ausrüstungs-Shop.",
    },
    fullDescription: {
      es: "Pàdel Indoor Son Hugo es el club de referencia del pádel mallorquín con 24 pistas de césped artificial Mondo Sport y Deco Turf. Dispone de vestuarios con taquillas individuales, sauna, zona de fisioterapia y restaurante. Sede oficial de la Federació Balear de Pàdel y punto de clasificación para el circuito FIP.",
      en: "Mallorca's reference padel club with 24 Mondo Sport / Deco Turf artificial turf courts. Full facilities: individual lockers, sauna, physiotherapy room, and restaurant. Official venue of the Balearic Padel Federation and FIP ranking circuit point.",
      ca: "El club de pàdel de referència a Mallorca amb 24 pistes de gespa artificial Mondo Sport. Vestuaris amb taquilles, sauna, fisioterapia i restaurant. Seu oficial de la Federació Balear de Pàdel.",
      de: "Mallorcas Referenz-Padelclub mit 24 Mondo-Sport / Deco-Turf-Kunstrasenfeldern. Vollständige Anlage: Individualschränke, Sauna, Physiotherapieraum und Restaurant. Offizieller Veranstaltungsort des Balearischen Padelverbands und FIP-Rankingturnier.",
    },
    highlights: {
      es: [
        "24 pistas de pádel indoor con césped artificial premium Mondo Sport / Deco Turf",
        "Academia con 12 entrenadores titulados FBP para clases individuales y grupales",
        "Sede oficial de la Federació Balear de Pàdel y torneos del circuito FIP",
        "App propia para reservar pista online, ver historial y apuntarse a torneos",
      ],
      en: [
        "24 indoor padel courts with premium Mondo Sport / Deco Turf artificial turf",
        "Academy with 12 FBP-certified coaches for individual and group lessons",
        "Official venue of the Balearic Padel Federation and FIP circuit tournaments",
        "Own app for online court booking, match history, and tournament sign-up",
      ],
      ca: [
        "24 pistes de pàdel indoor amb gespa artificial premium",
        "Acadèmia amb 12 entrenadors titulats FBP",
        "Seu oficial de la Federació Balear de Pàdel",
        "App pròpia per reservar pista i apuntar-se a tornejos",
      ],
      de: [
        "24 Indoor-Padelfelder mit Premium-Kunstrasen Mondo Sport / Deco Turf",
        "Akademie mit 12 FBP-zertifizierten Trainern für Einzel- und Gruppenunterricht",
        "Offizieller Veranstaltungsort des Balearischen Padelverbands und FIP-Circuit",
        "Eigene App für Online-Feldbuchung und Turniereinschreibung",
      ],
    },
    servicesProvided: {
      es: [
        "Alquiler de pistas de pádel por horas (reserva online disponible 24h)",
        "Clases individuales y grupales con entrenadores titulados FBP",
        "Torneos federados mensuales y ligas sociales por niveles",
        "Tienda de pádel con material oficial Head, Bullpadel, Nox y NOX",
      ],
      en: [
        "Padel court hire by the hour (online booking available 24h)",
        "Individual and group lessons with FBP-certified coaches",
        "Monthly federated tournaments and social leagues by level",
        "Padel shop with official Head, Bullpadel, Nox, and NOX equipment",
      ],
      ca: [
        "Lloguer de pistes per hores (reserva en línia 24h)",
        "Classes individuals i grupals amb entrenadors FBP",
        "Tornejos federats mensuals i lligues socials per nivells",
        "Botiga de pàdel amb material oficial Head, Bullpadel i NOX",
      ],
      de: [
        "Stundenweise Padelfeldvermietung (24h Online-Buchung)",
        "Einzel- und Gruppenunterricht mit FBP-lizenzierten Trainern",
        "Monatliche Verbandsturniere und soziale Ligen nach Niveau",
        "Padelshop mit offizieller Ausrüstung von Head, Bullpadel und NOX",
      ],
    },
  },

  // ── 4. LIMPIEZA PROFESIONAL DE VILLAS ──
  {
    slug: "limpieza-villas-fincas-mallorca-clean-palma",
    name: "Mallorca Villa Cleaning Servicio Limpieza Profesional Villas & Fincas",
    category: "limpieza-villas-fincas",
    sectorFolder: "hogar-limpieza",
    sectorArrayName: "HOGAR_SERVICES",
    subcategories: ["limpieza-fin-estancia-villas", "cambio-ropa-cama-toallas", "limpieza-piscina-jardin"],
    zone: "calvia-andratx",
    address: "Carrer de Casablanca, 22, 07181 Portals Nous, Calvià",
    coordinates: { lat: 39.5168, lng: 2.5721 },
    rating: 4.9,
    reviewCount: 567,
    priceRange: "€€€",
    phone: "+34 645 789 012",
    website: "https://mallorkavillaclean.com",
    schedule: "Diario: 08:00 - 20:00 (365 días al año)",
    tags: ["zona:calvia-andratx", "product:limpieza-villas", "mod:cita-previa"],
    shortDescription: {
      es: "Servicio profesional de limpieza de villas, fincas y alquileres vacacionales en el suroeste de Mallorca: cambios entre huéspedes, limpieza a fondo, lavandería y gestión de ropa de cama.",
      en: "Professional villa, finca, and vacation rental cleaning service in southwest Mallorca: turnover cleans, deep cleans, laundry service, and linen management.",
      ca: "Servei professional de neteja de vil·les, finques i lloguers vacacionals al sud-ouest de Mallorca: canvis entre hostes i neteja a fons.",
      de: "Professioneller Reinigungsservice für Villen, Fincas und Ferienunterkünfte im Südwesten Mallorcas: Gästewechselreinigung, Grundreinigung und Wäscheservice.",
    },
    fullDescription: {
      es: "Empresa especializada en limpieza de villas y fincas de alquiler vacacional en las zonas de mayor demanda del suroeste: Calvià, Portals Nous, Puerto Portals, Camp de Mar, Andratx y Santa Ponsa. Equipo de 35 profesionales con vehículos propios. Coordinación directa con las principales plataformas de alquiler.",
      en: "Specialised villa and vacation finca cleaning for the southwest's highest-demand areas: Calvià, Portals Nous, Puerto Portals, Camp de Mar, Andratx, and Santa Ponsa. Team of 35 professionals with own vehicles and direct coordination with major rental platforms.",
      ca: "Especialitzada en neteja de vil·les a les zones de major demanda: Calvià, Portals Nous, Puerto Portals i Santa Ponsa. Equip de 35 professionals amb vehicles propis.",
      de: "Spezialisiert auf die meistgefragten Gebiete im Südwesten: Calvià, Portals Nous, Puerto Portals, Camp de Mar, Andratx und Santa Ponsa. 35-köpfiges Team mit eigenem Fuhrpark.",
    },
    highlights: {
      es: [
        "Equipo de 35 limpiadores profesionales con formación en hospitalidad y villas de lujo",
        "Servicio de lavandería propio con planchado y doblado con estándares hoteleros",
        "Coordinación directa con Airbnb, HomeAway y agencias inmobiliarias locales",
        "Certificado de calidad limpieza COVID-enhanced con productos desinfectantes homologados",
      ],
      en: [
        "Team of 35 professional cleaners trained in hospitality and luxury villa standards",
        "Own laundry service with hotel-standard ironing and folding",
        "Direct coordination with Airbnb, HomeAway, and local real estate agencies",
        "COVID-enhanced cleaning quality certification with approved disinfectant products",
      ],
      ca: [
        "35 nets professionals amb formació en hoteleria i vil·les de luxe",
        "Servei de bugaderia propi amb planxat i doblegat d'estàndard hoteler",
        "Coordinació directa amb Airbnb, HomeAway i agències locals",
        "Certificació de qualitat neteja COVID-enhanced",
      ],
      de: [
        "35 professionell ausgebildete Reinigungskräfte nach Hospitality- und Luxusvilla-Standard",
        "Eigener Wäscheservice mit Bügeln und Falten nach Hotelstandard",
        "Direkte Koordination mit Airbnb, HomeAway und lokalen Immobilienagenturen",
        "COVID-erweiterte Reinigungszertifizierung mit zugelassenen Desinfektionsmitteln",
      ],
    },
    servicesProvided: {
      es: [
        "Limpieza de cambio entre huéspedes con cambio de sábanas y toallas",
        "Limpieza a fondo de fin de temporada para villas y fincas de alquiler",
        "Servicio de lavandería: lavado, secado, planchado y doblado de ropa de cama",
        "Reporte fotográfico post-limpieza con inventario de estado de la villa",
      ],
      en: [
        "Guest turnover cleaning with fresh bed linen and towel change",
        "End-of-season deep clean for rental villas and fincas",
        "Laundry service: washing, drying, ironing, and folding of bed linen",
        "Post-clean photographic report with villa condition inventory",
      ],
      ca: [
        "Neteja de canvi entre hostes amb canvi de llençols i tovalloles",
        "Neteja a fons de fi de temporada",
        "Servei de bugaderia: rentat, assecatge i planxat de roba de llit",
        "Informe fotogràfic post-neteja amb inventari de la vil·la",
      ],
      de: [
        "Gästewechselreinigung mit frischer Bettwäsche und Handtüchern",
        "Saisonabschluss-Grundreinigung für Mietvillen und Fincas",
        "Wäscheservice: Waschen, Trocknen, Bügeln und Falten von Bettwäsche",
        "Fotobericht nach Reinigung mit Inventarzustand der Villa",
      ],
    },
  },

  // ── 5. FORMACIÓN & ESCUELAS INTERNACIONALES ──
  {
    slug: "ies-mallorca-international-school-palma-british",
    name: "Mallorca International School Colegio Británico Palma (IES)",
    category: "escuelas-internacionales",
    sectorFolder: "educacion-formacion",
    sectorArrayName: "EDUCACION_SERVICES",
    subcategories: ["colegio-britanico-mallorca", "ib-bachillerato-internacional", "primaria-secundaria-ingles"],
    zone: "palma",
    address: "Carrer del General Riera, 71, 07010 Palma",
    coordinates: { lat: 39.5841, lng: 2.6567 },
    rating: 4.9,
    reviewCount: 287,
    priceRange: "€€€€",
    phone: "+34 971 799 800",
    website: "https://mallorcainternationalschool.com",
    schedule: "Lunes a Viernes: 08:00 - 17:00 (Septiembre a Junio)",
    tags: ["zona:palma-centro", "product:premium", "mod:cita-previa"],
    shortDescription: {
      es: "Colegio internacional de currículo británico (Cambridge) e IB en Palma: educación bilingüe español-inglés desde nursery hasta A-Levels, con acreditación CIE de Cambridge y acceso directo a universidades del Reino Unido y Estados Unidos.",
      en: "British curriculum (Cambridge) and IB international school in Palma: bilingual Spanish-English education from nursery through A-Levels, CIE Cambridge accredited with direct pathways to UK and US universities.",
      ca: "Col·legi internacional de currículum britànic (Cambridge) i IB a Palma: educació bilingüe espanyol-anglès des de nursery fins a A-Levels amb acreditació CIE de Cambridge.",
      de: "Britisches Lehrplanzentrum (Cambridge) und IB-Internationale Schule in Palma: zweisprachige Spanisch-Englisch-Ausbildung von der Nursery bis zu den A-Levels mit CIE Cambridge-Akkreditierung.",
    },
    fullDescription: {
      es: "El Mallorca International School ofrece una educación de excelencia a través del Cambridge Assessment International Education (CAIE) desde nursery (3 años) hasta los A-Levels (18 años). Cuenta con 450 alumnos de más de 45 nacionalidades, instalaciones deportivas completas, laboratorios STEM y un claustro de profesores nativos y bilingües.",
      en: "MIS offers Cambridge Assessment International Education (CAIE) excellence from nursery (age 3) to A-Levels (age 18). 450 students from 45+ nationalities, full sports facilities, STEM labs, and a faculty of native and bilingual teachers.",
      ca: "MIS ofereix educació d'excel·lència Cambridge des de nursery (3 anys) fins als A-Levels (18 anys). 450 alumnes de més de 45 nacionalitats, instal·lacions esportives i laboratoris STEM.",
      de: "MIS bietet Cambridge-CAIE-Exzellenz von der Nursery (3 Jahre) bis zu den A-Levels (18 Jahre). 450 Schüler aus 45+ Nationen, vollständige Sportanlagen, STEM-Labore und muttersprachliche Lehrer.",
    },
    highlights: {
      es: [
        "Acreditado por Cambridge Assessment International Education (CAIE)",
        "Currículo Cambridge desde EYFS hasta IGCSE y A-Levels con IB Diploma",
        "450 alumnos de más de 45 nacionalidades en un entorno multicultural",
        "Campus con instalaciones completas: piscina, pistas deportivas, teatro y laboratorios",
      ],
      en: [
        "Cambridge Assessment International Education (CAIE) accredited school",
        "Cambridge curriculum from EYFS through IGCSE and A-Levels with IB Diploma option",
        "450 students from 45+ nationalities in a multicultural environment",
        "Full campus: swimming pool, sports courts, theatre, and STEM laboratories",
      ],
      ca: [
        "Escola acreditada per Cambridge Assessment International Education (CAIE)",
        "Currículum Cambridge des d'EYFS fins a IGCSE i A-Levels amb Diploma IB",
        "450 alumnes de més de 45 nacionalitats",
        "Campus amb piscina, pistes esportives, teatre i laboratoris STEM",
      ],
      de: [
        "Cambridge Assessment International Education (CAIE) akkreditierte Schule",
        "Cambridge-Lehrplan von EYFS über IGCSE und A-Levels bis zum IB-Diplom",
        "450 Schüler aus 45+ Nationen in multikulturellem Umfeld",
        "Vollständiger Campus: Schwimmbad, Sportplätze, Theater und STEM-Labore",
      ],
    },
    servicesProvided: {
      es: [
        "Educación pre-escolar (Nursery y Reception, 3-5 años) en bilingüe español-inglés",
        "Primary School (6-11 años) con currículo Cambridge Primary y National Curriculum inglés",
        "Secondary School (12-16 años): Cambridge IGCSE en 10+ asignaturas",
        "Sexto Curso (16-18 años): A-Levels de Cambridge y opción de Diploma del Bachillerato Internacional (IB)",
      ],
      en: [
        "Pre-school education (Nursery and Reception, ages 3-5) in bilingual Spanish-English",
        "Primary School (ages 6-11) with Cambridge Primary and English National Curriculum",
        "Secondary School (ages 12-16): Cambridge IGCSE in 10+ subjects",
        "Sixth Form (ages 16-18): Cambridge A-Levels and International Baccalaureate (IB) Diploma option",
      ],
      ca: [
        "Educació preescolar (Nursery i Reception, 3-5 anys) bilingüe",
        "Primary School (6-11 anys) amb currículum Cambridge Primary",
        "Secondary School (12-16 anys): Cambridge IGCSE",
        "Sisè Curs (16-18 anys): A-Levels de Cambridge i opció Diploma IB",
      ],
      de: [
        "Vorschulische Bildung (Nursery und Reception, 3-5 Jahre) zweisprachig Spanisch-Englisch",
        "Primary School (6-11 Jahre) mit Cambridge Primary und Nationalcurriculum",
        "Secondary School (12-16 Jahre): Cambridge IGCSE in 10+ Fächern",
        "Sixth Form (16-18 Jahre): Cambridge A-Levels und IB-Diplom-Option",
      ],
    },
  },
];

console.log("Ingesting Batch 12 of 5 verified businesses...");
ingestBatch(BATCH_12);
