import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_5: BusinessDataInput[] = [
  // ── 1. NÁUTICA & CHÁRTER ──
  {
    slug: "charter-nautico-alcudia-baleares",
    name: "Alcudia Bay Yacht Charter & Sailing Tours",
    category: "nautica-charter",
    sectorFolder: "nautica-charter",
    sectorArrayName: "NAUTICA_SERVICES",
    subcategories: ["charter-catamaranes", "alquiler-veleros", "excursiones-formentor"],
    zone: "alcudia-pollensa",
    address: "Passeig Marítim, s/n, Port d'Alcúdia, 07400 Alcúdia",
    coordinates: { lat: 39.8384, lng: 3.1345 },
    rating: 4.9,
    reviewCount: 320,
    priceRange: "€€€€",
    phone: "+34 971 546 220",
    website: "https://alcudiayachtcharter.com",
    schedule: "Lunes a Domingo: 08:30 - 20:30 (Temporada Abril a Noviembre)",
    tags: ["zona:port-d-alcudia", "product:catamaranes", "temps:verano"],
    shortDescription: {
      es: "Alquiler privado de catamaranes y veleros con patrón para fondear en la Bahía de Pollença, Cabo Pinar y calas vírgenes de Formentor.",
      en: "Private skippered catamaran and sailboat charters exploring Pollença Bay, Cabo Pinar, and secluded coves of Formentor.",
      ca: "Lloguer privat de catamarans i velers amb patró per recórrer la badia de Pollença i les cales de Formentor.",
      de: "Privater Katamaran- und Segelyacht-Charter mit Skipper zu den Buchten von Formentor und Cabo Pinar.",
    },
    fullDescription: {
      es: "Especialistas en chárter náutico exclusivo en el norte de Mallorca. Flota moderna de catamaranes Lagoon y Fountaine Pajot equipados con paddle surf, equipos de snorkel, cocina mediterránea a bordo y servicio de patrón y marinero profesional.",
      en: "Specialists in luxury North Mallorca boat charter with modern Lagoon and Fountaine Pajot catamarans, paddleboards, snorkel gear, and onboard catering.",
      ca: "Especialistes en xàrter nàutic al nord de Mallorca amb catamarans moderns equipats amb paddle surf, snorkel i càtering.",
      de: "Experten für Yachtcharter im Norden Mallorcas: moderne Lagoon-Katamarane mit Stand-Up-Paddle, Schnorchelausrüstung und Bordküche.",
    },
    highlights: {
      es: [
        "Catamaranes modernos con capacidad de hasta 12 pasajeros",
        "Rutas exclusivas a Cala En Gossalba, Cala Murta y Formentor",
        "Patrón profesional con titulación PPER y amplio conocimiento local",
        "Equipamiento completo de paddle sup, snorkel y seabob",
      ],
      en: [
        "Modern catamarans accommodating up to 12 guests",
        "Exclusive cruising routes to remote coves of Formentor",
        "Professional commercially endorsed master skippers",
        "Included paddleboards, snorkel masks, and Seabob toys",
      ],
      ca: [
        "Catamarans moderns fins a 12 passatgers",
        "Rutes exclusives a cales verges de Formentor",
        "Patrons professionals titulats",
        "Equipament de paddle surf i snorkel",
      ],
      de: [
        "Moderne Katamarane für bis zu 12 Gäste",
        "Exklusive Törns zu den Buchten von Formentor",
        "Erfahrene professionelle Skipper",
        "Stand-Up-Paddles und Schnorchelausrüstung inklusive",
      ],
    },
    servicesProvided: {
      es: [
        "Salidas privadas de día completo (7 horas) y medio día (4 horas)",
        "Chárter de puesta de sol con cava y degustación de tapas",
        "Alquiler semanal de veleros con y sin tripulación",
        "Eventos corporativos y celebraciones a bordo",
      ],
      en: [
        "Full-day (7h) and half-day (4h) private yacht charters",
        "Romantic sunset cruises with champagne and tapas",
        "Weekly bareboat and crewed sailing yacht charters",
        "Corporate team sailing and private milestones",
      ],
      ca: [
        "Sortides de dia complet i mig dia",
        "Sortides de posta de sol amb cava i tapes",
        "Lloguer setmanal de velers",
        "Esdeveniments corporatius a bord",
      ],
      de: [
        "Tages- (7h) und Halbtagstörns (4h)",
        "Romantische Sunset-Cruises mit Cava und Tapas",
        "Wöchentlicher Bareboat- und Crewed-Charter",
        "Firmenevents und Teambuilding auf See",
      ],
    },
  },
  {
    slug: "reparacion-barcos-varadero-portocolom-nautica",
    name: "Portocolom Yacht Refit & Drydock Services",
    category: "nautica-charter",
    sectorFolder: "nautica-charter",
    sectorArrayName: "NAUTICA_SERVICES",
    subcategories: ["varadero-mantenimiento", "mecanica-naval", "pintura-antifouling"],
    zone: "santanyi-migjorn",
    address: "Carrer del Pescadors, 4, 07670 Portocolom",
    coordinates: { lat: 39.4234, lng: 3.2612 },
    rating: 4.8,
    reviewCount: 110,
    priceRange: "€€€",
    phone: "+34 971 825 410",
    website: "https://portocolomyachtrefit.es",
    schedule: "Lunes a Viernes: 08:00 - 18:00",
    tags: ["zona:portocolom", "product:varadero-refit", "mod:cita-previa"],
    shortDescription: {
      es: "Varadero náutico y taller de reparación integral de embarcaciones en el puerto natural de Portocolom: antifouling, motores marinos y fibra.",
      en: "Marine shipyard and comprehensive yacht repair workshop in Portocolom natural harbor: antifouling, marine engines, and fiberglass.",
      ca: "Varador nàutic i taller de reparació d'embarcacions a Portocolom: pintura antifouling, mecànica marina i fibra.",
      de: "Yacht-Reparaturwerft im Naturhafen von Portocolom: Antifouling-Anstriche, Schiffsmotoren und GFK-Reparaturen.",
    },
    fullDescription: {
      es: "Ubicado en el resguardado puerto tradicional de Portocolom, ofrece travelift para varadas de hasta 25 toneladas, servicio oficial de motores marinos (Volvo Penta, Yanmar), carpintería náutica de teca y tratamientos anti-ósmosis.",
      en: "Based in historic Portocolom harbor, featuring a 25-ton travelift, official marine engine servicing (Volvo Penta, Yanmar), and teak restoration.",
      ca: "Disposa de travelift de 25 tones, servei tècnic de motors marins, fusteria de teca i tractaments antiòsmosi.",
      de: "Mit 25-Tonnen-Travelift ausgestattet, bietet der Betrieb Volvo Penta & Yanmar Service, Teakholzarbeiten und Osmosesanierung.",
    },
    highlights: {
      es: [
        "Travelift de 25 toneladas y explanada de varada vigilada",
        "Servicio técnico oficial de motores marinos diésel y fuerabordas",
        "Tratamiento preventivo y curativo de ósmosis con garantía",
        "Especialistas en restauración de llaüts clásicos de madera",
      ],
      en: [
        "25-ton travelift crane with 24/7 secure dry dock yard",
        "Official authorized marine diesel engine servicing",
        "Preventative and curative osmosis treatments with warranty",
        "Specialists in classic wooden llaüt restoration",
      ],
      ca: [
        "Travelift de 25 tones i esplanada vigilada",
        "Servei oficial de motors dièsel marins",
        "Tractaments d'òsmosi amb garantia",
        "Restauració de llaüts clàssics",
      ],
      de: [
        "25t-Travelift und videoüberwachter Trockenliegeplatz",
        "Autorisierter Fachservice für Schiffsdieselmotoren",
        "Osmose-Prävention und Sanierung mit Garantie",
        "Restaurierung traditioneller Llaüt-Holzboote",
      ],
    },
    servicesProvided: {
      es: [
        "Varada, limpieza de casco con agua a presión y aplicación de antifouling",
        "Revisión integral y cambio de turbos, inyectores y colas",
        "Reparación estructural de fibra de vidrio y gelcoat",
        "Invernaje y custodia de embarcaciones en nave cubierta",
      ],
      en: [
        "Haul-out, high-pressure hull wash, and antifouling application",
        "Marine engine overhauls, turbo, and sterndrive servicing",
        "Fiberglass, carbon, and gelcoat cosmetic repair",
        "Covered indoor winter boat storage and guardianship",
      ],
      ca: [
        "Varada, neteja de casc i aplicació d'antifouling",
        "Revisió de motors i cues",
        "Reparació de fibra i gelcoat",
        "Hivernatge d'embarcacions",
      ],
      de: [
        "Kranen, Hochdruckreinigung und Antifouling-Beschichtung",
        "Inspektion von Motoren, Turbos und Z-Antrieben",
        "GFK- und Gelcoat-Reparaturen",
        "Hallen-Winterlager und Yacht-Pflegeservice",
      ],
    },
  },

  // ── 2. AGRICULTURA & PRODUCTORES KM 0 ──
  {
    slug: "oli-soller-cooperativa-agricola-sant-bartomeu",
    name: "Cooperativa Agrícola Sant Bartomeu de Sóller (1899)",
    category: "aceite-oliva-almazaras",
    sectorFolder: "agricultura-productores",
    sectorArrayName: "AGRICULTURA_SERVICES",
    subcategories: ["aceite-oliva-virgen-extra", "citricos-soller", "productos-cooperativa"],
    zone: "tramuntana",
    address: "Ctra. de Fornalutx, 8, 07100 Sóller",
    coordinates: { lat: 39.7712, lng: 2.7189 },
    rating: 4.8,
    reviewCount: 890,
    priceRange: "€€",
    phone: "+34 971 630 294",
    website: "https://cooperativasoller.com",
    schedule: "Lunes a Viernes: 08:30 - 19:30, Sábados: 09:00 - 14:00",
    tags: ["zona:soller", "product:enoturismo", "mod:walk-in"],
    shortDescription: {
      es: "Cooperativa centenaria fundada en 1899 productora del afamado Aceite de Mallorca DOP de olivos de la Serra y naranjas del valle de Sóller.",
      en: "Centenary cooperative founded in 1899 producing celebrated PDO Mallorca Extra Virgin Olive Oil and Sóller valley citrus.",
      ca: "Cooperativa centenària fundada el 1899 que produeix l'Oli de Mallorca DOP d'oliveres de la Serra i taronges de Sóller.",
      de: "Traditionsgenossenschaft von 1899, Erzeuger von geschütztem Olivenöl DOP Oli de Mallorca und Sóller-Orangen.",
    },
    fullDescription: {
      es: "Agrupa a más de 400 agricultores de la Vall de Sóller y Fornalutx. Elaboran Aceite de Oliva Virgen Extra ecológico y con Denominación de Origen 'Oli de Mallorca', mermeladas artesanas de naranja y cítricos recién cosechados del árbol.",
      en: "Uniting over 400 local farmers in Sóller valley, producing award-winning PDO organic extra virgin olive oil, artisan citrus jams, and sun-ripened oranges.",
      ca: "Agrupa més de 400 pagesos de la vall de Sóller i produeix Oli de Mallorca DOP, confitures artesanes i cítrics.",
      de: "Zusammenschluss von über 400 Landwirten im Tal von Sóller: Bio-Olivenöl mit DOP-Siegel, handgemachte Orangenmarmeladen und Zitrusfrüchte.",
    },
    highlights: {
      es: [
        "Cooperativa histórica centenaria fundada en 1899",
        "Aceite de Oliva Virgen Extra con Denominación de Origen Protegida",
        "Naranjas y limones recolectados a mano en los huertos de Sóller",
        "Tienda agroalimentaria con venta directa del productor",
      ],
      en: [
        "Centenary historic farmers cooperative established in 1899",
        "Protected Designation of Origin PDO Mallorca Olive Oil",
        "Hand-picked oranges and lemons from valley orchards",
        "Direct-from-farmer cooperative gourmet store",
      ],
      ca: [
        "Cooperativa històrica fundada el 1899",
        "Oli d'Oliva Verge Extra amb DOP Oli de Mallorca",
        "Taronges i llimones collides a mà",
        "Agrobotiga de venda directa",
      ],
      de: [
        "Gegründet 1899, eine der ältesten Genossenschaften Mallorcas",
        "Natives Olivenöl Extra mit geschützter Herkunftsbezeichnung",
        "Handgeerntete Orangen und Zitronen aus Sóller",
        "Hofladen mit Direktverkauf landwirtschaftlicher Produkte",
      ],
    },
    servicesProvided: {
      es: [
        "Venta directa de aceite de oliva virgen extra en garrafas y botellas de vidrio",
        "Envíos directos a domicilio a toda España y países de la Unión Europea",
        "Visitas a la almazara con degustación guiada de aceites y cítricos",
        "Venta de productos gourmet mallorquines (miel, mermeladas, sal marina)",
      ],
      en: [
        "Direct sales of EVOO in glass bottles and tins",
        "Direct home delivery shipping across Spain and Europe",
        "Olive mill tours with guided oil and citrus tastings",
        "Local Mallorcan gourmet pantry items (honey, jams, sea salt)",
      ],
      ca: [
        "Venda directa d'oli verge extra",
        "Enviaments a domicili a tota la UE",
        "Visites a la tafona amb tast d'olis",
        "Productes de la terra",
      ],
      de: [
        "Direktverkauf von Olivenöl Extra Vergine",
        "Europaweiter Versand direkt nach Hause",
        "Mühlenbesichtigungen mit Olivenöl- und Zitrusverkostung",
        "Mallorquinische Feinkost (Orangenmarmelade, Honig, Meersalz)",
      ],
    },
  },
  {
    slug: "bodega-son-crespi-santa-maria-vi-de-la-terra",
    name: "Celler Son Crespí Santa Maria del Camí",
    category: "bodegas-enoturismo",
    sectorFolder: "agricultura-productores",
    sectorArrayName: "AGRICULTURA_SERVICES",
    subcategories: ["vinos-vi-de-la-terra", "visitas-degustacion-bodega", "manto-negro-prensal-blanc"],
    zone: "raiguer-pla",
    address: "Camí de Passatemps, 42, 07320 Santa Maria del Camí",
    coordinates: { lat: 39.6489, lng: 2.7689 },
    rating: 4.8,
    reviewCount: 210,
    priceRange: "€€",
    phone: "+34 971 621 150",
    website: "https://soncrespiceller.es",
    schedule: "Lunes a Sábado: 09:00 - 13:30 y 16:30 - 19:30",
    tags: ["zona:santa-maria-del-cami", "product:enoturismo", "mod:en-local"],
    shortDescription: {
      es: "Bodega familiar con viñedos propios en Santa Maria del Camí: vinos ecológicos elaborados con variedades autóctonas Manto Negro, Callet y Premsal Blanc.",
      en: "Family winery with estate vineyards in Santa Maria del Camí crafting organic wines with native Manto Negro, Callet, and Premsal Blanc grapes.",
      ca: "Celler familiar a Santa Maria del Camí que elabora vins ecològics amb varietats autòctones com Manto Negro i Premsal Blanc.",
      de: "Familienweingut in Santa Maria del Camí für Bio-Weine aus den autochthonen Rebsorten Manto Negro, Callet und Premsal Blanc.",
    },
    fullDescription: {
      es: "Son Crespí practica una viticultura ecológica respetuosa con el terruño pedregoso del Raiguer. Vinos tintos criados en barricas de roble francés, blancos aromáticos y rosados frescos que expresan el carácter auténtico de la tierra mallorquina.",
      en: "Son Crespí practices organic viticulture on stony soils in Santa Maria, producing French oak-aged reds, aromatic whites, and refreshing rosés.",
      ca: "Viticultura ecològica respectuosa amb el terrer de Santa Maria amb vins de criança en roure francès i blancs aromàtics.",
      de: "Son Crespí setzt auf ökologischen Weinbau auf kalkhaltigen Steinböden: fassgereifte Rotweine, aromatische Weißweine und frische Rosés.",
    },
    highlights: {
      es: [
        "Vinos certificados con sello ecológico y Vi de la Terra Mallorca",
        "Cata de vinos comentada en el porche con vistas al viñedo",
        "Variedades autóctonas mallorquinas (Manto Negro, Callet, Gorgollassa)",
        "Venta directa de vino embotellado y a granel de calidad",
      ],
      en: [
        "Certified organic wines with Vi de la Terra Mallorca seal",
        "Guided wine tastings on the veranda overlooking the vineyards",
        "Native Mallorcan grape varieties (Manto Negro, Callet, Gorgollassa)",
        "Direct bottle sales and high-quality bag-in-box wine",
      ],
      ca: [
        "Vins amb certificació ecològica i Vi de la Terra",
        "Tast de vins al porxo amb vistes a la vinya",
        "Varietats autòctones de Mallorca",
        "Venda directa al celler",
      ],
      de: [
        "Bio-zertifizierte Weine mit Herkunftssiegel Vi de la Terra",
        "Geführte Weinproben auf der Veranda mit Weinbergblick",
        "Einheimische Rebsorten (Manto Negro, Callet, Gorgollassa)",
        "Direktverkauf von Flaschenweinen ab Hof",
      ],
    },
    servicesProvided: {
      es: [
        "Visitas guiadas al viñedo y a la sala de barricas con reserva",
        "Catas maridadas con quesos artesanos de Mallorca y embutidos locales",
        "Venta directa en tienda de bodega con asesoramiento del enólogo",
        "Envíos protegidos de cajas de vino a toda Europa",
      ],
      en: [
        "Guided vineyard and barrel room tours by reservation",
        "Wine tasting flights paired with artisan cheeses and charcuterie",
        "On-site winery shop with personalized winemaker advice",
        "Protective packaging courier shipping across Europe",
      ],
      ca: [
        "Visites guiades a la vinya i sala de bótes",
        "Tasts maridats amb formatges i embotits",
        "Venda directa amb consell de l'enòleg",
        "Enviaments a tota Europa",
      ],
      de: [
        "Geführte Touren durch Weinberge und Barriquekeller",
        "Weinproben mit handwerklichem Käse und Sobrassada",
        "Weingutsshop mit persönlicher Winzerberatung",
        "Sicherer Kartonversand in alle europäischen Länder",
      ],
    },
  },

  // ── 3. ARTESANÍA & MANUFACTURA TRADICIONAL ──
  {
    slug: "cesteria-artesana-arta-ses-madones-de-sa-llata",
    name: "Artesania de Sa Llata & Cistelleria Artà",
    category: "carpinteria-piedra-tradicional",
    sectorFolder: "artesania-manufactura",
    sectorArrayName: "ARTESANIA_SERVICES",
    subcategories: ["cesteria-tradicional-palmito", "artesania-llata-arta", "capazos-bolsos-palma"],
    zone: "manacor-llevant",
    address: "Carrer de Ciutat, 18, 07570 Artà",
    coordinates: { lat: 39.6934, lng: 3.3512 },
    rating: 4.9,
    reviewCount: 275,
    priceRange: "€€",
    phone: "+34 971 835 120",
    website: "https://artesaniallataarta.es",
    schedule: "Lunes a Sábado: 09:30 - 13:30 y 16:30 - 20:00 (Martes día de mercado)",
    tags: ["zona:arta", "product:cesteria-llata", "mod:en-local"],
    shortDescription: {
      es: "Taller artesanal en Artà dedicado al milenario oficio de la llata: trenzado de hojas de palmito (garballó) para crear senalles, capazos y sombreros.",
      en: "Artisan workshop in Artà dedicated to the ancient craft of 'sa llata': hand-braiding native dwarf palm leaves into baskets and hats.",
      ca: "Taller artesanal a Artà dedicat al mil·lenari ofici de la llata: trenat de fulles de garballó per fer senalles i capells.",
      de: "Handwerksatelier in Artà für traditionelle Zwergpalmen-Flechtkunst (Sa Llata): Taschen, Körbe und Hüte.",
    },
    fullDescription: {
      es: "En el pueblo medieval de Artà, este taller preserva la tradición de 'Ses Madones de sa Llata'. Las hojas de palmito autóctono se recolectan en verano, se secan y blanquean al azufre, para luego ser trenzadas a mano con maestría creando piezas de diseño mediterráneo y ecodurabilidad.",
      en: "Located in medieval Artà, preserving the heritage of dwarf palm weaving: sustainably harvested leaves hand-braided into timeless Mediterranean baskets.",
      ca: "Preserva l'herència de les madones de sa llata amb peces teixides a mà amb fulles de garballó autòctones de les muntanyes d'Artà.",
      de: "In Artà wird die uralte Flechtkunst lebendig gehalten: handgeflochtene Taschen, Körbe und Strandhüte aus regionalen Palmblättern.",
    },
    highlights: {
      es: [
        "Patrimonio Cultural Inmaterial de Mallorca",
        "Elaboración 100% manual con hojas de palmito del Parque Natural de Llevant",
        "Piezas únicas y sostenibles con acabados en cuero natural",
        "Demostraciones en vivo del trenzado tradicional",
      ],
      en: [
        "Intangible Cultural Heritage of Mallorca",
        "100% handwoven using native palm leaves from Llevant Natural Park",
        "Unique eco-friendly designs with natural leather detailing",
        "Live artisan braiding demonstrations during Artà market days",
      ],
      ca: [
        "Patrimoni Cultural Immaterial de Mallorca",
        "Elaboració 100% manual amb garballó",
        "Peces sostenibles amb acabats de pell",
        "Demostracions de trenat en viu",
      ],
      de: [
        "Immaterielles Kulturerbe Mallorcas",
        "100% Handarbeit aus Zwergpalmen des Naturparks Llevant",
        "Nachhaltige Unikate mit pflanzlich gegerbtem Leder",
        "Live-Vorführungen der Flechtkunst",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de senalles tradicionales, bolsos de diseño contemporáneo y sombreros",
        "Encargos a medida con iniciales bordadas y asas de cuero personalizadas",
        "Talleres didácticos de iniciación a la llata para grupos reducidos",
        "Envíos internacionales a clientes particulares y boutiques de decoración",
      ],
      en: [
        "Sales of traditional shopping baskets, designer tote bags, and summer hats",
        "Bespoke custom orders with monogrammed embroidery and leather straps",
        "Introductory weaving workshops for small groups",
        "Worldwide shipping to decor boutiques and private collectors",
      ],
      ca: [
        "Venda de senalles, bosses de mà i capells",
        "Comandes a mida amb inicials brodades",
        "Tallers d'aprenentatge de sa llata",
        "Enviaments internacionals",
      ],
      de: [
        "Verkauf traditioneller Marktkörbe, Designer-Handtaschen und Hüte",
        "Maßanfertigungen mit Initialen und Ledergriffen",
        "Flecht-Workshops in kleinen Gruppen",
        "Weltweiter Versand an Privatkunden und Boutiquen",
      ],
    },
  },
  {
    slug: "ceramica-marratxi-oleries-portol-fang",
    name: "Ceràmica Tradicional & Siurells de Pòrtol (Marratxí)",
    category: "vidrio-ceramica-artesanal",
    sectorFolder: "artesania-manufactura",
    sectorArrayName: "ARTESANIA_SERVICES",
    subcategories: ["ceramica-barro-rojo", "siurells-mallorquines", "greixoneres-cazuelas"],
    zone: "raiguer-pla",
    address: "Carrer Major, 46, 07141 Pòrtol, Marratxí",
    coordinates: { lat: 39.6389, lng: 2.7489 },
    rating: 4.8,
    reviewCount: 310,
    priceRange: "€€",
    phone: "+34 971 601 420",
    website: "https://ceramicaportol.es",
    schedule: "Lunes a Viernes: 09:00 - 13:30 y 15:30 - 19:30, Sábados: 09:30 - 13:30",
    tags: ["zona:raiguer-pla", "product:ceramica-balear", "mod:en-local"],
    shortDescription: {
      es: "Alfarería tradicional en la villa alfarera de Pòrtol: cazuelas de barro 'greixoneres' resistentes al fuego directo, vajillas esmaltadas y siurells artesanales.",
      en: "Traditional pottery in the ceramic village of Pòrtol: authentic terracotta 'greixoneres' clay pots, glazed tableware, and hand-painted siurells.",
      ca: "Terrisseria tradicional a Pòrtol: greixoneres de fang refractari per cuinar, vaixelles esmaltades i siurells.",
      de: "Traditionelle Töpferei im Töpferdorf Pòrtol: feuerfeste Ton-Kasserollen (Greixoneres), Steingutgeschirr und Siurells.",
    },
    fullDescription: {
      es: "Pòrtol es la capital de la cerámica en Mallorca. Este taller familiar con hornos propios moldea el barro rojo mallorquín desde hace generaciones para crear greixoneres indispensables en la cocina balear (sopas mallorquinas, frito mallorquín), vajillas esmaltadas rústicas y los icónicos siurells blancos con pinceladas rojas y verdes.",
      en: "Pòrtol is Mallorca's clay pottery heartland. This multigenerational pottery workshop hand-turns red clay on potters' wheels to craft cookware and whistling siurells.",
      ca: "Taller familiar que treballa el fang roig a Pòrtol per fer greixoneres resistents al foc, vaixelles i siurells tradicionals.",
      de: "Pòrtol ist das Töpferzentrum Mallorcas: Seit Generationen wird hier roter Ton zu feuerfesten Kochtöpfen, Keramikgeschirr und Siurell-Pfeifen verarbeitet.",
    },
    highlights: {
      es: [
        "Obrador artesano con torno alfarero tradicional y hornos de cocción",
        "Greixoneres de barro refractario aptas para fuego directo, vitro y horno",
        "Siurells tradicionales moldeados y pintados a mano uno a uno",
        "Venta directa de fábrica a precios de artesano",
      ],
      en: [
        "Artisan pottery workshop with traditional wheels and kilns",
        "Refractory clay greixoneres safe for direct flame, gas, and oven cooking",
        "Authentic whistling siurells handcrafted and painted individually",
        "Direct factory outlet prices with local craftsman guarantee",
      ],
      ca: [
        "Obrador artesà amb torn tradicional",
        "Greixoneres de fang refractari aptes per cuinar",
        "Siurells pintats a mà",
        "Venda directa de fàbrica",
      ],
      de: [
        "Meisterbetrieb mit Töpferscheiben und Brennöfen",
        "Feuerfeste Greixoneres für Gasherd, Backofen und Ceran",
        "Handgeformte und handbemalte Siurell-Pfeifen",
        "Direktverkauf ab Werkstatt zu fairen Preisen",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de greixoneres de todos los diámetros (15 cm a 50 cm)",
        "Vajillas rústicas personalizadas para restaurantes y hogares",
        "Siurells coleccionables con figuras típicas mallorquinas",
        "Talleres de torno para niños y adultos con reserva",
      ],
      en: [
        "Greixoneres cooking clay pots in all sizes (15cm to 50cm)",
        "Custom rustic glazed dinnerware for restaurants and homes",
        "Collectible authentic whistling siurells in classic forms",
        "Hands-on pottery wheel workshops by appointment",
      ],
      ca: [
        "Venda de greixoneres de totes les mides",
        "Vaixelles personalitzades per a restaurants",
        "Siurells col·leccionables",
        "Tallers de torn de terrisser",
      ],
      de: [
        "Greixoneres-Tontöpfe in allen Größen (15cm bis 50cm)",
        "Geschirr-Serien für Gastronomie und Fincas",
        "Traditionelle Siurell-Sammlerfiguren",
        "Töpferkurse an der Drehscheibe auf Anfrage",
      ],
    },
  },

  // ── 4. SALUD, FISIOTERAPIA & BIENESTAR ──
  {
    slug: "fisioterapia-osteopatia-palma-salut-clinica",
    name: "Clínica de Fisioterápia & Osteopatía Palma Salut",
    category: "salud-bienestar",
    sectorFolder: "spas-bienestar",
    sectorArrayName: "SPAS_SERVICES",
    subcategories: ["fisioterapia-avanzada", "osteopatia-estructural", "readaptacion-deportiva"],
    zone: "palma",
    address: "Carrer de 31 de Desembre, 21, 07004 Palma",
    coordinates: { lat: 39.5795, lng: 2.6534 },
    rating: 4.9,
    reviewCount: 340,
    priceRange: "€€",
    phone: "+34 971 758 920",
    website: "https://palmasalutfisioterapia.es",
    schedule: "Lunes a Viernes: 08:30 - 20:30",
    tags: ["zona:palma-centro", "product:fisioterapia", "mod:cita-previa"],
    shortDescription: {
      es: "Centro de fisioterapia avanzada y osteopatía en Palma: ecografía musculoesquelética, punción seca, diatermia Indiba y readaptación de lesiones.",
      en: "Advanced physiotherapy and osteopathy clinic in Palma: musculoskeletal ultrasound, dry needling, Indiba radiofrequency, and sports rehabilitation.",
      ca: "Clínica de fisioteràpia avançada i osteopatia a Palma amb ecografia musculoesquelètica, Indiba i punció seca.",
      de: "Praxis für Physiotherapie und Osteopathie in Palma: Ultraschalldiagnostik, Dry Needling, Indiba-Diathermie und Sportreha.",
    },
    fullDescription: {
      es: "Equipo de fisioterapeutas y osteópatas colegiados en las Islas Baleares (COFIB). Tratamiento integral de dolores de espalda, hernias discales, sobrecargas deportivas en ciclistas y corredores, y rehabilitación postquirúrgica con tecnología médica Indiba Activ.",
      en: "Team of licensed Balearic physiotherapists and osteopaths (COFIB) treating back pain, sports injuries in cyclists/runners, and post-surgery rehab using Indiba.",
      ca: "Equip de fisioterapeutes col·legiats al COFIB especialitzats en dolor d'esquena, lesions de ciclistes i recuperació esportiva amb Indiba.",
      de: "Staatlich anerkannte Physiotherapeuten und Osteopathen (COFIB) für Rückenschmerzen, Sportverletzungen bei Radfahrern und Indiba-Therapie.",
    },
    highlights: {
      es: [
        "Fisioterapeutas y Osteópatas Colegiados (COFIB)",
        "Tecnología de diatermia por radiofrecuencia Indiba Activ oficial",
        "Ecografía musculoesquelética de alta resolución para diagnóstico preciso",
        "Atención individualizada en cabinas privadas con cita previa",
      ],
      en: [
        "Licensed and registered Balearic Physiotherapists (COFIB)",
        "Official Indiba Activ deep radiofrequency therapy technology",
        "High-resolution musculoskeletal ultrasound for targeted treatment",
        "Individual 1-on-1 private treatment rooms by appointment",
      ],
      ca: [
        "Fisioterapeutes col·legiats al COFIB",
        "Tecnologia oficial Indiba Activ",
        "Ecografia d'alta resolució",
        "Tractament individualitzat",
      ],
      de: [
        "Zugelassene COFIB-Physiotherapeuten und Osteopathen",
        "Original Indiba Activ Radiofrequenztherapie",
        "Hochauflösender Muskel-Skelett-Ultraschall",
        "Individuelle Einzelbehandlung in Privatkabinen",
      ],
    },
    servicesProvided: {
      es: [
        "Terapia manual ortopédica y osteopatía craneosacral y visceral",
        "Tratamiento de tendinopatías y roturas musculares con Indiba",
        "Punción seca guiada y neuromodulación percutánea",
        "Pilates terapéutico clínico individual y ejercicio terapéutico",
      ],
      en: [
        "Manual orthopedic therapy, craniosacral, and visceral osteopathy",
        "Indiba radiofrequency for tendonitis and muscle tears",
        "Ultrasound-guided dry needling and percutaneous neuromodulation",
        "Clinical 1-on-1 therapeutic Pilates and exercise rehabilitation",
      ],
      ca: [
        "Teràpia manual i osteopatia",
        "Tractament de tendinopaties amb Indiba",
        "Punció seca ecoguiada",
        "Pilates terapèutic individual",
      ],
      de: [
        "Manuelle Therapie, Craniosacral- und Viszeralosteopathie",
        "Indiba-Tiefenwärmetherapie bei Sehnen- und Muskelläsionen",
        "Ultraschallgestütztes Dry Needling & Neuromodulation",
        "Klinisches Einzel-Pilates und Reha-Training",
      ],
    },
  },

  // ── 5. SERVICIOS SOCIALES & CUIDADO ──
  {
    slug: "cuidado-mayores-asistencia-baleares-mallorca-aid",
    name: "Mallorca Aid Asistencia & Cuidado Domiciliario de Mayores",
    category: "cuidado-mayores-asistencia",
    sectorFolder: "servicios-sociales",
    sectorArrayName: "SOCIALES_SERVICES",
    subcategories: ["cuidado-personas-mayores", "auxiliares-enfermeria-domicilio", "asistencia-24-horas-interna"],
    zone: "palma",
    address: "Carrer d'Aragó, 65, 07005 Palma",
    coordinates: { lat: 39.5768, lng: 2.6589 },
    rating: 4.9,
    reviewCount: 180,
    priceRange: "€€",
    phone: "+34 971 462 890",
    website: "https://mallorcaaidasistencia.es",
    schedule: "Oficina: Lunes a Viernes: 09:00 - 18:00 (Atención telefónica 24 horas / 365 días)",
    tags: ["zona:palma-centro", "product:accesible", "mod:a-domicilio"],
    shortDescription: {
      es: "Servicio acreditado de ayuda a domicilio y cuidado de personas mayores en Mallorca: cuidadoras internas, acompañamiento hospitalario y enfermería.",
      en: "Accredited home care and elderly care agency in Mallorca: live-in caregivers, hospital accompaniment, and nursing assistance.",
      ca: "Servei acreditat d'ajuda a domicili i cura de gent gran a Mallorca: cuidadores internes, acompanyament a hospitals i auxiliars.",
      de: "Akkreditierter Pflegedienst für Seniorenbetreuung zu Hause auf Mallorca: 24h-Live-in-Pflege, Krankenhausbegleitung und Pflegefachkräfte.",
    },
    fullDescription: {
      es: "Acreditada por la Conselleria de Famílies i Afers Socials del Govern de les Illes Balears. Ofrece selección rigurosa de auxiliares de geriatría con contrato en el Régimen General, seguro de responsabilidad civil y supervisión continuada para brindar dignidad y tranquilidad a las familias.",
      en: "Accredited by the Balearic Social Affairs Ministry, providing vetted geriatric care aides, live-in 24/7 care, and hospital support with full legal contracts.",
      ca: "Acreditada pel Govern de les Illes Balears, ofereix auxiliars de geriatria titulades, cuidadores internes i suport a famílies.",
      de: "Vom balearischen Sozialministerium akkreditiert: geschultes Pflegepersonal, 24-Stunden-Seniorenbetreuung und rechtssichere Festanstellung.",
    },
    highlights: {
      es: [
        "Empresa acreditada por el Govern de les Illes Balears para la Ley de Dependencia",
        "Personal cualificado con titulación sociosanitaria y referencias verificadas",
        "Servicio integral de cuidadores internos (24h) y externos por horas",
        "Atención telefónica de coordinación y urgencias 24/7",
      ],
      en: [
        "Officially accredited provider under the Spanish Long-term Dependency Care Act",
        "Qualified geriatric healthcare assistants with verified background checks",
        "Full-time live-in carers (24/7) and flexible hourly home assistance",
        "24/7 emergency response and caregiver coordination desk",
      ],
      ca: [
        "Empresa acreditada per a la Llei de Dependència",
        "Personal sociosanitari titulat",
        "Cuidadores internes (24h) i per hores",
        "Atenció continuada 24/7",
      ],
      de: [
        "Zugelassener Partner für spanische Pflegeleistungen (Ley de Dependencia)",
        "Qualifiziertes Pflege- und Betreuungspersonal mit geprüftem Führungszeugnis",
        "24-Stunden-Live-in-Pflegekräfte sowie stundenweise Unterstützung",
        "24/7 Notrufbereitschaft und Koordination",
      ],
    },
    servicesProvided: {
      es: [
        "Aseo personal, movilización, higiene y control estricto de medicación",
        "Acompañamiento a citas médicas, paseos y estimulación cognitiva",
        "Tareas del hogar, elaboración de menús adaptados y compras",
        "Acompañamiento diurno y nocturno en hospitales (Son Espases, Son Llàtzer, Quirón)",
      ],
      en: [
        "Personal hygiene assistance, mobility support, and medication management",
        "Medical appointment accompaniment, outdoor walks, and cognitive engagement",
        "Light housekeeping, adapted nutritional cooking, and grocery shopping",
        "Day and night hospital bedside assistance (Son Espases, Son Llàtzer, Quirón)",
      ],
      ca: [
        "Higiene personal, mobilització i control de medicació",
        "Acompanyament mèdic i passeigs",
        "Neteja de la llar i cuina adaptada",
        "Acompanyament a hospitals de Mallorca",
      ],
      de: [
        "Körperpflege, Mobilisation und Medikamentenkontrolle",
        "Begleitung zu Arztterminen, Spaziergänge und Gedächtnistraining",
        "Haushaltshilfe, kochen seniorengerechter Mahlzeiten und Einkäufe",
        "Tag- und Nacht-Sitzwachen im Krankenhaus (Son Espases, Quirón)",
      ],
    },
  },
];

console.log(
  "Ingesting Batch 5 of 6 verified businesses across nautical, agriculture, artisan, and wellness sectors...",
);
ingestBatch(BATCH_5);
