import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_8: BusinessDataInput[] = [
  // ── 1. ALOJAMIENTO & TURISMO ──
  {
    slug: "gran-hotel-son-net-puigpunyent-palacio",
    name: "Gran Hotel Son Net Palacio Histórico Puigpunyent (1672)",
    category: "hoteles-boutique-agroturismo",
    sectorFolder: "alojamiento-turismo",
    sectorArrayName: "ALOJAMIENTO_SERVICES",
    subcategories: ["hotel-palacio-lujo", "restaurante-estrella", "spa-vistas-montana"],
    zone: "tramuntana",
    address: "Carrer del Castillo de Son Net, s/n, 07194 Puigpunyent",
    coordinates: { lat: 39.6224, lng: 2.5278 },
    rating: 4.9,
    reviewCount: 520,
    priceRange: "€€€€",
    phone: "+34 971 147 000",
    website: "https://sonnetpalacehotel.com",
    schedule: "Recepción 24 horas (Abierto todo el año)",
    tags: ["zona:puigpunyent", "product:lujo", "temps:todo-el-ano"],
    shortDescription: {
      es: "Palacio histórico señorial del siglo XVII restaurado como hotel de gran lujo en Puigpunyent: piscina de 30 metros, viñedo propio y arte clásico.",
      en: "Restored 17th-century historic aristocratic palace hotel in Puigpunyent: 30-meter pool, estate vineyard, and museum-grade fine art.",
      ca: "Palau senyorial històric del segle XVII a Puigpunyent amb piscina de 30 metres, vinya pròpia i col·lecció d'art.",
      de: "Historischer Adelspalast aus dem 17. Jh. in Puigpunyent: 30-Meter-Pool, eigener Weinberg und klassische Kunstsammlung.",
    },
    fullDescription: {
      es: "Situado sobre una colina con vistas al valle de Puigpunyent y al monte Galatzó, Son Net es un santuario de refinamiento. Alberga una prensa de aceite de oliva del siglo XVII restaurada como restaurante, cabañas privadas junto a la piscina y suites decoradas con vigas de madera noble y azulejos artesanales.",
      en: "Perched on a hilltop overlooking Puigpunyent valley and Mount Galatzó, featuring a historic 17th-century olive press restaurant and luxury private pool cabanas.",
      ca: "Sobre un turó a Puigpunyent, Son Net ofereix una premsa d'oli del segle XVII convertida en restaurant i suites amb bigues de fusta noble.",
      de: "Auf einem Hügel in Puigpunyent mit Blick auf den Berg Galatzó: Historische Olivenölmühle als Restaurant, Luxus-Cabanas und edle Suiten.",
    },
    highlights: {
      es: [
        "Palacio señorial de 1672 con capilla privada y almazara histórica",
        "Piscina exterior monumental de 30 metros rodeada de cabañas privadas",
        "Viñedo privado de Malvasía con producción de vino propio",
        "Colección privada de arte con obras originales de Chagall y Warhol",
      ],
      en: [
        "Historic 1672 aristocratic palace with private chapel and olive press",
        "Monumental 30-meter outdoor pool framed by private cabanas",
        "Estate Malvasia vineyard producing proprietary wines",
        "Private art collection featuring works by Chagall, Frank Stella, and Warhol",
      ],
      ca: [
        "Palau de 1672 amb capella i tafona històrica",
        "Piscina de 30 metres amb cabanyes privades",
        "Vinya pròpia de Malvasia",
        "Col·lecció d'art clàssic i contemporani",
      ],
      de: [
        "Adelspalast von 1672 mit Schlosskapelle und historischer Ölmühle",
        "30-Meter-Panoramapool mit privaten Liege-Cabanas",
        "Eigenes Malvasia-Weingut mit Finca-Weinverkostung",
        "Exklusive Kunstsammlung mit Originalen von Chagall und Warhol",
      ],
    },
    servicesProvided: {
      es: [
        "Alojamiento en suites palaciegas con chimenea y terraza panorámica",
        "Alta gastronomía mediterránea en el restaurante 'Mar&Duix'",
        "Tratamientos wellness y spa con cosmética termal y masajes botánicos",
        "Catas privadas de vino en la bodega histórica del palacio",
      ],
      en: [
        "Palatial suite accommodation with fireplaces and private garden verandas",
        "Fine Mediterranean dining at signature restaurant 'Mar&Duix'",
        "Wellness spa treatments using botanical and thermal skincare",
        "Private wine tastings in the palace's historic vaulted cellars",
      ],
      ca: [
        "Suites senyorials amb llar de foc i terrassa",
        "Alta cuina mediterrània al restaurant 'Mar&Duix'",
        "Spa i tractaments de benestar botànics",
        "Tasts de vi al celler del palau",
      ],
      de: [
        "Übernachtung in Palast-Suiten mit Kamin und Panoramablick",
        "Gehobene mediterrane Küche im Restaurant 'Mar&Duix'",
        "Wellness-Spa mit balearischen Pflanzen-Extrakten",
        "Private Weinproben im historischen Gewölbekeller",
      ],
    },
  },

  // ── 2. RETAIL & JOYERÍA DE AUTOR ──
  {
    slug: "joyeria-artesana-isabel-guarch-palma",
    name: "Isabel Guarch Alta Joyería & Diseño Mediterráneo Palma",
    category: "boutiques-moda-mallorca",
    sectorFolder: "retail-comercio",
    sectorArrayName: "RETAIL_SERVICES",
    subcategories: ["joyeria-autor-oro", "diseno-joyas-mallorca", "perlas-australianas-tahiti"],
    zone: "palma",
    address: "Plaça del Mercat, 16, 07001 Palma",
    coordinates: { lat: 39.5718, lng: 2.6489 },
    rating: 4.9,
    reviewCount: 310,
    priceRange: "€€€€",
    phone: "+34 971 284 785",
    website: "https://isabelguarchjoyas.com",
    schedule: "Lunes a Sábado: 10:30 - 20:00",
    tags: ["zona:palma-centro", "product:joyeria-artesanal", "mod:walk-in"],
    shortDescription: {
      es: "Firma de alta joyería mediterránea en la Plaça del Mercat de Palma inspirada en la arquitectura, la Cruz de Calatrava y los fondos marinos de Mallorca.",
      en: "Iconic Mediterranean fine jewelry atelier in Palma's Plaça del Mercat inspired by Balearic history, heritage crosses, and sea corals.",
      ca: "Joieria d'autor a la Plaça del Mercat de Palma inspirada en la història, l'arquitectura i el mar de Mallorca.",
      de: "Renommierte balearische Schmuckdesignerin am Plaça del Mercat in Palma: handgefertigter Goldschmuck inspiriert von Mallorcas Kultur.",
    },
    fullDescription: {
      es: "Con más de 30 años de trayectoria, la diseñadora mallorquina Isabel Guarch crea colecciones icónicas en oro de 18 quilates, diamantes éticos y perlas naturales. Sus piezas rinden homenaje a la cultura balear (colección Formentor, Vents, Nostra) con elegancia atemporal.",
      en: "With over 30 years of design heritage, Isabel Guarch crafts fine 18k gold, ethical diamonds, and natural pearls celebrating Mallorcan roots.",
      ca: "Més de 30 anys creant col·leccions en or de 18 quirats, diamants i perles que reten homenatge a la cultura de l'illa.",
      de: "Seit über 30 Jahren kreiert Isabel Guarch edlen Schmuck aus 18-Karat-Gold, konfliktfreien Diamanten und Zuchtperlen mit balearischer Seele.",
    },
    highlights: {
      es: [
        "Diseño 100% de autor inspirado en el patrimonio de Mallorca",
        "Metales nobles: Oro de 18K reciclado y plata de ley 925",
        "Gemas naturales certificadas y perlas de los Mares del Sur",
        "Atelier propio para diseño a medida y joyas por encargo",
      ],
      en: [
        "100% signature designer jewelry inspired by Mallorcan heritage",
        "Noble metals: Recycled 18k yellow/white gold and 925 sterling silver",
        "Certified natural gemstones and South Sea cultured pearls",
        "Private custom atelier for bespoke fine jewelry commissions",
      ],
      ca: [
        "Disseny d'autor inspirat en Mallorca",
        "Or de 18 quirats i plata de llei",
        "Gemma naturals certificades i perles",
        "Atelier de joies a mida",
      ],
      de: [
        "Echtes Autoren-Schmuckdesign mit mallorquinischem Bezug",
        "18-Karat-Gold und 925er Sterlingsilber",
        "Zertifizierte Edelsteine und Südsee-Zuchtperlen",
        "Eigenes Atelier für individuelle Kundenanfertigungen",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de colecciones de alta joyería (pendientes, anillos, colgantes)",
        "Diseño y fabricación personalizada de anillos de compromiso y alianzas",
        "Transformación y modernización de joyas familiares antiguas",
        "Envíos asegurados a todo el mundo con estuche de lujo",
      ],
      en: [
        "Fine jewelry collections (earrings, cocktail rings, necklaces)",
        "Bespoke engagement ring and wedding band design service",
        "Redesign and modern upcycling of heirloom family jewelry",
        "Insured worldwide courier shipping in signature presentation boxes",
      ],
      ca: [
        "Venda de joieria d'alta gamma",
        "Anells de compromís i aliances a mida",
        "Transformació de joies familiars antigues",
        "Enviaments assegurats a tot el món",
      ],
      de: [
        "Verkauf exklusiver Schmuckkollektionen",
        "Maßanfertigung von Verlobungs- und Eheringen",
        "Umarbeitung und Modernisierung von Erbstücken",
        "Weltweiter Wertversand in Luxusetuis",
      ],
    },
  },

  // ── 3. AGRICULTURA & QUESERÍAS ARTESANAS KM 0 ──
  {
    slug: "queseria-artesana-son-jover-formatges-inca",
    name: "Formatges Son Jover Formatgeria Artesana Inca (1998)",
    category: "queserias-producto-km0",
    sectorFolder: "agricultura-productores",
    sectorArrayName: "AGRICULTURA_SERVICES",
    subcategories: ["queso-artesano-oveja-roja", "leche-cruda-ecologica", "formatge-mallorqui"],
    zone: "raiguer-pla",
    address: "Camí de Son Jover, s/n, 07300 Inca",
    coordinates: { lat: 39.7089, lng: 2.8934 },
    rating: 4.9,
    reviewCount: 340,
    priceRange: "€€",
    phone: "+34 971 504 120",
    website: "https://formatgessonjover.es",
    schedule: "Lunes a Sábado: 09:00 - 14:00 y 16:30 - 19:30",
    tags: ["zona:inca", "product:enoturismo", "mod:en-local"],
    shortDescription: {
      es: "Quesería artesana y ganadería ecológica en Inca productora de quesos de leche cruda de oveja roja mallorquina (ovella roja) y cabra autóctona.",
      en: "Artisan organic dairy in Inca crafting raw milk cheeses from endangered native red Mallorcan sheep (ovella roja) and local goats.",
      ca: "Formatgeria artesana i ramaderia ecològica a Inca que elabora formatges de llet crua d'ovella roja mallorquina i cabra.",
      de: "Traditionelle Bio-Käserei in Inca für Rohmilchkäse vom gefährdeten Roten Mallorquinischen Schaf (Ovella Roja) und Inselziegen.",
    },
    fullDescription: {
      es: "Son Jover es pionera en la recuperación de la raza autóctona ovella roja mallorquina criada en pastos ecológicos. Elaboran quesos semicurados y curados de leche cruda con corteza natural frotada en aceite de oliva y pimentón 'tap de cortí', requesón fresco (brossat) y yogures de granja.",
      en: "Son Jover champions the conservation of native red sheep pasture-grazed organically, producing raw-milk cured cheeses rubbed in paprika and EVOO.",
      ca: "Pionera en la recuperació de l'ovella roja mallorquina, elabora formatges semicurats i curats amb pebre bord tap de cortí i brossat fresc.",
      de: "Bio-Bauernhof mit Schaf- und Ziegenzucht: Handwerklicher Rohmilchkäse mit natürlicher Rinde (mit Tap de Cortí Paprika gerieben) und frischer Brossat-Quark.",
    },
    highlights: {
      es: [
        "Quesos con sello de Producción Ecológica y Artesanía Alimentaria de Baleares",
        "Leche cruda 100% de rebaño propio de oveja roja mallorquina en libertad",
        "Curación natural en cueva sobre tablas de madera noble",
        "Premios GourmetQuesos y World Cheese Awards",
      ],
      en: [
        "Certified Organic and Official Balearic Artisan Food Producer status",
        "100% raw milk from proprietary free-range native red sheep herds",
        "Aged naturally in traditional curing cellars on timber planks",
        "Awarded medals at GourmetQuesos and World Cheese Awards",
      ],
      ca: [
        "Producció Ecològica certificada",
        "Llet crua d'ovella roja mallorquina pròpia",
        "Maduració en cava sobre fusta",
        "Guardons nacionals i internacionals",
      ],
      de: [
        "Bio-zertifiziert und offizielles balearisches Lebensmittel-Handwerk",
        "100% Rohmilch von eigenen freilaufenden Roten Inselschafen",
        "Natürliche Höhlenreifung auf unbehandelten Holzbrettern",
        "Ausgezeichnet bei den World Cheese Awards",
      ],
    },
    servicesProvided: {
      es: [
        "Venta directa de quesos curados, semicurados, brossat y yogures ecológicos",
        "Visitas guiadas a la granja, sala de ordeño y quesería con reserva previa",
        "Tablas de degustación con maridaje de panes de xeixa y mermeladas",
        "Envíos refrigerados a domicilio a toda Mallorca y Península",
      ],
      en: [
        "Direct farm shop sales of cured cheese wheels, fresh brossat, and yogurts",
        "Guided farm tours visiting sheep pastures and the cheesemaking facility",
        "Cheese tasting boards paired with native xeixa bread and artisan jams",
        "Temperature-controlled courier home delivery across Mallorca and Spain",
      ],
      ca: [
        "Venda directa de formatges, brossat i iogurts",
        "Visites a la granja i formatgeria",
        "Tasts maridats amb pa de xeixa",
        "Enviaments refrigerats a domicili",
      ],
      de: [
        "Hofladen-Verkauf von Käselaiben, frischem Brossat und Joghurt",
        "Hofführungen mit Weide- und Käsereibesichtigung",
        "Käseverkostungen mit lokalem Xeixa-Brot und Chutneys",
        "Gekühlter Frischeversand inselweit und aufs spanische Festland",
      ],
    },
  },

  // ── 4. REFORMAS, ENERGÍA SOLAR & ELECTRICIDAD ──
  {
    slug: "energia-solar-fotovoltaica-balear-sun-palma",
    name: "Balear Sun Fotovoltaica & Energía Solar Palma",
    category: "reformas-hogar",
    sectorFolder: "reformas-construccion",
    sectorArrayName: "REFORMAS_SERVICES",
    subcategories: ["placas-solares-autoconsumo", "baterias-litio-acumulacion", "cargadores-coche-electrico"],
    zone: "palma",
    address: "Carrer del Gremi de Teixidors, 26, Son Castelló, 07009 Palma",
    coordinates: { lat: 39.6062, lng: 2.6698 },
    rating: 4.8,
    reviewCount: 280,
    priceRange: "€€€",
    phone: "+34 971 432 990",
    website: "https://balearsunsolar.es",
    schedule: "Lunes a Viernes: 08:00 - 18:30",
    tags: ["zona:palma-centro", "product:energia-solar-fotovoltaica", "mod:cita-previa"],
    shortDescription: {
      es: "Ingeniería e instalación de energía solar fotovoltaica para villas y empresas en Mallorca: paneles solares de alta eficiencia, baterías de litio y puntos de recarga VE.",
      en: "Solar PV engineering and installation for luxury villas and businesses in Mallorca: Tier-1 panels, lithium battery storage, and EV wallbox chargers.",
      ca: "Enginyeria i instal·lació d'energia solar fotovoltaica per a vil·les a Mallorca amb bateries de liti i carregadors de vehicles elèctrics.",
      de: "Photovoltaik-Ingenieurbetrieb für Villen und Fincas auf Mallorca: Hochleistungs-Solarmodule, Batteriespeicher und E-Auto-Ladestationen.",
    },
    fullDescription: {
      es: "Empresa instaladora autorizada en Baleares. Especialistas en proyectos de autoconsumo residencial con monitorización por app, sistemas aislados para fincas rústicas sin conexión a red (off-grid) y tramitación integral de subvenciones europeas Next Generation y bonificaciones de IBI.",
      en: "Licensed Balearic electrical & solar installer providing grid-tied and off-grid solar systems, battery storage, and full handling of EU NextGen subsidies.",
      ca: "Instal·ladors autoritzats especialitzats en autoconsum, finques aïllades de la xarxa i tramitació de subvencions del Govern Balear.",
      de: "Zertifizierter Fachbetrieb für netzgekoppelte Anlagen und autarke Finca-Inselanlagen (Off-Grid) mit Abwicklung aller balearischen Förderanträge.",
    },
    highlights: {
      es: [
        "Instaladores autorizados oficiales en Industria Baleares",
        "Paneles solares Tier-1 con garantía de producción de 25 años",
        "Baterías de litio de alto voltaje (Tesla Powerwall, Huawei, BYD)",
        "Gestión 'Llave en Mano' de subvenciones públicas y legalización",
      ],
      en: [
        "Official licensed electrical & photovoltaic engineering firm",
        "Tier-1 solar panels with 25-year manufacturer performance guarantee",
        "High-voltage lithium batteries (Tesla Powerwall, Huawei, BYD)",
        "Complete turnkey grant filing and town hall permit legalization",
      ],
      ca: [
        "Instal·ladors autoritzats d'Indústria",
        "Plafons solars Tier-1 amb 25 anys de garantia",
        "Bateries de liti Tesla i Huawei",
        "Gestió de subvencions públiques",
      ],
      de: [
        "Zugelassener Fachbetrieb für erneuerbare Energien",
        "Tier-1 Solarmodule mit 25 Jahren Leistungsgarantie",
        "Lithium-Speichersysteme (Tesla Powerwall, Huawei, BYD)",
        "Schlüsselfertige Abwicklung inklusive Behördengenehmigung",
      ],
    },
    servicesProvided: {
      es: [
        "Estudio solar y diseño 3D personalizado sin compromiso",
        "Instalación de paneles solares fotovoltaicos sobre tejado y pérgolas",
        "Sistemas solares aislados con generador de respaldo para fincas rústicas",
        "Instalación de cargadores inteligentes de coche eléctrico (Wallbox)",
      ],
      en: [
        "Custom 3D solar yield modeling and complimentary feasibility assessment",
        "Rooftop and carport pergola solar panel installations",
        "Off-grid standalone solar setups with automated backup generator",
        "Smart EV charging station (Wallbox) residential installations",
      ],
      ca: [
        "Estudi solar 3D personalitzat",
        "Instal·lació de plaques solars en teulades",
        "Sistemes aïllats per a finques rústiques",
        "Instal·lació de carregadors de cotxe elèctric",
      ],
      de: [
        "Kostenlose 3D-Ertragsanalyse und Wirtschaftlichkeitsberechnung",
        "Dach- und Solar-Carport-Installationen",
        "Autarke Inselanlagen mit Notstrom-Generator für Fincas",
        "Installation intelligenter Wallbox-Ladestationen",
      ],
    },
  },

  // ── 5. HOGAR, CONTROL DE PLAGAS & DESINFECCIÓN ──
  {
    slug: "control-plagas-desinfeccion-mallorca-llucmajor",
    name: "Mallorca EcoPlagas & Control Ambiental Llucmajor",
    category: "control-plagas-desinfeccion",
    sectorFolder: "hogar-limpieza",
    sectorArrayName: "HOGAR_SERVICES",
    subcategories: ["control-picudo-rojo-palmeras", "fumigacion-ecologica-fincas", "desratizacion-desinsectacion"],
    zone: "santanyi-migjorn",
    address: "Carrer del Bisbe Taixequet, 44, 07620 Llucmajor",
    coordinates: { lat: 39.4895, lng: 2.8912 },
    rating: 4.8,
    reviewCount: 190,
    priceRange: "€€",
    phone: "+34 971 661 820",
    website: "https://mallorcaecoplagas.es",
    schedule: "Lunes a Viernes: 08:00 - 19:00 (Servicio de Urgencias 24h)",
    tags: ["zona:llucmajor", "product:accesible", "mod:a-domicilio"],
    shortDescription: {
      es: "Empresa de sanidad ambiental y control de plagas en Mallorca: endoterapia preventiva del picudo rojo en palmeras, procesionaria del pino y control de roedores.",
      en: "Environmental pest control company in Mallorca: palm tree red weevil endotherapy, pine processionary moth eradication, and rodent control.",
      ca: "Empresa de control de plagues i sanitat ambiental a Mallorca: endoteràpia contra el morrut de la palmera i processionària del pi.",
      de: "Fachbetrieb für Schädlingsbekämpfung und Baumschutz auf Mallorca: Bauminjektion gegen Roten Palmenrüssler, Pinienprozessionsspinner und Nager.",
    },
    fullDescription: {
      es: "Inscrita en el Registro Oficial de Establecimientos y Servicios Biocidas de las Islas Baleares (ROESB). Emplea métodos biológicos y endoterapia vegetal sin fumigación aérea para salvaguardar la salud de familias y mascotas en jardines y fincas rurales.",
      en: "Registered with the Balearic Biocide Health Registry (ROESB), utilizing targeted biological treatments and tree micro-injections safe for children and pets.",
      ca: "Inscrita al ROESB, utilitza mètodes biològics respectuosos amb el medi ambient i les mascotes per protegir jardins i finques.",
      de: "Eingetragen im balearischen Biozid-Register (ROESB) mit Schwerpunkt auf umweltfreundlichen biologischen Verfahren und gezielten Bauminjektionen.",
    },
    highlights: {
      es: [
        "Empresa homologada en el registro oficial ROESB de Baleares",
        "Endoterapia vegetal certificada para salvar palmeras del picudo rojo",
        "Tratamientos biológicos de procesionaria sin peligro para perros",
        "Certificados oficiales de desinfección para hostelería y alquiler vacacional",
      ],
      en: [
        "Officially certified by the Balearic ROESB Biocide Registry",
        "Certified tree micro-injection to cure and protect palms from weevils",
        "Biological processionary caterpillar treatment pet-friendly for dogs",
        "Official hygiene compliance certificates for holiday rentals (ETV)",
      ],
      ca: [
        "Empresa homologada al registre oficial ROESB",
        "Endoteràpia per salvar palmeres del morrut",
        "Tractaments biològics contra la processionària",
        "Certificats oficials per a lloguer turístic",
      ],
      de: [
        "Staatlich anerkannter Fachbetrieb im balearischen ROESB-Register",
        "Gezielte Endotherapie zur Rettung von Palmen vor dem Rüssler",
        "Biologische Bekämpfung des Pinienprozessionsspinners (hundefreundlich)",
        "Amtliche Desinfektionszertifikate für Ferienvermietung (ETV)",
      ],
    },
    servicesProvided: {
      es: [
        "Tratamiento integral de palmeras contra picudo rojo (Rhynchophorus ferrugineus)",
        "Retirada de nidos de procesionaria en pinos antes de la bajada",
        "Control preventivo y correctivo de roedores, cucarachas y hormigas",
        "Desinfección de aljibes de agua potable y depósitos según normativa",
      ],
      en: [
        "Complete palm protection protocol against red palm weevil",
        "Pine processionary nest removal and biological spraying",
        "Integrated rodent, cockroach, and ant prevention programs",
        "Drinking water cistern and tank disinfection complying with sanitary laws",
      ],
      ca: [
        "Tractament de palmeres contra el morrut",
        "Eliminació de bosses de processionària",
        "Control de rates, paneroles i formigues",
        "Desinfecció d'aljubs d'aigua potable",
      ],
      de: [
        "Palmenrettung und Vorsorge gegen den Roten Palmenrüssler",
        "Entfernung von Pinienprozessionsspinner-Nestern",
        "Schädlingsbekämpfung (Nager, Schaben, Ameisen)",
        "Desinfektion und Reinigung von Trinkwasserzisternen",
      ],
    },
  },
];

console.log("Ingesting Batch 8 of 5 verified businesses to reach 608 total services...");
ingestBatch(BATCH_8);
