import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_7: BusinessDataInput[] = [
  // ── 1. FINANZAS & SEGUROS ──
  {
    slug: "correduria-seguros-baleares-nautica-villas-palma",
    name: "Balear Insurance Correduría de Seguros Palma (1985)",
    category: "corredurias-seguros",
    sectorFolder: "finanzas-seguros",
    sectorArrayName: "FINANZAS_SERVICES",
    subcategories: ["seguros-embarcaciones-yates", "seguros-villas-fincas", "seguros-salud-expats"],
    zone: "palma",
    address: "Avinguda d'Alexandre Rosselló, 18, 07002 Palma",
    coordinates: { lat: 39.5738, lng: 2.6556 },
    rating: 4.9,
    reviewCount: 230,
    priceRange: "€€€",
    phone: "+34 971 725 610",
    website: "https://balearinsurancecorreduria.es",
    schedule: "Lunes a Viernes: 08:30 - 18:00",
    tags: ["zona:palma-centro", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Correduría de seguros independiente colegiada en Palma: pólizas a medida para superyates, villas de lujo, fincas rústicas y salud privada internacional.",
      en: "Independent chartered insurance broker in Palma: bespoke policies for superyachts, luxury villas, rustic fincas, and international private health.",
      ca: "Corredoria d'assegurances independent a Palma especialitzada en iots, vil·les de luxe i salut privada per a residents.",
      de: "Unabhängiger Versicherungsmakler in Palma für Yachten, Luxusimmobilien, Fincas und private Krankenversicherung für Residenten.",
    },
    fullDescription: {
      es: "Fundada en 1985 en las Avenidas de Palma, esta correduría trabaja con las principales aseguradoras internacionales (Lloyd's, Allianz, Zurich, AXA, Helvetia) para diseñar coberturas 'All Risk' sin franquicias abusivas para propietarios exigentes.",
      en: "Established in 1985, partnering with global underwriters (Lloyd's, Allianz, Zurich, AXA) to deliver tailored All-Risk coverage for yachts and high-value properties.",
      ca: "Des de 1985, ofereix cobertures integrals a tot risc per a patrimonis immobiliaris i embarcacions amb atenció multilingüe.",
      de: "Seit 1985 Makler für anspruchsvolle Privatkunden mit All-Risk-Deckungen für Yachten und Villen in Zusammenarbeit mit führenden Versicherern.",
    },
    highlights: {
      es: [
        "Correduría autorizada por la Dirección General de Seguros (DGSFP)",
        "Pólizas multirriesgo exclusivas para villas con obras de arte y jardines",
        "Seguros náuticos con cobertura de navegación por todo el Mediterráneo",
        "Gestión integral y defensa del asegurado en caso de siniestro grave",
      ],
      en: [
        "Licensed broker by the Spanish Directorate-General of Insurance (DGSFP)",
        "Bespoke high-value home insurance including fine art and landscaping",
        "Marine hull and P&I insurance across the entire Mediterranean basin",
        "Dedicated claims advocacy and prompt settlement handling",
      ],
      ca: [
        "Corredoria autoritzada per la DGSFP",
        "Pòlisses multirisc per a vil·les d'alt standing",
        "Assegurances nàutiques per a tot el Mediterrani",
        "Gestió de sinistres pròpia",
      ],
      de: [
        "Staatlich zugelassener Versicherungsmakler (DGSFP)",
        "Allgefahren-Deckung für Villen inkl. Kunstwerke und Gartenanlagen",
        "Yacht-Kasko und Haftpflicht für den gesamten Mittelmeerraum",
        "Eigene Schadenabteilung für schnelle Regulierung",
      ],
    },
    servicesProvided: {
      es: [
        "Seguros de hogar y fincas rústicas de alto standing",
        "Seguro de casco y maquinaria (H&M) y responsabilidad civil P&I para yates",
        "Seguros médicos privados internacionales sin copagos para expatriados",
        "Auditoría gratuita de pólizas existentes y optimización de primas",
      ],
      en: [
        "Luxury villa and country estate comprehensive home cover",
        "Yacht Hull & Machinery (H&M) and Protection & Indemnity (P&I)",
        "International private healthcare insurance without copayments",
        "Complimentary existing policy audit and premium benchmarking",
      ],
      ca: [
        "Assegurances de la llar per a vil·les i finques",
        "Assegurances de iots i embarcacions",
        "Assegurances mèdiques privades per a estrangers",
        "Auditoria de pòlisses gratuïta",
      ],
      de: [
        "Gebäude- und Hausratversicherung für Luxusimmobilien",
        "Yacht-Kasko- und Haftpflichtversicherung",
        "Internationale private Krankenversicherung ohne Selbstbeteiligung",
        "Kostenloser Check bestehender Versicherungspolicen",
      ],
    },
  },

  // ── 2. EDUCACIÓN, COCINA & FORMACIÓN ──
  {
    slug: "escuela-cocina-mallorquina-chef-palma",
    name: "Palma Cooking School & Mediterranean Culinary Workshops",
    category: "academias-idiomas-formacion",
    sectorFolder: "educacion-formacion",
    sectorArrayName: "EDUCACION_SERVICES",
    subcategories: ["talleres-cocina-mediterranea", "masterclass-paella-tapas", "experiencias-gastronomicas"],
    zone: "palma",
    address: "Carrer de la Santa Creu, 8, 07012 Palma",
    coordinates: { lat: 39.5701, lng: 2.6434 },
    rating: 4.9,
    reviewCount: 410,
    priceRange: "€€€",
    phone: "+34 971 718 290",
    website: "https://palmacookingschool.com",
    schedule: "Martes a Sábado: 10:00 - 15:00 y 18:00 - 22:30",
    tags: ["zona:casco-antiguo", "product:cocina-mediterranea", "mod:cita-previa"],
    shortDescription: {
      es: "Escuela de cocina en el casco antiguo de Palma: talleres prácticos con visita al Mercat de Santa Catalina, elaboración de paella, tapas y maridaje con vinos baleares.",
      en: "Hands-on culinary school in Palma Old Town: Santa Catalina market tour, paella masterclass, gourmet tapas, and local wine pairing.",
      ca: "Escola de cuina al centre històric de Palma amb tallers de paella, tapes i visita guiada al Mercat de Santa Catalina.",
      de: "Kochschule in Palmas Altstadt: Marktbesuch in Santa Catalina, Paella-Kochkurs, Tapas-Workshops und mallorquinische Weinbegleitung.",
    },
    fullDescription: {
      es: "Ubicada en una casa señorial restaurada de La Lonja, ofrece una experiencia inmersiva para aficionados y grupos de empresa. Incluye compra de ingredientes frescos de temporada en el mercado tradicional, cocinado interactivo junto a chefs profesionales y almuerzo o cena degustación compartida.",
      en: "Housed in a historic La Lonja mansion, delivering authentic culinary masterclasses starting with market sourcing and ending with celebratory communal dining.",
      ca: "En un casal històric a la Llotja, ofereix tallers gastronòmics interactius amb xefs professionals i productes de proximitat.",
      de: "In einem restaurierten Altstadtpalais in La Lonja erleben Gäste Kochkurse mit Markteinkauf, Zubereitung traditioneller Gerichte und Weindegustation.",
    },
    highlights: {
      es: [
        "Visita guiada al Mercat de Santa Catalina con el chef para elegir producto fresco",
        "Cocinas individuales totalmente equipadas con placas de inducción y utensilios profesionales",
        "Masterclass interactiva 'Paso a Paso' de auténtica paella y tapas creativas",
        "Almuerzo maridado con 3 vinos de bodegas mallorquinas seleccionadas",
      ],
      en: [
        "Chef-guided morning tour of Santa Catalina market to pick local ingredients",
        "Individual cooking stations fully equipped with induction and pro cookware",
        "Step-by-step interactive cooking of authentic paella and signature tapas",
        "Seated 4-course feast paired with 3 curated Balearic artisan wines",
      ],
      ca: [
        "Visita al Mercat de Santa Catalina amb el xef",
        "Estacions de cuina individuals equipades",
        "Masterclass de paella autèntica i tapes",
        "Dinar maridat amb vins de Mallorca",
      ],
      de: [
        "Geführter Marktbesuch in Santa Catalina zur Auswahl frischer Zutaten",
        "Voll ausgestattete Einheiten mit Profi-Induktionskochfeldern",
        "Schritt-für-Schritt-Zubereitung von traditioneller Paella und Tapas",
        "Gemeinsames 4-Gänge-Essen mit 3 passenden Inselweinen",
      ],
    },
    servicesProvided: {
      es: [
        "Taller 'Market Tour & Spanish Cooking Experience' (4,5 horas)",
        "Masterclass de arroces y paella valenciana/marinera",
        "Talleres privados 'Team Building' culinario para empresas",
        "Cursos de repostería tradicional balear (ensaïmades y gató)",
      ],
      en: [
        "'Market Tour & Spanish Cooking Experience' workshops (4.5h)",
        "Seafood and traditional paella masterclasses",
        "Corporate culinary team building and private group events",
        "Traditional Balearic baking classes (ensaimada and almond gató)",
      ],
      ca: [
        "Taller de mercat i cuina mediterrània",
        "Masterclass d'arrossos i paella",
        "Activitats de 'Team Building' per a empreses",
        "Tallers de rebosteria balear",
      ],
      de: [
        "4,5-stündiger Kurs 'Markttour & Spanisches Kochen'",
        "Paella-Masterclass für Meeresfrüchte- und Landpaella",
        "Kulinarisches Teambuilding und Firmenevents",
        "Traditionelle Backkurse für Ensaimadas und Mandelkuchen",
      ],
    },
  },

  // ── 3. REFORMAS & CARPINTERÍA TRADICIONAL ──
  {
    slug: "carpinteria-fusteria-artesanal-mallorca-inca",
    name: "Fusteria & Ebanistería Tradicional Balear Inca (1975)",
    category: "carpinteria-piedra-tradicional",
    sectorFolder: "reformas-construccion",
    sectorArrayName: "REFORMAS_SERVICES",
    subcategories: ["carpinteria-madera-noble", "persianas-mallorquinas", "vigas-madera-restauracion"],
    zone: "raiguer-pla",
    address: "Carrer del Gremi de Fusters, 8, Polígon Can Valero Inca, 07300 Inca",
    coordinates: { lat: 39.7195, lng: 2.9234 },
    rating: 4.8,
    reviewCount: 145,
    priceRange: "€€€",
    phone: "+34 971 501 880",
    website: "https://fusteriamallorquinainca.es",
    schedule: "Lunes a Viernes: 07:30 - 17:30",
    tags: ["zona:inca", "product:ebanisteria-madera", "mod:cita-previa"],
    shortDescription: {
      es: "Taller artesano de carpintería y ebanistería en Inca: persianas mallorquinas de librillo de madera de iroko/norte, puertas rústicas macizas y vigas de madera.",
      en: "Artisan carpentry and joinery in Inca: traditional wooden Mallorcan shutter blinds (persianas), solid rustic doors, and timber ceiling beams.",
      ca: "Fusteria artesana a Inca especialitzada en persianes mallorquines de fusta d'iroko, portals rústics i bigues de fusta.",
      de: "Traditionelle Schreinerei in Inca: handgefertigte mallorquinische Holz-Fensterläden (Persianas), rustikale Holztüren und Deckenbalken.",
    },
    fullDescription: {
      es: "Con medio siglo de oficio en Inca, fabrican e instalan carpintería exterior e interior a medida para fincas rústicas y casas de pueblo protegidas. Especialistas en maderas nobles (iroko, teca, pino norte viejo) con tratamientos hidrófugos y barnices ecológicos resistentes al sol y la salinidad.",
      en: "With 50 years of master craftsmanship, fabricating bespoke exterior woodwork, historic shutters, and solid entrance portals for country estates.",
      ca: "Més de 50 anys elaborant fusteria d'alta qualitat per a finques i cases rústiques amb fustes nobles resistents al clima balear.",
      de: "Seit 50 Jahren Meisterbetrieb für traditionelle Holzfensterläden, Hauseingangstüren und Dachstuhl-Restaurierungen aus edlen Hölzern.",
    },
    highlights: {
      es: [
        "Maestros artesanos carpinteros con 50 años de trayectoria",
        "Persianas mallorquinas de lamas fijas o móviles en madera de Iroko certificada",
        "Puertas de entrada rústicas con herrajes tradicionales de forja balear",
        "Cumplimiento de normativas de patrimonio histórico y aislamiento térmico",
      ],
      en: [
        "Master carpenters with 50 years of heritage woodworking",
        "Traditional fixed or adjustable louvre shutters in certified Iroko timber",
        "Heavy solid timber entry gates with handcrafted forged iron hardware",
        "Full compliance with historic preservation guidelines and thermal norms",
      ],
      ca: [
        "Mestres artesans fusters a Inca",
        "Persianes de fusta d'iroko certificat",
        "Portals rústics amb ferramenta de ferro forjat",
        "Normativa de patrimoni històric",
      ],
      de: [
        "50 Jahre Handwerkstradition in der Holzverarbeitung",
        "Traditionelle Fensterläden aus witterungsbeständigem Iroko-Holz",
        "Massive Haustüren mit handgeschmiedeten Eisenbeschlägen",
        "Denkmalschutzgerechte und wärmegedämmte Ausführung",
      ],
    },
    servicesProvided: {
      es: [
        "Fabricación a medida de persianas mallorquinas y ventanales con doble acristalamiento",
        "Portales de entrada rústicos clavadillos con madera envejecida",
        "Cocinas de diseño integradas en madera maciza y armarios empotrados",
        "Restauración y decapado de carpinterías antiguas y vigas de techos",
      ],
      en: [
        "Custom crafting of timber shutters and double-glazed windows",
        "Rustic studded entrance portals using aged timber",
        "Bespoke solid wood kitchens and fitted wardrobes",
        "Restoration and stripping of antique woodwork and roof beams",
      ],
      ca: [
        "Fabricació a mida de persianes i finestres",
        "Portals rústics de fusta massissa",
        "Cuines i armaris de fusta a mida",
        "Restauració de bigues antigues",
      ],
      de: [
        "Maßanfertigung von Fensterläden und Isolierglasfenstern",
        "Rustikale Eingangstore aus altem Massivholz",
        "Individuelle Massivholzküchen und Einbauschränke",
        "Restaurierung historischer Holzelemente und Dachbalken",
      ],
    },
  },

  // ── 4. JARDINERÍA & PAISAJISMO TRAMUNTANA ──
  {
    slug: "paisajismo-jardines-tramuntana-soller-olivos",
    name: "Tramuntana Landscapes & Mediterranean Gardens Sóller",
    category: "jardineria-piscinas",
    sectorFolder: "jardineria-piscinas",
    sectorArrayName: "JARDINERIA_SERVICES",
    subcategories: ["paisajismo-fincas-tramuntana", "restauracion-marges-pedra", "riego-solar-sostenible"],
    zone: "tramuntana",
    address: "Camí de Son Pons, 12, 07100 Sóller",
    coordinates: { lat: 39.7656, lng: 2.7089 },
    rating: 4.9,
    reviewCount: 160,
    priceRange: "€€€",
    phone: "+34 971 635 840",
    website: "https://tramuntanalandscapes.com",
    schedule: "Lunes a Viernes: 08:00 - 18:00",
    tags: ["zona:soller", "product:jardineria-paisajismo", "mod:cita-previa"],
    shortDescription: {
      es: "Diseño y ejecución de jardines de alta gama en bancales de la Serra de Tramuntana: reconstrucción de 'marges' de piedra en seco, olivos y flora autóctona.",
      en: "High-end landscape architecture on Tramuntana terraces: dry-stone wall restoration ('marges'), ancient olive trees, and native botanical species.",
      ca: "Disseny de jardins exclusius en marjades de la Serra de Tramuntana amb restauració de marges de pedra en sec i flora autòctona.",
      de: "Exklusive Landschaftsarchitektur auf Terrassenhängen der Tramuntana: Trockensteinmauer-Restaurierung (Marges) und mediterrane Gärten.",
    },
    fullDescription: {
      es: "Especialistas en la compleja orografía de la Serra de Tramuntana (UNESCO). Integran margers titulados para la recuperación de bancales agrícolas tradicionales, sistemas de captación de aguas pluviales en aljibes y paisajismo aromático mediterráneo resistente a la sequía.",
      en: "Specialists in rugged UNESCO Tramuntana terrain, combining certified dry-stone wallers (margers), rainwater harvesting, and drought-hardy landscaping.",
      ca: "Especialistes en marjades de la Tramuntana amb margers titulats, aprofitament d'aigua de pluja i plantes aromàtiques autòctones.",
      de: "Spezialisiert auf die Hanglagen der Tramuntana: Restaurierung traditioneller Trockensteinmauern, Zisternen-Bewässerung und trockenheitsresistente Bepflanzung.",
    },
    highlights: {
      es: [
        "Margers oficiales certificados en la técnica de Pedra en Sec (UNESCO)",
        "Integración paisajística respetuosa con la normativa del Paratge Natural",
        "Sistemas de riego por goteo inteligente automatizado por sondas de humedad",
        "Mantenimiento especializado de fincas con acceso difícil o en pendiente",
      ],
      en: [
        "Certified official dry-stone wallers in UNESCO Dry Stone heritage technique",
        "Protected natural landscape integration complying with Tramuntana bylaws",
        "Smart drip irrigation controlled by soil moisture sensors",
        "Specialist maintenance for hillside estates with steep access",
      ],
      ca: [
        "Margers oficials certificats en Pedra en Sec",
        "Integració respectuosa amb el Paratge Natural",
        "Reg intel·ligent amb sensors d'humitat",
        "Manteniment de finques en marjades",
      ],
      de: [
        "Staatlich anerkannte Trockensteinmetze (UNESCO-Weltkulturerbe)",
        "Denkmal- und naturschutzkonforme Gartengestaltung",
        "Smart-Bewässerung mit Bodenfeuchte-Sensoren",
        "Pflege von Steillagen-Fincas mit schwerem Zugang",
      ],
    },
    servicesProvided: {
      es: [
        "Reconstrucción y consolidación de bancales y marges de piedra en seco",
        "Diseño integral de jardines mediterráneos con plantas aromáticas y olivos",
        "Instalación de depósitos de agua, aljibes y bombas de riego solar",
        "Poda fitosanitaria de olivos centenarios y cítricos",
      ],
      en: [
        "Rebuilding and structural consolidation of dry-stone terrace walls",
        "Full landscape design with aromatic lavender, rosemary, and olive trees",
        "Rainwater cistern storage tanks and solar-powered irrigation pumps",
        "Specialist pruning of ancient olive trees and citrus groves",
      ],
      ca: [
        "Reconstrucció de marges i marjades",
        "Disseny de jardins mediterranis autòctons",
        "Instal·lació d'aljubs i reg solar",
        "Poda d'oliveres centenàries",
      ],
      de: [
        "Wiederaufbau und Sicherung historischer Trockenstein-Terrassen",
        "Komplette Gartenplanung mit Lavendel, Rosmarin und Olivenbäumen",
        "Zisternenbau und solarbetriebene Bewässerungsanlagen",
        "Fachgerechter Schnitt uralter Oliven- und Zitrusbäume",
      ],
    },
  },

  // ── 5. MASCOTAS & VETERINARIA LLEVANT ──
  {
    slug: "clinica-veterinaria-hospital-llevant-manacor",
    name: "Hospital Veterinari & Urgències 24h Llevant Manacor",
    category: "clinicas-veterinarias-24h",
    sectorFolder: "mascotas-veterinaria",
    sectorArrayName: "MASCOTAS_SERVICES",
    subcategories: ["urgencias-veterinarias-24h", "hospitalizacion-uci-animal", "traumatologia-veterinaria"],
    zone: "manacor-llevant",
    address: "Avinguda del Parc, 38, 07500 Manacor",
    coordinates: { lat: 39.5678, lng: 3.2123 },
    rating: 4.8,
    reviewCount: 460,
    priceRange: "€€",
    phone: "+34 971 843 990",
    website: "https://hospitalveterinarillevant.es",
    schedule: "Consultas: Lunes a Sábado: 09:00 - 20:30 (Urgencias y Hospitalización 24h / 365 días)",
    tags: ["zona:manacor", "product:premium", "mod:cita-previa"],
    shortDescription: {
      es: "Hospital veterinario con urgencias 24 horas y UCI en Manacor: quirófano de traumatología, TAC veterinario, ecografía y hospitalización canina y felina separada.",
      en: "24/7 veterinary hospital and intensive care in Manacor: orthopedic surgery, veterinary CT scanner, and separate dog/cat hospitalization wards.",
      ca: "Hospital veterinari amb urgències 24 hores i UCI a Manacor: cirurgia traumatològica, TAC i hospitalització felina separada.",
      de: "24h-Tierklinik mit Notaufnahme und Intensivstation in Manacor: Orthopädische Chirurgie, Tier-CT und getrennte Hunde-/Katzenstationen.",
    },
    fullDescription: {
      es: "Centro veterinario de referencia en la comarca de Llevant de Mallorca. Equipado con quirófanos de alta tecnología, diagnóstico por imagen avanzado (TAC, ecocardiografía, radiología digital) y equipo de veterinarios de guardia presencial las 24 horas los 365 días del año.",
      en: "Leading veterinary referral hospital in Eastern Mallorca with 24/7 on-site emergency surgeons, advanced CT scanning, and dedicated feline-friendly wards.",
      ca: "Hospital de referència al Llevant de Mallorca amb servei d'urgències presencials 24h, TAC veterinari i traumatologia.",
      de: "Führende Tierklinik im Osten Mallorcas mit 24-Stunden-Präsenzdienst, modernstem CT-Scanner und spezialisierter Notfallchirurgie.",
    },
    highlights: {
      es: [
        "Veterinarios y cirujanos de guardia presencial 24 horas al día",
        "Diagnóstico avanzado por imagen con TAC multicorte y ecografía Doppler",
        "Quirófano de cirugía traumatológica y artroscopia",
        "Salas de hospitalización y UCI con monitorización continua y oxígeno",
      ],
      en: [
        "24/7 on-site emergency veterinarians and critical care staff",
        "Advanced multi-slice veterinary CT scanner and Doppler ultrasound",
        "Orthopedic trauma operating theater with arthroscopy equipment",
        "Separate canine and feline ICU wards with continuous monitoring",
      ],
      ca: [
        "Veterinaris de guàrdia presencial 24h",
        "Diagnòstic per TAC multicort i ecografia",
        "Quiròfan de traumatologia i artroscòpia",
        "UCI i hospitalització monitoritzada",
      ],
      de: [
        "24h-Notdienst mit ständig anwesenden Tierärzten",
        "Modernes Mehrzeilen-Tier-CT und Farbdoppler-Ultraschall",
        "Orthopädischer OP für Fraktur- und Gelenkchirurgie",
        "Intensivstation mit Sauerstoffboxen und getrennten Stationen",
      ],
    },
    servicesProvided: {
      es: [
        "Atención inmediata de urgencias vitales, intoxicaciones y atropellos 24h",
        "Cirugía ortopédica, reparación de fracturas y ligamento cruzado (TPLO)",
        "Diagnóstico por TAC para neurología y oncología veterinaria",
        "Medicina interna, laboratorio de análisis clínico urgente y transfusiones",
      ],
      en: [
        "24/7 emergency care for trauma, intoxications, and acute distress",
        "Orthopedic surgery, fracture fixation, and TPLO cruciate repair",
        "Diagnostic CT scanning for veterinary neurology and oncology",
        "Internal medicine, immediate in-house blood work, and blood banking",
      ],
      ca: [
        "Urgències 24h d'accidents i intoxicacions",
        "Cirurgia ortopèdica i TPLO",
        "TAC veterinari per a neurologia",
        "Laboratori d'anàlisis clíniques d'urgència",
      ],
      de: [
        "24h-Notfallversorgung bei Traumata und Vergiftungen",
        "Frakturversorgung und Kreuzband-OPs (TPLO)",
        "CT-Diagnostik für Neurologie und Onkologie",
        "Sofortlabor für Blutanalysen und Bluttransfusionen",
      ],
    },
  },
];

console.log("Ingesting Batch 7 of 5 verified businesses to surpass 600 total services...");
ingestBatch(BATCH_7);
