import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const MASS_CURATED_SERVICES: BusinessDataInput[] = [
  // ── SECTOR 1: REFORMAS & CONSTRUCCIÓN (construccion-reformas) ──
  {
    slug: "reformas-integrales-mallorca-nord-alcudia",
    name: "Mallorca Nord Reformes & Construcció Alcúdia",
    category: "reformas-hogar",
    sectorFolder: "reformas-construccion",
    sectorArrayName: "REFORMAS_SERVICES",
    subcategories: ["reformas-integrales", "rehabilitacion-fincas", "albanileria-tradicional"],
    zone: "alcudia-pollensa",
    address: "Passeig Pere Ventayol, 14, 07400 Alcúdia",
    coordinates: { lat: 39.8524, lng: 3.1215 },
    rating: 4.8,
    reviewCount: 92,
    priceRange: "€€€",
    phone: "+34 971 547 890",
    website: "https://reformesnordalcudia.es",
    schedule: "Lunes a Viernes: 08:00 - 18:00",
    tags: ["zona:alcudia", "product:premium", "mod:cita-previa"],
    shortDescription: {
      es: "Empresa constructora especializada en reformas integrales de viviendas históricas en el casco antiguo y chalets costeros.",
      en: "Construction company specializing in comprehensive renovations of historic townhouses and coastal villas in Northern Mallorca.",
      ca: "Empresa constructora especialitzada en reformes integrals de cases de poble i xalets de costa.",
      de: "Bauunternehmen für Komplettsanierungen historischer Stadthäuser und Küstenvillen im Norden Mallorcas.",
    },
    fullDescription: {
      es: "Mallorca Nord combina albañilería tradicional mallorquina con técnicas de bioconstrucción y eficiencia energética. Realizan proyectos llave en mano con dirección de obra, fontanería, electricidad y acabados de microcemento y piedra de marés.",
      en: "Mallorca Nord combines traditional Mallorcan masonry with eco-building and energy efficiency, managing turnkey renovations with plumbing, electrical, and microcement.",
      ca: "Combina paleta tradicional mallorquina amb bioconstrucció i eficiència energètica en projectes clau en mà.",
      de: "Mallorca Nord verbindet traditionelle mallorquinische Steinmetzkunst mit ökologischem Bauen und schlüsselfertiger Ausführung.",
    },
    highlights: {
      es: [
        "Proyectos integrales 'Llave en Mano'",
        "Especialistas en piedra de marés y vigas vistas de madera",
        "Gestión integral de licencias de obra menor y mayor",
        "Garantía decenal y seguro de responsabilidad civil",
      ],
      en: [
        "Turnkey renovation project management",
        "Experts in sandstone (marés) and exposed timber beams",
        "Complete handling of municipal building permits",
        "10-year structural warranty and liability cover",
      ],
      ca: [
        "Projectes 'Clau en Mà'",
        "Especialistes en marès i bigues de fusta",
        "Gestió de llicències municipals",
        "Garantia decennal",
      ],
      de: [
        "Schlüsselfertige Sanierungskonzepte",
        "Spezialisten für Marés-Sandstein und Holzbalkendecken",
        "Abwicklung aller Baugenehmigungen",
        "10 Jahre Gewährleistung",
      ],
    },
    servicesProvided: {
      es: [
        "Reformas integrales de cocinas y baños",
        "Rehabilitación de fachadas y tejados tradicionales",
        "Aislamiento térmico y aerotermia",
        "Acabados de microcemento continuo y yeso",
      ],
      en: [
        "Full kitchen and bathroom remodels",
        "Historic facade and tile roof restoration",
        "Thermal insulation and heat-pump aerothermia",
        "Continuous microcement flooring and plasterwork",
      ],
      ca: [
        "Reformes de cuines i banys",
        "Rehabilitació de façanes i teulades",
        "Aïllament tèrmic i aerotèrmia",
        "Microciment i acabats",
      ],
      de: [
        "Komplette Küchen- und Badsanierung",
        "Fassaden- und Dachsanierung",
        "Wärmedämmung und Wärmepumpen",
        "Fugenlose Mikrozementböden",
      ],
    },
  },
  {
    slug: "fontaneria-climatizacion-calvia-express",
    name: "Calvià Express Fontanería & Aerotermia",
    category: "reformas-hogar",
    sectorFolder: "reformas-construccion",
    sectorArrayName: "REFORMAS_SERVICES",
    subcategories: ["fontaneria-urgente", "aerotermia-calefaccion", "descalcificadores-agua"],
    zone: "calvia-andratx",
    address: "Carrer de les Illes Canàries, 18, 07180 Santa Ponsa",
    coordinates: { lat: 39.5134, lng: 2.4789 },
    rating: 4.9,
    reviewCount: 168,
    priceRange: "€€",
    phone: "+34 971 692 310",
    website: "https://fontaneriacalviaexpress.com",
    schedule: "Lunes a Viernes: 08:00 - 19:00 (Servicio de Urgencias 24h)",
    tags: ["zona:santa-ponsa", "product:accesible", "mod:a-domicilio"],
    shortDescription: {
      es: "Instalación y reparación urgente de fontanería, aerotermia, suelo radiante y sistemas de descalcificación en el suroeste de Mallorca.",
      en: "Emergency plumbing, heat pump aerothermia, underfloor heating, and water softening systems in Southwest Mallorca.",
      ca: "Instal·lació i reparació urgent de fontaneria, aerotèrmia, terra radiant i descalcificadors a Calvià.",
      de: "Notdienst-Sanitärinstallation, Wärmepumpen-Aerothermie, Fußbodenheizung und Wasserenthärtungsanlagen in Calvià.",
    },
    fullDescription: {
      es: "Empresa homologada con instaladores autorizados RITE. Solucionan fugas de agua, termos eléctricos, sustitución de tuberías antiguas y montaje de calderas de alta eficiencia energética para chalets y apartamentos.",
      en: "Authorized RITE licensed installers fixing pipe leaks, water heaters, pipe repiping, and high-efficiency heat pumps across Calvià and Andratx.",
      ca: "Instal·ladors autoritzats RITE que solucionen fuites d'aigua, termos i aerotèrmia amb atenció ràpida.",
      de: "Zertifizierter Fachbetrieb für Leckageortung, Warmwasserbereiter, Rohrsanierung und energieeffiziente Wärmepumpen.",
    },
    highlights: {
      es: [
        "Instaladores autorizados RITE en Baleares",
        "Detección de fugas sin obra mediante geófono y cámara térmica",
        "Expertos en descalcificadores automáticos contra la cal balear",
        "Urgencias de fontanería 24 horas",
      ],
      en: [
        "Licensed RITE certified technicians in Balearics",
        "Non-destructive leak detection with thermal imaging",
        "Specialists in automated water softeners for hard water",
        "24/7 emergency plumbing call-outs",
      ],
      ca: [
        "Instal·ladors autoritzats RITE",
        "Detecció de fuites sense obres",
        "Descalcificadors contra la calç",
        "Urgències 24 hores",
      ],
      de: [
        "Staatlich anerkannte RITE-Fachinstallateure",
        "Zerstörungsfreie Leckortung per Wärmebildkamera",
        "Spezialisten für Entkalkungsanlagen",
        "24h Sanitär-Notdienst",
      ],
    },
    servicesProvided: {
      es: [
        "Reparación de fugas y desatascos urgentes",
        "Instalación de bombas de calor y aerotermia",
        "Montaje de osmosis inversa y descalcificadores",
        "Suelo radiante y climatización por conductos",
      ],
      en: [
        "Leak repair and urgent drain clearing",
        "Heat pump and aerothermia installation",
        "Reverse osmosis and water softener setups",
        "Underfloor heating and ducted climate control",
      ],
      ca: [
        "Reparació de fuites i desatascs",
        "Bombes de calor i aerotèrmia",
        "Osmosi inversa i descalcificadors",
        "Terra radiant",
      ],
      de: [
        "Rohrreparaturen und Abflussreinigung",
        "Wärmepumpen- und Klimainstallation",
        "Umkehrosmose und Entkalker",
        "Fußbodenheizung und Klimatechnik",
      ],
    },
  },

  // ── SECTOR 2: SERVICIOS PROFESIONALES & LEGAL ──
  {
    slug: "balearic-lawyers-property-tax-palma",
    name: "Balearic Property & Tax Lawyers Palma",
    category: "servicios-profesionales",
    sectorFolder: "servicios-profesionales",
    sectorArrayName: "PROFESIONALES_SERVICES",
    subcategories: ["abogados-inmobiliarios", "derecho-fiscal-tributario", "herencias-internacionales"],
    zone: "palma",
    address: "Carrer de Sant Jaume, 12, 07012 Palma",
    coordinates: { lat: 39.5721, lng: 2.6468 },
    rating: 4.9,
    reviewCount: 190,
    priceRange: "€€€€",
    phone: "+34 971 719 500",
    website: "https://balearicpropertylawyers.com",
    schedule: "Lunes a Viernes: 09:00 - 18:30",
    tags: ["zona:palma-centro", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Bufete internacional de abogados colegiados en Palma especializado en compraventas inmobiliarias, urbanismo y planificación fiscal de no residentes.",
      en: "International law firm in Palma specializing in luxury real estate conveyancing, urban planning, and non-resident tax structuring.",
      ca: "Bufet internacional d'advocats a Palma especialitzat en compravendes immobiliàries, urbanisme i dret fiscal.",
      de: "Internationale Anwaltskanzlei in Palma, spezialisiert auf Immobilienkaufrecht, Baurecht und Steuergestaltung für Nicht-Residenten.",
    },
    fullDescription: {
      es: "Con más de 25 años de trayectoria en el Ilustre Colegio de Abogados de Baleares (ICAIB), el equipo ofrece asesoramiento integral y 'Due Diligence' registral, catastral y urbanística previa a la compra de villas, fincas y suelo rústico en Mallorca.",
      en: "With 25+ years of membership at the Balearic Bar Association (ICAIB), delivering rigorous due diligence for buying luxury villas and rustic plots.",
      ca: "Amb més de 25 anys d'experiència a l'ICAIB, ofereix 'Due Diligence' registral i urbanística abans de comprar vil·les i finques.",
      de: "Seit über 25 Jahren Mitglied der balearischen Anwaltskammer (ICAIB) mit Expertise in Due Diligence bei Finca- und Villenkäufen.",
    },
    highlights: {
      es: [
        "Abogados colegiados en ICAIB con idiomas inglés y alemán",
        "Auditoría legal y urbanística completa (Due Diligence)",
        "Gestión de NIE, cuentas bancarias y poderes notariales",
        "Planificación sucesoria y testamentos internacionales",
      ],
      en: [
        "ICAIB registered lawyers fluent in English, German, and Spanish",
        "Comprehensive legal and urbanistic Due Diligence audits",
        "NIE numbers, power of attorney, and Spanish bank setup",
        "Cross-border estate planning and international wills",
      ],
      ca: [
        "Advocats col·legiats a l'ICAIB (anglès, alemany, català)",
        "Auditoria urbanística completa",
        "Tramitació de NIE i poders notarials",
        "Planificació successòria",
      ],
      de: [
        "Zugelassene ICAIB-Anwälte (Deutsch, Englisch, Spanisch)",
        "Vollständige juristische und baurechtliche Due Diligence",
        "Beantragung von NIE-Nummern und Vollmachten",
        "Internationales Erbrecht und Testamentsgestaltung",
      ],
    },
    servicesProvided: {
      es: [
        "Asesoramiento legal en compraventa de inmuebles",
        "Verificación de licencias de habitabilidad y legalidad urbanística",
        "Liquidación de impuestos (ITP, Plusvalía, IRPF No Residentes)",
        "Constitución de sociedades patrimoniales y mercantiles",
      ],
      en: [
        "Legal conveyancing for real estate acquisitions",
        "Habitability license and planning compliance checks",
        "Spanish tax settlement (Transfer Tax, Plusvalía, Non-resident IRNR)",
        "Holding company formation and corporate structuring",
      ],
      ca: [
        "Assessorament en compravenda d'immobles",
        "Verificació de cèdules d'habitabilitat",
        "Liquidació d'impostos i tributs",
        "Constitució de societats",
      ],
      de: [
        "Rechtliche Kaufabwicklung bei Immobilien",
        "Prüfung von Cédula de Habitabilidad und Baurecht",
        "Steuerabwicklung (Grunderwerbsteuer, Nichtresidentensteuer)",
        "Gründung spanischer Kapitalgesellschaften",
      ],
    },
  },
  {
    slug: "gestoria-administrativa-asesoria-marroig-palma",
    name: "Gestoría Administrativa & Asesoría Marroig Palma",
    category: "servicios-profesionales",
    sectorFolder: "servicios-profesionales",
    sectorArrayName: "PROFESIONALES_SERVICES",
    subcategories: ["gestoria-trafico", "asesoria-laboral-fiscal", "tramites-extranjeria"],
    zone: "palma",
    address: "Carrer del Baró de Santa Maria del Sepulcre, 8, 07012 Palma",
    coordinates: { lat: 39.5714, lng: 2.6451 },
    rating: 4.8,
    reviewCount: 220,
    priceRange: "€€",
    phone: "+34 971 721 110",
    website: "https://gestoriamarroigpalma.es",
    schedule: "Lunes a Jueves: 08:30 - 17:30, Viernes: 08:30 - 14:30",
    tags: ["zona:palma-centro", "product:accesible", "mod:cita-previa"],
    shortDescription: {
      es: "Gestoría administrativa colegiada en Palma: matriculación y transferencia de vehículos, visados de residencia y asesoría contable-fiscal para autónomos y pymes.",
      en: "Chartered administrative agency in Palma for vehicle registration, residency visa processing, and tax/payroll accounting for SMEs.",
      ca: "Gestoria administrativa col·legiada a Palma per a tràmits de trànsit, estrangeria i assessoria fiscal.",
      de: "Zugelassene Gestoría in Palma für Kfz-Zulassungen, Aufenthaltsgenehmigungen und steuerliche Beratung für Selbstständige.",
    },
    fullDescription: {
      es: "Con más de 40 años de servicio en el centro de Palma, simplifican los trámites ante la DGT, Seguridad Social, Hacienda Tributaria de Baleares y Extranjería, ofreciendo agilidad y cercanía en cuatro idiomas.",
      en: "Operating for 40+ years in central Palma, streamlining bureaucracy with the Traffic Department (DGT), Tax Agency, and Immigration Office.",
      ca: "Amb més de 40 anys a Palma, simplifiquen la burocràcia davant la DGT, Hisenda i Estrangeria amb agilitat.",
      de: "Seit über 40 Jahren in Palma spezialisiert auf schnelle Abwicklung bei Verkehrsamt (DGT), Finanzamt und Ausländerbehörde.",
    },
    highlights: {
      es: [
        "Gestores Administrativos Colegiados en Baleares",
        "Cambios de titularidad y matriculaciones DGT en el mismo día",
        "Tramitación de Residencia (TIE, Certificado UE, Golden Visa)",
        "Contabilidad y nóminas telemáticas para empresas",
      ],
      en: [
        "Chartered Balearic Administrative Gestores",
        "Same-day vehicle transfer and DGT registration",
        "Residency processing (TIE, EU Certificate, Golden Visa)",
        "Digital payroll and corporate tax filing for SMEs",
      ],
      ca: [
        "Gestors Administratius Col·legiats",
        "Canvis de nom de vehicles el mateix dia",
        "Tràmits de residència i estrangeria",
        "Comptabilitat i nòmines",
      ],
      de: [
        "Zugelassene balearische Gestoría",
        "Kfz-Ummeldung und DGT-Zulassung am selben Tag",
        "Aufenthaltsstatus (TIE, EU-Bescheinigung, Golden Visa)",
        "Laufende Buchhaltung und Lohnabrechnungen",
      ],
    },
    servicesProvided: {
      es: [
        "Matriculación de coches extranjeros e inspección ITV",
        "Canje y renovación de permisos de conducir",
        "Declaraciones de IRPF, IVA, Sociedades y censos",
        "Trámites de visados, arraigo y nacionalidad española",
      ],
      en: [
        "Import registration of foreign vehicles and ITV booking",
        "Driving license exchange and renewals",
        "Income tax, VAT, and corporate tax returns",
        "Visa applications, Golden Visa, and Spanish nationality",
      ],
      ca: [
        "Matriculació de vehicles estrangers",
        "Canvi de carnet de conduir",
        "Declaracions d'Hisenda i IVA",
        "Tràmits de visats i nacionalitat",
      ],
      de: [
        "Kfz-Importverzollung und Zulassung mit ITV",
        "Führerscheinumschreibung in spanische Fahrerlaubnis",
        "Steuererklärungen (Einkommen-, Mehrwert-, Körperschaftsteuer)",
        "Visa-Verfahren und spanische Staatsbürgerschaft",
      ],
    },
  },

  // ── SECTOR 3: MOTOR & TRANSPORTE ──
  {
    slug: "classic-car-rental-mallorca-soller",
    name: "Mallorca Driving Classic Cars & Roadsters Sóller",
    category: "motor-transporte",
    sectorFolder: "motor-transporte",
    sectorArrayName: "TRANSPORTE_SERVICES",
    subcategories: ["alquiler-coches-clasicos", "rutas-tramuntana", "roadsters-descapotables"],
    zone: "tramuntana",
    address: "Carrer de Sa Lluna, 32, 07100 Sóller",
    coordinates: { lat: 39.7684, lng: 2.7156 },
    rating: 4.9,
    reviewCount: 175,
    priceRange: "€€€€",
    phone: "+34 971 638 720",
    website: "https://mallorcadrivingclassics.com",
    schedule: "Lunes a Domingo: 08:30 - 20:00",
    tags: ["zona:soller", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Alquiler de coches clásicos descapotables (Morgan, Porsche 356, Alfa Romeo Spider) para recorrer las curvas de la Serra de Tramuntana.",
      en: "Vintage and classic roadster car rental (Morgan, Porsche 356, Alfa Romeo) for scenic Serra de Tramuntana drives.",
      ca: "Lloguer de cotxes clàssics descapotables per recórrer la Serra de Tramuntana.",
      de: "Vermietung klassischer Oldtimer-Roadster (Morgan, Porsche 356, Alfa Romeo) für Touren durch die Serra de Tramuntana.",
    },
    fullDescription: {
      es: "Ubicado en el valle de Sóller, ofrece una flota de automóviles clásicos impecablemente restaurados y mantenidos. Ideal para bodas de ensueño, reportajes fotográficos y escapadas románticas por las carreteras costeras de Deià, Valldemossa y Sa Calobra.",
      en: "Based in Sóller valley, providing a fleet of restored vintage roadsters for dream weddings, photoshoots, and coastal road trips across Deià and Valldemossa.",
      ca: "A la vall de Sóller, disposa d'una flota de cotxes d'època restaurats per a casaments i rutes per la costa.",
      de: "Im Tal von Sóller bietet dieser Verleih restaurierte Oldtimer-Cabrios für Hochzeiten, Filmproduktionen und Traumfahrten nach Deià und Sa Calobra.",
    },
    highlights: {
      es: [
        "Flota propia de roadsters descapotables históricos",
        "Modelos icónicos: Morgan 4/4, Porsche Speedster, Triumph TR6",
        "Servicio de entrega en aeropuerto, fincas y hoteles",
        "Seguro a todo riesgo y asistencia en carretera incluida",
      ],
      en: [
        "Proprietary fleet of historic open-top roadsters",
        "Iconic models: Morgan 4/4, Porsche Speedster, Triumph TR6",
        "Delivery to Palma airport, private villas, and hotels",
        "Full comprehensive insurance and roadside assistance included",
      ],
      ca: [
        "Flota pròpia de cotxes clàssics descapotables",
        "Models mítics com Morgan, Porsche i Triumph",
        "Entrega a l'aeroport i hotels",
        "Assegurança a tot risc",
      ],
      de: [
        "Eigener Fuhrpark klassischer Cabriolet-Roadster",
        "Kult-Klassiker: Morgan 4/4, Porsche Speedster, Triumph TR6",
        "Direktzustellung an Flughafen, Fincas und Luxushotels",
        "Vollkaskoversicherung und Pannenhilfe inklusive",
      ],
    },
    servicesProvided: {
      es: [
        "Alquiler diario de coches clásicos sin conductor",
        "Vehículos nupciales con chófer uniformado para bodas",
        "Rutas guiadas por GPS precargado con los mejores miradores",
        "Packs regalo para aniversarios y experiencias sorpresa",
      ],
      en: [
        "Self-drive daily vintage car rentals",
        "Chauffeured classic bridal wedding cars",
        "Pre-loaded GPS scenic routes with top viewpoints",
        "Gift experience vouchers and anniversary packages",
      ],
      ca: [
        "Lloguer de cotxes clàssics sense conductor",
        "Cotxes per a casaments amb xofer",
        "Rutes guiades per GPS",
        "Targetes regal per a experiències",
      ],
      de: [
        "Oldtimer-Tagesmiete zum Selberfahren",
        "Hochzeitsautos mit Chauffeur",
        "Vorprogrammierte GPS-Panoramatouren",
        "Geschenkgutscheine für besondere Anlässe",
      ],
    },
  },
  {
    slug: "taller-mecanico-bosom-bosch-car-service-palma",
    name: "Taller Mecánico Bosom Bosch Car Service Palma (1968)",
    category: "motor-transporte",
    sectorFolder: "motor-transporte",
    sectorArrayName: "TRANSPORTE_SERVICES",
    subcategories: ["taller-mecanico-oficial", "diagnosis-electronica", "mantenimiento-marcas-alemanas"],
    zone: "palma",
    address: "Carrer del Gremi de Sabaters, 44, Son Castelló, 07009 Palma",
    coordinates: { lat: 39.6071, lng: 2.6689 },
    rating: 4.8,
    reviewCount: 340,
    priceRange: "€€",
    phone: "+34 971 431 220",
    website: "https://tallerbosomboschpalma.com",
    schedule: "Lunes a Viernes: 08:00 - 18:00",
    tags: ["zona:palma-centro", "product:premium", "mod:cita-previa"],
    shortDescription: {
      es: "Taller multimarca oficial Bosch Car Service en Palma: diagnosis electrónica avanzada, mantenimiento oficial sin perder garantía y mecánica de precisión.",
      en: "Official Bosch Car Service workshop in Palma: advanced electronic diagnostics, warranty-preserving maintenance, and engine mechanics.",
      ca: "Taller multimarca oficial Bosch Car Service a Palma amb diagnosi electrònica i manteniment oficial.",
      de: "Offizielle Bosch Car Service Meisterwerkstatt in Palma: Elektronik-Diagnose, Inspektionen nach Herstellervorgaben und Mechanik.",
    },
    fullDescription: {
      es: "Fundado en 1968 en Palma, el taller cuenta con tecnología de diagnosis de última generación para vehículos alemanes (BMW, Mercedes, Audi, Porsche) e híbridos/eléctricos, con recambios originales de calidad de primer equipo.",
      en: "Established in 1968, equipped with state-of-the-art diagnostic machinery for German prestige brands (BMW, Mercedes, Audi, Porsche) and electric/hybrid vehicles.",
      ca: "Fundat el 1968 a Palma, disposa de tecnologia avançada per a vehicles alemanys i híbrids amb recanvis originals.",
      de: "Seit 1968 Meisterbetrieb mit modernster Diagnosetechnik für deutsche Premiummarken (BMW, Mercedes, Audi, Porsche) sowie Hybrid- und E-Fahrzeuge.",
    },
    highlights: {
      es: [
        "Certificación oficial de la red Bosch Car Service",
        "Mantenimiento periódico sellando el libro oficial sin perder garantía",
        "Técnicos certificados en vehículos de alta gama e híbridos",
        "Vehículo de cortesía gratuito para clientes",
      ],
      en: [
        "Official Bosch Car Service network certification",
        "Scheduled maintenance with official digital service book entries",
        "Certified master technicians in premium and EV platforms",
        "Complimentary courtesy replacement car available",
      ],
      ca: [
        "Certificació oficial Bosch Car Service",
        "Manteniment oficial amb segell digital",
        "Tècnics certificats en alta gamma",
        "Vehicle de cortesia gratuït",
      ],
      de: [
        "Zertifizierte Bosch Car Service Qualitätswerkstatt",
        "Inspektion nach Herstellervorgaben mit digitalem Serviceheft-Eintrag",
        "Geschulte Mechatroniker für Premium- und Hybridfahrzeuge",
        "Kostenloser Ersatzwagen während der Reparatur",
      ],
    },
    servicesProvided: {
      es: [
        "Revisión oficial y cambio de aceite, filtros y frenos",
        "Diagnosis computarizada de centralitas electrónicas",
        "Carga y reparación de sistemas de aire acondicionado R1234yf",
        "Pre-ITV completa y paso de inspección oficial",
      ],
      en: [
        "Official scheduled servicing (oil, filters, brakes)",
        "Advanced ECU electronic scan and calibration",
        "R1234yf air conditioning re-gas and repairs",
        "Full pre-ITV check and test center presentation",
      ],
      ca: [
        "Revisió oficial i canvi d'oli, filtres i frens",
        "Diagnosi de centraletes electròniques",
        "Càrrega d'aire condicionat",
        "Pre-ITV i pas de la inspecció",
      ],
      de: [
        "Inspektion nach Herstellervorgabe, Bremsen- & Ölservice",
        "Fehlerdiagnose und Steuergeräte-Codierung",
        "Klimaservice und Kältemittel R1234yf",
        "Vollständige Vorab-ITV-Prüfung inkl. Prüfstellenvorführung",
      ],
    },
  },

  // ── SECTOR 4: INMOBILIARIA & FINCAS ──
  {
    slug: "mallorca-fincas-country-estates-santa-maria",
    name: "Mallorca Fincas & Historic Country Estates Santa Maria",
    category: "inmobiliaria-villas",
    sectorFolder: "inmobiliaria-villas",
    sectorArrayName: "INMOBILIARIA_SERVICES",
    subcategories: ["fincas-rusticas-lujo", "posesiones-historicas", "propiedades-ecuestres"],
    zone: "raiguer-pla",
    address: "Plaça Hostals, 6, 07320 Santa Maria del Camí",
    coordinates: { lat: 39.6512, lng: 2.7734 },
    rating: 4.9,
    reviewCount: 110,
    priceRange: "€€€€",
    phone: "+34 971 620 440",
    website: "https://mallorcafincasestates.com",
    schedule: "Lunes a Viernes: 09:30 - 19:00, Sábados: 10:00 - 14:00",
    tags: ["zona:santa-maria-del-cami", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Agencia inmobiliaria boutique especializada exclusivamente en la compraventa de fincas rústicas, viñedos y posesiones históricas en el interior de Mallorca.",
      en: "Boutique real estate agency specializing exclusively in rustic estates, vineyard properties, and historic manor houses in central Mallorca.",
      ca: "Immobiliària boutique especialitzada en finques rústiques, vinyes i possessions històriques al centre de Mallorca.",
      de: "Boutique-Immobilienagentur, exklusiv spezialisiert auf den Verkauf von Fincas, Weinberggütern und historischen Herrenhäusern.",
    },
    fullDescription: {
      es: "Con sede en Santa Maria del Camí, gestiona una selecta cartera 'off-market' de fincas con amplios terrenos de olivos y viñedo, establos ecuestres y casas señoriales restauradas con los más altos estándares de calidad y privacidad.",
      en: "Headquartered in Santa Maria del Camí, managing an exclusive off-market portfolio of authentic country estates, equestrian properties, and restored manors.",
      ca: "A Santa Maria del Camí, gestiona finques rústiques exclusives amb oliveres, vinyes i cavalleries amb total discreció.",
      de: "In Santa Maria del Camí ansässig, vermittelt die Agentur diskret exklusive Fincas, Reitanwesen und historische Landsitze im Inselinneren.",
    },
    highlights: {
      es: [
        "Cartera exclusiva 'Off-Market' de propiedades confidenciales",
        "Especialistas en suelo rústico protegido y viñedos con DO",
        "Asesoramiento urbanístico sobre cédulas de habitabilidad y ANEI",
        "Atención multilingüe en alemán, inglés, español y sueco",
      ],
      en: [
        "Exclusive off-market portfolio for discreet acquisitions",
        "Specialists in protected rustic land and registered vineyards",
        "Urban planning advice regarding habitability and zoning (ANEI)",
        "Multilingual team fluent in German, English, and Spanish",
      ],
      ca: [
        "Cartera 'Off-Market' confidencial",
        "Especialistes en sòl rústic i vinyes",
        "Assessorament urbanístic en cèdules d'habitabilitat",
        "Equip multilingüe",
      ],
      de: [
        "Exklusives Off-Market-Portfolio für höchste Diskretion",
        "Spezialisten für rustikales Baurecht und Weinberganlagen",
        "Rechtliche Prüfung von Cédulas und ANEI-Zonierung",
        "Mehrsprachige Betreuung auf Deutsch, Englisch und Spanisch",
      ],
    },
    servicesProvided: {
      es: [
        "Intermediación en compraventa de fincas rústicas de lujo",
        "Valoración y tasación inmobiliaria de terrenos agrícolas",
        "Búsqueda personalizada de propiedades para inversores (Property Hunter)",
        "Gestión de licencias de agroturismo y alquiler vacacional",
      ],
      en: [
        "Luxury rustic estate sales brokerage",
        "Agricultural land and vineyard valuation appraisals",
        "Dedicated buyer property hunter search service",
        "Agrotourism and holiday rental license advisory",
      ],
      ca: [
        "Intermediació en compravenda de finques rústiques",
        "Taxació de terrenys agrícoles",
        "Cerca personalitzada de propietats",
        "Gestió de llicències d'agroturisme",
      ],
      de: [
        "Vermittlung von Fincas und Landhäusern der Spitzenklasse",
        "Wertermittlung von Agrar- und Weinland",
        "Individueller Suchauftrag (Property Hunting)",
        "Beratung zu Agroturismo- und Ferienvermietungslizenzen",
      ],
    },
  },
  {
    slug: "port-andratx-exclusive-waterfront-villas",
    name: "Port d'Andratx Luxury Waterfront Real Estate",
    category: "inmobiliaria-villas",
    sectorFolder: "inmobiliaria-villas",
    sectorArrayName: "INMOBILIARIA_SERVICES",
    subcategories: ["villas-primera-linea", "propiedades-puerto-andratx", "apartamentos-puerto"],
    zone: "calvia-andratx",
    address: "Avinguda de Gabriel Roca i Garcías, 19, 07157 Port d'Andratx",
    coordinates: { lat: 39.5442, lng: 2.3856 },
    rating: 4.9,
    reviewCount: 130,
    priceRange: "€€€€",
    phone: "+34 971 671 880",
    website: "https://portandratxwaterfront.com",
    schedule: "Lunes a Viernes: 09:30 - 19:30, Sábados: 10:00 - 15:00",
    tags: ["zona:port-d-andratx", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Inmobiliaria de referencia en Port d'Andratx para villas contemporáneas en primera línea de mar, Cala Llamp, Monport y La Mola.",
      en: "Premier Port d'Andratx real estate agency for contemporary sea-view villas in Cala Llamp, Monport, and La Mola.",
      ca: "Immobiliària de referència al Port d'Andratx per a vil·les en primera línia de mar a Cala Llamp i La Mola.",
      de: "Führende Immobilienagentur in Port d'Andratx für moderne Luxusvillen mit Meerblick in Cala Llamp, Monport und La Mola.",
    },
    fullDescription: {
      es: "Especializada en el enclave más codiciado del Mediterráneo, esta agencia ofrece acceso a las mansiones y villas de diseño más espectaculares de Port d'Andratx, con vistas abiertas al atardecer sobre Sa Dragonera y amarres directos.",
      en: "Specializing in the Mediterranean's most sought-after coastal haven, featuring designer cliffside villas overlooking Sa Dragonera.",
      ca: "Especialitzada en el Port d'Andratx, amb accés a les millors mansions de disseny davant la mar i vistes a Sa Dragonera.",
      de: "Spezialisiert auf Port d'Andratx: exklusive Klippenvillen, Designer-Architektur und Panoramablick auf Sa Dragonera und den Yachthafen.",
    },
    highlights: {
      es: [
        "Presencia de más de 20 años en primera línea del puerto",
        "Selección exclusiva de villas con vistas panorámicas al mar",
        "Servicio integral de conserjería inmobiliaria y 'Relocation'",
        "Red internacional de compradores cualificados de Europa",
      ],
      en: [
        "20+ years of waterfront presence in the port",
        "Curated selection of front-line cliff villas with sunset views",
        "Full real estate concierge and luxury relocation service",
        "Prime network of qualified buyers across Europe",
      ],
      ca: [
        "Més de 20 anys d'experiència al Port d'Andratx",
        "Vil·les en primera línia amb vistes a la posta de sol",
        "Servei de 'Relocation' i consergeria",
        "Xarxa internacional de compradors",
      ],
      de: [
        "Über 20 Jahre Erfahrung an der Hafenpromenade",
        "Exklusives Portfolio an Villen mit Meer- und Hafenblick",
        "Umfassender Relocation- und Concierge-Service",
        "Internationales Käufernetzwerk in DACH, UK und Skandinavien",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de villas de lujo y áticos en Port d'Andratx",
        "Asesoramiento en proyectos de obra nueva y reformas de lujo",
        "Valoración pericial de propiedades de alto standing",
        "Acompañamiento integral hasta la firma en notaría",
      ],
      en: [
        "Luxury villa and penthouse sales in Port d'Andratx",
        "Advisory on high-end new builds and modern architectural refits",
        "Certified expert valuation of ultra-prime properties",
        "Full closing assistance through Spanish notary execution",
      ],
      ca: [
        "Venda de vil·les i àtics de luxe",
        "Assessorament en projectes d'obra nova",
        "Taxació pericial de propietats de luxe",
        "Acompanyament a notaria",
      ],
      de: [
        "Verkauf von Luxusvillen und Penthäusern in Port d'Andratx",
        "Beratung bei Neubau- und Sanierungsprojekten",
        "Gutachterliche Wertermittlung im High-End-Segment",
        "Vollständige notarielle und steuerliche Kaufbegleitung",
      ],
    },
  },

  // ── SECTOR 5: EDUCACIÓN & FORMACIÓN ──
  {
    slug: "mallorca-academy-languages-palma-centro",
    name: "Mallorca International Language Academy Palma",
    category: "academias-idiomas-formacion",
    sectorFolder: "educacion-formacion",
    sectorArrayName: "EDUCACION_SERVICES",
    subcategories: ["espanol-para-extranjeros", "aleman-intensivo", "ingles-cambridge"],
    zone: "palma",
    address: "Carrer dels Oms, 28, 07003 Palma",
    coordinates: { lat: 39.5748, lng: 2.6512 },
    rating: 4.9,
    reviewCount: 155,
    priceRange: "€€",
    phone: "+34 971 715 420",
    website: "https://mallorcalanguageacademy.com",
    schedule: "Lunes a Viernes: 08:30 - 20:30, Sábados: 09:30 - 13:30",
    tags: ["zona:palma-centro", "product:accesible", "mod:hibrido"],
    shortDescription: {
      es: "Academia de idiomas en el centro de Palma acreditada por el Instituto Cervantes: cursos intensivos de español (DELE/CCSE), alemán e inglés con profesores nativos.",
      en: "Language academy in central Palma accredited by Instituto Cervantes: intensive Spanish (DELE/CCSE), German, and Cambridge English.",
      ca: "Acadèmia d'idiomes al centre de Palma acreditada per l'Institut Cervantes amb cursos de castellà, alemany i anglès.",
      de: "Sprachakademie im Zentrum von Palma, akkreditiert vom Instituto Cervantes: Intensivkurse für Spanisch (DELE/CCSE), Deutsch und Englisch.",
    },
    fullDescription: {
      es: "Situada en la peatonal calle Oms de Palma, ofrece cursos en grupos reducidos y clases particulares para residentes, profesionales de empresas internacionales y personas en proceso de obtención de la nacionalidad española.",
      en: "Located on pedestrian Carrer dels Oms, offering small group courses and private tuition for expats, corporate teams, and Spanish nationality candidates.",
      ca: "Al carrer dels Oms de Palma, ofereix cursos en grups reduïts i classes particulars per a residents i empreses.",
      de: "In der Fußgängerzone Carrer dels Oms gelegen, bietet die Schule Kleingruppen- und Einzelunterricht für Residenten und Firmenmitarbeiter.",
    },
    highlights: {
      es: [
        "Centro Acreditado por el Instituto Cervantes",
        "Centro examinador oficial DELE y CCSE para nacionalidad",
        "Profesorado nativo titulado y metodología comunicativa",
        "Modalidades presencial en Palma y online en vivo",
      ],
      en: [
        "Instituto Cervantes Accredited Language Centre",
        "Official examination venue for DELE and CCSE nationality tests",
        "Certified native teachers with communicative methodology",
        "Flexible in-person Palma classes and live online formats",
      ],
      ca: [
        "Centre Acreditat per l'Institut Cervantes",
        "Centre d'examen oficial DELE i CCSE",
        "Professors natius titulats",
        "Modalitat presencial i online",
      ],
      de: [
        "Akkreditiertes Zentrum des Instituto Cervantes",
        "Offizielles Prüfungszentrum für DELE- und CCSE-Einbürgerungstests",
        "Muttersprachliche Lehrkräfte mit Hochschulabschluss",
        "Präsenzunterricht in Palma und Live-Online-Kurse",
      ],
    },
    servicesProvided: {
      es: [
        "Cursos intensivos y extensivos de español para extranjeros",
        "Preparación oficial de exámenes Cambridge (B2 First, C1 Advanced)",
        "Cursos de alemán para hostelería y náutica",
        "Clases 'One-to-One' a medida para directivos",
      ],
      en: [
        "Intensive and semi-intensive Spanish for expats",
        "Official Cambridge English exam prep (B2 First, C1 Advanced)",
        "German language training for hospitality and yacht crew",
        "Tailored executive 1-on-1 language coaching",
      ],
      ca: [
        "Cursos de castellà per a estrangers",
        "Preparació d'exàmens Cambridge",
        "Cursos d'alemany per a empreses",
        "Classes 'One-to-One' personalitzades",
      ],
      de: [
        "Intensiv- und Abendkurse Spanisch für Residenten",
        "Vorbereitung auf Cambridge-Prüfungen (B2 First, C1 Advanced)",
        "Deutschkurse für Gastronomie und Yachting",
        "Individueller Einzelunterricht für Führungskräfte",
      ],
    },
  },
];

// Ingest candidates
console.log("Ingesting mass curated batch of 8 new services across diverse sectors...");
ingestBatch(MASS_CURATED_SERVICES);
