import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_11: BusinessDataInput[] = [
  // ── 1. INMOBILIARIA & VILLAS DE LUJO ──
  {
    slug: "kensington-international-real-estate-palma-lujo",
    name: "Kensington International Real Estate Mallorca Palma",
    category: "inmobiliaria-villas",
    sectorFolder: "inmobiliaria-villas",
    sectorArrayName: "INMOBILIARIA_SERVICES",
    subcategories: ["compraventa-villas-lujo", "alquiler-propiedades-premium", "inversion-inmobiliaria"],
    zone: "palma",
    address: "Carrer de Jaume III, 5, 07012 Palma",
    coordinates: { lat: 39.5714, lng: 2.6456 },
    rating: 4.9,
    reviewCount: 412,
    priceRange: "€€€€",
    phone: "+34 971 710 075",
    website: "https://kensington-international.com/mallorca",
    schedule: "Lunes a Viernes: 09:00 - 18:30; Sábado: 10:00 - 14:00",
    tags: ["zona:palma-centro", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Boutique inmobiliaria de lujo en Palma especializada en villas señoriales, propiedades frente al mar y fincas en Son Vida, Andratx y la Serra de Tramuntana.",
      en: "Luxury real estate boutique in Palma specialising in prime villas, waterfront estates, and luxury fincas in Son Vida, Andratx, and the Tramuntana range.",
      ca: "Boutique immobiliària de luxe a Palma especialitzada en vil·les senyorials, propietats davant del mar i finques a Son Vida i Andratx.",
      de: "Luxus-Immobilienboutique in Palma für erstklassige Villen, Anwesen am Meer und Fincas in Son Vida, Andratx und dem Tramuntana-Gebirge.",
    },
    fullDescription: {
      es: "Kensington Fine Properties Mallorca ofrece asesoramiento inmobiliario exclusivo con licencias internacionales en las principales zonas residenciales de la isla: Palma Centro, Son Vida, Puerto Portals, Bendinat, Port d'Andratx y Sóller.",
      en: "Kensington Fine Properties Mallorca delivers exclusive real estate advisory across the island's prime residential enclaves: Central Palma, Son Vida, Puerto Portals, Bendinat, Port d'Andratx, and Sóller.",
      ca: "Kensington Fine Properties Mallorca ofereix assessorament immobiliari exclusiu a Palma Centre, Son Vida, Puerto Portals, Bendinat i Port d'Andratx.",
      de: "Kensington Fine Properties Mallorca bietet exklusive Immobilienberatung in Palmas Altstadt, Son Vida, Puerto Portals, Bendinat, Port d'Andratx und Sóller.",
    },
    highlights: {
      es: [
        "Agencia galardonada con la distinción International Property Awards Best Real Estate Agency",
        "Red global de inversores privados y family offices de Europa y América",
        "Consultores bilingües en español, inglés, alemán, francés y ruso",
        "Asesoramiento jurídico y fiscal integral para compradores extranjeros",
      ],
      en: [
        "International Property Awards winner for Best Real Estate Agency",
        "Global network of private investors and family offices across Europe and the Americas",
        "Bilingual consultants in Spanish, English, German, French, and Russian",
        "Full legal and tax guidance for international buyers",
      ],
      ca: [
        "Agència guardonada amb l'International Property Awards Best Real Estate Agency",
        "Xarxa global d'inversors privats i family offices",
        "Consultors en cinc idiomes",
        "Assessorament jurídic i fiscal integral",
      ],
      de: [
        "Ausgezeichnet mit den International Property Awards als beste Immobilienagentur",
        "Globales Netzwerk privater Investoren und Family Offices",
        "Beratung auf Deutsch, Englisch, Spanisch, Französisch und Russisch",
        "Vollständige Rechts- und Steuerberatung für internationale Käufer",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de villas de lujo, chalets independientes y fincas rústicas señoriales",
        "Valoración y peritaje inmobiliario profesional oficial",
        "Búsqueda de propiedades 'Off-Market' para clientes de alto patrimonio (HNWI)",
        "Gestión de alquileres vacacionales de lujo y larga estancia",
      ],
      en: [
        "Sales of luxury villas, detached chalets, and historic country estates",
        "Professional official property valuation and appraisal services",
        "Off-market property search for high-net-worth individuals (HNWIs)",
        "Luxury holiday rental and long-term lease management",
      ],
      ca: [
        "Venda de vil·les de luxe, xalets i finques rústiques",
        "Valoració i peritatge immobiliari professional",
        "Cerca de propietats off-market per a clients d'alt patrimoni",
        "Gestió de lloguers de luxe",
      ],
      de: [
        "Verkauf von Luxusvillen, freistehenden Chalets und Landanwesen",
        "Professionelle offizielle Wertermittlung und Immobiliengutachten",
        "Off-Market-Suche für vermögende Privatkunden (HNWIs)",
        "Luxus-Ferienvermietung und Langzeitverwaltung",
      ],
    },
  },

  // ── 2. MOTOR & ALQUILER DE COCHES ──
  {
    slug: "alquiler-coches-lujo-mallorca-elite-car-rental-palma",
    name: "Elite Car Mallorca Alquiler Coches Lujo & Deportivos Palma",
    category: "motor-transporte",
    sectorFolder: "motor-transporte",
    sectorArrayName: "MOTOR_SERVICES",
    subcategories: ["alquiler-ferrari-lamborghini", "coches-lujo-mallorca", "transfer-aeropuerto-vip"],
    zone: "palma",
    address: "Carrer de Manacor, 36, Bajos, 07006 Palma",
    coordinates: { lat: 39.5734, lng: 2.6671 },
    rating: 4.9,
    reviewCount: 412,
    priceRange: "€€€€",
    phone: "+34 971 462 290",
    website: "https://elitecarrentalmallorca.com",
    schedule: "Diario: 08:00 - 21:00 (365 días / Entrega en aeropuerto 24h)",
    tags: ["zona:palma-centro", "product:alquiler-coches-lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Alquiler de coches de lujo y deportivos de alta gama en Mallorca: Ferrari, Lamborghini, Porsche, Range Rover y McLaren con entrega en aeropuerto, hotel o puerto deportivo.",
      en: "Luxury and sports car hire in Mallorca: Ferrari, Lamborghini, Porsche, Range Rover, and McLaren with delivery to airport, hotel, or marina.",
      ca: "Lloguer de cotxes de luxe i esportius a Mallorca: Ferrari, Lamborghini, Porsche i McLaren amb lliurament a l'aeroport, hotel o port esportiu.",
      de: "Luxus- und Sportwagenvermietung auf Mallorca: Ferrari, Lamborghini, Porsche, Range Rover und McLaren mit Lieferung an Flughafen, Hotel oder Marina.",
    },
    fullDescription: {
      es: "Flota de más de 60 vehículos de lujo y deportivos de última generación. Servicio de transfer VIP con chófer profesional disponible las 24 horas. Entrega y recogida en todo Mallorca sin cargos extra. Seguros a todo riesgo incluidos con cobertura ante rotura de llanta y cristales.",
      en: "Fleet of 60+ latest-generation luxury and sports vehicles. 24-hour VIP chauffeur transfer service. Island-wide delivery and collection at no extra charge. Comprehensive insurance with tyre and windscreen cover included.",
      ca: "Flota de més de 60 vehicles de luxe i esportius. Servei de transfer VIP amb xofer professional 24 hores. Lliurament a tota Mallorca sense càrrecs extra.",
      de: "Flotte von 60+ Luxus- und Sportwagen neuester Generation. 24h VIP-Chauffeur-Service. Inselweite Lieferung ohne Aufpreis. Vollkasko mit Reifen- und Windschutzscheibenschutz inklusive.",
    },
    highlights: {
      es: [
        "Flota de más de 60 vehículos: Ferrari Roma, Lamborghini Urus, McLaren GT, Porsche 911",
        "Entrega 24h en aeropuerto PMI, hoteles y puertos de toda Mallorca sin cargo extra",
        "Seguros a todo riesgo con franquicia cero opcionales incluidos",
        "Chófer privado bilingüe disponible por horas o días completos",
      ],
      en: [
        "Fleet of 60+ vehicles: Ferrari Roma, Lamborghini Urus, McLaren GT, Porsche 911",
        "24h delivery to PMI airport, hotels, and marinas across Mallorca at no extra cost",
        "Optional zero-excess comprehensive insurance packages available",
        "Bilingual private chauffeur available by the hour or full day",
      ],
      ca: [
        "Flota de més de 60 vehicles: Ferrari Roma, Lamborghini Urus, McLaren GT",
        "Lliurament 24h a l'aeroport PMI, hotels i ports",
        "Assegurances a tot risc amb franquícia zero opcionals",
        "Xofer privat bilingüe per hores o dies complets",
      ],
      de: [
        "Flotte von 60+ Fahrzeugen: Ferrari Roma, Lamborghini Urus, McLaren GT, Porsche 911",
        "24h Lieferung an PMI-Flughafen, Hotels und Marinas ohne Aufpreis",
        "Optionale Vollkasko-Pakete mit Nullselbstbehalt",
        "Zweisprachiger Privatchauffeur stundenweise oder tageweise",
      ],
    },
    servicesProvided: {
      es: [
        "Alquiler de coches deportivos: Ferrari, Lamborghini, McLaren, Porsche 911 GT3",
        "Alquiler de SUVs y todoterrenos de lujo: Range Rover, Bentley Bentayga, Rolls-Royce Cullinan",
        "Servicio de chófer privado con Mercedes Clase S o BMW Serie 7",
        "Alquiler de coches clásicos y descapotables para bodas y eventos especiales",
      ],
      en: [
        "Sports car rental: Ferrari, Lamborghini, McLaren, Porsche 911 GT3",
        "Luxury SUV and 4x4 hire: Range Rover, Bentley Bentayga, Rolls-Royce Cullinan",
        "Private chauffeur service in Mercedes S-Class or BMW 7 Series",
        "Classic and convertible car hire for weddings and special events",
      ],
      ca: [
        "Lloguer de cotxes esportius: Ferrari, Lamborghini, McLaren, Porsche 911",
        "SUVs de luxe: Range Rover, Bentley Bentayga, Rolls-Royce Cullinan",
        "Xofer privat amb Mercedes Classe S o BMW Sèrie 7",
        "Cotxes clàssics i descapotables per a casaments",
      ],
      de: [
        "Sportwagen: Ferrari, Lamborghini, McLaren, Porsche 911 GT3",
        "Luxus-SUV: Range Rover, Bentley Bentayga, Rolls-Royce Cullinan",
        "Privatchauffeur im Mercedes S-Klasse oder BMW 7er",
        "Oldtimer und Cabrios für Hochzeiten und Events",
      ],
    },
  },

  // ── 3. GOLF & CLUBS ──
  {
    slug: "golf-son-muntaner-palma-arabella-hotel",
    name: "Golf Son Muntaner Club & Academy Palma (Arabella Hotels)",
    category: "golf-clubs-mallorca",
    sectorFolder: "deportes-fitness",
    sectorArrayName: "DEPORTES_SERVICES",
    subcategories: ["campo-golf-palma", "academia-golf-mallorca", "golf-hotel-lujo"],
    zone: "palma",
    address: "Urbanización Son Vida, 07013 Palma",
    coordinates: { lat: 39.5978, lng: 2.6121 },
    rating: 4.9,
    reviewCount: 645,
    priceRange: "€€€€",
    phone: "+34 971 783 030",
    website: "https://arabellasoncampos.com/golf/son-muntaner",
    schedule: "Diario: 07:30 - Sunset (todo el año)",
    tags: ["zona:palma-centro", "product:golf", "mod:cita-previa"],
    shortDescription: {
      es: "Campo de golf par 72 de 18 hoyos en la exclusiva urbanización Son Vida de Palma: diseño de Folco Nardi con vistas a la bahía, academia de golf con pros certificados PGA y putting green.",
      en: "Par-72 18-hole golf course in Palma's exclusive Son Vida estate: Folco Nardi design with bay views, PGA-certified academy, and pro-quality putting green.",
      ca: "Camp de golf par 72 de 18 forats a la urbanització exclusiva de Son Vida: disseny de Folco Nardi amb vistes a la badia i acadèmia de golf amb pros PGA.",
      de: "Par-72, 18-Loch-Golfplatz in Palmas exklusiver Son-Vida-Urbanisation: Folco-Nardi-Design mit Blick auf die Bucht, PGA-zertifizierte Akademie und Profi-Puttinggrün.",
    },
    fullDescription: {
      es: "Son Muntaner es uno de los tres campos de golf del grupo Arabella Hotels en Mallorca, junto con Son Vida y Son Quint. Ofrece 18 hoyos con bunkers de arena blanca, obstáculos de agua y un recorrido que se integra en el paisaje de Son Vida, con magníficas vistas a la bahía de Palma y la Serra de Tramuntana.",
      en: "Son Muntaner is one of three Arabella Hotels golf courses in Mallorca, alongside Son Vida and Son Quint. 18 holes with white sand bunkers, water hazards, and a course woven into the Son Vida landscape with stunning views of Palma Bay and the Tramuntana.",
      ca: "Son Muntaner és un dels tres camps del grup Arabella Hotels a Mallorca. 18 forats amb búnquers de sorra blanca, obstacles d'aigua i vistes a la badia de Palma.",
      de: "Son Muntaner ist einer von drei Arabella-Hotels-Golfplätzen auf Mallorca. 18 Löcher mit Weißsandbunkern, Wasserhindernissen und Blick auf die Bucht von Palma und das Tramuntana-Gebirge.",
    },
    highlights: {
      es: [
        "Tres campos de golf en Son Vida: Son Muntaner (par 72), Son Vida (par 71) y Son Quint (par 70)",
        "Academia de golf con 8 profesionales PGA para clases individuales y grupales",
        "Driving range de 20 posiciones con césped natural y cubierta",
        "Restaurante 'Club House' con terraza panorámica y cocina mediterránea de mercado",
      ],
      en: [
        "Three Son Vida courses: Son Muntaner (par 72), Son Vida (par 71) and Son Quint (par 70)",
        "Golf academy with 8 PGA professionals for individual and group lessons",
        "20-bay driving range with natural grass and covered stations",
        "Club House restaurant with panoramic terrace and market-fresh Mediterranean cuisine",
      ],
      ca: [
        "Tres camps al complex Son Vida: Son Muntaner, Son Vida i Son Quint",
        "Acadèmia de golf amb 8 professionals PGA",
        "Driving range de 20 posicions amb gespa natural",
        "Restaurant 'Club House' amb terrassa panoràmica",
      ],
      de: [
        "Drei Plätze im Son-Vida-Komplex: Son Muntaner, Son Vida und Son Quint",
        "Golfakademie mit 8 PGA-Pros für Einzel- und Gruppenunterricht",
        "20-Abschlagbahnen mit Naturrasen und überdachten Stationen",
        "Clubhaus-Restaurant mit Panoramaterrasse und mediterraner Küche",
      ],
    },
    servicesProvided: {
      es: [
        "Green fees para 18 hoyos en cualquiera de los tres campos del complejo Son Vida",
        "Clases de golf individuales y grupales con profesionales certificados PGA",
        "Alquiler de material de golf: palos, carros eléctricos y buggy",
        "Bonos de golf multi-ronda y membresías anuales para residentes",
      ],
      en: [
        "Green fees for 18 holes at any of the three Son Vida complex courses",
        "Individual and group golf lessons with PGA-certified professionals",
        "Golf equipment hire: clubs, electric trolleys, and buggies",
        "Multi-round golf vouchers and annual memberships for residents",
      ],
      ca: [
        "Green fees per a 18 forats als tres camps del complex Son Vida",
        "Classes de golf individuals i grupals amb pros PGA",
        "Lloguer de material: pals, carros elèctrics i buggy",
        "Bons multi-ronda i membresia anual per a residents",
      ],
      de: [
        "Greenfees für 18 Löcher an jedem der drei Son-Vida-Plätze",
        "Einzel- und Gruppenunterricht mit PGA-zertifizierten Pros",
        "Leihausrüstung: Schläger, Elektro-Trolleys und Buggys",
        "Mehr-Runden-Voucher und Jahresmitgliedschaften für Residenten",
      ],
    },
  },

  // ── 4. ARTESANÍA & VIDRIO SOPLADO ──
  {
    slug: "menestralia-vidre-bufat-artesanal-campanet",
    name: "Menestralia Vidre Bufat Artesanal Campanet (1965)",
    category: "vidrio-ceramica-artesanal",
    sectorFolder: "artesania-manufactura",
    sectorArrayName: "ARTESANIA_SERVICES",
    subcategories: ["vidrio-soplado-mallorca", "cristaleria-artesana-norte", "lamparas-vidrio-artesanal"],
    zone: "raiguer-pla",
    address: "Carretera Palma-Alcúdia, km 36, 07310 Campanet",
    coordinates: { lat: 39.7712, lng: 2.9641 },
    rating: 4.8,
    reviewCount: 389,
    priceRange: "€€",
    phone: "+34 971 516 022",
    website: "https://menestralia.es",
    schedule: "Lunes a Sábado: 09:00 - 18:30; Domingo: 09:30 - 13:30",
    tags: ["zona:raiguer-pla", "product:vidrio-soplado", "mod:walk-in"],
    shortDescription: {
      es: "Fábrica artesanal de vidrio soplado a pie de autopista en Campanet: demostraciones en vivo de soplado tradicional con caña y exposición de lámparas y artesanía balear.",
      en: "Artisan glassblowing workshop at Campanet along the northern highway: live traditional blowpipe demonstrations, blown glass lamps, and Balearic craft gallery.",
      ca: "Fàbrica artesanal de vidre bufat a Campanet: demostracions en viu de bufat tradicional i exposició de llànties i artesania balear.",
      de: "Handwerkliche Glasbläserei in Campanet an der Nordautobahn: Live-Vorführungen der traditionellen Glasbläserkunst und Ausstellung von Leuchten und Kunsthandwerk.",
    },
    fullDescription: {
      es: "Fundada en 1965 junto a las Cuevas de Campanet, Menestralia mantiene viva la tradición del vidrio soplado artesano del norte de Mallorca. Especialistas en lámparas rústicas balears, tulipas y recipientes decorativos hechos por maestros vidrieros.",
      en: "Established in 1965 near Campanet Caves, Menestralia preserves northern Mallorca's handblown glassblowing legacy, specialising in rustic Balearic chandeliers and decorative glassware.",
      ca: "Fundada el 1965 a prop de les Coves de Campanet, Menestralia manté viva la tradició del vidre bufat artesà del nord de Mallorca.",
      de: "1965 nahe den Höhlen von Campanet gegründet: Menestralia bewahrt die Glasbläsertradition Nordmallorcas mit Spezialisierung auf rustikale balearische Kronleuchter.",
    },
    highlights: {
      es: [
        "Taller artesano tradicional con soplado en vivo frente a los visitantes",
        "Especialistas en la fabricación a mano de lámparas rústicas mallorquinas",
        "Espacio amplio de exposición con más de 1.000 artículos de cristal y cerámica",
        "Ubicación estratégica junto a las Cuevas de Campanet",
      ],
      en: [
        "Traditional artisan workshop with live glassblowing in front of visitors",
        "Specialists in handcrafted rustic Mallorcan blown-glass chandeliers",
        "Spacious showroom featuring 1,000+ glass and ceramic items",
        "Strategic location adjacent to Campanet Caves",
      ],
      ca: [
        "Taller artesà tradicional amb bufat en viu",
        "Especialistes en la fabricació a mà de llànties rústiques mallorquines",
        "Exposició amb més de 1.000 articles de vidre i ceràmica",
        "Ubicació al costat de les Coves de Campanet",
      ],
      de: [
        "Traditionelle Handwerkswerkstatt mit Live-Glasblasen vor Besuchern",
        "Spezialisten für handgefertigte rustikale Kronleuchter aus Mallorquiner Glas",
        "Großer Showroom mit 1.000+ Glas- und Keramikartikeln",
        "Lage direkt bei den Höhlen von Campanet",
      ],
    },
    servicesProvided: {
      es: [
        "Demostraciones públicas diarias de soplado de vidrio con caña de hierro",
        "Venta directa de lámparas artesanas, floreros, botellas y cristalería",
        "Restauración y sustitución de tulipas de cristal antiguas por encargo",
        "Envíos empaquetados y asegurados a cualquier país del mundo",
      ],
      en: [
        "Daily public demonstrations of traditional blowpipe glassmaking",
        "Direct sales of artisan chandeliers, vases, bottles, and glassware",
        "Bespoke restoration and replacement of antique glass shades",
        "Insured and reinforced packaging for worldwide shipping",
      ],
      ca: [
        "Demostracions públiques diàries de bufat de vidre",
        "Venda directa de llànties artesanes, florers i cristalleria",
        "Restauració de tulipes de vidre antigues",
        "Enviaments assegurats a tot el món",
      ],
      de: [
        "Tägliche öffentliche Vorführungen der Pfeifen-Glasbläserei",
        "Direktverkauf von Kronleuchtern, Vasen, Flaschen und Gläsern",
        "Restaurierung und Anfertigung antiker Lampenschirme nach Maß",
        "Sicherer weltweiter Frachtversand mit Spezialverpackung",
      ],
    },
  },

  // ── 5. RESTAURANTES & BEACH CLUBS ──
  {
    slug: "beach-club-illetes-mhares-sea-club-calvia",
    name: "Mhares Sea Club Beach Club & Restaurante Illetes Calvià",
    category: "beach-clubs-rooftops",
    sectorFolder: "gastronomia-restaurantes",
    sectorArrayName: "GASTRONOMIA_SERVICES",
    subcategories: ["beach-club-mallorca", "restaurante-frente-mar", "sunset-bar-illetes"],
    zone: "calvia-andratx",
    address: "Carretera d'Illetes, 39, 07181 Illetes, Calvià",
    coordinates: { lat: 39.5261, lng: 2.5812 },
    rating: 4.8,
    reviewCount: 1024,
    priceRange: "€€€€",
    phone: "+34 971 402 762",
    website: "https://mharesmallorca.com",
    schedule: "Diario: 11:00 - 23:00 (Temporada: Mayo – Octubre)",
    tags: ["zona:calvia-andratx", "product:bares-playa-chiringuitos", "mod:cita-previa"],
    shortDescription: {
      es: "Beach club y restaurante de referencia en las aguas turquesas de Illetes (Calvià): gastronomía mediterránea de autor, zona de baño privado, piscina infinita con DJ y sunsets legendarios.",
      en: "Iconic beach club and restaurant on the turquoise waters of Illetes (Calvià): signature Mediterranean cuisine, private swimming area, infinity pool with DJ sessions, and legendary sunsets.",
      ca: "Beach club i restaurant de referència a les aigües turqueses d'Illetes (Calvià): gastronomia mediterrània d'autor, zona de bany privada i piscina infinita amb DJ.",
      de: "Ikones Beach Club und Restaurant an den türkisfarbenen Gewässern von Illetes (Calvià): Signature-Mittelmeerküche, privater Badebereich, Infinity-Pool mit DJ und legendäre Sonnenuntergänge.",
    },
    fullDescription: {
      es: "Mhares Sea Club está integrado directamente en las rocas de Illetes con acceso privado al mar Mediterráneo. El restaurante sirve una cocina mediterránea de producto con pescados y mariscos del día, arroces melosos y cócteles de autor. La zona lounge y la piscina infinita se fusionan con el horizonte marino en uno de los atardeceres más fotografiados de Mallorca.",
      en: "Mhares Sea Club is built directly into the rocks of Illetes with private Mediterranean Sea access. The restaurant serves product-driven Mediterranean cuisine: fresh fish, daily shellfish, creamy rice dishes, and signature cocktails. The lounge and infinity pool merge with the sea horizon at one of Mallorca's most photographed sunset spots.",
      ca: "Mhares Sea Club s'integra a les roques d'Illetes amb accés privat al mar. El restaurant serveix cuina mediterrània de producte amb peixos i mariscos del dia i arrossos melosos.",
      de: "Mhares Sea Club liegt direkt in den Felsen von Illetes mit privatem Meereszugang. Das Restaurant serviert produktgetriebene mediterrane Küche: frischer Fisch, Meeresfrüchte, cremige Reisgerichte und Signature-Cocktails.",
    },
    highlights: {
      es: [
        "Ubicación privilegiada sobre las rocas de Illetes con acceso privado al mar",
        "Piscina infinita con vistas al horizonte y sesiones de DJ ambient en el lounge",
        "Cocina mediterránea de autor con pescados y mariscos de la lonja de Palma",
        "Uno de los atardeceres más espectaculares de Mallorca (Top Sunsets CN Traveller)",
      ],
      en: [
        "Prime cliffside location at Illetes with exclusive private sea access",
        "Infinity pool merging with sea horizon and ambient DJ lounge sessions",
        "Signature Mediterranean cuisine with daily fresh fish from Palma fish market",
        "One of Mallorca's most spectacular sunsets (CN Traveller Top Sunsets)",
      ],
      ca: [
        "Ubicació privilegiada a les roques d'Illetes amb accés privat al mar",
        "Piscina infinita amb DJ ambient al lounge",
        "Cuina mediterrània d'autor amb peix i marisc de la llotja",
        "Un dels millors atardejades de Mallorca",
      ],
      de: [
        "Privilegierte Felslage in Illetes mit exklusivem Privatmeereszugang",
        "Infinity-Pool am Meershorizont mit Ambient-DJ-Lounge",
        "Signature-Mittelmeerküche mit tagesfrischem Fisch vom Markt in Palma",
        "Einer der spektakulärsten Sonnenuntergänge Mallorcas (CN Traveller)",
      ],
    },
    servicesProvided: {
      es: [
        "Restaurante de cocina mediterránea con carta de temporada de producto local",
        "Beach club con tumbonas y sombrillas en acceso exclusivo al mar",
        "Piscina infinity con servicio de barra y sesiones de DJ (mediodía y sunset)",
        "Celebraciones privadas, bodas íntimas y eventos corporativos frente al mar",
      ],
      en: [
        "Mediterranean restaurant with seasonal menu of locally sourced produce",
        "Beach club with sun loungers and parasols on exclusive private sea access",
        "Infinity pool with poolside bar service and DJ sessions (midday and sunset)",
        "Private celebrations, intimate weddings, and corporate events by the sea",
      ],
      ca: [
        "Restaurant de cuina mediterrània amb carta de temporada",
        "Beach club amb lliteres i para-sols en accés exclusiu al mar",
        "Piscina infinity amb servei de barra i sessions de DJ",
        "Celebracions privades i bodes íntimes davant del mar",
      ],
      de: [
        "Mediterranes Restaurant mit Saisonkarte aus lokalen Produkten",
        "Beach Club mit Sonnenliegen und Sonnenschirmen am Privatmeereszugang",
        "Infinity-Pool mit Poolbar und DJ-Sessions (Mittag und Sonnenuntergang)",
        "Privatfeiern, intime Hochzeiten und Firmenevents am Meer",
      ],
    },
  },
];

console.log("Ingesting Batch 11 with Menestralia...");
ingestBatch(BATCH_11);
