import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_10: BusinessDataInput[] = [
  // ── 1. SPAS & BIENESTAR ──
  {
    slug: "spa-son-brull-hotel-wellness-pollensa",
    name: "Son Brull Hotel & Spa Boutique Pollença",
    category: "salud-bienestar",
    sectorFolder: "spas-bienestar",
    sectorArrayName: "SPAS_SERVICES",
    subcategories: ["spa-ecologico-mallorca", "hotel-boutique-relais-chateaux", "tratamientos-aceite-oliva"],
    zone: "alcudia-pollensa",
    address: "Carretera Palma-Pollença, km 50, 07460 Pollença",
    coordinates: { lat: 39.8654, lng: 3.0124 },
    rating: 4.9,
    reviewCount: 450,
    priceRange: "€€€€",
    phone: "+34 971 535 353",
    website: "https://sonbrull.com",
    schedule: "Diario: 10:00 - 20:00 (Abierto Abril – Noviembre)",
    tags: ["zona:alcudia-pollensa", "product:spa-circuitos-termales", "mod:cita-previa"],
    shortDescription: {
      es: "Spa ecológico en un antiguo monasterio del siglo XVIII en Pollença: tratamientos holísticos con aceite de oliva de cosecha propia, almendra y sal marina de Mallorca.",
      en: "Eco-spa in a restored 18th-century monastery in Pollença: holistic treatments featuring estate-harvested olive oil, almond, and Mallorcan sea salt.",
      ca: "Spa ecològic en un antic monestir del segle XVIII a Pollença: tractaments holístics amb oli d'oliva de collita pròpia i ametlla de Mallorca.",
      de: "Öko-Spa in einem restaurierten Kloster aus dem 18. Jahrhundert in Pollença: ganzheitliche Behandlungen mit eigenem Olivenöl, Mandel und Meersalz.",
    },
    fullDescription: {
      es: "Son Brull Spa forma parte del exclusivo complejo Relais & Châteaux en el norte de Mallorca. Es el primer spa de la isla en utilizar exclusivamente cosmética 100% natural elaborada con ingredientes procedentes de su propia finca orgánica.",
      en: "Part of the Relais & Châteaux estate in northern Mallorca, Son Brull is the island's pioneer eco-spa utilizing 100% natural organic skincare harvested directly from their farmland.",
      ca: "Part del complex Relais & Châteaux al nord de Mallorca, és el primer spa ecològic en utilitzar cosmètica 100% natural de la seva pròpia finca.",
      de: "Teil des Relais & Châteaux Anwesens im Norden Mallorcas: Pionier-Öko-Spa mit 100% natürlicher Kosmetik aus eigener Bio-Landwirtschaft.",
    },
    highlights: {
      es: [
        "Miembro oficial de la prestigiosa cadena Relais & Châteaux",
        "Cosmética ecológica propia con aceite de oliva virgen extra orgánico",
        "Piscina termal exterior climatizada con vistas al valle de Pollença",
        "Sauna sueca, hammam de vapor con eucalipto y zona de relax ajardinada",
      ],
      en: [
        "Official member of prestigious Relais & Châteaux",
        "Proprietary organic skincare made with estate extra virgin olive oil",
        "Outdoor heated thermal pool overlooking Pollença valley",
        "Swedish sauna, eucalyptus steam hammam, and lush relaxation garden",
      ],
      ca: [
        "Membre de la cadena Relais & Châteaux",
        "Cosmètica ecològica pròpia amb oli d'oliva verge extra",
        "Piscina termal exterior climatitzada a Pollença",
        "Sauna sueca, hammam i zona de relax ajardinada",
      ],
      de: [
        "Offizielles Mitglied von Relais & Châteaux",
        "Eigene Bio-Kosmetik mit eigenem nativen Olivenöl extra",
        "Beheizter Außen-Thermalpool mit Blick auf das Pollença-Tal",
        "Schwedische Sauna, Eukalyptus-Hammam und üppiger Entspannungsgarten",
      ],
    },
    servicesProvided: {
      es: [
        "Masaje insignia Son Brull con aceite de oliva tibio y almendra dulce",
        "Ritual corporal exfoliante con sal marina de Es Trenc y flores de lavanda",
        "Circuito de agua en spa con piscina climatizada, hammam y sauna",
        "Tratamientos faciales orgánicos con extractos botánicos de la Sierra de Tramuntana",
      ],
      en: [
        "Signature Son Brull massage using warm estate olive oil and sweet almond",
        "Exfoliating body ritual with Es Trenc sea salt and lavender flowers",
        "Hydrotherapy circuit with heated pool, hammam, and Swedish sauna",
        "Organic facial treatments with Tramuntana botanical extracts",
      ],
      ca: [
        "Massatge Son Brull amb oli d'oliva tibiat i ametlla dolça",
        "Ritual corporal exfoliant amb sal d'Es Trenc i lavanda",
        "Circuit d'aigua amb piscina climatitzada, hammam i sauna",
        "Tractaments facials orgànics amb extractes de la Tramuntana",
      ],
      de: [
        "Son Brull Signature-Massage mit warmem Olivenöl und Mandelöl",
        "Peeling-Körperritual mit Es Trenc Meersalz und Lavendelblüten",
        "Hydrotherapie-Kreislauf mit beheiztem Pool, Hammam und Sauna",
        "Bio-Gesichtsbehandlungen mit Botanik-Extrakten der Tramuntana",
      ],
    },
  },

  // ── 2. GUÍAS & EXPERIENCIAS ──
  {
    slug: "guia-senderismo-tramuntana-mallorca-expert",
    name: "Tramuntana Trekking Expert Guías de Montaña Soller",
    category: "guias-experiencias-tours",
    sectorFolder: "entretenimiento-ocio",
    sectorArrayName: "ENTRETENIMIENTO_SERVICES",
    subcategories: ["senderismo-sierra-tramuntana", "rutas-gr221-pedra-en-sec", "guias-montaña-mallorca"],
    zone: "tramuntana",
    address: "Plaça de la Constitució, 1, 07100 Sóller",
    coordinates: { lat: 39.7667, lng: 2.7158 },
    rating: 5.0,
    reviewCount: 389,
    priceRange: "€€",
    phone: "+34 634 812 445",
    website: "https://tramuntanatrekking.com",
    schedule: "Diario: 07:00 - 19:00 (Septiembre a Junio)",
    tags: ["zona:soller", "product:senderismo-rutas", "mod:cita-previa"],
    shortDescription: {
      es: "Guías de montaña certificados UIMLA en la Sierra de Tramuntana Patrimonio UNESCO: rutas del GR-221 Pedra en Sec, rutas al Puig Major, Barranc de Biniaraix y paso de sa Costera.",
      en: "UIMLA-certified mountain guides in the UNESCO Sierra de Tramuntana: GR-221 Pedra en Sec long-distance route, Puig Major, Biniaraix Gorge, and Sa Costera coastal path.",
      ca: "Guies de muntanya certificats UIMLA a la Serra de Tramuntana Patrimoni UNESCO: rutes del GR-221 Pedra en Sec i el Barranc de Biniaraix.",
      de: "UIMLA-zertifizierte Bergführer im UNESCO-Welterbe Tramuntana-Gebirge: GR-221 Trockenmauer-Fernwanderweg, Puig Major und Biniaraix-Schlucht.",
    },
    fullDescription: {
      es: "Empresa de guías de montaña certificados UIMLA (International Mountain Leader) con más de 15 años guiando la Serra de Tramuntana, declarada Patrimonio Mundial de la UNESCO en 2011. Especialistas en el trekking de varios días por el GR-221 y en rutas temáticas de flora, geología y patrimonio histórico de los caminos de piedra en seco.",
      en: "UIMLA-certified mountain guide company with 15+ years in the UNESCO Tramuntana mountains. Specialists in multi-day GR-221 trekking and themed botanical, geological, and dry-stone heritage walks.",
      ca: "Empresa de guies UIMLA amb més de 15 anys a la Serra de Tramuntana UNESCO. Especialistes en el GR-221 i rutes temàtiques de flora i patrimoni.",
      de: "UIMLA-zertifiziertes Bergführerunternehmen mit 15+ Jahren Erfahrung im UNESCO-Tramuntana-Gebirge: Mehrtagestouren auf dem GR-221 und thematische Botanik-/Kulturerbe-Wanderungen.",
    },
    highlights: {
      es: [
        "Guías certificados UIMLA (International Mountain Leader) y Montañeros de España",
        "Especialistas en el GR-221 Pedra en Sec – el gran trekking de Mallorca",
        "Grupos reducidos de máximo 8 personas para mayor seguridad e inmersión",
        "Materiales incluidos: bastones, mapa topográfico y botiquín de primeros auxilios",
      ],
      en: [
        "UIMLA International Mountain Leader and Spanish Mountaineering Federation certified",
        "GR-221 Pedra en Sec multi-day trek specialists",
        "Maximum group size of 8 for safety and immersion",
        "Included: trekking poles, topographic map, and first-aid kit",
      ],
      ca: [
        "Guies certificats UIMLA i Muntanyisme Espanyol",
        "Especialistes en el GR-221 Pedra en Sec",
        "Grups d'un màxim de 8 persones",
        "Materials inclosos: bastons, mapa i farmaciola",
      ],
      de: [
        "UIMLA-zertifizierte Bergführer und spanische Bergsteigerfederation",
        "GR-221 Mehrtageswanderung: die große Tramuntana-Tour",
        "Maximale Gruppengröße von 8 Personen",
        "Inkl. Wanderstöcke, Topographische Karte und Erste-Hilfe-Set",
      ],
    },
    servicesProvided: {
      es: [
        "Rutas guiadas de un día por la Serra de Tramuntana (8-22 km)",
        "Trekking de varios días por el GR-221 con alojamiento en refugios y fincas rurales",
        "Rutas botánicas y geológicas temáticas en grupos especializados",
        "Transfers desde Palma y Sóller incluidos en rutas de más de 15 km",
      ],
      en: [
        "Single-day guided hikes in the Serra de Tramuntana (8-22 km routes)",
        "Multi-day GR-221 trekking packages with mountain hut and rural estate accommodation",
        "Specialist botanical and geological themed group walks",
        "Transfers from Palma and Sóller included for routes over 15 km",
      ],
      ca: [
        "Rutes guiades d'un dia per la Tramuntana (8-22 km)",
        "Trekking de diversos dies pel GR-221 amb allotjament en refugis",
        "Rutes botàniques i geològiques temàtiques",
        "Trasllats des de Palma i Sóller inclosos",
      ],
      de: [
        "Eintägige Tagestouren im Tramuntana-Gebirge (8-22 km)",
        "Mehrtägige GR-221 Trekkingpakete mit Berghütten und Finca-Übernachtungen",
        "Botanische und geologische Themen-Gruppentouren",
        "Transfers von Palma und Sóller für Routen über 15 km inkl.",
      ],
    },
  },

  // ── 3. EVENTOS & BODAS DE LUJO ──
  {
    slug: "wedding-planner-lujo-mallorca-bella-rosa-events",
    name: "Bella Rosa Luxury Weddings & Events Mallorca Palma",
    category: "eventos-bodas-musica",
    sectorFolder: "entretenimiento-ocio",
    sectorArrayName: "ENTRETENIMIENTO_SERVICES",
    subcategories: ["wedding-planner-mallorca", "bodas-lujo-fincas", "eventos-corporativos"],
    zone: "palma",
    address: "Carrer de la Missió, 7A, 07003 Palma",
    coordinates: { lat: 39.5711, lng: 2.6523 },
    rating: 5.0,
    reviewCount: 178,
    priceRange: "€€€€",
    phone: "+34 971 221 890",
    website: "https://bellarosaevents.com",
    schedule: "Lunes a Viernes: 09:30 - 18:00 (Con cita previa)",
    tags: ["zona:palma-centro", "product:organizacion-bodas-eventos", "mod:cita-previa"],
    shortDescription: {
      es: "Wedding planner de lujo en Mallorca especializada en bodas exclusivas en fincas históricas, castillos y yates privados con coordinación integral y red de proveedores premium en la isla.",
      en: "Luxury wedding planner in Mallorca specializing in exclusive weddings at historic estates, castles, and private yachts with full coordination and a premium island supplier network.",
      ca: "Wedding planner de luxe a Mallorca especialitzada en bodes exclusives a finques històriques, castells i iots privats.",
      de: "Luxushochzeitsplanung auf Mallorca: exklusive Hochzeiten auf historischen Fincas, Schlössern und Privatyachten mit Vollkoordination.",
    },
    fullDescription: {
      es: "Bella Rosa Events lleva más de 12 años organizando bodas de destino de alta gama en Mallorca. Su equipo trilingüe gestiona bodas civiles y religiosas para parejas internacionales (británicas, alemanas, escandinavas y americanas). Acceso privilegiado a las mejores fincas de lujo: Son Marroig, La Fortaleza, Son Vida y castillos privados.",
      en: "12+ years organising high-end destination weddings in Mallorca. Trilingual team manages civil and religious ceremonies for international couples. Privileged access to Mallorca's finest estates: Son Marroig, La Fortaleza, Son Vida, and private castles.",
      ca: "Més de 12 anys organitzant bodes de destinació d'alta gamma a Mallorca amb equip trilingüe i accés a les millors finques.",
      de: "Seit über 12 Jahren organisiert Bella Rosa hochwertige Ziel-Hochzeiten auf Mallorca: dreisprachiges Team, Zugang zu Mallorcas exklusivsten Fincas und Privatschlössern.",
    },
    highlights: {
      es: [
        "Acceso exclusivo a fincas y castillos privados de lujo en toda Mallorca",
        "Equipo trilingüe (español, inglés, alemán) para parejas internacionales",
        "Red de más de 200 proveedores premium verificados: floristas, chefs, músicos",
        "Ganadora del Bodas.net Award of Excellence durante 5 años consecutivos",
      ],
      en: [
        "Exclusive access to private luxury estates and castles across Mallorca",
        "Trilingual team (Spanish, English, German) for international couples",
        "Network of 200+ vetted premium suppliers: florists, private chefs, musicians",
        "5 consecutive years winning the Bodas.net Award of Excellence",
      ],
      ca: [
        "Accés exclusiu a finques i castells privats de luxe",
        "Equip trilingüe per a parelles internacionals",
        "Xarxa de més de 200 proveïdors premium verificats",
        "Guanyadora del premi Bodas.net Award of Excellence 5 anys consecutius",
      ],
      de: [
        "Exklusiver Zugang zu privaten Luxus-Fincas und Schlössern auf Mallorca",
        "Dreisprachiges Team für internationale Paare",
        "Netzwerk aus 200+ geprüften Premium-Dienstleistern",
        "5 Jahre in Folge: Bodas.net Award of Excellence",
      ],
    },
    servicesProvided: {
      es: [
        "Planificación y coordinación integral de bodas de destino en Mallorca",
        "Selección y reserva de las mejores fincas, castillos y espacios únicos",
        "Coordinación de proveedores: catering, flores, música en directo, fotógrafos",
        "Organización de eventos corporativos de lujo, team-buildings y retreats privados",
      ],
      en: [
        "Full destination wedding planning and day-of coordination in Mallorca",
        "Venue selection and reservation of top estates, castles, and unique spaces",
        "Supplier coordination: gourmet catering, floral design, live music, photography",
        "Luxury corporate events, team-building retreats, and private incentive trips",
      ],
      ca: [
        "Planificació i coordinació integral de bodes a Mallorca",
        "Selecció i reserva de les millors finques i castells",
        "Coordinació de proveïdors: càtering, flors, música i fotògrafs",
        "Organització d'esdeveniments corporatius de luxe",
      ],
      de: [
        "Vollständige Hochzeitsplanung und Tageskoordination auf Mallorca",
        "Venue-Auswahl und Reservierung der besten Fincas und Schlösser",
        "Dienstleister-Koordination: Catering, Blumen, Live-Musik, Fotografie",
        "Luxuriöse Firmenevents, Team-Building-Retreats und Private Incentives",
      ],
    },
  },

  // ── 4. TECNOLOGÍA & ALARMAS ──
  {
    slug: "seguridad-alarmas-mallorca-prosegur-inca",
    name: "SecurBalear Sistemas de Seguridad & Alarmas Mallorca Inca",
    category: "tecnologia-seguridad",
    sectorFolder: "tecnologia-seguridad",
    sectorArrayName: "TECNOLOGIA_SERVICES",
    subcategories: ["alarmas-hogar-fincas", "camaras-cctv-vigilancia", "control-accesos-automatismos"],
    zone: "raiguer-pla",
    address: "Polígon Industrial Can Valero, Carrer Foners 12, 07009 Palma",
    coordinates: { lat: 39.5878, lng: 2.6812 },
    rating: 4.8,
    reviewCount: 234,
    priceRange: "€€",
    phone: "+34 971 423 560",
    website: "https://securbalear.es",
    schedule: "Lunes a Viernes: 08:30 - 18:30 (CRA 24h/365 días)",
    tags: ["zona:raiguer-pla", "product:domotica-smart-home", "mod:cita-previa"],
    shortDescription: {
      es: "Empresa instaladora de sistemas de seguridad electrónica en Mallorca: alarmas grado 2 y grado 3, CCTV-IP 4K, control de accesos biométrico y central receptora de alarmas propia 24h.",
      en: "Electronic security systems installer in Mallorca: Grade 2 & 3 burglar alarms, 4K IP CCTV, biometric access control, and in-house 24h alarm receiving centre.",
      ca: "Empresa instal·ladora de sistemes de seguretat electrònica a Mallorca: alarmes grau 2 i 3, CCTV-IP 4K i control d'accés biomètric.",
      de: "Fachbetrieb für elektronische Sicherheitssysteme auf Mallorca: Einbruchmeldeanlagen Grad 2 & 3, 4K IP-Videoüberwachung, biometrische Zugangskontrolle und eigene 24h-Notrufzentrale.",
    },
    fullDescription: {
      es: "SecurBalear es instaladora autorizada por el Ministerio del Interior (Número de Empresa de Seguridad Privada: ESP-02-B-07-XXX). Ofrece cobertura en toda Mallorca con técnicos en 30 minutos ante cualquier alarma real. Integra sistemas Ajax, Honeywell, Hikvision y Paxton con monitorización en app móvil.",
      en: "Ministry of Interior authorised private security company. Full Mallorca coverage with 30-minute on-site response guarantee. Integrates Ajax, Honeywell, Hikvision, and Paxton systems with mobile app monitoring.",
      ca: "Empresa autoritzada pel Ministeri de l'Interior amb cobertura a tota Mallorca i resposta de 30 minuts. Integra sistemes Ajax, Honeywell i Hikvision.",
      de: "Vom Innenministerium zugelassenes Sicherheitsunternehmen mit 30-Minuten-Einsatz-Garantie auf ganz Mallorca. Integration von Ajax, Honeywell, Hikvision und Paxton mit App-Überwachung.",
    },
    highlights: {
      es: [
        "Empresa autorizada por el Ministerio del Interior (MESAP)",
        "Central Receptora de Alarmas propia con respuesta garantizada en 30 min",
        "Instaladores oficiales Ajax, Honeywell, Hikvision y Bosch",
        "Sin permanencias: contratos flexibles mensuales o anuales sin penalización",
      ],
      en: [
        "Ministry of Interior authorised private security firm (MESAP certified)",
        "Own Alarm Receiving Centre with guaranteed 30-min on-site response",
        "Official Ajax, Honeywell, Hikvision, and Bosch certified installers",
        "No long-term lock-in: flexible monthly or annual contracts without penalty",
      ],
      ca: [
        "Empresa autoritzada pel Ministeri de l'Interior",
        "CRA pròpia amb resposta de 30 minuts garantida",
        "Instal·ladors oficials Ajax, Honeywell i Hikvision",
        "Sense permanències: contractes flexibles mensuals o anuals",
      ],
      de: [
        "Vom Innenministerium zugelassener Sicherheitsbetrieb (MESAP-zertifiziert)",
        "Eigene Notrufzentrale mit garantierter 30-Minuten-Reaktionszeit",
        "Offizielle Ajax-, Honeywell-, Hikvision- und Bosch-Installateure",
        "Keine Bindungsfristen: flexible Monats- oder Jahresverträge",
      ],
    },
    servicesProvided: {
      es: [
        "Instalación de alarmas grado 2 y 3 homologadas para viviendas y fincas rurales",
        "Instalación de videovigilancia IP 4K con visión nocturna y alertas por movimiento en app",
        "Control de accesos biométrico (huella, tarjeta, móvil) y automatismos de puerta",
        "Monitorización 24/365 en Central Receptora propia con aviso a policía y propietario",
      ],
      en: [
        "Grade 2 & 3 burglar alarm installation for homes and rural fincas",
        "4K IP CCTV installation with night vision and mobile app motion alerts",
        "Biometric access control (fingerprint, card, smartphone) and gate automation",
        "24/365 monitoring at own Alarm Receiving Centre with police and owner notification",
      ],
      ca: [
        "Alarmes grau 2 i 3 per a habitatges i finques rurals",
        "Videovigilància IP 4K amb alertes per moviment a l'app",
        "Control d'accés biomètric i automatismes de porta",
        "Monitoratge 24/365 a CRA pròpia",
      ],
      de: [
        "Einbruchmeldeanlagen Grad 2 & 3 für Wohnhäuser und Landfincas",
        "4K IP-Videoüberwachung mit Nachtsicht und App-Bewegungsalarm",
        "Biometrische Zugangskontrolle und Torautomatik",
        "24/365-Überwachung durch eigene Notrufzentrale mit Polizei- und Eigentümerbenachrichtigung",
      ],
    },
  },

  // ── 5. MASCOTAS & PELUQUERÍA CANINA ──
  {
    slug: "peluqueria-canina-mallorca-the-dog-spa-palma",
    name: "The Dog Spa Peluquería Canina & Estética Felina Palma",
    category: "peluqueria-estetica-canina",
    sectorFolder: "mascotas-veterinaria",
    sectorArrayName: "MASCOTAS_SERVICES",
    subcategories: ["peluqueria-canina-premium", "bano-seco-feline-grooming", "spa-mascotas-mallorca"],
    zone: "palma",
    address: "Carrer de Joan Miró, 148, 07015 Palma",
    coordinates: { lat: 39.5627, lng: 2.6095 },
    rating: 4.9,
    reviewCount: 398,
    priceRange: "€€",
    phone: "+34 971 450 212",
    website: "https://thedogspamallorca.com",
    schedule: "Lunes a Sábado: 09:00 - 19:30",
    tags: ["zona:palma-centro", "product:accesible", "mod:cita-previa"],
    shortDescription: {
      es: "Peluquería canina y felina premium en Palma con estilistas especializados por razas: baño medicado, corte de raza, tratamientos de spa anti-estrés y servicio de recogida y entrega a domicilio.",
      en: "Premium dog and cat grooming salon in Palma with breed-specialist stylists: medicated baths, show-cut styling, anti-stress spa treatments, and home pick-up & drop-off.",
      ca: "Perruqueria canina i felina premium a Palma amb estilistes especialitzats per races: bany medicat, talla de raça i tractaments spa anti-estrès.",
      de: "Premium-Hundefriseur und Katzenpflege-Salon in Palma mit rassenspezialisierten Stylistinnen: medizinische Bäder, Rassencut, Anti-Stress-Spa und Heim-Abhol-Service.",
    },
    fullDescription: {
      es: "The Dog Spa cuenta con 6 peluqueras caninas y 2 groomers felinos certificados por la Asociación Nacional de Peluqueros Caninos (ANPEC). Especialistas en razas como el Bichón Maltés, Caniche, Cocker Spaniel, Yorkshire Terrier, Schnauzer y razas nórdicas. Productos 100% naturales, sin parabenos ni sulfatos.",
      en: "Team of 6 ANPEC-certified dog groomers and 2 feline groomers. Breed specialists for Maltese Bichon, Poodle, Cocker Spaniel, Yorkshire Terrier, Schnauzer, and Nordic breeds. 100% natural, paraben-free, sulphate-free products.",
      ca: "6 perruqueres canines i 2 groomers felins certificats per ANPEC. Especialistes en Bichon Maltès, Caniche, Cocker, Yorkshire i races nòrdiques. Productes 100% naturals.",
      de: "6 ANPEC-zertifizierte Hundefrisöre und 2 Katzenpfleger. Spezialisten für Malteser, Pudel, Cocker Spaniel, Yorkshire Terrier, Schnauzer und Nordische Rassen. 100% natürliche Produkte ohne Parabene.",
    },
    highlights: {
      es: [
        "6 peluqueras certificadas ANPEC y 2 groomers felinos especializados",
        "Productos 100% naturales de gama profesional: Iv San Bernard, Chris Christensen",
        "Cabinas individuales insonorizadas anti-estrés para gatos y perros nerviosos",
        "Servicio de recogida y entrega a domicilio en Palma y municipios del área metropolitana",
      ],
      en: [
        "6 ANPEC-certified groomers and 2 specialist cat groomers",
        "Premium 100% natural professional products: Iv San Bernard, Chris Christensen",
        "Individual soundproofed anti-stress cabins for nervous cats and dogs",
        "Home pick-up and drop-off service across Palma and the metropolitan area",
      ],
      ca: [
        "6 perruqueres ANPEC i 2 groomers felins",
        "Productes 100% naturals professionals: Iv San Bernard, Chris Christensen",
        "Cabines individuals insonoritzades anti-estrès",
        "Servei de recollida i lliurament a domicili a Palma",
      ],
      de: [
        "6 ANPEC-zertifizierte Hundefrisöre und 2 Katzenpfleger",
        "Premium-Naturprodukte: Iv San Bernard, Chris Christensen",
        "Schallisolierte Einzelkabinen gegen Stress für ängstliche Tiere",
        "Heim-Abhol- und -Lieferservice in Palma und Umgebung",
      ],
    },
    servicesProvided: {
      es: [
        "Baño completo con productos naturales, secado y cepillado para perros y gatos",
        "Corte y estilismo de raza a mano con tijera, máquina y stripping",
        "Tratamientos spa: barro volcánico, aceite de argán, masaje capilar y aromaterapia",
        "Limpieza de oídos, corte de uñas y expresión de glándulas anales incluidos en el servicio",
      ],
      en: [
        "Full natural-product bath, blow-dry, and brush-out for dogs and cats",
        "Breed-standard cut and styling by hand, clippers, and stripping techniques",
        "Spa treatments: volcanic mud, argan oil, scalp massage, and aromatherapy",
        "Ear cleaning, nail trimming, and anal gland expression included in the service",
      ],
      ca: [
        "Bany complet amb productes naturals, assecat i raspallat",
        "Tall i estilisme de raça a mà, màquina i stripping",
        "Tractaments spa: fang volcànic, oli d'argà i aromaterapia",
        "Neteja d'orelles, tall d'ungles i glàndules anals inclosos",
      ],
      de: [
        "Vollbad mit Naturprodukten, Föhnen und Bürsten für Hunde und Katzen",
        "Rassengerechter Schnitt per Hand, Schermaschine und Trimmen",
        "Spa-Behandlungen: Vulkanschlamm, Arganöl, Kopfmassage und Aromatherapie",
        "Ohrenreinigung, Nagelschnitt und Analdrüsen im Service inklusive",
      ],
    },
  },
];

console.log("Ingesting Batch 10 with Son Brull Eco Spa...");
ingestBatch(BATCH_10);
