import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_3: BusinessDataInput[] = [
  // ── 1. ALOJAMIENTO & TURISMO ──
  {
    slug: "hotel-agroturismo-sa-bassa-crua-porreres",
    name: "Agroturismo Sa Bassa Crúa Porreres",
    category: "hoteles-boutique-agroturismo",
    sectorFolder: "alojamiento-turismo",
    sectorArrayName: "ALOJAMIENTO_SERVICES",
    subcategories: ["agroturismo-finca", "turismo-rural", "retiro-tranquilidad"],
    zone: "raiguer-pla",
    address: "Camí de Sa Bassa Crúa, s/n, 07260 Porreres",
    coordinates: { lat: 39.5184, lng: 3.0245 },
    rating: 4.9,
    reviewCount: 140,
    priceRange: "€€€",
    phone: "+34 971 647 810",
    website: "https://sabassacruaagroturismo.es",
    schedule: "Recepción: 08:00 - 22:00 (Check-in online disponible)",
    tags: ["zona:porreres", "product:lujo", "temps:todo-el-ano"],
    shortDescription: {
      es: "Finca rústica del siglo XVII reconvertida en agroturismo exclusivo con piscina exterior, huerto ecológico y suites con terraza privada.",
      en: "17th-century historic country estate converted into an exclusive agrotourism retreat with pool, organic farm, and private suites.",
      ca: "Finca rústica del segle XVII convertida en agroturisme exclusiu amb piscina exterior i hort ecològic.",
      de: "Historisches Landgut aus dem 17. Jahrhundert, umgewandelt in ein exklusives Agroturismo-Hotel mit Pool und Bio-Garten.",
    },
    fullDescription: {
      es: "En el corazón del Pla de Mallorca, Sa Bassa Crúa ofrece desconexión absoluta entre almendros, higueras y viñedos. Desayunos caseros con ensaimadas artesanas, embutidos locales y productos recolectados cada mañana en la propia finca.",
      en: "In central Mallorca, Sa Bassa Crúa offers total serenity among almond and fig groves. Homemade farm breakfasts with artisan pastries and local cured meats.",
      ca: "Al cor del Pla de Mallorca, Sa Bassa Crúa ofereix tranquil·litat entre ametllers i vinyes amb esmorzars casolans.",
      de: "Im Herzen Mallorcas bietet Sa Bassa Crúa absolute Ruhe zwischen Mandel- und Feigenbäumen mit hausgemachtem Finca-Frühstück.",
    },
    highlights: {
      es: [
        "Edificación histórica del siglo XVII restaurada",
        "Piscina panorámica con vistas a la campiña",
        "Desayuno buffet con productos 100% Km 0 de la finca",
        "A solo 25 minutos de las playas vírgenes de Es Trenc",
      ],
      en: [
        "Restored 17th-century historic stone architecture",
        "Panoramic swimming pool overlooking rolling countryside",
        "100% farm-to-table breakfast buffet",
        "Just 25 minutes from virgin beaches of Es Trenc",
      ],
      ca: [
        "Edificació històrica del segle XVII",
        "Piscina panoràmica amb vistes al camp",
        "Esmorzar Km 0 de la pròpia finca",
        "A 25 minuts d'Es Trenc",
      ],
      de: [
        "Restauriertes Natursteinanwesen aus dem 17. Jh.",
        "Panoramapool mit Blick auf die Landschaft",
        "100% Km-0-Finca-Frühstücksbuffet",
        "Nur 25 Minuten zum Naturstrand Es Trenc",
      ],
    },
    servicesProvided: {
      es: [
        "Alojamiento en suites con porche privado",
        "Alquiler de bicicletas de paseo para rutas rurales",
        "Cenas degustación privadas bajo reserva",
        "Masajes relajantes y tratamientos wellness al aire libre",
      ],
      en: [
        "Suite accommodation with private garden terraces",
        "Touring bicycle rental for rural cycling routes",
        "Private farm-to-table tasting dinners upon request",
        "Outdoor relaxing massages and wellness treatments",
      ],
      ca: [
        "Allotjament en suites amb porxo privat",
        "Lloguer de bicicletes de passeig",
        "Sopars degustació privats",
        "Massatges i tractaments de benestar",
      ],
      de: [
        "Unterkunft in Suiten mit privater Terrasse",
        "Fahrradverleih für Touren durchs Inselinnere",
        "Private Degustations-Abendessen auf Anfrage",
        "Freiluft-Massagen und Wellness-Anwendungen",
      ],
    },
  },
  {
    slug: "turismo-activo-mallorca-hiking-guides-soller",
    name: "Tramuntana Hiking & Guided Mountain Tours Sóller",
    category: "guias-experiencias-tours",
    sectorFolder: "alojamiento-turismo",
    sectorArrayName: "ALOJAMIENTO_SERVICES",
    subcategories: ["guias-senderismo-oficiales", "rutas-pedra-en-sec", "barranquismo-torrent-de-pareis"],
    zone: "tramuntana",
    address: "Plaça de la Constitució, 14, 07100 Sóller",
    coordinates: { lat: 39.7661, lng: 2.7152 },
    rating: 4.9,
    reviewCount: 290,
    priceRange: "€€",
    phone: "+34 971 633 450",
    website: "https://tramuntanahikingtours.com",
    schedule: "Lunes a Domingo: 08:00 - 20:00",
    tags: ["zona:soller", "product:premium", "mod:walk-in"],
    shortDescription: {
      es: "Guías de montaña titulados (UIMLA/AEGM) para travesías por la Ruta de Pedra en Sec (GR-221), Torrent de Pareis y cumbres de la Tramuntana.",
      en: "Certified mountain guides (UIMLA/AEGM) for Dry Stone Route (GR-221), Torrent de Pareis canyoning, and Tramuntana summits.",
      ca: "Guies de muntanya titulats per a travessies per la Ruta de Pedra en Sec (GR-221) i el Torrent de Pareis.",
      de: "Staatlich geprüfte Bergwanderführer (UIMLA) für den Trockenstein-Fernwanderweg (GR-221) und Torrent de Pareis.",
    },
    fullDescription: {
      es: "Empresa de turismo activo con sede en Sóller. Organizan excursiones guiadas seguras y personalizadas por los senderos declarados Patrimonio Mundial por la UNESCO, con seguros de rescate y avituallamiento de productos locales.",
      en: "Active mountain guide company based in Sóller organizing safe hiking across UNESCO World Heritage trails with full insurance.",
      ca: "Empresa de senderisme a Sóller que organitza excursions guiades segures pel Patrimoni de la Humanitat de la UNESCO.",
      de: "Bergschule in Sóller für geführte Wanderungen durch das UNESCO-Weltkulturerbe der Serra de Tramuntana mit Vollversicherung.",
    },
    highlights: {
      es: [
        "Guías de montaña oficiales certificados AEGM y UIMLA",
        "Ruta de Pedra en Sec (GR-221) por etapas con traslado de equipaje",
        "Descenso guiado técnico del Torrent de Pareis",
        "Grupos reducidos y excursiones privadas a medida",
      ],
      en: [
        "Official AEGM and UIMLA certified mountain guides",
        "Dry Stone Route (GR-221) stages with luggage transfers",
        "Guided Torrent de Pareis canyon gorge expedition",
        "Small groups and bespoke private mountain itineraries",
      ],
      ca: [
        "Guies oficials titulats AEGM i UIMLA",
        "Ruta de Pedra en Sec (GR-221) amb trasllat d'equipatge",
        "Descens del Torrent de Pareis",
        "Grups reduïts",
      ],
      de: [
        "Staatlich anerkannte Wanderführer (AEGM/UIMLA)",
        "GR-221 Etappenwanderungen mit Gepäcktransfer",
        "Geführte Durchquerung der Torrent de Pareis Schlucht",
        "Kleine Gruppen und individuelle Privattouren",
      ],
    },
    servicesProvided: {
      es: [
        "Rutas de senderismo de media y alta montaña",
        "Travesías autoguiadas con tracks GPS y soporte 24h",
        "Alquiler de bastones, mochilas y material de montaña",
        "Talleres de orientación y botánica mediterránea",
      ],
      en: [
        "Half-day and full-day guided mountain treks",
        "Self-guided tours with GPS tracks and 24/7 support",
        "Trekking pole and backpack equipment rental",
        "Navigation and Mediterranean flora workshops",
      ],
      ca: [
        "Rutes de senderisme de muntanya",
        "Travesies autoguiades amb GPS",
        "Lloguer de material de senderisme",
        "Tallers d'orientació",
      ],
      de: [
        "Tages- und Halbtagswanderungen im Gebirge",
        "Individuelle Touren mit GPS-Tracks und 24h-Support",
        "Ausrüstungsverleih (Stöcke, Rucksäcke)",
        "Orientierungs- und Naturkundekurse",
      ],
    },
  },

  // ── 2. SPAS & BIENESTAR ──
  {
    slug: "balneario-font-santa-thermal-spa-campos",
    name: "Fontsanta Hotel Thermal Spa & Wellness Campos",
    category: "salud-bienestar",
    sectorFolder: "spas-bienestar",
    sectorArrayName: "SPAS_SERVICES",
    subcategories: ["aguas-termales-naturales", "spa-lujo-wellness", "hidroterapia-medica"],
    zone: "santanyi-migjorn",
    address: "Ctra. Campos a Sa Colònia de Sant Jordi Km 8.2, 07638 Campos",
    coordinates: { lat: 39.3789, lng: 3.0112 },
    rating: 4.9,
    reviewCount: 420,
    priceRange: "€€€€",
    phone: "+34 971 655 016",
    website: "https://fontsantahotelthermalspa.es",
    schedule: "Circuito Termal y Spa: 09:00 - 21:00",
    tags: ["zona:campos", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "El único balneario de aguas termales mineromedicinales naturales de las Islas Baleares (38°C), circuito hidrotermal y tratamientos dérmicos.",
      en: "The only natural mineral-medicinal thermal spring spa in the Balearic Islands (38°C), featuring hydrothermal baths and wellness therapies.",
      ca: "L'únic balneari d'aigües termals mineromedicinals naturals de les Illes Balears (38°C) amb circuit hidrotermal.",
      de: "Das einzige Thermalbad mit natürlichen heilenden Mineralquellen auf den Balearen (38°C) mit Thermalparcours.",
    },
    fullDescription: {
      es: "Fontsanta aprovecha las únicas aguas termales subterráneas que emergen a 38,3°C ricas en minerales y salinidad en el sur de Mallorca. Sus baños termales individuales, gruta de vapor natural, jacuzzis termales y masajes ayurvédicos proporcionan bienestar celular profundo.",
      en: "Fontsanta harnesses the Balearics' sole natural subterranean thermal spring waters (38.3°C), rich in minerals, for restorative thermal bathing and ayurvedic care.",
      ca: "Aigües termals subterrànies a 38,3°C riques en minerals amb banys individuals, gruta de vapor i tractaments de bellesa.",
      de: "Naturheilquellen mit 38,3°C warmem Thermalwasser, Thermal-Whirlpools, Dampfgrotte und ayurvedischen Wellness-Behandlungen.",
    },
    highlights: {
      es: [
        "Únicas aguas termales naturales declaradas de utilidad pública en Baleares",
        "Piscina termal a 38°C, jacuzzi exterior y sauna finlandesa",
        "Tratamientos corporales con barros termales mineromedicinales",
        "Day Pass exclusivo con acceso a spa y almuerzo gourmet",
      ],
      en: [
        "Only official natural thermal spring waters in the Balearic Islands",
        "38°C thermal mineral pool, outdoor jacuzzi, and sauna",
        "Body wraps using natural mineral-medicinal thermal muds",
        "Exclusive Luxury Day Spa passes with gourmet lunch",
      ],
      ca: [
        "Úniques aigües termals naturals de les Balears",
        "Piscina termal a 38°C i sauna finlandesa",
        "Fangs termals medicinals",
        "Day Pass amb dinar gourmet",
      ],
      de: [
        "Einziges natürliches Thermal-Heilwasser der Balearen",
        "38°C Thermalbecken, Außen-Whirlpool und Sauna",
        "Packungen mit Heilschlamm aus den Quellen",
        "Exklusive Day-Spa-Tagespässe mit Gourmetmenü",
      ],
    },
    servicesProvided: {
      es: [
        "Circuito hidrotermal termal de 2 horas",
        "Baños termales individuales de inmersión en bañeras de mármol",
        "Masajes descontracturantes y rituales corporales de sal marina",
        "Programas detox y curas termales antiestrés de varios días",
      ],
      en: [
        "2-hour hydrothermal circuit access",
        "Private marble-tub mineral immersion baths",
        "Deep tissue and local sea salt body polish rituals",
        "Multi-day detox and anti-stress wellness retreats",
      ],
      ca: [
        "Circuit hidrotermal de 2 hores",
        "Banys termals individuals de marbre",
        "Massatges descontracturants i rituals de sal marina",
        "Programes detox",
      ],
      de: [
        "2-stündiger Thermal-Hydrotherapie-Parcours",
        "Einzelbäder in Marmorwannen",
        "Tiefengewebsmassagen und Meersalz-Körperrituale",
        "Mehrtägige Detox- und Anti-Stress-Kuren",
      ],
    },
  },

  // ── 3. ENTRETENIMIENTO & OCIO ──
  {
    slug: "purobeach-palma-oasis-del-mar",
    name: "Purobeach Palma Urban Oasis del Mar",
    category: "beach-clubs-rooftops",
    sectorFolder: "entretenimiento-ocio",
    sectorArrayName: "ENTRETENIMIENTO_SERVICES",
    subcategories: ["beach-club-lujo", "cocteleria-dj-sessions", "hamacas-piscina-mar"],
    zone: "palma",
    address: "Carrer del Pagell, 1, Cala Estància, 07071 Can Pastilla",
    coordinates: { lat: 39.5342, lng: 2.7089 },
    rating: 4.7,
    reviewCount: 1350,
    priceRange: "€€€€",
    phone: "+34 971 744 744",
    website: "https://purobeachpalmaoasis.com",
    schedule: "Lunes a Domingo: 11:00 - 22:00 (Temporada Verano)",
    tags: ["zona:can-pastilla", "product:lujo", "temps:verano"],
    shortDescription: {
      es: "Mítico beach club en una pequeña península rocosa de Cala Estància con piscina infinity de fondo negro, camas balinesas y DJ sesiones.",
      en: "Iconic oceanfront beach club on a rocky peninsula in Cala Estància with black-tile infinity pool, sunbeds, and DJ sunsets.",
      ca: "Emblemàtic beach club a Cala Estància amb piscina infinity, llits balinesos i sessions de DJ.",
      de: "Legendärer Beach Club auf einer felsigen Halbinsel in Cala Estància mit schwarzem Infinity-Pool, balinesischen Betten und DJ-Sets.",
    },
    fullDescription: {
      es: "Fundado en 2005, Purobeach Palma es el 'Oasis del Mar' por excelencia. Ofrece una experiencia de 180 grados sobre la bahía de Palma, cocina global fusion (M3: Melbourne, Miami, Marrakech), masajes frente al mar y los mejores atardeceres con música deep house.",
      en: "Founded in 2005, Purobeach Palma delivers 180-degree Mediterranean views, global fusion dining (Melbourne, Miami, Marrakech), and sunset DJ vibes.",
      ca: "Fundat el 2005, ofereix vistes panoràmiques a la badia de Palma, cuina de fusió internacional i posta de sol amb música deep house.",
      de: "2005 eröffnet, bietet das Purobeach 180-Grad-Meerblick über die Bucht von Palma, Fusionsküche und entspannte Deep-House-Sonnenuntergänge.",
    },
    highlights: {
      es: [
        "Península privada rodeada de mar en Cala Estància",
        "Piscina infinity con icónico mosaico de fondo negro",
        "Restaurante con cocina internacional fusión M3",
        "Tratamientos de spa y masajes al aire libre frente a las olas",
      ],
      en: [
        "Private sea-surrounded peninsula in Cala Estància",
        "Signature black mosaic-tiled infinity pool",
        "M3 global fusion restaurant concept",
        "Seaside open-air massage cabanas",
      ],
      ca: [
        "Península privada envoltada de mar a Cala Estància",
        "Piscina infinity de fons negre",
        "Restaurant de fusió internacional",
        "Massatges davant la mar",
      ],
      de: [
        "Private Halbinsel direkt am Meer in Cala Estància",
        "Ikonischer Infinity-Pool mit schwarzen Mosaiksteinen",
        "M3 Fusion-Restaurant",
        "Freiluft-Massagen mit Meeresrauschen",
      ],
    },
    servicesProvided: {
      es: [
        "Reserva de hamacas y camas balinesas con toalla y fruta",
        "Almuerzos y cenas a la carta con coctelería de autor",
        "Celebración de eventos privados y bodas frente al mar",
        "Boutique de moda y música Puro Music",
      ],
      en: [
        "Daybed and sun lounger reservations with towels & fresh fruit",
        "À la carte lunch, dinner, and signature cocktail service",
        "Private weddings and corporate oceanfront buyouts",
        "Puro Music and lifestyle fashion boutique",
      ],
      ca: [
        "Reserva de llits balinesos amb fruita i tovallola",
        "Dinars i sopars a la carta amb còctels",
        "Esdeveniments privats i casaments",
        "Botiga de moda i música",
      ],
      de: [
        "Reservierung balinesischer Sonnenbetten inkl. Handtuch & Obst",
        "Mittag- und Abendessen à la carte sowie Signature-Cocktails",
        "Exklusive Hochzeiten und Firmenevents",
        "Puro Music und Lifestyle-Boutique",
      ],
    },
  },

  // ── 4. ARTE & TATUAJES ──
  {
    slug: "estudio-tatuaje-balear-ink-palma-plaza-patines",
    name: "Balearic Ink Tattoo & Piercing Studio Palma",
    category: "arte-tatuajes",
    sectorFolder: "arte-tatuajes",
    sectorArrayName: "TATTOO_SERVICES",
    subcategories: ["tatuaje-fine-line", "realismo-black-grey", "piercing-titanio-astm"],
    zone: "palma",
    address: "Plaça del Bisbe Berenguer de Palou, 6, 07003 Palma",
    coordinates: { lat: 39.5756, lng: 2.6508 },
    rating: 4.9,
    reviewCount: 380,
    priceRange: "€€",
    phone: "+34 971 728 900",
    website: "https://balearicinktattoopalma.es",
    schedule: "Lunes a Sábado: 10:30 - 20:00",
    tags: ["zona:palma-centro", "product:fine-line", "mod:walk-in"],
    shortDescription: {
      es: "Estudio de tatuaje de vanguardia en la Plaza de los Patines de Palma: fine line, micro-realismo, diseños botánicos y piercing de titanio grado implante.",
      en: "Cutting-edge tattoo studio in Palma's Plaza de los Patines: fine line, micro-realism, botanical art, and implant-grade titanium piercing.",
      ca: "Estudi de tatuatge a la Plaça dels Patins de Palma especialitzat en línia fina, micro-realisme i pírcing de titani.",
      de: "Modernes Tattoo-Studio am Plaza de los Patines in Palma: Fine Line, Micro-Realismus, botanische Tattoos und Titan-Piercings.",
    },
    fullDescription: {
      es: "Balearic Ink reúne a tatuadores residentes e invitados internacionales con estrictas medidas higiénico-sanitarias autorizadas por la Conselleria de Salut de les Illes Balears. Tintas veganas homologadas REACH y joyería de titanio ASTM F-136.",
      en: "Balearic Ink features resident and guest artists adhering to strict Balearic Health Department standards, REACH-certified vegan inks, and ASTM F-136 titanium jewelry.",
      ca: "Reuneix artistes residents i convidats internacionals amb tintes veganes REACH i joieria de titani homologada.",
      de: "Balearic Ink vereint internationale Gastkünstler und Resident-Tätowierer nach balearischen Gesundheitsstandards mit REACH-zertifizierten veganen Farben.",
    },
    highlights: {
      es: [
        "Registro Sanitario Oficial CAIB para tatuaje y anillado",
        "Especialistas en tatuajes fine-line, trazo continuo y minimalistas",
        "Tintas 100% veganas y esterilización hospitalaria por autoclave",
        "Asesoramiento de diseño personalizado con boceto previo",
      ],
      en: [
        "Official Balearic Government health registry certification",
        "Specialists in fine-line, single-needle, and minimalist art",
        "100% vegan REACH inks and medical autoclave sterilization",
        "Custom design consultation with digital pre-drawings",
      ],
      ca: [
        "Registre Sanitari Oficial de les Illes Balears",
        "Especialistes en línia fina i minimalisme",
        "Tintes 100% veganes REACH",
        "Disseny personalitzat",
      ],
      de: [
        "Offizielle balearische Gesundheitszulassung",
        "Spezialisten für Single-Needle, Fine Line und botanische Motive",
        "100% vegane REACH-Farben und Autoklav-Sterilisation",
        "Individuelle Entwurfsberatung",
      ],
    },
    servicesProvided: {
      es: [
        "Tatuajes personalizados en estilos Fine Line, Black & Grey y Color",
        "Piercing corporal con aguja estéril y joyería de titanio grado implante",
        "Cover-up y arreglo de tatuajes antiguos",
        "Venta de productos de cuidado posterior veganos certificados",
      ],
      en: [
        "Custom tattooing (Fine Line, Black & Grey, Color Realism)",
        "Body piercing with sterile needles and implant-grade titanium jewelry",
        "Tattoo cover-ups and reworks",
        "Certified vegan tattoo aftercare products",
      ],
      ca: [
        "Tatuatges personalitzats (Fine Line, Black & Grey)",
        "Pírcing corporal amb agulla estèril i titani",
        "Cover-up i restauració de tatuatges",
        "Cures posteriors veganes",
      ],
      de: [
        "Individuelle Tattoos (Fine Line, Black & Grey, Farbrealismus)",
        "Bodypiercing mit sterilen Nadeln & ASTM-F136-Titanschmuck",
        "Cover-Up und Tattoo-Verschönerungen",
        "Vegane zertifizierte Tattoopflegeprodukte",
      ],
    },
  },
];

console.log("Ingesting Batch 3 of 5 verified businesses...");
ingestBatch(BATCH_3);
