import { ingestBatch, type BusinessDataInput } from "./mass-curator.ts";

export const BATCH_18: BusinessDataInput[] = [
  // ── 1. ALOJAMIENTO & AGROTURISMO ──
  {
    slug: "agroturismo-son-mercadal-porreres-finca-rural",
    name: "Agroturismo Son Mercadal Finca Rural Porreres",
    category: "hoteles-boutique-agroturismo",
    sectorFolder: "alojamiento-turismo",
    sectorArrayName: "ALOJAMIENTO_SERVICES",
    subcategories: ["agroturismo-porreres", "hotel-rural-pla-mallorca", "finca-ecologica-porreres"],
    zone: "raiguer-pla",
    address: "Camí de Son Mercadal, s/n, 07260 Porreres",
    coordinates: { lat: 39.5124, lng: 3.0234 },
    rating: 4.9,
    reviewCount: 260,
    priceRange: "€€€",
    phone: "+34 971 647 120",
    website: "https://sonmercadal.es",
    schedule: "Recepción: 08:30 - 21:00 (Marzo a Noviembre)",
    tags: ["zona:raiguer-pla", "product:lujo", "mod:cita-previa"],
    shortDescription: {
      es: "Finca de agroturismo señorial del siglo XIV en Porreres: 100 hectáreas de cultivo ecológico, piscina entre jardines autóctonos y desayunos con mermeladas de albaricoque de la finca.",
      en: "14th-century manor agritourism estate in Porreres: 100 hectares of organic farming, swimming pool surrounded by native gardens, and estate apricot jam breakfasts.",
      ca: "Finca d'agroturisme senyorial del segle XIV a Porreres amb 100 hectàrees de conreu ecològic i piscina entre jardins.",
      de: "Historisches Finca-Agritourismus aus dem 14. Jahrhundert in Porreres: 100 Hektar Bio-Landwirtschaft, Pool im Naturgarten und hauseigene Aprikosenmarmelade.",
    },
    fullDescription: {
      es: "Son Mercadal es una de las possessións más antiguas del Pla de Mallorca. Sus habitaciones y suites conservan las paredes de piedra vista de 800 años de antigüedad, techos con vigas de roble y mobiliario de época restaurado.",
      en: "One of Pla de Mallorca's oldest country estates. Rooms feature 800-year-old exposed stone walls, oak beam ceilings, and restored antique Balearic furniture.",
      ca: "Una de les possessións més antigues del Pla de Mallorca. Habitacions amb parets de pedra de 800 anys i sostres de fusta.",
      de: "Eines der ältesten Landgüter der Insel. Zimmer mit 800 Jahre alten Natursteinmauern, Eichenbalken und antiken Möbeln.",
    },
    highlights: {
      es: [
        "Finca señorial del siglo XIV declarada Bien de Interés Cultural",
        "100 hectáreas de cultivo ecológico de albaricoqueros, olivos y algarrobos",
        "Piscina de agua salada integrada en el paisaje rural de Porreres",
        "Desayunos gourmet con productos 100% de la finca y repostería artesana",
      ],
      en: [
        "14th-century heritage manor estate designated Cultural Interest Site",
        "100 hectares of organic apricot, olive, and carob orchards",
        "Saline swimming pool seamlessly integrated into Porreres countryside",
        "Gourmet breakfasts featuring 100% farm-grown produce and artisan pastries",
      ],
      ca: [
        "Finca senyorial del segle XIV declarada Bé d'Interès Cultural",
        "100 hectàrees de conreu ecològic d'albercoquers i oliveres",
        "Piscina d'aigua salada integrada al paisatge rural",
        "Esmorzars gourmet amb productes 100% de la finca",
      ],
      de: [
        "Kulturerbe-Landgut aus dem 14. Jahrhundert unter Denkmalschutz",
        "100 Hektar Bio-Anbau von Aprikosen-, Oliven- und Johannisbrotbäumen",
        "Salzwasserpool harmonisch in die Landschaft von Porreres eingebettet",
        "Gourmet-Frühstück mit 100% eigenen Hofprodukten und Hausgebäck",
      ],
    },
    servicesProvided: {
      es: [
        "Alojamiento en suites históricas con terraza privada y vistas al campo",
        "Cenas tradicionales mallorquinas para huéspedes elaboradas con verdura del huerto",
        "Rutas guiadas a pie y en bicicleta por la finca agrícola y viñedos",
        "Catas de aceite de oliva virgen extra orgánico producido en la propia finca",
      ],
      en: [
        "Historic suite accommodation with private terraces and country views",
        "Traditional Mallorcan dinners for guests cooked with vegetable garden produce",
        "Guided walking and cycling tours through the agricultural estate and vineyards",
        "Estate-produced organic extra virgin olive oil tasting sessions",
      ],
      ca: [
        "Allotjament en suites històriques amb terrassa privada",
        "Sopars tradicionals mallorquins per a hostes amb verdures de l'hort",
        "Rutes guiades per la finca agrícola i vinyes",
        "Tasts d'oli d'oliva verge extra ecològic de la finca",
      ],
      de: [
        "Übernachtung in historischen Suiten mit privater Terrasse und Landblick",
        "Traditionelle mallorquinische Abendessen mit frischem Hofgemüse für Gäste",
        "Geführte Wander- und Radtouren durch das Landgut und die Weinberge",
        "Verkostungen des hauseigenen Bio-Olivenöls extra vergine",
      ],
    },
  },

  // ── 2. ARTESANÍA & TEXTIL TELA DE LLENGÜES ──
  {
    slug: "teixits-vicens-textil-tradicional-ikat-pollensa",
    name: "Teixits Vicens Taller Textil Tradicional Tela de Llengües Pollença (1854)",
    category: "vidrio-ceramica-artesanal",
    sectorFolder: "artesania-manufactura",
    sectorArrayName: "ARTESANIA_SERVICES",
    subcategories: ["tela-de-llengues-pollensa", "textil-artesanal-mallorca", "taller-ikat-balear"],
    zone: "alcudia-pollensa",
    address: "Carretera Palma-Pollença, km 52, 07460 Pollença",
    coordinates: { lat: 39.8712, lng: 3.0189 },
    rating: 4.9,
    reviewCount: 490,
    priceRange: "€€€",
    phone: "+34 971 530 450",
    website: "https://teixitsvicens.com",
    schedule: "Lunes a Viernes: 09:00 - 19:30; Sábado: 09:00 - 13:30",
    tags: ["zona:alcudia-pollensa", "product:textil-mallorquin", "mod:walk-in"],
    shortDescription: {
      es: "Taller textil familiar de 'Robba de Llengües' (Ikat balear) en Pollença desde 1854: tejeduría artesana en telares mecánicos centenarios, mantelerías, cojines y moda sostenible.",
      en: "Family artisan 'Robba de Llengües' (Balearic Ikat) weaving workshop in Pollença operating since 1854: historic mechanical looms, table linens, cushions, and sustainable decor.",
      ca: "Taller textil familiar de Robba de Llengües a Pollença des del 1854: teixiduria artesana en telers centenaris, estelatge, coixins i decoració.",
      de: "Familiengeführte Handweberei für 'Robba de Llengües' (balearisches Ikat) in Pollença seit 1854: historische Webstühle, Tischwäsche, Kissen und nachhaltige Mode.",
    },
    fullDescription: {
      es: "Teixits Vicens es uno de los últimos talleres de Europa que conserva la técnica ancestral del Ikat oriental traída a Mallorca en el siglo XVI. Cuarta generación de maestros tejedores en Pollença.",
      en: "One of the last workshops in Europe preserving the ancient Oriental Ikat technique brought to Mallorca in the 16th century. 4th generation master weavers in Pollença.",
      ca: "Un dels darrers tallers d'Europa que conserva la tècnica ancestral de l'Ikat a Mallorca. Quarta generació de mestres teixidors.",
      de: "Eine der letzten Manufakturen Europas für die seit dem 16. Jh. auf Mallorca gepflegte orientalische Ikat-Webtechnik. 4. Generation Meisterweber in Pollença.",
    },
    highlights: {
      es: [
        "Taller textil artesano en activo de forma ininterrumpida desde 1854",
        "Auténtica 'Tela de Llengües' tejida en algodón y lino natural con tinte previo",
        "Demostraciones gratuitas del proceso de tejeduría en el taller histórico",
        "Boutique de 300 m² con productos de decoración de hogar y confección a medida",
      ],
      en: [
        "Family-run artisan textile workshop continuously operating since 1854",
        "Authentic 'Tela de Llengües' woven in natural cotton and linen with resist dyeing",
        "Free live weaving demonstrations on historic looms for workshop visitors",
        "300 m² showroom displaying home decor products and bespoke tailoring",
      ],
      ca: [
        "Taller artesà en actiu des del 1854 de forma ininterrompuda",
        "Autèntica Robba de Llengües teixida en cotó i lli natural",
        "Demostracions gratuïtes del procés de teixiduria en viu",
        "Boutique de 300 m² amb productes de decoració",
      ],
      de: [
        "Handweberei seit 1854 ununterbrochen in Familienbesitz",
        "Echte 'Tela de Llengües' aus Baumwolle und Leinen mit charakteristischem Zungenmuster",
        "Kostenlose Live-Vorführungen des Webprozesses an historischen Webstühlen",
        "300 m² Showroom mit Heimtextilien, Kissen und Maßkonfektion",
      ],
    },
    servicesProvided: {
      es: [
        "Venta de telas de llengües por metros en lino y algodón natural de alta densidad",
        "Confección a medida de cortinas, manteles, fundas de cojín y tapicería",
        "Visita guiada al taller textil artesano para grupos y profesionales del diseño",
        "Envíos asegurados a domicilio en toda la Unión Europea y América",
      ],
      en: [
        "Sale of authentic Ikat fabrics by the metre in high-density natural linen and cotton",
        "Bespoke tailoring of curtains, tablecloths, cushion covers, and upholstery",
        "Guided tours of the historic weaving workshop for design professionals and groups",
        "Insured door-to-door courier shipping across the EU and international destinations",
      ],
      ca: [
        "Venda de roba de llengües per metres en lli i cotó natural",
        "Confecció a mida de cortines, estelatge, coixins i tapisseria",
        "Visita guiada al taller per a grups i professionals del disseny",
        "Enviaments assegurats a domicili a la UE",
      ],
      de: [
        "Verkauf von Ikat-Stoffen vom Ballen in Leinen und Naturbaumwolle",
        "Maßanfertigung von Vorhängen, Tischdecken, Kissenbezügen und Polsterstoffen",
        "Führungen durch die historische Weberei für Design-Profis und Gruppen",
        "Gesicherter weltweiter Versand von Textilwaren",
      ],
    },
  },

  // ── 3. DEPORTES & NÁUTICA / VELA ──
  {
    slug: "club-nautico-can-picafort-escuela-vela-kayak",
    name: "Club Náutico Ca'n Picafort Escuela de Vela & Kayak",
    category: "deportes-fitness",
    sectorFolder: "deportes-fitness",
    sectorArrayName: "DEPORTES_SERVICES",
    subcategories: ["escuela-vela-can-picafort", "alquiler-kayak-paddle-surf", "puerto-deportivo-alcudia-bay"],
    zone: "alcudia-pollensa",
    address: "Passeig Marítim, 1, 07458 Can Picafort",
    coordinates: { lat: 39.7689, lng: 3.1512 },
    rating: 4.8,
    reviewCount: 390,
    priceRange: "€€",
    phone: "+34 971 850 012",
    website: "https://cncanpicafort.com",
    schedule: "Diario: 08:30 - 20:30 (Abril a Octubre)",
    tags: ["zona:muro", "product:vela-ligera", "mod:cita-previa"],
    shortDescription: {
      es: "Club náutico y escuela de deportes acuáticos en la bahía de Alcúdia: cursos de vela ligera para niños y adultos, alquiler de kayaks de mar, paddle surf y windsurf.",
      en: "Nautical club and water sports school in Alcúdia Bay: dinghy sailing courses for adults and kids, sea kayak, SUP, and windsurf rentals.",
      ca: "Club nàutic i escola d'esports aquàtics a la badia d'Alcúdia amb cursos de vela, caiac de mar i paddle surf.",
      de: "Segelclub und Wassersportschule in der Bucht von Alcúdia: Jollensegeln für Kinder und Erwachsene, Seekajaks, SUP und Windsurfen.",
    },
    fullDescription: {
      es: "El Club Náutico Ca'n Picafort está situado en la mayor extensión de playa de arena de Mallorca. Sus condiciones de viento térmico por la tarde (embat) son ideales para el aprendizaje y práctica de la vela ligera, el windsurf y el wing foil.",
      en: "Located along Mallorca's longest sandy beach bay, offering ideal thermal afternoon winds ('embat') for dinghy sailing, windsurfing, and wing foiling.",
      ca: "Situat a la major extensió de platja de sorra de Mallorca. Les condicions de vent 'embat' són ideals per a la vela i el windsurf.",
      de: "Direkt an Mallorcas größtem Sandstrand gelegen mit perfekten Nachmittags-Thermikwinden ('Embat') zum Segeln, Windsurfen und Wingfoilen.",
    },
    highlights: {
      es: [
        "Escuela de vela homologada por la Federación Balear de Vela (FBV)",
        "Ubicación directa en la playa de arena fina de la bahía de Alcúdia",
        "Flota de catamares Hobie Cat, barcos Optimist, Laser y tablas de Paddle Surf",
        "Vestuarios con taquillas, duchas de agua dulce y terraza de club náutico sobre la playa",
      ],
      en: [
        "Balearic Sailing Federation (FBV) accredited sailing school",
        "Direct beach access on the fine sand of Alcúdia Bay",
        "Fleet of Hobie Cat catamarans, Optimist dinghies, Laser sailboats, and SUP boards",
        "Changing rooms with lockers, fresh-water showers, and beachfront clubhouse terrace",
      ],
      ca: [
        "Escola de vela homologada per la Federació Balear de Vela",
        "Accés directe a la platja de sorra fina de la badia d'Alcúdia",
        "Flota de catamarans Hobie Cat, Optimist i taules de SUP",
        "Vestuaris amb dutxes i terrassa de club nàutic",
      ],
      de: [
        "Zertifizierte Segelschule des Balearischen Segelverbands (FBV)",
        "Direkter Strandzugang am feinsandigen Strand der Bucht von Alcúdia",
        "Flotte aus Hobie-Cat-Katamaranen, Optimisten, Laser-Jollen und SUP-Boards",
        "Umkleiden mit Duschen, Schließfächern und Clubhaus-Terrasse am Strand",
      ],
    },
    servicesProvided: {
      es: [
        "Cursos de vela ligera semanales para niños (de 6 a 16 años) y adultos",
        "Cursos de iniciación y perfeccionamiento de Windsurf y Wing Foil",
        "Alquiler por horas de kayaks de mar individuales y dobles y tablas de SUP",
        "Alquiler de amarres deportivos y varadero para embarcaciones privadas",
      ],
      en: [
        "Weekly dinghy sailing courses for children (ages 6-16) and adults",
        "Beginner and advanced Windsurfing and Wing Foiling group lessons",
        "Hourly sea kayak (single & double) and stand-up paddleboard (SUP) rentals",
        "Sport mooring berths and boat yard storage for private vessels",
      ],
      ca: [
        "Cursos de vela lleugera setmanals per a infants i adults",
        "Cursos de Windsurf i Wing Foil per a tots els nivells",
        "Lloguer per hores de caiacs de mar i taules de SUP",
        "Lloguer d'amarraments per a embarcacions privades",
      ],
      de: [
        "Wöchentliche Jollensegelkurse für Kinder (6-16 Jahre) und Erwachsene",
        "Einsteiger- und Fortgeschrittenenkurse für Windsurfen und Wing-Foilen",
        "Stundenweiser Verleih von Seekajaks (Einzel & Doppel) und SUP-Boards",
        "Liegeplatz- und Trockenliege-Vermietung für Privatyachten",
      ],
    },
  },

  // ── 4. GASTRONOMÍA & PESCADO EN PORTO CRISTO ──
  {
    slug: "restaurante-sa-llama-porto-cristo-marisco-vistas",
    name: "Restaurante Sa Llama Porto Cristo Pescados & Arroces Frente al Mar",
    category: "gastronomia-catering",
    sectorFolder: "gastronomia-restaurantes",
    sectorArrayName: "GASTRONOMIA_SERVICES",
    subcategories: ["restaurante-pescado-porto-cristo", "arroces-marineros-manacor", "restaurante-puerto-natural"],
    zone: "manacor-llevant",
    address: "Carrer de Bordils, 18, 07680 Porto Cristo, Manacor",
    coordinates: { lat: 39.5412, lng: 3.3345 },
    rating: 4.8,
    reviewCount: 540,
    priceRange: "€€€",
    phone: "+34 971 820 102",
    website: "https://sallamaportocristo.es",
    schedule: "Diario: 12:30 - 16:00 y 19:30 - 23:00 (Cerrado Miércoles en Invierno)",
    tags: ["zona:manacor", "product:paellas-arroces", "mod:walk-in"],
    shortDescription: {
      es: "Restaurante marinero sobre la ría natural de Porto Cristo: pescados frescos desembarcados en el puerto, caldereta de langosta balear y arroz meloso de ciego.",
      en: "Seafood restaurant along Porto Cristo's natural fjord: fresh fish landed at the harbor, Balearic lobster stew, and creamy seafood rice.",
      ca: "Restaurant mariner sobre la ria natural de Porto Cristo amb peix fresc del port, caldereta de llamàntol balear i arròs melós.",
      de: "Meeresfrüchte-Restaurant am natürlichen Fjord von Porto Cristo: tagesfrischer Fisch aus dem Hafen, Balearischer Hummer-Eintopf und cremiger Reis.",
    },
    fullDescription: {
      es: "Sa Llama es un referente de la gastronomía marinera en el puerto de Porto Cristo. Ubicado frente a la Ría Natural con vistas a las embarcaciones de pescadors tradicionales (llaüts), sirve marisco de las lonjas de Porto Cristo y Cala Rajada.",
      en: "A reference for seafood dining along Porto Cristo's natural fjord inlet, overlooking traditional wooden fishing llaüts with seafood sourced from eastern Mallorca fish markets.",
      ca: "Referent de la gastronomia marinera al port de Porto Cristo. Enfront de la ria amb vistes als llaüts tradicionals.",
      de: "Referenz für Fischgastronomie am natürlichen Fjord von Porto Cristo mit Blick auf die traditionellen Holz-Llaüts und frischen Fischen aus den Ostküsten-Märkten.",
    },
    highlights: {
      es: [
        "Ubicación en primera línea del puerto natural de Porto Cristo",
        "Pescados frescos del día a la sal o a la mallorquina (dentón, mero, caproig)",
        "Caldereta tradicional de langosta balear por encargo",
        "Amplia terraza sombreada orientada al canal marino",
      ],
      en: [
        "Frontline waterfront location along Porto Cristo's natural harbour",
        "Daily fresh fish salt-crusted or Mallorcan-style (dentex, grouper, scorpionfish)",
        "Traditional Balearic lobster stew ('caldereta') prepared to order",
        "Spacious shaded outdoor terrace overlooking the marine channel",
      ],
      ca: [
        "Ubicació a primera línia del port natural de Porto Cristo",
        "Peix fresc del dia a la sal o a la mallorquina",
        "Caldereta tradicional de llamàntol balear per encàrrec",
        "Terrassa ombrejada cap al canal de mar",
      ],
      de: [
        "Erstklassige Uferlage am natürlichen Hafenkanal von Porto Cristo",
        "Tagesfrischer Fisch im Salzmantel oder auf mallorquinische Art",
        "Traditioneller Balearischer Hummer-Eintopf auf Vorbestellung",
        "Große schattige Terrasse mit Blick auf die Hafeneinfahrt",
      ],
    },
    servicesProvided: {
      es: [
        "Almuerzos y cenas a la carta con mariscos y pescados frescos de la isla",
        "Servicio de arroces a la banda, paella mixta y fideuá para grupos",
        "Carta de vinos de bodegas locales de Felanitx, Binissalem y Pla i Llevant",
        "Reservas para comidas familiares tras la visita a las Coves del Drach",
      ],
      en: [
        "À la carte lunch and dinner featuring fresh island fish and shellfish",
        "Seafood paella, black rice, and fideuá menu for group dining",
        "Wine list highlighting local boutique wineries from Felanitx and Binissalem",
        "Post-tour family lunch reservations after visiting the nearby Coves del Drach",
      ],
      ca: [
        "Dinars i sopars a la carta amb peix fresc i marisc de l'illa",
        "Servei d'arrossos a la banda i paelles per a grups",
        "Carta de vins de cellers locals de Felanitx i Binissalem",
        "Reserves per a dinars familiars després de les Coves del Drach",
      ],
      de: [
        "À-la-carte-Mittags- und Abendessen mit frischem Fisch der Insel",
        "Meeresfrüchte-Paella, schwarzer Reis und Fideuá für Gruppenessen",
        "Weinkarte mit Weinen aus Felanitx, Binissalem und Pla i Llevant",
        "Familienessen-Reservierungen nach dem Besuch der Drachenhöhlen",
      ],
    },
  },

  // ── 5. MASCOTAS & VETERINARIA 24H ──
  {
    slug: "clinica-veterinaria-son-dureta-palma-24h",
    name: "Clínica Veterinaria Son Dureta Hospital & Urgencias 24h Palma",
    category: "clinicas-veterinarias-24h",
    sectorFolder: "mascotas-veterinaria",
    sectorArrayName: "MASCOTAS_SERVICES",
    subcategories: [
      "urgencias-veterinarias-24h-palma",
      "hospitalizacion-perros-gatos",
      "traumatologia-veterinaria-palma",
    ],
    zone: "palma",
    address: "Carrer de Andrea Doria, 44, 07014 Palma",
    coordinates: { lat: 39.5712, lng: 2.6289 },
    rating: 4.8,
    reviewCount: 680,
    priceRange: "€€",
    phone: "+34 971 731 012",
    website: "https://vetsondureta.es",
    schedule: "Urgencias 24 horas / 365 días (Consultas: Lunes a Sábado 09:00 - 20:30)",
    tags: ["zona:palma-centro", "product:accesible", "mod:walk-in"],
    shortDescription: {
      es: "Hospital veterinario 24 horas en el barrio de Son Dureta de Palma: servicio médico presencial 24/7, cirugía de urgencia, ecografía avanzada, laboratorio clínico y UCI animal.",
      en: "24-hour veterinary hospital in Palma's Son Dureta district: 24/7 on-site emergency care, emergency surgery, advanced ultrasound, ICU, and blood bank.",
      ca: "Hospital veterinari 24 hores al barri de Son Dureta de Palma amb atenció presencial 24/7, cirurgia d'urgència i UCI.",
      de: "24-Stunden-Veterinärklinik im Viertel Son Dureta in Palma: 24/7 Präsenz-Notdienst, Notfall-OP, Ultraschall, Labor und Intensivstation.",
    },
    fullDescription: {
      es: "Clínica Veterinaria Son Dureta es un centro veterinario de alta tecnología asistencial en Palma con más de 20 años de experiencia. Dispone de un equipo permanente de veterinarios y auxiliares de urgencias 24h, 2 quirófanos equipados y hospitalización felina y canina separada.",
      en: "High-tech veterinary hospital in Palma with 20+ years of clinical experience. Features a permanent 24/7 emergency veterinary team, 2 operating rooms, and separate cat and dog wards.",
      ca: "Centre veterinari d'alta tecnologia a Palma amb més de 20 anys d'experiència. Equip permanent de veterinaris 24h i 2 quiròfans equipats.",
      de: "Modernes Tier-Gesundheitszentrum in Palma mit 20+ Jahren Erfahrung. Ständiges 24h-Notarzt-Team, 2 OP-Säle und getrennte Katzen- und Hunde-Klinikstationen.",
    },
    highlights: {
      es: [
        "Servicio de urgencias veterinarias presenciales las 24h del día los 365 días del año",
        "Unidades de hospitalización independientes y climatizadas para perros y gatos (Cat-Friendly)",
        "Laboratorio de análisis clínicos propio con resultados de sangre en 15 minutos",
        "Especialistas en traumatología, cirugía ortopédica y neurocirugía animal",
      ],
      en: [
        "On-site emergency veterinary care 24 hours a day, 365 days a year",
        "Separate climate-controlled hospitalization wards for dogs and cats (Cat-Friendly certified)",
        "In-house clinical diagnostic laboratory providing blood panel results in 15 minutes",
        "Board-certified specialists in orthopedics, traumatology, and animal neurosurgery",
      ],
      ca: [
        "Atenció d'urgències veterinàries presencials 24h els 365 dies de l'any",
        "Unitats d'hospitalització independents per a gossos i gats",
        "Laboratori d'anàlisis pròpia amb resultats de sang en 15 minuts",
        "Especialistes en traumatologia i cirurgia ortopèdica",
      ],
      de: [
        "24-Stunden-Präsenz-Notaufnahme an 365 Tagen im Jahr ohne Voranmeldung",
        "Getrennte klimatisierte Pflegestationen für Hunde und Katzen (Cat-Friendly zertifiziert)",
        "Hauseigenes Labor mit Blutbild-Ergebnissen innerhalb von 15 Minuten",
        "Spezialisten für Orthopädie, Traumatologie und Tier-Neurochirurgie",
      ],
    },
    servicesProvided: {
      es: [
        "Atención de emergencias médicas, intoxicaciones y traumatismos las 24 horas",
        "Cirugía general, abdominal, torácica y ortopédica de urgencia",
        "Pruebas diagnósticas: ecografía Doppler abdominal, radiología digital y electrocardiograma",
        "Planes de salud anuales, vacunación, microchip oficial y pasaporte europeo de mascotas",
      ],
      en: [
        "24-hour emergency medical care for trauma, poisonings, and acute conditions",
        "Emergency general, abdominal, thoracic, and orthopedic surgical procedures",
        "Diagnostic imaging: abdominal Doppler ultrasound, digital X-rays, and ECG",
        "Annual preventive health plans, vaccinations, microchipping, and EU pet passports",
      ],
      ca: [
        "Atenció d'emergències mèdiques, intoxicacions i traumatismes 24 hores",
        "Cirurgia general, d'urgència i ortopèdica",
        "Ecografia Doppler, radiologia digital i electrocardiograma",
        "Vacunació, microxip oficial i passaport europeu",
      ],
      de: [
        "24-Stunden-Notaufnahme bei Unfällen, Vergiftungen und akuten Erkrankungen",
        "Notfall-Chirurgie für Bauchraum-, Thorax- und Knochenbrüche",
        "Diagnostik: Doppler-Ultraschall, digitales Röntgen und EKG",
        "Jahres-Gesundheits-Abos, Impfungen, offizieller Microchip und EU-Heimtierausweis",
      ],
    },
  },
];

console.log("Ingesting Batch 18 of 5 verified businesses...");
ingestBatch(BATCH_18);
